[[add-to-keystore]]
= add-to-keystore

Adds the specified keystore bundle to a target domain keystore.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin add-to-keystore [--help]
[--reload={false|true}]
[--domainName=name]
[--domainDir=directory]
[--node=nodeName]
[--nodeDir=directory]
[--listener=listenername]
[--target=instanceName]
[--file=<file-path>]
[alias]
----

[[description]]
== Description

This command adds a certificate bundle (e.g. `.p12` or `.jks` file) to the target instance or listener's key store using the provided alias.

If the instance or listener is configured to use the default key store, the command will instead synchronize the instance with the DAS (under the assumption the certificate has been added to the default key store of the DAS), since any certificates added to the instance stores would be lost upon next synchronisation.

NOTE: This will overwrite an entry already present with the same alias. A certificate without a private key cannot be used by an HTTP listener and will generate a warning.

[[options]]
== Options

`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are adding to its keystore. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--reload`::
Whether the HTTP listeners should be reloaded. Defaults to `false`
`--listener`::
The name of the HTTP or IIOP listener to add the certificate to.
`--domainname`::
The name of the domain where the target instance exists.
+
Defaults to `domain1` or the existing domain if only one exists.
`--domainDir`::
The path to the directory containing the target domain.
+
Defaults to
`as-install/glassfish/domains`
`--node`::
The name of the node where the target instance exists.
+
Defaults to `localhost-$domainname`
`--nodeDir`::
The path to the directory containing the target node.
+
Defaults to `as-install/glassfish/nodes`

`--file`::
The bundle file to add to the target keystore.

[[operands]]
== Operands

alias::
The alias name to store the certificate bundle in the keystore under.

[[examples]]
== Examples

*Example 1 Add the specified P12 bundle under the `mycert` alias*

[source, shell]
----
asadmin add-to-keystore --file mycert.p12 mycert
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Security Guide/SSL Certificate Management.adoc[SSL Certificate Management],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/add-to-truststore.adoc[`add-to-truststore`]
