[[generate-csr]]
= generate-csr

Generates a new CSR (certificate signing request).

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin generate-csr [--help]
[--domainName=name]
[--domainDir=directory]
[--node=nodeName]
[--nodeDir=directory]
[--listener=listenername]
[--target=instanceName]
[alias]
----

[[description]]
== Description

This command can generate a certificate signing request (CSR) for an instance or listener's self-signed certificate, placing the resultant CSR file in the `as-install/glassfish/tls` directory, using the alias name as the generated file name for the CSR.

IMPORTANT: The command overwrite a CSR with the same name already present in the directory.

[[options]]
== Options

`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are generating the CSR. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--listener`::
The name of the HTTP or IIOP listener to add the certificate to.
`--domainname`::
The name of the domain where the target instance exists.
+
Defaults to `domain1` or the existing domain if only one exists.
`--domainDir`::
The path to the directory containing the target domain.
+
Defaults to
`as-install/glassfish/domains`
`--node`::
The name of the node where the target instance exists.
+
Defaults to `localhost-$domainname`
`--nodeDir`::
The path to the directory containing the target node.
+
Defaults to `as-install/glassfish/nodes`

[[operands]]
== Operands

alias::
The alias name to use when generating the CSR for the corresponding self-signed certificate.

[[examples]]
== Examples

*Example 1 Generate a new CSR for the certificate with the `test-cert` alias*

[source, shell]
----
asadmin generate-csr --listener http-listener-2 --target instance-1 test_cert
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Security Guide/SSL Certificate Management.adoc[SSL Certificate Management],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/generate-self-signed-certificate.adoc[`generate-self-signed-certificate`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/renew-self-signed-certificates.adoc[`renew-self-signed-certificates`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/add-to-truststore.adoc[`add-to-truststore`]
