[[get-slack-notifier-configuration]]
= get-slack-notifier-configuration

Retrieves the settings of the Slack notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-slack-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the Slack notifier in Payara Server.

IMPORTANT: This command is available as long as the Slack notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the Slack notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to on a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the Slack notifier in the DAS*

[source, shell]
----
asadmin get-slack-notifier-configuration

Enabled  Noisy  Token 1    Token 2    Token 3
true     false  T43CHENUC  B441EFQB1  Jas8P3jCZ4wK8Y2m88dCxGkn
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-slack-notifier-configuration.adoc#set-slack-notifier-configuration[`set-slack-notifier-configuration`]
