[[get-teams-notifier-configuration]]
= get-teams-notifier-configuration

Retrieves the settings of the MS Teams notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-teams-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the MS Teams notifier in Payara Server.

IMPORTANT: This command is available as long as the MS Teams notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the MS Teams notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to on a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the MS Teams notifier in the DAS*

[source, shell]
----
asadmin get-teams-notifier-configuration

Enabled  Noisy  Webhook URL
true     false  https://outlook.office.com/webhook/xyz
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-teams-notifier-configuration.adoc#set-teams-notifier-configuration[`set-teams-notifier-configuration`]
