[[get-xmpp-notifier-configuration]]
= get-xmpp-notifier-configuration

Retrieves the settings of the XMPP notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-xmpp-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the XMPP notifier in Payara Server.

IMPORTANT: This command is available as long as the XMPP notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the XMPP notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to on a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the XMPP notifier in the DAS*

[source, shell]
----
asadmin get-xmpp-notifier-configuration

Enabled  Noisy  Host          XMPP Port  Service Name            Username         Password  Security Disabled  Room ID
true     false  172.28.128.3  5222       conference.payara.fish  payara_notifier  payara    true               server
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-xmpp-notifier-configuration.adoc#set-xmpp-notifier-configuration[`set-xmpp-notifier-configuration`]
