[[get-snmp-notifier-configuration]]
= get-snmp-notifier-configuration

Retrieves the settings of the SNMP notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-snmp-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the SNMP notifier in Payara Server.

IMPORTANT: This command is available as long as the SNMP notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the SNMP notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to on a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the SNMP notifier in the DAS*

[source, shell]
----
asadmin > get-snmp-notifier-configuration

Enabled  Noisy  Community  OID                Version  Host       SNMP Port
true     false  example    .1.3.6.1.2.1.1.8   v2c      127.0.0.1  162
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-snmp-notifier-configuration.adoc#set-snmp-notifier-configuration[`set-snmp-notifier-configuration`]
