[[list-nodes-version]]
= list-nodes-version

Lists all Payara Server nodes in a domain with their versions.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-nodes-version [--help]
[--node=nodeName]
----

[[description]]
== Description

The `list-nodes-version` subcommand lists all Payara Server nodes in a domain with their version.

By default, the subcommand displays the following information for each
node that is listed:

       *   The name of the node
       *   The node version, which includes a table of up to 3 different versions: 
       ** Current - the current node version
       ** Staged - the staged node version
       ** Old - the previous version that can be rolled back


[[options]]
== Options

`--help`::
`-?`::
Displays the help text for the subcommand.
`--node`::
Targets specific node.

[[examples]]
== Examples

*Example 1 Listing Node Version*

This example displays the name and versions for all nodes.

[source, shell]
----
asadmin> list-nodes-version

Nodes              Current  Staged  Old
localhost-domain1  7.0.0
SSH-Node           7.0.0    7.0.1   6.5.2
Command list-nodes-version executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Upgrade Guide/Upgrade Tool.adoc#downtime-upgrade[Zero Downtime upgrade],
