[[set-newrelic-notifier-configuration]]
= set-newrelic-notifier-configuration

Configures the settings of the New Relic notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-newrelic-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--accountId accountId]
[--key key]
----

[[description]]
== Description

This command can be used to configure the behaviour of the New Relic notifier in Payara Server.

IMPORTANT: This command is available as long as the New Relic notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the New Relic notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the log notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--accountId`::
Defines the New Relic account Id.
`--key`::
Defines the license key to be used by the notifier.

[[examples]]
== Examples

*Example 1 Enable the New Relic and set its license and account configuration*

[source, shell]
----
asadmin set-newrelic-notifier-configuration --dynamic=true --enabled=true --accountId=1658989 --key=b5815wdxj6lF_tmMBljQa5y1603JTiLh
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-newrelic-notifier-configuration.adoc#get-newrelic-notifier-configuration[`get-newrelic-notifier-configuration`]
