[[set-discord-notifier-configuration]]
= set-discord-notifier-configuration

Configures the settings of the Discord notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-discord-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--webhookId id]
[--webhookToken token]
----

[[description]]
== Description

This command can be used to configure the behaviour of the Discord notifier in Payara Server.

IMPORTANT: This command is available as long as the Discord notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the Discord notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the log notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--webhookId`::
The ID of the webhook required to authenticate to the corresponding Discord channel.
`--webhookToken`::
The token required to authenticate the webhook to the corresponding Discord channel.

[[examples]]
== Examples

*Example 1 Enable the Discord notifier and set its required webhook settings*

[source, shell]
----
asadmin set-discord-notifier-configuration --enabled=true --dynamic=true --webhookId=xxx --webhookToken=yyy
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-discord-notifier-configuration.adoc#get-discord-notifier-configuration[`get-discord-notifier-configuration`]
