[[set-datadog-notifier-configuration]]
= set-datadog-notifier-configuration

Configures the settings of the DataDog notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-datadog-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--key key]
----

[[description]]
== Description

This command can be used to configure the behaviour of the DataDog notifier in Payara Server.

IMPORTANT: This command is available as long as the Datadog notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the DataDog notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the log notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--key`::
Defines the license key to be used by the notifier.

[[examples]]
== Examples

*Example 1 Enable the DataDog notifier and set its license key*

[source, shell]
----
asadmin set-datadog-notifier-configuration --dynamic=true --key=af510f122026bc9107f7c5f4f049e597 --enabled=true
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-datadog-notifier-configuration.adoc#get-datadog-notifier-configuration[`get-datadog-notifier-configuration`]
