[[set-teams-notifier-configuration]]
= set-teams-notifier-configuration

Configures the settings of the MS Teams notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-teams-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[webhook-url]
----

[[description]]
== Description

This command can be used to configure the behaviour of the MS Teams notifier in Payara Server.

IMPORTANT: This command is available as long as the Datadog notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the MS Teams notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the log notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.

[[operands]]
== Operands

webhook-url::
The url of the MS Teams channel webhook to link the notifier to.

[[examples]]
== Examples

*Example 1 Enable the MS Teams notifier and set its webhook URL*

[source, shell]
----
asadmin set-teams-notifier-configuration --enabled=true --dynamic=true https://outlook.office.com/webhook/xyz
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-teams-notifier-configuration.adoc#get-teams-notifier-configuration[`get-teams-notifier-configuration`]
