[[set-slack-notifier-configuration]]
= set-slack-notifier-configuration

Configures the settings of the Slack notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-slack-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--token1 token]
[--token2 token]
[--token3 token]
----

[[description]]
== Description

This command can be used to configure the behaviour of the Slack notifier in Payara Server.

IMPORTANT: This command is available as long as the Slack notifier's core module is installed in the server. +
This notifier's extension is installed by default on Payara Server Enterprise.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the Slack notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the log notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--token1`::
The first token required to authenticate to the corresponding Slack channel.
`--token2`::
The second token required to authenticate to the corresponding Slack channel.
`--token3`::
The third token required to authenticate to the corresponding Slack channel.

[[examples]]
== Examples

*Example 1 Enable the Slack notifier and set its required tokens*

[source, shell]
----
asadmin set-slack-notifier-configuration --enabled=true --dynamic=true --token1=T43CHENUC --token2=B441EFQB1 --token3=Jas8P3jCZ4wK8Y2m88dCxGkn
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-slack-notifier-configuration.adoc#get-slack-notifier-configuration[`get-slack-notifier-configuration`]
