:ordinal: 900
= Payara Apache NetBeans IDE tools

Apache NetBeans IDE 11.1 provides out-of-the-box support for Payara Platform 
to integrate Payara Server and Payara Micro into the Apache NetBeans IDE.

[[installing]]
== Installing Apache NetBeans IDE

You can install NetBeans IDE in different ways:

* Via an installer: https://netbeans.apache.org/download/index.html

* Extracting from a ZIP: https://netbeans.apache.org/download/index.html

* Building from sources: https://github.com/apache/netbeans (see the Overview)


[[tools]]
== Tools

* xref:Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Server.adoc[Payara Server] - Apache NetBeans enables developers to
 download the latest version of Payara Server that can be easily configured and 
added as a recognised server in NetBeans IDE. This means you can easily deploy 
and manage applications from the NetBeans IDE interface by selecting the target 
Payara Server in the application properties.

* xref:Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Micro.adoc[Payara Micro] - Apache NetBeans IDE also provides 
first-class support to create and run Payara Micro maven web applications from 
the NetBeans interface which is the microservices-ready version of Payara Server.
