[[add-instance-to-deployment-group]]
= add-instance-to-deployment-group

Adds a standalone instance to an existing deployment group.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] add-instance-to-deployment-group [--help]
[--instance instanceName]
[--deploymentgroup deploymentGroupName]
----

[[description]]
== Description

The `add-instance-to-deployment-group` subcommand will add the referenced instance to the referenced deployment group.

This command will only work with standalone instances (see xref:Technical Documentation/Payara Server Documentation/High Availability/Administering Payara Server Instances.adoc#types-of-payara-server-instances[here] for more information).

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
Displays the help text for the subcommand.

`--instance`::
The name of the standalone instance that will be added to the deployment group. The command will fail if the name doesn't match to an existing standalone instance.

`--deploymentGroup`::
The name of the deployment group to which the standalone instance will be added. The command will fail if the name doesn't match to an existing deployment group.

[[examples]]
== Examples

*Example 1 Add an instance to a Deployment Group*

This example adds an instance named `test-instance-1` to a deployment group named `test-dgroup`:

[source,shell]
----
asadmin add-instance-to-deployment-group --instance=test-instance-1 --deploymentGroup=test-dgroup

Command add-instance-to-deployment-group executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

See Also

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-deployment-group.adoc#create-deployment-group[`create-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-deployment-group.adoc#delete-deployment-group[`delete-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-deployment-groups.adoc#list-deployment-groups[`list-deployment-groups`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/remove-instance-from-deployment-group.adoc#remove-instance-from-deployment-group[`remove-instance-from-deployment-group`]
