[[application]]
= Applications
:ordinal: 6

Server-side Jakarta EE applications and web services.

[[description]]
== Description

The Jakarta EE platform enables applications to access systems that are outside of the application server. Applications connect to these systems through resources.

The Payara Server infrastructure supports the deployment of many types of distributed applications and is an ideal foundation for building applications based on Service Oriented Architectures (SOA). SOA is a design methodology aimed at maximizing the reuse of application services. These features enable you to run scalable and highly available Jakarta EE applications.

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-application-ref.adoc#create-application-ref[`create-application-ref`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc#deploy[`deploy`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-applications.adoc#list-applications[`list-applications`]


