[[apply-http-lb-changes]]
= apply-http-lb-changes

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
 +
The documentation in this page may not be accurate.

Applies load balancer configuration changes to the load balancer.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] apply-http-lb-changes [--help]
lb-name
----

[[description]]
== Description

Use the `apply-http-lb-changes` subcommand to apply the changes in the load balancer configuration to the physical load balancer. The load balancer must already exist. To create a physical load balancer, use the `create-http-lb` subcommand.

[[context]]
== Context

The Load Balancer distributes the workload among multiple Payara Server instances , increasing the overall throughput of the system. The Load Balancer also enables requests to failover from one server instance to another. For HTTP session information to persist, configure HTTP session persistence.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

lb-name::
  The name of the load balancer to which changes are applied. The load balancer must already exist. You can create it with the `create-http-lb` subcommand.

[[examples]]
== Examples

*Example 1 Using the `apply-http-lb-changes` subcommand*

This example applies configuration changes to a load balancer named `mylb`.

[source,shell]
----
asadmin> apply-http-lb-changes mylb
Command apply-http-lb-changes executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb.adoc#create-http-lb[`create-http-lb`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb-config.adoc#create-http-lb-config[`create-http-lb-config`]


