[[backup-domain]]
= backup-domain

Performs a backup on the domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] backup-domain [--help]
[--long[={false|true}]]
[--description description-text]
[--domaindir domain-root-dir]
[--backupdir backup-directory]
[--backupconfig backup-config-name]
[domain_name]
----

[[description]]
== Description

The `backup-domain` subcommand backs up files under the named domain.

To complete the command, however, *the domain must be stopped first*. This will mean that any application deployed to the DAS is unavailable while the backup takes place.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these   options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
  Displays the help text for the subcommand.

`--long`::
`-l`::
  Displays detailed information about the backup operation.
+
The default value is `false`.

`--description`::
  Specifies a description to store in the backup file. The description is displayed as part of the information about a backup file.
+
The default value has this form:
+
[source,text]
----
domain-name_YYYY_MM_DD_backup-number
----
`--domaindir`::
  Specifies the domain root directory, the parent directory of the   domain to back up.
+
The default value is `as-install/domains`.

`--backupdir`::
  Specifies the directory under which the backup file is to be stored.
+
The default value is `as-install/domains/domain-dir/backups`. If the domain is not in the default location, the location is `domain-dir/backups`.

[[operands]]
== Operands

domain-name::
Specifies the name of the domain to be backed up.
+
This operand is optional if only one domain exists in the Payara Server installation.

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-backups.adoc#list-backups[`list-backups`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restore-domain.adoc#restore-domain[`restore-domain`]


