[[change-master-broker]]
= change-master-broker

Changes the master broker in a Message Queue cluster providing JMS services for a Payara Server cluster.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] change-master-broker [--help]
clustered-instance-name
----

[[description]]
== Description

The `change-master-broker` subcommand changes the master broker in a Message Queue cluster that is the JMS provider for a Payara Server
cluster. By default, the master broker is the one associated with the first instance configured in the Payara Server cluster.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

clustered-instance-name::
  The name of the server instance whose Message Queue broker is to become the master broker of the Message Queue cluster. This server instance must be an instance in a
  Payara Server cluster.

[[examples]]
== Examples

*Example 1 Changing the master broker*

The following subcommand changes the Message Queue master broker to the
one for the `clustinst3` clustered instance.

[source,shell]
----
asadmin> change-master-broker clustinst3
Command change-master-broker executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]


