[[purge-jbatch-repository]]
= clean-jbatch-repository

Deletes records of Jakarta Batch job executions.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] clean-jbatch-repository
[--status={COMPLETED|ALL}]
[--days] days
[job_name]
----

[[description]]
== Description

The `clean-jbatch-repository` subcommand will remove the history of all job records related to an specific Jakarta Batch execution job.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--status`::
The status of batch jobs executions to which delete the records of. Valid values are as follows: +
`COMPLETED`;;
Only job executions that successfully completed will be deleted.
`ALL`;;
All job executions will be deleted, regardless of status.
`--days`::
The number of days previous that the end time of the job execution must be to get deleted.
+
Defaults to `1` day

[[operands]]
== Operands

job_name::
The name of the Jakarta Batch job that will be cleared in the repository.

[[examples]]
== Examples

The following command will delete all job records for the `testjob` job that were executed before 7 days ago.

[source, shell]
----
asadmin > clean-jbatch-repository --status=ALL --days=7 testjob
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-jobs.adoc#list-batch-jobs[`list-batch-jobs`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-job-executions.adoc#list-batch-job-executions[`list-batch-job-executions`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-job-steps.adoc#list-batch-job-steps[`list-batch-job-steps`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-runtime-configuration.adoc#list-batch-runtime-configuration[`list-batch-runtime-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/purge-jbatch-repository.adoc#purge-jbatch-repository[`purge-jbatch-repository`]

