[[configuration]]
= Configuration
:ordinal: 3

The data set that determines how a Payara Server instance operates.

[[description]]
== Description

The configuration of Payara Server is the data set that determines how it operates. Parts of this configuration determine the operation of specific parts of Payara Server, such as the following:

* Services, such as the transaction service
* Resources, such as databases
* Deployed applications or modules, such as web applications
* Clusters and server instances

The term configuration is also used to describe a part of the overall configuration, such as the transaction service configuration or the configuration of a database. In clustered environments, clusters, deployment groups or server instances can share configurations.

Examples of configuration data are port numbers, flags that enable or disable processes, application names, and so on. Most of these data points are name/value pairs, either hard-coded attributes or more flexibly defined properties.

The hierarchical structure of the configuration is explained in the dotted names page. You can view and change most of the Payara Server configuration using either the Administration Console or the `asadmin` utility and its subcommands.

To list the structure of all or part of the configuration, use the `list` subcommand. To view the value of one or more attributes or properties, use the `get` subcommand. To change the value of an attribute or property, use the `set` subcommand.

[[see-also]]
== See Also

* xref:Technical Documentation/Payara Server Documentation/Command Reference/get.adoc#get[`get`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list.adoc#list[`list`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set.adoc#set[`set`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/Dotted Names.adoc#dotted-names[`dotted-names`]
* xref:Technical Documentation/Payara Server Documentation/General Administration/Overview.adoc#configuration-tasks[Configuration Tasks] in the Payara Server General Administration section
