[[configure-ldap-for-admin]]
= configure-ldap-for-admin

Configures the authentication realm named admin-realm for the given LDAP.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] configure-ldap-for-admin [--help]
----

[[description]]
== Description

The `configure-ldap-for-admin` subcommand configures the authentication realm named `admin-realm` for the given LDAP. The `configure-ldap-for-admin` subcommand is interactive.
The subcommand prompts the user for the `basedn` and `ldap-group` options.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Configuring the LDAP Authentication Realm*

[source,shell]
----
asadmin> configure-ldap-for-admin 
Enter the value for the basedn option>
Enter the value for the ldap-group option>
The LDAP Auth Realm admin-realm was configured correctly 
in admin server's configuration.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/change-admin-password.adoc#change-admin-password[`change-admin-password`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-auth-realm.adoc#create-auth-realm[`create-auth-realm`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-auth-realms.adoc#list-auth-realms[`list-auth-realms`]


