[[create-protocol-filter]]
= create-protocol-filter

Adds a new protocol filter.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-protocol-filter [--help]
--protocol protocol-name 
--classname class-name 
[--target server]
protocol-filter-name
----

[[description]]
== Description

The `create-protocol-filter` subcommand creates a protocol filter for a protocol. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--protocol`::
  The name of the associated protocol.
`--classname`::
  The fully qualified name of the Java class that implements the protocol filter.
`--target`::
  Creates the protocol filter only on the specified target. Valid values are as follows: +
  `server`;;
    Creates the protocol filter on the default server instance. This is the default value.
  configuration-name;;
    Creates the protocol filter in the specified configuration.
  cluster-name;;
    Creates the protocol filter on all server instances in the specified cluster.
  standalone-instance-name;;
    Creates the protocol filter on the specified standalone server instance.

[[operands]]
== Operands

protocol-filter-name::
  The name of the protocol filter.

[[examples]]
== Examples

*Example 1 Creating a Protocol Filter*

The following command creates a protocol filter named `http1-filter`:

[source,shell]
----
asadmin> create-protocol-filter --protocol http1
--classname com.company22.MyProtocolFilter http1-filter
Command create-protocol-filter executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-protocol.adoc#create-protocol[`create-protocol`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-protocol-filter.adoc#delete-protocol-filter[`delete-protocol-filter`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-protocol-filters.adoc#list-protocol-filters[`list-protocol-filters`]


