[[create-connector-work-security-map]]
= create-connector-work-security-map

Creates a work security map for the specified resource adapter.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-connector-work-security-map [--help] 
--raname raname
[--principalsmap eis-principal1=principal_name1[, eis-principal2=principal_name2]* 
|--groupsmap eis-group1=server-group1[, eis-group2=server-group2]*}
[--description description] 
mapname
----

[[description]]
== Description

The `create-connector-work-security-map` subcommand maps the caller identity of the work submitted by the resource adapter EIS principal or
EIS user group to a suitable principal or user group in the Payara Server security domain. One or more work security maps may be associated with a resource adapter.
The connector work security map configuration supports the use of the wild card asterisk (`*`) to indicate all users or all user groups.

The enterprise information system (EIS) is any system that holds the data of an organization. It can be a mainframe, a messaging system, a database system, or an application.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--description`::
  Text providing descriptive details about the connector work security
  map.
`--groupsmap`::
  Specifies a map of the backend EIS user group to the Payara Server user group. Use a comma-separated list to specify more than one
  mapping. Use either the `--principalsmap` option or the `--groupsmap` option, but not both.
`--principalsmap`::
  Specifies a map of the backend EIS principal to the Payara Server principal. Use a comma-separated list to specify more than one
  mapping. Use either the `--principalsmap` option or the `--groupsmap` option, but not both.
`--raname`::
  Indicates the connector module name, which is the name of the resource adapter.

[[operands]]
== Operands

mapname::
  The name of the work security map to be created.

[[examples]]
== Examples

*Example 1 Creating a Connector Work Security Map (Principal)*

This example creates connector work security map `workSecurityMap1` that maps the backend EIS principal to the Payara Server principal.

[source,shell]
----
asadmin create-connector-work-security-map --raname my-resource-adapter
--principalsmap eis-principal-1=server-principal-1,eis-principal-2
=server-principal-2,eis-principal-3=server-principal-1 
workSecurityMap1
Command create-connector-work-security-map executed successfully.
----

*Example 2 Creating a Connector Work Security Map (Group)*

This example creates connector work security map `workSecurityMap2` that maps the backend EIS user group to the Payara Server user group.

[source,shell]
----
asadmin create-connector-work-security-map --raname my-resource-adapter
--groupsmap eis-group-1=server-group-1,eis-group-2=server-group-2,
eis-group-3=server-group-1 workSecurityMap2
Command create-connector-work-security-map executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-connector-work-security-map.adoc#delete-connector-work-security-map[`delete-connector-work-security-map`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-connector-work-security-maps.adoc#list-connector-work-security-maps[`list-connector-work-security-maps`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-connector-work-security-map.adoc#update-connector-work-security-map[`update-connector-work-security-map`]


