[[create-password-alias]]
= create-password-alias

Creates a password alias.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-password-alias [--help] 
aliasname
----

[[description]]
== Description

The `create-password-alias` subcommand creates an alias for a password.
An alias is a token of the form `${ALIAS=aliasname}`. The password that corresponds to the alias name is stored in an encrypted form.

The `create-password-alias` subcommand can be run interactively or noninteractively.

* When run interactively, the subcommand prompts the user for the alias password and to confirm the alias password.
* When run noninteractively, the subcommand reads the alias password from a file that is passed through the `--passwordfile` option of the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] utility. The file must
contain an entry of the form `{cprefix}ALIASPASSWORD`=alias-password, where alias-password is the alias password. The noninteractive form of this command is suitable for use in scripts.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

aliasname::
  Your choice of name for the password alias.

[[examples]]
== Examples

*Example 1 Creating a Password Alias Interactively*

This example creates the password alias `jmspassword-alias` interactively.

[source,shell]
----
asadmin> create-password-alias jmspassword-alias 
Enter the alias password>
Enter the alias password again>
Command create-password-alias executed successfully.
----

*Example 2 Creating a Password Alias Noninteractively*

This example uses the `--passwordfile` option of the `asadmin` utility to create the password alias `winuser` noninteractively.

[source,shell]
----
$ asadmin --passwordfile aspwfile.txt create-password-alias winuser
Command create-password-alias executed successfully.
----

The file `aspwfile.txt` contains the following entry to specify the alias password:

[source,shell]
----
AS_ADMIN_ALIASPASSWORD=sp@rky
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-password-alias.adoc#delete-password-alias[`delete-password-alias`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-password-aliases.adoc#list-password-aliases[`list-password-aliases`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-password-alias.adoc#update-password-alias[`update-password-alias`]


