[[create-jndi-resource]]
= create-jndi-resource

Registers a JNDI resource.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-jndi-resource [--help] 
[--target target] 
--restype restype --factoryclass factoryclass 
--jndilookupname jndilookupname [--enabled={true|false}] 
[--description description] 
[--property (name=value)[:name=value]*] 
jndi-name
----

[[description]]
== Description

The `create-jndi-resource` subcommand registers a JNDI resource.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target for which you are registering a JNDI resource. Valid values for target are described below. +

NOTE: The resource is always created for the domain as a whole, but the `resource-ref` for the resource is only created for the specified `--target`. This means that although the resource is defined at the domain level, it is only available at the specified target level. Use the `create-resource-ref` subcommand to refer to the resource in multiple targets if needed.

  `server`;;
    Creates the resource for the default server instance. This value is
    the default.
  `domain`;;
    Creates the resource for the domain
  cluster-name;;
    Creates the resource for every server instance in the cluster
  instance-name;;
    Creates the resource for a particular server instance
`--restype`::
  The JNDI resource type. Valid values are `topic` or `queue`.
`--factoryclass`::
  The class that creates the JNDI resource.
`--jndilookupname`::
  The lookup name that the external container uses.
`--enabled`::
  Determines whether the resource is enabled at runtime. Default is true.
`--description`::
  The text that provides details about the JNDI resource.
`--property`::
  Optional properties for configuring the resource. Each property is specified as a name-value pair. The available properties are specific to the implementation that is specified by the `--factoryclass` option and are used by that implementation. Payara Server itself does not define any properties for configuring a JNDI resource.

[[operands]]
== Operands

jndi-name::
  The unique name of the JNDI resource to be created.

[[examples]]
== Examples

*Example 1 Creating a JNDI Resource*

This example creates the JNDI resource `my-jndi-resource` for the default server instance.

[source,shell]
----
asadmin> create-jndi-resource 
--restype com.example.jndi.MyResourceType 
--factoryclass com.example.jndi.MyInitialContextFactoryClass 
--jndilookupname remote-jndi-name 
--description "sample JNDI resource" my-jndi-resource
JNDI resource my-jndi-resource created.
Command create-jndi-resource executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-resource-ref.adoc#create-resource-ref[`create-resource-ref`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jndi-resource.adoc#delete-jndi-resource[`delete-jndi-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jndi-resources.adoc#list-jndi-resources[`list-jndi-resources`]


