[[create-module-config]]
= create-module-config

Adds the default configuration of a module to `domain.xml`.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-module-config [--help]
[--dryrun={false|true}]
[--all={false|true}]
[--target target] 
[service_name]
----

[[description]]
== Description

The `create-module-config` subcommand adds the default configuration of a module to `domain.xml`.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--dryrun`::
  Displays the default configuration of a module but does not add it to `domain.xml`. The default value is `false`.
`--all`::
  Adds all default configurations of modules to `domain.xml` if they are not already in it. The default value is `false`.
`--target`::
  Specifies the target to which the default configuration is being added. +
  Possible values are as follows: +
  `server`;;
    Adds the default configuration to the default server instance. This is the default value.
  `domain`;;
    Adds the default configuration to the default domain.
  cluster-name;;
    Adds the default configuration to every server instance in the specified cluster.
  instance-name;;
    Adds the default configuration to the specified instance.

[[operands]]
== Operands

service_name::
  The name of the module for which the default configuration is to be added.

[[examples]]
== Examples

*Example 1 Adding a Default Configuration to domain.xml*

This example adds the default configuration of the web container module to `domain1` in `server-config` (the default configuration). Use the `--dryrun` option to preview the configuration before it is added.

[source,shell]
----
asadmin> create-module-config web-container
Command create-module-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-module-config.adoc#delete-module-config[`delete-module-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-active-module-config.adoc#get-active-module-config[`get-active-module-config`]


