[[create-protocol]]
= create-protocol

Adds a new protocol.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-protocol [--help]
[--securityenabled={false|true}]
[--target target]
protocol-name
----

[[description]]
== Description

The `create-protocol` subcommand creates a protocol. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--securityenabled`::
  If set to `true`, the protocol runs SSL. You can turn SSL2 or SSL3 ON or OFF and set ciphers using an `ssl` element. The security setting
  globally enables or disables SSL by making certificates available to the server instance. The default value is `false`.
`--target`::
  Creates the protocol only on the specified target. Valid values are as follows: +
  `server`;;
    Creates the protocol on the default server instance. This is the default value.
  configuration-name;;
    Creates the protocol in the specified configuration.
  cluster-name;;
    Creates the protocol on all server instances in the specified cluster.
  standalone-instance-name;;
    Creates the protocol on the specified standalone server instance.

[[operands]]
== Operands

protocol-name::
  The name of the protocol.

[[examples]]
== Examples

*Example 1 Creating a Protocol*

The following command creates a protocol named `http-1` with security enabled:

[source,shell]
----
asadmin> create-protocol --securityenabled=true http-1
Command create-protocol executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-protocol.adoc#delete-protocol[`delete-protocol`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-protocols.adoc#list-protocols[`list-protocols`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-network-listener.adoc#create-network-listener[`create-network-listener`]


