[[create-protocol-finder]]
= create-protocol-finder

Adds a new protocol finder.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] create-protocol-finder [--help]
--protocol protocol-name 
--targetprotocol target-protocol-name 
--classname class-name 
[--target server]
protocol-finder-name
----

[[description]]
== Description

The `create-protocol-finder` subcommand creates a protocol finder for a protocol. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--protocol`::
  The name of the associated protocol.
`--targetprotocol`::
  The name of the target protocol.
`--classname`::
  The fully qualified name of the Java class that implements the protocol finder.
`--target`::
  Creates the protocol finder only on the specified target. Valid values are as follows: +
  `server`;;
    Creates the protocol finder on the default server instance. This is the default value.
  configuration-name;;
    Creates the protocol finder in the specified configuration.
  cluster-name;;
    Creates the protocol finder on all server instances in the specified cluster.
  standalone-instance-name;;
    Creates the protocol finder on the specified standalone server instance.

[[operands]]
== Operands

protocol-finder-name::
  The name of the protocol finder.

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-protocol-finder.adoc#delete-protocol-finder[`delete-protocol-finder`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-protocol-finders.adoc#list-protocol-finders[`list-protocol-finders`]


