[[delete-file-user]]
= delete-file-user

Removes the named file user.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-file-user [--help] 
[--authrealmname auth_realm_name] 
[--target target] 
username
----

[[description]]
== Description

The `delete-file-user` subcommand deletes the entry in the keyfile for the specified username.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--authrealmname`::
  The name of the authentication realm with which the user was created.
`--target`::
  This is the name of the target on which the command operates. The valid targets are: +
  `server`;;
    Deletes the file user on the default server instance. This is the default value
  `domain`;;
    Deletes the file user in the domain.
  cluster_name;;
    Deletes the file user from every server instance in the cluster.
  instance_name;;
    Deletes the file user from a particular server instance.

[[operands]]
== Operands

username::
  This is the name of file user to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a User From a File Realm*

The following example shows how to delete user named `sample_user` from a file realm.

[source,shell]
----
asadmin> delete-file-user
sample_user
Command delete-file-user executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-file-user.adoc#create-file-user[`create-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-groups.adoc#list-file-groups[`list-file-groups`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-users.adoc#list-file-users[`list-file-users`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-file-user.adoc#update-file-user[`update-file-user`]


