[[delete-virtual-server]]
= delete-virtual-server

Removes a virtual server.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-virtual-server [--help]
[--target target] virtual-server-id
----

[[description]]
== Description

The `delete-virtual-server` subcommand removes the virtual server with the specified virtual server ID. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the virtual server only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the virtual server from the default server instance. This is the default value.
  configuration-name;;
    Deletes the virtual server from the specified configuration.
  cluster-name;;
    Deletes the virtual server from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the virtual server from the specified standalone server instance.

[[operands]]
== Operands

virtual-server-id::
  The unique identifier for the virtual server to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Virtual Server*

The following command deletes the virtual server named `sample_vs1`:

[source,shell]
----
asadmin> delete-virtual-server sample_vs1
Command delete-virtual-server executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-virtual-server.adoc#create-virtual-server[`create-virtual-server`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-virtual-servers.adoc#list-virtual-servers[`list-virtual-servers`]


