[[delete-managed-thread-factory]]
= delete-managed-thread-factory

Removes a managed thread factory resource with the specified JNDI name.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-managed-thread-factory [--help]
[--target target]
managed_thread_factory_name
----

[[description]]
== Description

The `delete-managed-thread-factory` subcommand removes a managed thread
factory resource with the specified JNDI name.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
Specifies the target from which you are deleting the resource. Valid
targets are:
+
`server`;;
Deletes the resource from the default server instance. This is the
default value.
`domain`;;
Deletes the resource from the domain.
cluster_name;;
Deletes the resource from every server instance in the specified
cluster.
instance_name;;
Deletes the resource from the specified server instance.

[[operands]]
== Operands

managed_thread_factory_name::
The JNDI name of the resource to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Managed Thread Factory Resource*

This example deletes the managed thread factory resource named `concurrent/myThreadFactory`.

[source,shell]
----
asadmin> delete-managed-thread-factory concurrent/Factory1
Managed thread factory concurrent/Factory1 deleted successfully.
Command delete-managed-thread-factory executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-managed-thread-factory.adoc#create-managed-thread-factory[`create-managed-thread-factory`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-managed-thread-factories.adoc#list-managed-thread-factories[`list-managed-thread-factories`]


