[[delete-transport]]
= delete-transport

Removes a transport.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-transport [--help]
[--target target]
transport-name
----

[[description]]
== Description

The `delete-transport` subcommand removes the specified transport. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the transport only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the transport from the default server instance. This is the default value.
  configuration-name;;
    Deletes the transport from the specified configuration.
  cluster-name;;
    Deletes the transport from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the transport from the specified standalone server instance.

[[operands]]
== Operands

transport-name::
  The name of the transport to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Transport*

The following command deletes the transport named `http1-trans`:

[source,shell]
----
asadmin> delete-transport http1-trans
Command delete-transport executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-transport.adoc#create-transport[`create-transport`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-transports.adoc#list-transports[`list-transports`]


