[[delete-system-property]]
= delete-system-property

Removes a system property of the domain, configuration, cluster, or server instance, one at a time.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-system-property [--help] 
[--target target_name ] 
[property_name]
----

[[description]]
== Description

The `delete-system-property` subcommand deletes a system property of a domain, configuration, cluster, or server instance. Make sure that the
system property is not referenced elsewhere in the configuration before deleting it.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are deleting the system properties. The valid targets for this subcommand are instance,
  cluster, configuration, domain, and server. Server is the default option.

[[operands]]
== Operands

property_name::
  The name of the system property to remove.

[[examples]]
== Examples

*Example 1 Deleting a System Property*

This example deletes the system property named `http-listener-port`.

[source,shell]
----
asadmin> delete-system-property http-listener-port
Command delete-system-property executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-system-properties.adoc#create-system-properties[`create-system-properties`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-system-properties.adoc#list-system-properties[`list-system-properties`]


