[[delete-http-lb-ref]]
= delete-http-lb-ref

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Deletes the cluster or server instance from a load balancer.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-lb-ref [--help] 
--config config_name | --lbname load_balancer_name
[--force=false] target
----

[[description]]
== Description

Use the `delete-http-lb-ref` subcommand to remove a reference to a cluster or standalone server instance from a load balancer configuration or load balancer. So that you do not interrupt user requests, make sure the standalone server instance or all server instances in the cluster are disabled before you remove them from the load balancer configuration. If the `force` option is set to true, the references are deleted even if server instances or clusters are enabled.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--config`::
  Specifies which load balancer configuration to delete cluster and server instance references from. +
  Specify either a load balancer configuration or a load balancer. Specifying both results in an error.
`--lbname`::
  Specifies the load balancer to delete cluster and server instance references from. +
  Specify either a load balancer configuration or a load balancer. Specifying both results in an error.
`--force`::
  If `force` is set to true, then the references are deleted even if there are currently enabled applications or instances. The default is false.

[[operands]]
== Operands

target::
  Specifies which cluster or instance to remove from the load balancer. Valid values are: +
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

[[example-1]]
*Example 1 Deleting a Cluster Reference from a Load Balancer Configuration*

This example deletes the reference to cluster named `cluster2` from a load balancer configuration named `mycluster-http-lb-config`.

[source,shell]
----
asadmin> delete-http-lb-ref --config mycluster-http-lb-config cluster2 

Command delete-http-lb-ref executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb-ref.adoc#create-http-lb-ref[`create-http-lb-ref`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-http-lb-server.adoc#disable-http-lb-server[`disable-http-lb-server`]


