[[delete-context-service]]
= delete-context-service

Removes a context service resource with the specified JNDI name.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-context-service [--help]
[--target target]
context-service-name
----

[[description]]
== Description

The `delete-context-service` subcommand removes a context service resource with the specified JNDI name.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

`--target`::
Specifies the target from which you are deleting the resource. Valid targets are:
+
`server`;;
Deletes the resource from the default server instance. This is the default value.
`domain`;;
Deletes the resource from the domain.
cluster-name;;
Deletes the resource from every server instance in the specified cluster.
instance-name;;
Deletes the resource from the specified server instance.

[[operands]]
== Operands

context-service-name::
The JNDI name of the resource to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Context Service Resource*

This example deletes the context service resource named `concurrent/myContextService`.

[source,shell]
----
asadmin> delete-context-service concurrent/myContextService
Context service concurrent/myContextService deleted successfully.
Command delete-context-service executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-context-service.adoc#create-context-service[`create-context-service`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-context-services.adoc#list-context-services[`list-context-services`]


