[[delete-custom-resource]]
= delete-custom-resource

Removes a custom resource.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-custom-resource [--help] 
[--target target] jndi-name
----

[[description]]
== Description

The `delete-custom-resource` subcommand removes a custom resource.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option helps specify the location of the custom resources that you are deleting. Valid targets are server, domain, cluster, and instance. The default is server. +

NOTE: Resources are always created for a domain as a whole but are only active for targets for which a `<resource-ref>` has been created using the `--target` option when the resource was created. This means that deleting a resource only deletes the `<resource-ref>` element for the specified `--target`, and does not delete the resource from the domain as a whole unless `domain` is specified as the `--target` for the deletion.

  `server`;;
    Deletes the resource for the default server instance. This is the default value.
  `domain`;;
    Deletes the resource for the domain.
  cluster_name;;
    Deletes the resource for every server instance in the cluster.
  instance_name;;
    Deletes the resource for a particular server instance.

[[operands]]
== Operands

jndi-name::
  The JNDI name of this resource.

[[examples]]
== Examples

*Example 1 Deleting a Custom Resource*

This example deletes a custom resource named `mycustomresource`.

[source,shell]
----
asadmin> delete-custom-resource mycustomresource
Command delete-custom-resource executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-custom-resource.adoc#create-custom-resource[`create-custom-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-custom-resources.adoc#list-custom-resources[`list-custom-resources`]


