[[delete-http-redirect]]
= delete-http-redirect

Removes an HTTP redirect.

[[synopsis]]
== Synopsis

[source,shell]
----
delete-http-redirect [--help]
[--target target]
protocol-name
----

[[description]]
== Description

The `delete-http-redirect` subcommand removes the specified HTTP redirect. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the HTTP redirect only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the HTTP redirect from the default server instance. This is the default value.
  configuration-name;;
    Deletes the HTTP redirect from the specified configuration.
  cluster-name;;
    Deletes the HTTP redirect from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the HTTP redirect from the specified standalone server instance.

[[operands]]
== Operands

protocol-name::
  The name of the associated protocol.

[[examples]]

*Example 1 Deleting a HTTP Redirect*

The following command deletes the HTTP redirect named `http-redirect`:

[source,shell]
----
asadmin> delete-http-redirect http-redirect
Command delete-http-redirect executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-redirect.adoc#create-http-redirect[`create-http-redirect`]


