[[delete-jms-host]]
= delete-jms-host

Removes a JMS host.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-jms-host [--help]
[--target target]
jms_host_name
----

[[description]]
== Description

The `delete-jms-host` subcommand removes the specified Java Message Service (JMS) host.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

Deleting the default JMS host, named `default_JMS_host`, is not recommended.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the JMS host only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the JMS host from the default server instance. This is the default value.
  configuration-name;;
    Deletes the JMS host from the specified configuration.
  cluster-name;;
    Deletes the JMS host from every server instance in the specified cluster.
  instance-name;;
    Deletes the JMS host from the specified server instance.

[[operandds]]
== Operands

jms_host_name::
  The name of the host to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a JMS host*

The following subcommand deletes the JMS host named `MyNewHost`.

[source,shell]
----
asadmin> delete-jms-host MyNewHost
Command delete-jms-host executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jms-host.adoc#create-jms-host[`create-jms-host`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/jms-ping.adoc#jms-ping[`jms-ping`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jms-hosts.adoc#list-jms-hosts[`list-jms-hosts`]


