[[delete-http-listener]]
= delete-http-listener

Removes a network listener.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-listener [--help]
[--target target]
listener-id
----

[[description]]
== Description

The `delete-http-listener` subcommand removes the specified network listener.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the network listener only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the network listener from the default server instance. This is the default value.
  configuration-name;;
    Deletes the network listener from the specified configuration.
  cluster-name;;
    Deletes the network listener from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the network listener from the specified standalone server instance.

[[operands]]
== Operands

listener-id::
  The unique identifier for the network listener to be deleted.

[[examples]]
== Examples

[[example-1]]
*Example 1 Using the delete-http-listener subcommand*

The following command deletes the network listener named `sampleListener`:

[source,shell]
----
asadmin> delete-http-listener sampleListener
Command delete-http-listener executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-listener.adoc#create-http-listener[`create-http-listener`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-http-listeners.adoc#list-http-listeners[`list-http-listeners`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-http-listeners.adoc#restart-http-listeners[`restart-http-listeners`]


