[[delete-connector-connection-pool]]
= delete-connector-connection-pool

Removes the specified connector connection pool.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-connector-connection-pool [--help] 
[--target target]
[--cascade={false|true}] poolname
----

[[description]]
== Description

The `delete-connector-connection-pool` subcommand removes the specified connector connection pool.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Do not specify this option. This option is retained for compatibility with earlier releases. If you specify this option, a syntax error does not occur. Instead, the subcommand runs successfully and displays a warning message that the option is ignored.
`--cascade`::
  When set to true, all connector resources associated with the pool, and the pool itself, are deleted. When set to false, the deletion of pool fails if any resources are associated with the pool. The resource must be deleted explicitly or the option must be set to true. Default is false.

[[operands]]
== Operands

poolname::
  The name of the connection pool to be removed.

[[examples]]
== Examples

*Example 1 Deleting a Connector Connection Pool*

This example deletes the connector connection pool named `jms/qConnPool`.

[source,shell]
----
asadmin> delete-connector-connection-pool
--cascade=false jms/qConnPool
Command delete-connector-connection-pool executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-connector-connection-pool.adoc#create-connector-connection-pool[`create-connector-connection-pool`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-connector-connection-pools.adoc#list-connector-connection-pools[`list-connector-connection-pools`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/ping-connection-pool.adoc#ping-connection-pool[`ping-connection-pool`]


