[[delete-module-config]]
= delete-module-config

Removes the configuration of a module from `domain.xml`.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-module-config [--help]
[--target target]
service_name
----

[[description]]
== Description

The `delete-module-config` subcommand removes the configuration of a module from `domain.xml` and causes the module to use the default configuration included in the module.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the link:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which the configuration is to be deleted. +
  Possible values are as follows: +
  `server`;;
    Deletes the configuration from the default server instance. This is the default value.
  `domain`;;
    Deletes the configuration from the default domain.
  cluster-name;;
    Deletes the configuration from every server instance in the specified cluster.
  instance-name;;
    Deletes the configuration from the specified instance.

[[operands]]
== Operands

service_name::
  The name of the module for which configuration is to be removed.

[[examples]]
== Examples

*Example 1 Deleting a Default Configuration From domain.xml*

This example deletes the configuration of the web container module from `domain1` in `server-config` (the default configuration).

[source,shell]
----
asadmin> delete-module-config web-container
Command delete-module-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-module-config.adoc#create-module-config[`create-module-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-active-module-config.adoc#get-active-module-config[`get-active-module-config`]


