[[delete-config]]
= delete-config

Deletes an existing named configuration.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-config [--help]
configuration-name
----

[[description]]
== Description

The `delete-config` subcommand deletes an existing named configuration from the configuration of the domain administration server (DAS). You can delete a configuration only if no Payara Server instances or clusters refer to the configuration. A standalone configuration is automatically deleted when the instance or cluster that refers to it is deleted. You cannot delete the `default-config` configuration that is copied to create standalone configurations.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

configuration-name::
  The name of the configuration that you are deleting.

[[examples]]
== Examples

*Example 1 Deleting a Named Configuration*

This example deletes the named configuration `pmdconfig`.

[source,shell]
----
asadmin> delete-config pmdconfig

Command delete-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/copy-config.adoc#copy-config[`copy-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-configs.adoc#list-configs[`list-configs`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/Configuration.adoc#configuration[`configuration`(5ASC)]


