[[delete-threadpool]]
= delete-threadpool

Removes a thread pool.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-threadpool [--help] 
[--target target] threadpool-id
----

[[description]]
== Description

Removes the thread pool with the specified ID. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target from which you are removing the thread pool. +
  Valid values are as follows: +
  `server`;;
    Deletes the thread pool for the default Payara Server instance `server` and is the default value.
  configuration-name;;
    Deletes the thread pool for the named configuration.
  cluster-name;;
    Deletes the thread pool for every instance in the cluster.
  instance-name;;
    Deletes the thread pool for a particular instance.

[[operands]]
== Operands

threadpool-id::
  An ID for the work queue, for example, `thread-pool1`, `threadpool-2`, and so forth.

[[examples]]
== Examples

*Example 1 Deleting a Thread Pool*

This example deletes `threadpool-l`.

[source,shell]
----
asadmin> delete-threadpool threadpool-1
Command delete-threadpool executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-threadpool.adoc#create-threadpool[`create-threadpool`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-threadpools.adoc#list-threadpools[`list-threadpools`]


