[[delete-iiop-listener]]
= delete-iiop-listener

Removes an IIOP listener.

[[synopsis]]
== Synopsis

[source,shell]
----
delete-iiop-listener [--help] [--target target] listener_id
----

[[description]]
== Description

The `delete-iiop-listener` subcommand removes the specified IIOP listener. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which you are deleting the IIOP listener. Valid values are +
  `server`;;
    Deletes the listener from the default server instance `server` and is the default value.
  configuration_name;;
    Deletes the listener from the named configuration.
  cluster_name;;
    Deletes the listener from every server instance in the cluster.
  instance_name;;
    Deletes the listener from a particular server instance.

[[operands]]
== Operands

listener_id::
  The unique identifier for the IIOP listener to be deleted.

[[examples]]
== Examples

[[example-1]]
*Example 1 Deleting an IIOP Listener*

The following command deletes the IIOP listener named `sample_iiop_listener`:

[source,shell]
----
asadmin> delete-iiop-listener sample_iiop_listener
Command delete-iiop-listener executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-iiop-listener.adoc#create-iiop-listener[`create-iiop-listener`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-iiop-listeners.adoc#list-iiop-listeners[`list-iiop-listeners`]


