[[delete-jndi-resource]]
= delete-jndi-resource

Removes a JNDI resource.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-jndi-resource [--help] 
[--target target] jndi_name
----

[[description]]
== Description

The `delete-jndi-resource` subcommand removes the specified JNDI resource. You must remove all associations to the JNDI resource before running this subcommand.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Valid targets are described below. +

NOTE: Resources are always created for a domain as a whole but are only active for targets for which a `<resource-ref>` has been created using the `--target` option when the resource was created. This means that deleting a resource only deletes the `<resource-ref>` element for the specified `--target`, and does not delete the resource from the domain as a whole unless `domain` is specified as the `--target` for the deletion.

  `server`;;
    Deletes the resource from the default server instance. This is the default value
  `domain`;;
    Deletes the resource from the domain
  cluster_name;;
    Deletes the resource for every server instance in the cluster
  instance_name;;
    Deletes the resource from the specified server instance

[[operandds]]
== Operands

jndi_name::
  The name of the JNDI resource to be removed.

[[examples]]
== Examples

*Example 1 Deleting a JNDI Resource*

This example removes an existing JNDI resource named `sample_jndi_resource`.

[source,shell]
----
asadmin> delete-jndi-resource sample_jndi_resource
Command delete-jndi-resource executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jndi-resource.adoc#create-jndi-resource[`create-jndi-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jndi-resources.adoc#list-jndi-resources[`list-jndi-resources`]


