[[delete-admin-object]]
= delete-admin-object

Removes the administered object with the specified JNDI name.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-admin-object [--help] 
[--target target] jndi_name
----

[[description]]
== Description

The `delete-admin-object` subcommand removes an administered object with the specified JNDI name.

This subcommand is supported in remote mote only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This is the name of the targets for which the administered object is to be deleted. Valid values are: +

NOTE: Resources are always created for a domain as a whole but are only active for targets for which a `<resource-ref>` has been created using
the `--target` option when the resource was created. This means that deleting a resource only deletes the `<resource-ref>` element for the
specified `--target`, and does not delete the resource from the domain as a whole unless `domain` is specified as the `--target` for the deletion.

  `server`;;
    Deletes the administered object for the default server instance `server` and is the default value.
  configuration_name;;
    Deletes the administered object for the specified configuration.
  cluster_name;;
    Deletes the administered object for the specified cluster.
  instance_name;;
    Deletes the administered object for a particular server instance.

[[operands]]
== Operands

jndi_name::
  JNDI name of the administered object to be deleted.

[[examples]]
== Examples

*Example 1 Deleting an Administered Object*

This example deletes the administered object named `jms/samplelqueue`.

[source,shell]
----
asadmin> delete-admin-object jms/samplequeue
Command delete-admin-object executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-admin-object.adoc#create-admin-object[`create-admin-object`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-admin-objects.adoc#list-admin-objects[`list-admin-objects`]


