[[delete-resource-adapter-config]]
= delete-resource-adapter-config

Deletes the resource adapter configuration.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-resource-adapter-config [--help] 
raname
----

[[description]]
== Description

The `delete-resource-adapter-config` subcommand deletes the configuration information for the connector module.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option is deprecated.

[[operands]]
== Operands

raname::
  Specifies the connector module name.

[[examples]]
== Examples

[[example-1]]
*Example 1 Deleting a Resource Adapter Configuration*

This example deletes the configuration information for `ra1`.

[source,shell]
----
asadmin> delete-resource-adapter-config ra1
Command delete-resource-adapter-config executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-resource-adapter-config.adoc#create-resource-adapter-config[`create-resource-adapter-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-resource-adapter-configs.adoc#list-resource-adapter-configs[`list-resource-adapter-configs`]


