[[delete-audit-module]]
= delete-audit-module

Removes the named audit-module.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-audit-module [--help]
[--target target]
audit_module_name
----

[[description]]
== Description

This subcommand removes the named audit module. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target on which you are deleting the audit module. Valid values are as follows: +
  `server`;;
    Deletes the audit module for the default server instance `server` and is the default value.
  configuration_name;;
    Deletes the audit module for the named configuration.
  cluster_name;;
    Deletes the audit module for every server instance in the cluster.
  instance_name;;
    Deletes the audit module for a particular server instance.

[[operands]]
== Operands

audit_module_name::
  The name of the audit module to be deleted.

[[examples]]
== Examples

*Example 1 Deleting an audit module*

[source,shell]
----
asadmin> delete-audit-module sampleAuditModule
Command delete-audit-module executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-audit-module.adoc#create-audit-module[`create-audit-module`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-audit-modules.adoc#list-audit-modules[`list-audit-modules`]


