[[delete-protocol-finder]]
= delete-protocol-finder

Removes a protocol finder.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-protocol-finder [--help]
--protocol protocol-name
[--target server]
protocol-finder-name
----

[[description]]
== Description

The `delete-protocol-finder` subcommand removes the specified protocol finder. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--protocol-name`::
  The name of the associated protocol.
`--target`::
  Deletes the protocol finder only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the protocol finder from the default server instance. This is the default value.
  configuration-name;;
    Deletes the protocol finder from the specified configuration.
  cluster-name;;
    Deletes the protocol finder from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the protocol finder from the specified standalone server instance.

[[operands]]
== Operands

protocol-finder-name::
  The name of the protocol finder to be deleted.

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-protocol-finder.adoc#create-protocol-finder[`create-protocol-finder`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-protocol-finders.adoc#list-protocol-finders[`list-protocol-finders`]


