[[delete-node-docker]]
= delete-node-docker

Deletes a Docker node

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-node-docker [--help]
node-name
----

[[description]]
== Description

The `delete-node-docker` subcommand deletes a Docker node. The command will assume that the node's configuration to be able to reach the container are still valid and will de-register the node configuration from the DAS and will automatically remove the container that corresponds to the deleted node.

If the settings of the Docker node are not valid or if the Docker engine is not reachable through its REST API endpoint, an error will occur and the command will fail.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[operands]]
== Operands

node-name::
The name of the node to delete.

[[examples]]
== Examples

[[example-1]]

*Example 1 Deleting a Docker Node*

This example deletes the node `docker-node-1`:

[source,shell]
----
asadmin> delete-node-docker docker-node-1
Command delete-node-docker executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-docker.adoc#create-node-docker[`create-node-docker`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-instance.adoc#delete-instance[`delete-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc#list-nodes[`list-nodes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-node-docker.adoc#update-node-docker[`update-node-docker`]


