[[delete-connector-work-security-map]]
= delete-connector-work-security-map

Deletes a work security map for the specified resource adapter.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-connector-work-security-map [--help] 
--raname raname
mapname
----

[[description]]
== Description

The `delete-connector-work-security-map` subcommand deletes a security map associated with the specified resource adapter. For this subcommand to succeed, you must have first created and deployed the specified resource adapter.

The enterprise information system (EIS) is any system that holds the data of an organization. It can be a mainframe, a messaging system, a database system, or an application.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--raname`::
  Indicates the connector module name with which the work security map is associated.

[[operands]]
== Operands

mapname::
  The name of the work security map to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Connector Work Security Map*

This example deletes the work security map named `work_security_map_name` for the resource adapter named `ra_name`.

[source,shell]
----
asadmin delete-connector-work-security-map
--raname ra_name work_security_map_name
Command delete-connector-work-security-map executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-connector-work-security-map.adoc#create-connector-work-security-map[`create-connector-work-security-map`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-connector-work-security-maps.adoc#list-connector-work-security-maps[`list-connector-work-security-maps`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-connector-work-security-map.adoc#update-connector-work-security-map[`update-connector-work-security-map`]


