[[delete-http-lb]]
= delete-http-lb

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Deletes a load balancer.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-lb [--help] 
load_balancer_name
----

[[description]]
== Description

Use the `delete-http-lb` subcommand to delete a physical load balancer.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

load_balancer_name::
  The name of the load balancer to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Load Balancer Configuration*

This example deletes the load balancer configuration named `mylb`.

[source,shell]
----
asadmin> delete-http-lb mylb

Command delete-http-lb executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb.adoc#create-http-lb[`create-http-lb`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-http-lbs.adoc#list-http-lbs[`list-http-lbs`]


