[[delete-lifecycle-module]]
= delete-lifecycle-module

Removes the lifecycle module.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-lifecycle-module [--help] 
[--target target] module_name
----

[[description]]
== Description

The `delete-lifecycle-module` subcommand removes a lifecycle module. A lifecycle module provides a means of running a short or long duration Java-based task at a specific stage in the server life cycle. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Indicates the location where the lifecycle module is to be deleted. Valid values are +
  * `server`- Specifies the default server instance as the target for deleting the lifecycle module. `server` is the name of the default server instance and is the default value for this option.
  * cluster_name - Specifies a particular cluster as the target for deleting the lifecycle module.
  * instance_name - Specifies a particular server instance as the target for deleting the lifecycle module.

[[operands]]
== Operands

module_name::
  This operand is a unique identifier for the deployed server lifecycle event listener module.

[[examples]]
== Examples

*Example 1 Deleting a Lifecycle Module*

The following example deletes a lifecycle module named `customSetup`.

[source,shell]
----
asadmin> delete-lifecycle-module customSetup
Command delete-lifecycle-module executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-lifecycle-module.adoc#create-lifecycle-module[`create-lifecycle-module`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-lifecycle-modules.adoc#list-lifecycle-modules[`list-lifecycle-modules`]


