[[delete-resource-ref]]
= delete-resource-ref

Removes a reference to a resource.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-resource-ref [--help] 
[--target target] reference_name
----

[[description]]
== Description

The `delete-resource-ref` subcommand removes from a cluster or an unclustered server instance a reference to a resource (for example, a JDBC resource). This effectively results in the removal of the resource from the JNDI tree of the targeted instance or cluster.

The target instance or instances making up the cluster need not be running or available for this subcommand to succeed. If one or more instances are not available, they will no longer load the resource in the JNDI tree the next time they start.

Removal of the reference does not result in removal of the resource from the domain. The resource is removed only by the `delete` subcommand for that resource (for example, `delete-jdbc-resource`).

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which you are removing the resource reference. Valid values are +
  `server`;;
    Removes the resource reference from the default server instance `server` and is the default value.
  cluster_name;;
    Removes the resource reference from every server instance in the cluster.
  instance_name;;
    Removes the resource reference from the named unclustered server instance.

[[operands]]
== Operands

reference_name::
  The name or JNDI name of the resource.

[[examples]]
== Examples

[[example-1]]
*Example 1 Removing a Reference to a Resource*

This example removes a reference to the JMS destination resource `jms/Topic` on the cluster `cluster1`.

[source,shell]
----
asadmin> delete-resource-ref --target cluster1 jms/Topic
resource-ref jms/Topic deleted successfully.
Command delete-resource-ref executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-resource-ref#create-resource-ref[`create-resource-ref`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-resource-refs#list-resource-refs[`list-resource-refs`]


