[[delete-http-lb-config]]
= delete-http-lb-config

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Deletes a load balancer configuration.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-lb-config [--help] 
config_name
----

[[description]]
== Description

Use the `delete-http-lb-config` subcommand to delete a load balancer configuration. The load balancer configuration must not reference any clusters or server instances enabled for load balancing. In addition, the load balancer configuration must not be referenced by any physical load balancers.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

config_name::
  The name of the load balancer configuration to delete. The configuration must not reference any clusters or server instances enabled for load balancing, or be used by any physical load balancers.

[[examples]]
== Examples

*Example 1 Deleting a Load Balancer Configuration*

This example deletes a load balancer configuration named `mylbconfig`

[source,shell]
----
asadmin> delete-http-lb-config mylbconfig
Command delete-http-lb-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb-config.adoc#create-http-lb-config[`create-http-lb-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-http-lb-configs.adoc#list-http-lb-configs[`list-http-lb-configs`]


