[[delete-network-listener]]
= delete-network-listener

Removes a network listener.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-network-listener [--help]
[--target target]
listener-name
----

[[description]]
== Description

The `delete-network-listener` subcommand removes the specified network listener. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the network listener only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the network listener from the default server instance. This is the default value.
  configuration-name;;
    Deletes the network listener from the specified configuration.
  cluster-name;;
    Deletes the network listener from all server instances in the
    specified cluster.
  standalone-instance-name;;
    Deletes the network listener from the specified standalone server instance.

[[operands]]
== Operands

listener-name::
  The name of the network listener to be deleted.

[[examples]]
== Examples

[[example-1]]
*Example 1 Deleting a Network Listener*

The following command deletes the network listener named `sampleListener`:

[source,shell]
----
asadmin> delete-network-listener sampleListener
Command delete-network-listener executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-network-listener.adoc#create-network-listener[`create-network-listener`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-network-listener-configuration.adoc#set-network-listener-configuration[`set-network-listener-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-network-listeners.adoc#list-network-listeners[`list-network-listeners`]


