[[delete-protocol]]
= delete-protocol

Removes a protocol.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-protocol [--help]
[--target target]
protocol-name
----

[[description]]
== Description

The `delete-protocol` subcommand removes the specified protocol. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Deletes the protocol only from the specified target. Valid values are as follows: +
  `server`;;
    Deletes the protocol from the default server instance. This is the default value.
  configuration-name;;
    Deletes the protocol from the specified configuration.
  cluster-name;;
    Deletes the protocol from all server instances in the specified cluster.
  standalone-instance-name;;
    Deletes the protocol from the specified standalone server instance.

[[operands]]
== Operands

protocol-name::
  The name of the protocol to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Protocol*

The following command deletes the protocol named `http-1`:

[source,shell]
----
asadmin> delete-protocol http-1
Command delete-protocol executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-protocol.adoc#create-protocol[`create-protocol`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-protocols.adoc#list-protocols[`list-protocols`]


