[[delete-profiler]]
= delete-profiler

Removes the profiler element.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-profiler [--help] 
[--target target_name]
----

[[description]]
== Description

The `delete-profiler` subcommand deletes the profiler element in the Java configuration. Only one profiler can exist at a time. If you
attempt to create a profiler while one already exists, an error message is displayed and the existing profiler must be deleted.

For changes to take effect, the server must restarted.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target profiler element which you are deleting. Valid values are +
  `server`;;
    Deletes the profiler element for the default server instance `server` and is the default value.
  configuration_name;;
    Deletes the profiler element for the named configuration.
  cluster_name;;
    Deletes the profiler element for every server instance in the cluster.
  instance_name;;
    Deletes the profiler element for a particular server instance.

[[examples]]
== Examples

*Example 1 Deleting a Profile*

This example deletes the profiler named `sample_profiler`.

[source,shell]
----
asadmin> delete-profiler sample_profiler
Command delete-profiler executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-profiler.adoc#create-profiler[`create-profiler`]


