[[delete-managed-scheduled-executor-service]]
= delete-managed-scheduled-executor-service

Removes a managed scheduled executor service resource with the specified JNDI name.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-managed-scheduled-executor-service [--help]
[--target target]
managed_scheduled_executor_service_name
----

[[description]]
== Description

The `delete-managed-scheduled-executor-service` subcommand removes a managed scheduled executor service resource with the specified JNDI name.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
Specifies the target from which you are deleting the resource. Valid targets are:
+
`server`;;
Deletes the resource from the default server instance. This is the default value.
`domain`;;
Deletes the resource from the domain.
cluster_name;;
Deletes the resource from every server instance in the specified cluster.
instance_name;;
Deletes the resource from the specified server instance.

[[operands]]
== Operands

managed_scheduled_executor_service_name::
The JNDI name of the resource to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Managed Scheduled Executor Service Resource*

This example deletes the managed scheduled executor service resource named `concurrent/myScheduledExecutor`.

[source,shell]
----
asadmin> delete-managed-scheduled-executor-service concurrent/ScheduledExecutor1
Managed scheduled executor service concurrent/ScheduledExecutor1 deleted successfully.
Command delete-managed-scheduled-executor-service executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-managed-scheduled-executor-service.adoc#create-managed-scheduled-executor-service[`create-managed-scheduled-executor-service`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-managed-scheduled-executor-services.adoc#list-managed-scheduled-executor-services[`list-managed-scheduled-executor-services`]


