[[delete-cluster]]
= delete-cluster

deletes a Payara Server cluster

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-cluster [--help]
[--autohadboverride={true|false}] [--node-agent=node-agent--name]
cluster-name
----

[[description]]
== Description

The `delete-cluster` subcommand deletes a Payara Server cluster. A cluster can be deleted only if the cluster contains no Payara Server
instances. If a cluster that you are deleting contains any instances, stop and delete the instances before deleting the cluster.

If the cluster's named configuration was created automatically for the cluster and no other clusters or unclustered instances refer to the
configuration, the configuration is deleted when the cluster is deleted.A configuration that is created automatically for a cluster is named
cluster-name`-config`, where cluster-name is the name of the cluster.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--autohadboverride`::
  Do not specify this option. This option is retained for compatibility with earlier releases. If you specify this option, a syntax error does not occur. Instead, the subcommand runs successfully and displays a warning message that the option is ignored.
`--nodeagent`::
  Do not specify this option. This option is retained for compatibility with earlier releases. If you specify this option, a syntax error does not occur. Instead, the subcommand runs successfully and displays a warning message that the option is ignored.

[[operands]]
== Operands

cluster-name::
  The name of the cluster to delete.

[[examples]]
== Examples

*Example 1 Deleting a Payara Server Cluster*

This example deletes the Payara Server cluster `adccluster`.

[source,shell]
----
asadmin> delete-cluster adccluster
Command delete-cluster executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-cluster.adoc#create-cluster[`create-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-instance.adoc#delete-instance[`delete-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-clusters.adoc#list-clusters[`list-clusters`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-cluster.adoc#start-cluster[`start-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-instance.adoc#stop-instance[`stop-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-local-instance.adoc#stop-local-instance[`stop-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-cluster.adoc#stop-cluster[`stop-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-cluster#restart-cluster[`restart-cluster`]


