[[delete-auth-realm]]
= delete-auth-realm

Removes the named authentication realm.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-auth-realm [--help]
[--target target]
auth_realm-name
----

[[description]]
== Description

The `delete-auth-realm` subcommand removes the named authentication realm. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target on which you are deleting the authentication realm. Valid values are +
  `server`;;
    Deletes the realm for the default server instance `server` and is the default value.
  configuration_name;;
    Deletes the realm for the named configuration.
  cluster_name;;
    Deletes the realm for every server instance in the cluster.
  instance_name;;
    Deletes the realm for a particular server instance.

[[operands]]
== Operands

auth_realm_name::
  Name of the realm to be deleted.

[[examples]]
== Examples

*Example 1 Deleting an Authentication Realm*

This example deletes the authentication realm `db`.

[source,shell]
----
asadmin> delete-auth-realm db
Command delete-auth-realm executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-auth-realm.adoc#create-auth-realm[`create-auth-realm`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-auth-realms.adoc#list-auth-realms[`list-auth-realms`]


