[[deployment-group]]
= Deployment Group
:ordinal: 5

A deployment group is a loose grouping of Payara Server instances that can be used as a target for *deployments*. Deployment Groups consist of one or more standalone instances and each instance can belong to one or more deployment groups.

[[description]]
== Description

Deployment groups are effective and more flexible replacements for traditional clusters, as they can be used to effectively manage the lifecycle of multiple server instances at once.

When you create a Deployment Group you can add and remove existing standalone instances from the group. However, Deployment Groups provide greater flexibility than traditional clusters:

* An instance can be in many different deployment groups.

* You can add an instance to a deployment group at any time and any targeted applications or resources will automatically be deployed.

* You can also remove an instance from a deployment group and applications and resources will be un-deployed.

Payara Server instances in the deployment group are not hidden in the administration console and are still visible for management under the 'Instances' section of the admin console navigation tree.
