[[disable-secure-admin]]
= disable-secure-admin

Disables secure admin if it is already enabled.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] disable-secure-admin [--help]
----

[[description]]
== Description

The `disable-secure-admin` subcommand disables secure admin if it is already enabled.

NOTE: You must restart any running servers in the domain after you enable or disable secure admin. It is simpler to enable or disable secure admin with only the DAS running, then restart the DAS, and then start any other instances.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

[[example-1]]

*Example 1 Disabling `secure admin` for a domain*

The following example shows how to disable `secure admin` for a domain.

[source,shell]
----
asadmin> disable-secure-admin
server-config
default-config

Command disable-secure-admin executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-secure-admin.adoc#enable-secure-admin[`enable-secure-admin`]


