[[disable-phone-home]]
= disable-phone-home

Disables the phone home services.

[[synopsis]]
== Synopsis

[source, shell]
----
asadmin> disable-phone-home
----

[[description]]
== Description

The phone home data is presently used to gather usage statistics about the corresponding distribution, such as how long users typically run instances, and what versions they use.
The phone home service is enabled by default when starting a Payara Server and can be disabled by using this command. Make sure to restart Payara Server for the changes to take effect.


[[examples]]
== Examples

*Example 1 Disable Phone Home Service*

[source, shell]
----
asadmin>  disable-phone-home
Phone Home Service is disabled

Command disable-phone-home executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-phone-home.adoc#enable-phone-home[`enable-phone-home`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-phone-home.adoc#list-phone-home[`list-phone-home`]


