[[disable-asadmin-recorder]]
= disable-asadmin-recorder

Disables the Asadmin recorder.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] disable-asadmin-recorder [--help]
----

[[description]]
== Description

The `disable-asadmin-recorder` subcommand deactivates the Asadmin Recorder feature, ceasing the capture and logging of asadmin commands executed through the Admin Console.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Disabling asadmin Recorder*

This example deactivates the Asadmin Recorder feature.

[source,shell]
----
asadmin disable-asadmin-recorder

Command disable-asadmin-recorder executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-asadmin-recorder.adoc#enable-asadmin-recorder[`enable-asadmin-recorder`]
