[[disable]]
= disable

Disables the component.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] disable [--help]
[--target target_name] component_name
----

[[description]]
== Description

The `disable` subcommand immediately disables the specified deployed component. If the component has not been deployed, an error message is returned.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are disabling the component. Valid values are: +
  `server`;;
    Disables the component on the default server instance `server` and is the default value.
  domain_name;;
    Disables the component on the named domain.
  cluster_name;;
    Disables the component on every server instance in the cluster.
  instance_name;;
    Disables the component on a particular clustered or stand-alone server instance.

[[operands]]
== Operands

component_name::
  name of the component to be disabled. +
  The name can include an optional version identifier, which follows the name and is separated from the name by a colon (`:`). The version identifier must begin with a letter or number. It can contain alphanumeric characters plus underscore (`_`), dash (`-`), and period (`.`) characters. To disable multiple versions, you can use an asterisk (`*`) as a wildcard character. For more information about module and application versions, see "xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc#module-and-application-versions[Module and Application Versions]" in Payara Server Application Deployment section.

[[examples]]
== Examples

*Example 1 Disabling a Component*

This example disables the deployed component `sampleApp`.

[source,shell]
----
asadmin> disable sampleApp
Command disable executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc#deploy[`deploy`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable.adoc#enable[`enable`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/undeploy.adoc#undeploy[`undeploy`]
* link:../application-deployment-guide/toc.html#GSDPG[Payara Server Application Deployment section]


