[[disable-monitoring]]
= disable-monitoring

Disables monitoring for the server or for specific monitorable module.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] disable-monitoring [--help]
[--modules module-name][:module-name]*
----

[[description]]
== Description

The `disable-monitoring` subcommand is used to turn off monitoring for Payara Server or for particular modules during runtime. Changes are dynamic, that is, server restart is not required.

Running the `disable-monitoring` subcommand without the `--module` option disables the monitoring service by setting the `monitoring-enabled` attribute of the `monitoring-service` element to `false`. The individual modules retain their monitoring levels, but no monitoring data is generated because the entire monitoring service is disabled.

This subcommand used with the `--modules` option disables monitoring for a module by setting the monitoring level to OFF. The status of the monitoring service is not affected. For a list of monitorable modules, see the `--modules` option in this help page.

An alternative method for disabling monitoring is to use the `set` subcommand. In this case, the server must be restarted for changes to take effect.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--modules`::
  Disables the specified module or modules by setting the monitoring level to OFF. Multiple modules are separated by : (colon). Monitorable modules include `connector-connection-pool`, `connector-service`, `ejb-container`, `http-service`, `jdbc-connection-pool`, `jersey`, `jpa`, `jms-service`, `jvm`, `security`, `thread-pool`, `transaction-service`, `web-container`, and `web-services-container`. Additional modules can be listed by using the `get` subcommand.

[[operands]]
== Operands

[[examples]]
== Examples

[[example-1]]

*Example 1 Disabling the Monitoring Service for Payara Server*

This example disables monitoring for Payara Server in general by setting the `enable-monitoring` flag to `false` (default is `true`).

[source,shell]
----
asadmin> disable-monitoring
Command disable-monitoring executed successfully
----

[[example-2]]

*Example 2 Disabling Monitoring for the Web and EJB Containers*

This example disables monitoring for specific containers. Their monitoring levels will be set to OFF.

[source,shell]
----
asadmin> disable-monitoring --modules web-container:ejb-container
Command disable-monitoring executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get.adoc#get[`get`], xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-monitoring.adoc#enable-monitoring[`enable-monitoring`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list.adoc#list[`list`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitor.adoc#monitor[`monitor`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set.adoc#set[`set`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc#monitoring[`monitoring`]
* "xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Monitoring Service.adoc#administering-the-monitoring-service[Administering the Monitoring Service]" in Payara Server General Administration section


