[[enable-asadmin-recorder]]
= enable-asadmin-recorder

Enables the asadmin recorder.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] enable-asadmin-recorder [--help]
----

[[description]]
== Description

The `enable-asadmin-recorder` subcommand activates the Asadmin Recorder feature, allowing for the capture and logging of all asadmin commands executed through the Admin Console.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Enabling asadmin Recorder*

This example activates the Asadmin Recorder feature.

[source,shell]
----
asadmin enable-asadmin-recorder

Command enable-asadmin-recorder executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-asadmin-recorder.adoc#disable-asadmin-recorder[`disable-asadmin-recorder`]


