[[enable-http-lb-application]]
= enable-http-lb-application

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Enables a previously-disabled application managed by a load balancer.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] enable-http-lb-application [--help] 
--name application_name target
----

[[description]]
== Description

The `enable-http-lb-application` subcommand enables load balancing for applications deployed on a standalone instance or cluster. You can enable load balancing for an application on all instances in a cluster, or on a single standalone server instance. By default, load balancing is enabled for applications.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--name`::
  The name of the application to be enabled.

[[operands]]
== Operands

target::
  This operand specifies on which server instance or cluster to enable the application. Valid values are: +
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

*Example 1 Enabling Load Balancing for an Application*

This example enables an application named `webapps-simple` to use load balancing on a cluster named `mycluster`.

[source,shell]
----
asadmin> enable-http-lb-application --name webapps-simple mycluster

Command enable-http-lb-application executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-http-lb-application.adoc#disable-http-lb-application[`disable-http-lb-application`]


