[[enable]]
= enable

Enables the component.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] enable [--help]
[--target target_name] component_name
----

[[description]]
== Description

The `enable` subcommand enables the specified deployed component. If the component is already enabled, then it is re-enabled. If it has not been deployed, then an error message is returned.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are enabling the component. Valid values are: +
  `server`;;
    Enables the default server instance `server` and is the default value.
  domain_name;;
    Enables the named domain.
  cluster_name;;
    Enables every server instance in the cluster.
  instance_name;;
    Enables a particular clustered or stand-alone server instance.

[[operands]]
== Operands

component_name::
  name of the component to be enabled. +
  The name can include an optional version identifier, which follows the name and is separated from the name by a colon (`:`). The version identifier must begin with a letter or number. It can contain alphanumeric characters plus underscore (`_`), dash (`-`), and period (`.`) characters. For more information about module and application versions, see "xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc#module-and-application-versions[Module and Application Versions]" in Payara Server Application Deployment section. +
  At most one version of a module or application can be enabled on a server instance. All other versions are disabled. Enabling one version automatically disables all others.

[[examples]]
== Examples

*Example 1 Enabling a Component*

This example enables the disabled component, `sampleApp`.

[source,shell]
----
asadmin> enable sampleApp
Command enable executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc#deploy[`deploy`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable.adoc#disable[`disable`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/undeploy.adoc#undeploy[`undeploy`]
* xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc[Payara Server Application Deployment section]


