[[flush-connection-pool]]
= flush-connection-pool

Reintializes all connections established in the specified connection pool.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] flush-connection-pool [--help] 
[--appname application [--modulename module]
pool_name 
----

[[description]]
== Description

The `flush-connection-pool` subcommand resets a JDBC connection pool or a connector connection pool to its initial state. Any existing live connections are destroyed, which means that the transactions associated with these connections are lost. The subcommand then recreates the initial connections for the pool, and restores the pool to its steady pool size.

This subcommand is supported in remote mode only.

Application Scoped Resources

The `flush-connection-pool` subcommand can target resources that are scoped to a specific application or module, as defined in the `glassfish-resources.xml` or `payara-resources.xml` for the Payara Server domain.

* To reference the `jndi-name` for an application scoped resource, perform the lookup using the `java:app` prefix.
* To reference the `jndi-name` for a module scoped resource, perform the lookup using the `java:module` prefix.

The `jndi-name` for application-scoped-resources or module-scoped-resources are specified using the format `java:app/`jdbc/myDataSource` or `java:module/`jdbc/myModuleLevelDataSource`. This naming scope is defined in the Jakarta EE Specification (`https://jakarta.ee/specifications/`).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--appname`::
  Name of the application in which the application scoped resource is defined.
`--modulename`::
  Name of the module in which the module scoped resource is defined.

[[operands]]
== Operands

pool_name::
  Name of the connection pool to be reinitialized.

[[flushing-a-connection-pool]]
== Flushing a Connection Pool

*This example reinitializes the JDBC connection pool named `__TimerPool`.*

[source,shell]
----
asadmin> flush-connection-pool __TimerPool
Command flush-connection-pool executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-connector-connection-pools.adoc#list-connector-connection-pools[`list-connector-connection-pools`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jdbc-connection-pools.adoc#list-jdbc-connection-pools[`list-jdbc-connection-pools`]


