[[flush-jmsdest]]
= flush-jmsdest

Purges messages in a JMS destination.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] flush-jmsdest [--help]
--desttype {topic|queue}
[--target target]
destname
----

[[description]]
== Description

The `flush-jmsdest` subcommand purges the messages from a physical destination in the server's Java Message Service (JMS) configuration.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--desttype`::
  This option indicates the type of physical destination from which you want to purge messages. The supported destination types are `topic` and `queue`.
`--target`::
  Purges messages from the physical destination only for the specified target. Valid values are as follows: +
  `server`;;
    Purges messages from the physical destination for the default server instance. This is the default value.
  configuration-name;;
    Purges messages from the physical destination in the specified configuration.
  cluster-name;;
    Purges messages from the physical destination for every server instance in the specified cluster.
  instance-name;;
    Purges messages from the physical destination for the specified server instance.

[[operands]]
== Operands

dest_name::
  The unique identifier of the JMS destination to be purged.

[[examples]]
== Examples

[[example-1]]

*Example 1 Purging messages from a physical destination*

The following subcommand purges messages from the queue named `PhysicalQueue`.

[source,shell]
----
asadmin> flush-jmsdest --desttype queue PhysicalQueue
Command flush-jmsdest executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jmsdest.adoc#create-jmsdest[`create-jmsdest`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jmsdest.adoc#list-jmsdest[`list-jmsdest`]


