[[generate-encryption-key]]
= generate-encryption-key

Generates an encryption key for Data Grid secure communication.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] generate-encryption-key
[--help]
[--dontCheckIfRunning={true|false}]
[--domaindir domaindir]
[domain-name]
----

[[description]]
== Description

This command can be used to generate an encryption key used by Payara Server to perform encryption and decryption of the data stored within the Data Grid.

For more information on the Data Grid mechanism, see xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc#datagrid-encryption[Data Grid Encryption].

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--dontCheckIfRunning`::
Determines whether to check if the targeted domain is running or not.
+
The default value is `false`.
`--domaindir`::
The path to the directory containing the target domain. The default domain directory is `as-install/domains`.

[[operands]]
== Operands

domain-name::
The name of the domain to target. The default is `domain1`.

[[examples]]
== Examples

*Example 1 Generates an encryption key.*

This example generates an encryption key used by Payara Server to perform encryption and decryption of the data stored within the data grid.

[source, shell]
----
asadmin> generate-encryption-key
Enter the current master password>
Command generate-encryption-key executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc[Domain Data Grid],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-cluster-members.adoc[`list-hazelcast-cluster-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-hazelcast.adoc[`restart-hazelcast`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-cache-keys.adoc[`list-cache-keys`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-caches.adoc[`list-caches`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/clear-cache.adoc[`clear-cache`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-hazelcast-configuration.adoc[`get-hazelcast-configuration`]
