[[generate-bash-autocomplete]]
= generate-bash-autocomplete

Creates an Asadmin CLI autocompletion script for bash.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin generate-bash-autocomplete [--help]
[--force=false]
[--localcommands=false]
[file]
----

[[description]]
== Description

The created file will be located in the server’s host and not the client. If they are on different hosts, then the file will be needed to copied from the server to the client.

TIP: You can add the resulting file to your bash path by adding source `path/to/outputfile` to your .bashrc settings or copy the file into the `/etc/bash_completion.d` directory.

This means that you can run asadmin commands by typing asadmin in a terminal, and you can use double-tab to autocomplete a command, similar to other bash commands.

[[options]]
== Options

`--help`::
`-?`::
  Displays the help text for the subcommand.

`--force`::
Whether to overwrite a script file if one already exists. The default value is `false`.

`--file`::
The path for the resulting file. The default value is `as-install/bin/bash_autocomplete`.

`--localCommands`::
This option will include local asadmin commands.
+
The default value is `false`.

[[examples]]
== Examples

[[example-1]]

*Example 1 Creating an asadmin autocompletion script for bash.*

This example shows a script that is generated if no file is specified.

[source,shell]
----
asadmin generate-bash-autocomplete
Written bash autocomplete file to /export/payara6/glassfish/bin/bash_autocomplete
Command generate-bash-autocomplete executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand
