[[get-ejb-invoker-configuration]]
= get-ejb-invoker-configuration

Retrieves the `ejb-invoker` application settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-ejb-invoker-configuration [--help]
[--target] target
----

[[description]]
== Description

Returns the current configuration options for the `ejb-invoker` application on the targeted configuration.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
Specifies the target for which retrieve the EJB invoker endpoint's configuration. Valid values are as follows: +
`server`;;
Retrieves the configuration for the EJB invoker endpoint configured for the default server instance `server` and is the default value.
cluster-name;;
Retrieves the configuration for the EJB invoker endpoint configured for every server instance in the cluster.
deployment-group-name;;
Retrieves the configuration for the EJB invoker endpoint configured for every server instance in the deployment group.
instance-name;;
Retrieves the configuration for the EJB invoker endpoint configured for a particular server instance.

[[examples]]
== Examples

The following command returns the current configuration options from the deployment group `test-dg`:

[source, shell]
----
asadmin> get-ejb-invoker-configuration --target test-dg
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-ejb-invoker-configuration.adoc#set-ejb-invoker-configuration[`set-ejb-invoker-configuration`]
