[[get-requesttracing-configuration]]
= get-requesttracing-configuration

Retrieves the Request Tracing service's configuration.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-requesttracing-configuration [--help]
----

[[description]]
== Description

This command can be used to list the configuration settings of the Request Tracing.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Retrieve Request Tracing Service Configuration*

[source, shell]
----
asadmin> get-requesttracing-configuration
----

Will give an output similar to the following:

----
Request Tracing Service Enabled?: true
Request Tracing Service Sample Rate: 1.0
Request Tracing Service Adaptive Sampling Enabled?: false
Request Tracing Service Application Only?: true
Request Tracing Service Threshold Value: 30
Request Tracing Service Threshold Unit: SECONDS
Request Tracing Service Sample Rate First?: true
Request Tracing Service Reservoir Sampling Enabled?: false
Request Tracing Service Trace Store Size: 20
Request Tracing Service Historic Trace Store Enabled?: false
Below are the configuration details of each notifier listed by its name.

Notifier Name         Notifier Enabled
jms-notifier          false
log-notifier          true
cdieventbus-notifier  false
eventbus-notifier     false
Command get-requesttracing-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-requesttracing-configuration.adoc#set-requesttracing-configuration[`set-requesttracing-configuration`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-requesttraces.adoc#list-requesttraces[`list-requesttraces`]
