[[get-config-property]]
= get-config-property

Provides a way to get a configuration property value for a particular configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-config-property --propertyName=<property.name> --source=domain|config|server|application|module|cluster --sourceName=<source.name> --moduleName=<module.name> --target=<target[default:server]>
----

[[description]]
== Description

The `get-config-property` gets the value for the given property name in one of the built-in config sources. The source is specified with --source and, where there is ambiguity, the --sourceName and --moduleName options can be used. For example, where the source is server, the --sourceName can be used to specify the name of the server where the config property is to be stored.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--propertyName`::
The name of the configuration property to get.
`--source`::
The ConfigSource where the property is stored.
`--sourceName`::
The name of the ConfigSource when there may be ambiguity, for example a ConfigSource of type application must specify the name of the application. This property is required for sources of type: config, server, application or module
`--moduleName`::
The name of the module when the ConfigSource is of type module. When this is specified, the sourceName parameter must be provided and must have the name of the application where the module is deployed.
`--target`::
Defaults to server (the DAS). The target configuration where the command should be run


[[examples]]
== Example

*Example 1 Getting the configuration property value*

This example gets the JMSBrokerURL property value within the configuration source named myApplication, belonging to the module myModule, and targeting the myAppCluster cluster.

[source,shell]
----
asadmin> get-config-property
    --propertyName=JMSBrokerURL
    --source=module
    --sourceName=myApplication
    --moduleName=myModule
    --target=myAppCluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-config-property.adoc#delete-config-property[`delete-config-property`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-config-property.adoc#set-config-property[`set-config-property`]
