[[get-config-ordinal]]
= get-config-ordinal

Returns the ordinal value for the given ConfigSource type.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-config-ordinal --source=domain|config|server|application|module|cluster
----

[[description]]
== Description

The `get-config-ordinal` returns ordinal value for the given ConfigSource type.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--source`::
The ConfigSource to get
the ordinal for. Must be one of: domain, config, server, application, module, cluster
[[examples]]
== Example

*Example 1 Getting the ordinal value*

This example gets the ordinal value for the source 'cluster'.

[source,shell]
----
asadmin> get-config-ordinal --source=cluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-config-ordinal.adoc#set-config-ordinal[`set-config-ordinal`]

