[[get-dynamodb-config-source-configuration]]
= get-dynamodb-config-source-configuration

Gets the configuration for the DynamoDB configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-dynamodb-config-source-configuration [--help]
[--target=server]
----

[[description]]
== Description

The `get-dynamodb-config-source-configuration` retrieves the current configuration for the DynamoDB Config Source.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting the configuration of the DynamoDB secrets*

This example retrieves the current configuration for the DynamoDB Config Source.

[source,shell]
----
asadmin get-dynamodb-config-source-configuration
Enabled  Region Name  Table Name  Key Column Name  Value Column Name  Limit
true     eu-west-2    Books       ISBN             Title              10
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-dynamodb-config-source-configuration.adoc#set-dynamodb-config-source-configuration[`set-dynamodb-config-source-configuration`]

