[[get-microprofile-healthcheck-configuration]]
= get-microprofile-healthcheck-configuration

Retrieves the configuration settings of the MicroProfile HealthCheck service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-microprofile-healthcheck-configuration [--help]
[--target=server-config]
----

[[description]]
== Description

The `get-microprofile-healthcheck-configuration` returns the current configuration options for the MicroProfile Health Check service on the specified target.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--target`::
Specifies the target of this command. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting MicroProfile Health Check configuration*

This example gets the current configuration of the Health Check service.

[source,shell]
----
asadmin get-microprofile-healthcheck-configuration --target=instance1

Enabled  EndPoint  VirtualServers  Security Enabled  Roles
true     health                    false             microprofile
Command get-microprofile-healthcheck-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-microprofile-healthcheck-configuration.adoc#set-microprofile-healthcheck-configuration[`set-microprofile-healthcheck-configuration`]
