[[get-ldap-config-source-configuration]]
= get-ldap-config-source-configuration

Gets the settings of the LDAP configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-ldap-config-source-configuration [--help] [--target=server]
----

[[description]]
== Description

The `get-ldap-config-source-configuration` gets the current configuration settings for the LDAP configuration source.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.

[[examples]]
== Example

*Example 1 Getting the LDAP configuration*

This example retrieves the current configuration for the LDAP Config Source.

[source,shell]
----
asadmin get-ldap-config-source-configuration
Enabled     Url                             Auth Type       Start TLS Enabled       BindDN                                  BindDN Password     Search Base     Search Filter       Search Scope        Connection Timeout      Read Timeout
true        ldap://ldap.forumsys.com:389    simple          false                   cn=read-only-admin,dc=example,dc=com    password
----


[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-ldap-config-source-configuration.adoc#set-ldap-config-source-configuration[`set-ldap-config-source-configuration`]

