[[get-config-dir]]
= get-config-dir

Gets the value of the Config Directory.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-config-dir --target=<target[default:server]>`
----

[[description]]
== Description

The `get-config-dir` gets the value of the directory to be used for the directory config source.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
Defaults to `server-config`. The target configuration where the command should be run.

[[examples]]
== Example

*Example 1 Getting the Config Directory.*

This example gets the directory to be used for the directory config source.

[source,shell]
----
asadmin> get-config-dir --target=myAppCluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-config-dir.adoc#set-config-dir[`set-config-dir`]
