[[get-healthcheck-configuration]]
= get-healthcheck-configuration

Lists the current Healthcheck service settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-healthcheck-configuration
[--help]
[--target target]
----

[[description]]
== Description

Lists the current configuration for the health check service, configured checkers and enabled notifiers.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the Healthcheck service settings. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieves configuration in the DAS*

A sample output is as follows:

[source, shell]
----
asadmin get-healthcheck-configuration

Health Check Service Configuration is enabled?: true
Historical Tracing Enabled?: true
Historical Tracing Store Size: 20

Name                  Notifier Enabled
log-notifier          true
jms-notifier          false
cdieventbus-notifier  false
eventbus-notifier     false

Below are the list of configuration details of each checker listed by its name.

Name  Enabled  Time  Unit     Add to MicroProfile Health  Critical Threshold  Warning Threshold  Good Threshold
CPUC  true     5     MINUTES  true                        80                  50                 0
HEAP  true     5     MINUTES  false                       80                  50                 0

Name   Enabled  Time  Unit     Add to MicroProfile Health  Threshold Time  Threshold Unit
STUCK  true     5     MINUTES  false                       5               MINUTES

Name  Enabled  Time  Unit     Add to MicroProfile Health
MPM   true     5     MINUTES  false

Monitored Metric Name  Description
base_thread_max_count Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.
base_gc_total_total    Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.

Command get-healthcheck-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-healthcheck-service-configuration.adoc[`set-healthcheck-service-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-healthcheck-services.adoc[`list-healthcheck-services`]
