[[get-monitoring-level]]
= get-monitoring-level

Retrieves the level configuration of a monitoring service's server module.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-monitoring-level
[--help]
[--module module]
[--target target]
----

[[description]]
== Description

This command can be used to get monitoring level of a module.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the level configuration of a monitored module. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--module`::
The name of the module. If omitted, the command will return the configuration of all registered modules.

[[examples]]
== Examples

*Example 1 Get the monitoring level set for the JVM Module*

[source, shell]
----
asadmin get-monitoring-level --module=jvm --target=server

Module  Monitoring Level
jvm     HIGH
Command get-monitoring-level executed successfully.

----

*Example 2 Get the monitoring level set for all modules*

[source, shell]
----
asadmin get-monitoring-level --target=server

Module                       Monitoring Level
cloud                        OFF
cloud-elasticity             OFF
cloud-orchestrator           OFF
cloud-tenant-manager         OFF
cloud-virt-assembly-service  OFF
connector-connection-pool    OFF
connector-service            OFF
deployment                   OFF
ejb-container                OFF
http-service                 LOW
jdbc-connection-pool         OFF
jersey                       OFF
jms-service                  OFF
jpa                          OFF
jvm                          HIGH
orb                          OFF
security                     OFF
thread-pool                  OFF
transaction-service          OFF
web-container                OFF
web-services-container       OFF

Command get-monitoring-level executed successfully.

----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-monitoring-service-configuration.adoc[`get-monitoring-service-configuration`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-monitoring-level.adoc[`set-monitoring-level`]
