[[get-hazelcast-configuration]]
= get-hazelcast-configuration

Retrieves the current Data Grid (Hazelcast) configuration.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-hazelcast-configuration
[--help]
[--target target]
[--checkEncrypted={true|false}]
----

[[description]]
== Description

This command can be used to retrieve the current Data Grid (Hazelcast) configuration settings.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are executing this operation. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
instance_name;;
Applies to a specified server instance.
`--checkEncrypted`::
This option helps check if encryption of data stored in the xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc[Domain Data Grid] store is enabled or disabled.

[[examples]]
== Examples

*Example 1 Retrieves the current Hazelcast configuration.*

[source, shell]
----
asadmin> get-hazelcast-configuration
Property Name                         PropertyValue           Scope
Configuration File                    hazelcast-config.xml    Domain
Interfaces                                                    Domain
Auto Increment Port                   false                   Domain
Start Port                            5902                    Domain
Cluster Name                          development             Domain
License Key                                                   Domain
Host Aware Partitioning               true                    Domain
DAS Public Address                                            Domain
DAS Bind Address                                              Domain
DAS Port                              4900                    Domain
Cluster Mode                          multicast               Domain
Tcpip Members                         127.0.0.1:5900          Domain
DNS Members                                                   Domain
MulticastGroup                        224.2.2.3               Domain
MulticastPort                         6666                    Domain
Kubernetes Namespace                                          Domain
Kubernetes Service Name                                       Domain
Encrypt Datagrid                      false                   Domain
Enabled                               true                    Config
JNDIName                              payara/Hazelcast        Config
Cache Manager JNDI Name               payara/CacheManager     Config
Caching Provider JNDI Name            payara/CachingProvider  Config
Lite Member                           false                   Config
Member Name                           payara                  Config
Member Group                          MicroShoal              Config
Executor Pool Size                    4                       Config
Executor Queue Capacity               20                      Config
Scheduled Executor Pool Size          4                       Config
Scheduled Executor Queue Capacity     20                      Config
Public Address                                                Config
Config Specific Data Grid Start Port                          Config
Command get-hazelcast-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc[Domain Data Grid],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-cluster-members.adoc[`list-hazelcast-cluster-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-hazelcast.adoc[`restart-hazelcast`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-cache-keys.adoc[`list-cache-keys`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-caches.adoc[`list-caches`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/clear-cache.adoc[`clear-cache`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/generate-encryption-key.adoc[`generate-encryption-key`]
