[[get-config-dir]]
= get-config-dir

Gets the settings of the Directory configuration settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-config-dir [--help] [--target=<target[default:server]>]
----

[[description]]
== Description

The `get-config-dir` gets the value of the directory to be used for the directory config source.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting the Config Directory.*

This example gets the directory to be used for the directory config source.

[source,shell]
----
asadmin get-config-dir --target=myAppCluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-config-dir.adoc#set-config-dir[`set-config-dir`]
