[[get-openapi-configuration]]
= get-openapi-configuration

Gets the current settings of the MicroProfile OpenAPI service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-openapi-configuration [--help]
  [--target=<target>]
----

[[description]]
== Description

This command get the current settings of the MicroProfile OpenAPI service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
Specifies the target of this command. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-openapi-configuration.adoc#set-openapi-configuration[`set-openapi-configuration`]
