[[get-environment-warning-configuration]]
= get-environment-warning-configuration

Retrieves the current settings of the Environment Warning feature in the Admin Console

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-environment-warning-configuration [--help]
----

[[description]]
== Description

The `get-environment-warning-configuration` subcommand gets the current environment warning configuration.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example*

[source, shell]
----
asadmin> get-environment-warning-configuration
Enabled  Message                         Background Colour  Text Colour
true     Caution, this is on production  #ff00ff            #00ff00
Command get-environment-warning-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-environment-warning-configuration.adoc#set-environment-warning-configuration[`set-environment-warning-configuration`]



