[[get-metrics-configuration]]
= get-metrics-configuration

Gets the configuration settings of the MicroProfile Metrics service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-metrics-configuration [--help]
[--target <instance-name>]
----

[[description]]
== Description

The `get-metrics-configuration` returns the current configuration options for the metrics service on the targeted configuration.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--target`::
Specifies the target for its respective configuration. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting the configuration of the metrics service*

This example get the metrics service configuration of the `dg1` deployment group

[source,shell]
----
asadmin get-metrics-configuration --target dg1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-metrics-configuration.adoc#set-metrics-configuration[`set-metrics-configuration`]


