[[get-openapi-configuration]]
= get-openapi-configuration

Gets the status of the OpenAPI service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-openapi-configuration
    [--target=<target>]
----

[[description]]
== Description

This command get the current status of the OpenAPI service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
Defaults to server-config. The target Payara config to apply the change to.


[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-openapi-configuration.adoc#set-openapi-configuration[`set-openapi-configuration`]