[[get-notification-configuration]]
= get-notification-configuration

Retrieves the notification service general settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-notification-configuration
[--help]
[--target target]
----

[[description]]
== Description

This command can be used to view the current configuration of the notification service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the notification service configuration. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.

[[examples]]
== Examples

*Example 1 Get current notification service configuration*

[source, shell]
----
asadmin get-notification-configuration

Notifier Name         Enabled  Notifier Enabled  Notifier Noisy
slack-notifier        true     false             true
snmp-notifier         true     false             true
teams-notifier        true     false             true
datadog-notifier      true     false             true
jms-notifier          true     false             true
newrelic-notifier     true     false             true
log-notifier          true     true              true
cdieventbus-notifier  true     false             true
eventbus-notifier     true     false             true
xmpp-notifier         true     false             true
email-notifier        true     false             true
discord-notifier      true     false             true

Command get-notification-configuration executed successfully.

----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-log-notifier-configuration.adoc#get-log-notifier-configuration[`get-log-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-jms-notifier-configuration.adoc#get-jms-notifier-configuration[`get-jms-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-eventbus-notifier-configuration.adoc#get-eventbus-notifier-configuration[`get-eventbus-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-cdieventbus-notifier-configuration.adoc#get-cdieventbus-notifier-configuration[`get-cdieventbus-notifier-configuration`]
