[[get-client-stubs]]
== get-client-stubs

Retrieves the application JAR files needed to launch the application client.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-client-stubs [--help]
--appname application_name
local_directory_path
----

[[description]]
== Description

The `get-client-stubs` subcommand copies the required JAR files for an `AppClient` standalone module or each `AppClient` module in an application from the server machine to the local directory. Each client's generated JAR file is retrieved, along with any required supporting JAR files . The client JAR file name is of the form app-name`Client.jar`. Before executing the `get-client-stubs` subcommand, you must deploy the application or module. The generated client JAR file is useful for running the application using the `appclient` utility. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--appname`::
  The name of the application or stand-alone client module. +
  The name can include an optional version identifier, which follows the name and is separated from the name by a colon (`:`). The version identifier must begin with a letter or number. It can contain alphanumeric characters plus underscore (`_`), dash (`-`), and period (`.`) characters. For more information about module and application versions, see "xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc#module-and-application-versions[Module and Application Versions]" in Payara Server Application Deployment section.

[[operands]]
== Operands

local_directory_path::
  The path to the local directory where the client stub JAR file should be stored.

[[examples]]
== Examples

[[example-1]]

*Example 1 Using get-client-stubs*

[source,shell]
----
asadmin> get-client-stubs --appname myapplication /sample/example
Command get-client-stubs executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc#deploy[`deploy`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/redeploy.adoc#redeploy[`redeploy`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/undeploy.adoc#undeploy[`undeploy`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/appclient.adoc#appclient[`appclient`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/package-appclient.adoc#package-appclient[`package-appclient`]
* xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc[Payara Server Application Deployment section]


