[[get-ldap-config-source-configuration]]
= get-ldap-config-source-configuration

Gets the configuration of the LDAP Config Source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-ldap-config-source-configuration
----

[[description]]
== Description

The `get-ldap-config-source-configuration` gets the current configuration for the LDAP Config Source

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Example

*Example 1 Getting the LDAP configuration*

This example retrieves the current configuration for the LDAP Config Source.

[source,shell]
----
asadmin> get-ldap-config-source-configuration
Enabled     Url                             Auth Type       Start TLS Enabled       BindDN                                  BindDN Password     Search Base     Search Filter       Search Scope        Connection Timeout      Read Timeout
true        ldap://ldap.forumsys.com:389    simple          false                   cn=read-only-admin,dc=example,dc=com    password
----


[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-ldap-config-source-configuration.adoc#set-ldap-config-source-configuration[`set-ldap-config-source-configuration`]

