[[get-active-module-config]]
= get-active-module-config

Displays the current active configuration of a service or instance.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-active-module-config [--help]
[--target target]
[--all={false|true}]
[service_name]
----

[[description]]
== Description

The `get-active-module-config` subcommand displays the current active configuration of a service or instance.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target for which you want to view the current active configuration of a specific service or an entire instance. +
  Possible values are as follows: +
  `server`;;
    Displays the current active configuration for the default server instance. This is the default value.
  `domain`;;
    Displays the current active configuration for the default domain.
  cluster-name;;
    Displays the current active configuration for every server instance in the specified cluster.
  instance-name;;
    Displays the current active configuration for the specified instance.
`--all`::
  Displays all current active configurations. +
  The default value is `false`.

[[operands]]
== Operands

service_name::
  The name of the module for which you want to display the current active configuration.

[[examples]]
== Examples

[[example-1]]
*Example 1 Displaying the Current Active Configuration*

This example displays the current active configuration for the JMS service in `server-config` (the default configuration).

[source,shell]
----
asadmin> get-active-module-config jms-service
At location: domain/configs/config[server-config]
<jms-service default-jms-host="default_JMS_host" type="EMBEDDED"
  <jms-host port="7676" host="localhost" name="default_JMS_host"/>
</jms-service>
Command get-active-module-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-module-config.adoc#create-module-config[`create-module-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-module-config.adoc#delete-module-config[`delete-module-config`]


