[[get-jmx-monitoring-configuration]]
= get-jmx-monitoring-configuration

Retrieves the JMX monitoring service general settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-jmx-monitoring-configuration
[--help]
[--target target]
[--pretty={false|true}]
----

[[description]]
== Description

This command can be used to view the current configuration of the JMX monitoring service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the JMX monitoring service configuration. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`pretty`::
Default to `false`. Whether to displays boolean configuration values options as a *tick* or a *cross*

[[examples]]
== Examples

*Example 1 Get current JMX monitoring service configuration*

[source, shell]
----
asadmin get-jmx-monitoring-configuration
JMX Monitoring Enabled  JMX Log Frequency  JMX Log Frequency Unit
true                    5                  MINUTES

Name                  Notifier Enabled
slack-notifier        false
snmp-notifier         false
teams-notifier        false
datadog-notifier      false
jms-notifier          false
newrelic-notifier     false
log-notifier          true
cdieventbus-notifier  false
eventbus-notifier     false
xmpp-notifier         false
email-notifier        false
discord-notifier      false

Object Name            Attribute             Description
java.lang:type=Memory  HeapMemoryUsage.used
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-amx-enabled.adoc[`set-amx-enabled`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-jmx-monitoring-configuration.adoc[`set-jmx-monitoring-configuration`]
