[[get-monitoring-service-configuration]]
= get-monitoring-service-configuration

Retrieves the monitoring service general settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-monitoring-service-configuration
[--help]
[--target target]
----

[[description]]
== Description

This command can be used to view the current configuration of the monitoring service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the monitoring service configuration. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.

[[examples]]
== Examples

*Example 1 Get current monitoring service configuration*

[source, shell]
----
asadmin get-monitoring-service-configuration
Monitoring Enabled  AMX Enabled  MBeans Enabled  DTrace Enabled
true                true         true            false

Command get-monitoring-service-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics],
