[[get-metrics-configuration]]
= get-metrics-configuration

Gets the configuration of the metrics service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-metrics-configuration [--target <instance-name>]
----

[[description]]
== Description

The `get-metrics-configuration` returns the current configuration options for the metrics service on the targeted configuration.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--target`::
Defaults to `server-config`. Specifies the target server/instance configuration.

[[examples]]
== Example

*Example 1 Getting the configuration of the metrics service*

This example get the metrics service configuration of cluster1

[source,shell]
----
asadmin> get-metrics-configuration --target cluster1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-metrics-configuration.adoc#set-metrics-configuration[`set-metrics-configuration`]


