[[get-cdieventbus-notifier-configuration]]
= get-cdieventbus-notifier-configuration

Retrieves the settings of the Event Bus notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-eventbus-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the Event Bus notifier in Payara Server.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the CDI Event Bus notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the CDI Event Bus notifier in the DAS*

[source, shell]
----
asadmin get-cdieventbus-notifier-configuration

Enabled  Noisy  Loopback
false    true   false
Command get-cdieventbus-notifier-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-cdieventbus-notifier-configuration.adoc#set-cdieventbus-notifier-configuration[`set-cdieventbus-notifier-configuration`]
