[[get-aws-config-source-configuration]]
= get-aws-config-source-configuration

Gets the configuration for the AWS Secrets configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-aws-config-source-configuration [--help]
[--target=server]
----

[[description]]
== Description

The `get-aws-config-source-configuration` retrieves the current configuration for the AWS Config Source.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting the configuration of the AWS secrets*

This example retrieves the AWS Secrets Cloud Config Source.

[source,shell]
----
asadmin get-aws-config-source-configuration

Enabled  Region Name  Secret Name
true     eu-west-2    payara/test/key
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-aws-config-source-configuration.adoc#set-aws-config-source-configuration[`set-aws-config-source-configuration`]
