[[get-admin-audit-configuration]]
= get-admin-audit-configuration

Retrieves the current settings of the Admin Audit Service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-admin-audit-configuration [--help]
[--target=server]
----

[[description]]
== Description

The `get-admin-audit-configuration` subcommand is used to list the configuration settings of the auditing service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`:: Specifies the server instance or cluster for which to display the current admin audit configuration.

[[examples]]
== Examples

*Example*

[source, shell]
----
asadmin> get-admin-audit-configuration

Enabled  Audit Level
false    MODIFIERS
Name     Notifier Enabled
LOG      false

Command get-admin-audit-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-admin-audit-configuration.adoc#set-admin-audit-configuration[`set-admin-audit-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-asadmin-recorder.adoc#enable-asadmin-recorder[`enable-asadmin-recorder`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-asadmin-recorder.adoc#disable-asadmin-recorder[`disable-asadmin-recorder`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin-recorder-enabled.adoc#asadmin-recorder-enabled[`asadmin-recorder-enabled`]


