[[get-jms-notifier-configuration]]
= get-jms-notifier-configuration

Retrieves the settings of the JMS notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-log-notifier-configuration [--help]
[--target target]
----

[[description]]
== Description

This command can be used to retrieves the current settings of the JMS notifier in Payara Server Full Profile.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are retrieving the settings of the JMS notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to on a specified server instance.

[[examples]]
== Examples

*Example 1 Retrieve the settings for the JMS notifier in the DAS*

[source, shell]
----
asadmin get-jms-notifier-configuration

Enabled  Noisy  Context Factory Class  Connection Factory Name  Queue Name  URL  Username  Password
true     true   com.sun.enterprise.naming.SerialInitContextFactory  jms/__defaultConnectionFactory  notifierQueue  localhost:7676  myusername  mypassword
Command get-jms-notifier-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-jms-notifier-configuration.adoc#set-jms-notifier-configuration[`set-jms-notifier-configuration`]
