[[get-hashicorp-config-source-configuration]]
= get-hashicorp-config-source-configuration

Gets the configuration for the HashiCorp Config Source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-HashiCorp-config-source-configuration [--target=server]
----

[[description]]
== Description

The `get-HashiCorp-config-source-configuration` retrieves the current configuration for the HashiCorp Config Source.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

`--target`::
Specifies the target server/instance configuration.

[[examples]]
== Example

*Example 1 Getting the configuration of the HashiCorp secrets*

This example retrieves the current configuration for the HashiCorp Config Source.

[source,shell]
----
asadmin> get-hashicorp-config-source-configuration

Enabled  API Version  Secrets Engine Path  Secrets Path  Vault Address
true     2            secret               my-secret     https://127.0.0.1:8200
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-hashicorp-config-source-configuration.adoc#set-hashicorp-config-source-configuration[`set-hashicorp-config-source-configuration`]

