[[get-fault-tolerance-configuration]]
= get-fault-tolerance-configuration

Retrieves the configuration settings of the MicroProfile Fault Tolerance service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-fault-tolerance-configuration [--help]
[--target=server-config]
----

[[description]]
== Description

The `get-fault-tolerance-configuration` returns the current configuration options for the MicroProfile Fault Tolerance service on the specified target.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--target`::
Specifies the target of this command. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Getting MicroProfile Fault Tolerance configuration*

This example gets the current configuration of the Fault Tolerance service.

[source,shell]
----
asadmin get-fault-tolerance-configuration --target=instance1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-fault-tolerance-configuration.adoc#set-fault-tolerance-configuration[`set-fault-tolerance-configuration`]
