[[get-fault-tolerance-configuration]]
= get-fault-tolerance-configuration

Provides a way to get the configuration of the fault tolerance service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> get-fault-tolerance-configuration [--target=server-config]
----

[[description]]
== Description

The `get-fault-tolerance-configuration` returns the current configuration options for the Fault Tolerance service on the targeted config.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--target`::
Defaults to `server-config` . The config to get the fault tolerance configuration for.

[[examples]]
== Example

*Example 1 Getting fault tolerance configuration*

This example gets the current configuration of the fault tolerance service.

[source,shell]
----
asadmin> get-fault-tolerance-configuration --target=instance1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-fault-tolerance-configuration.adoc#set-fault-tolerance-configuration[`set-fault-tolerance-configuration`]
