[[get-jdbc-config-source-configuration]]
= get-jdbc-config-source-configuration

Gets the settings of the JDBC configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-jdbc-config-source-configuration [--help] [--target=server]
----

[[description]]
== Description

The `get-jdbc-config-source-configuration` retrieves the current configuration for the JDBC Config Source

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.

[[examples]]
== Example

*Example 1 Retrieving the JDBC Config Source configurations.*

This example gets the configuration of the JDBC config source.

[source,shell]
----
asadmin get-jdbc-config-source-configuration
JNDI Name  Table Name  Key-Column Name  Value-Column Name
jndi-name  Books       ISBN             Title
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-jdbc-config-source-configuration.adoc#set-jdbc-config-source-configuration[`set-jdbc-config-source-configuration`]
