[[healthcheck-configure-service-threshold]]
= healthcheck-configure-service-threshold

Configures a specific performance metric service.

IMPORTANT: This command is deprecated and will be removed in a future release as it has been replaced by the `set-healthcheck-service-configuration` command.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] healthcheck-configure-service-threshold
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--servicename=serviceName]
[--thresholdcritical=threshold]
[--thresholdwarning=threshold]
[--thresholdgood=threshold]
----

[[description]]
== Description

Configures `CRITICAL`, `WARNING` and `GOOD` threshold range values for a service checker. The `dynamic` attribute should be set to `true` in order to apply the changes directly.

This command only configures thresholds for the following checkers:

* CPU Usage
* Connection Pool
* Heap Memory Usage
* Machine Memory Usage

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the Healthcheck performance metric service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the healthcheck service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
`--servicename`::
The performance service metric name. Required.
+
One of:

* `connection-pool` or `cp`
* `cpu-usage` or  `cu`
* `heap-memory-usage` or `hmu`
* `machine-memory-usage` or `mmu`

`--thresholdcritical`::
Defaults to `90`. The threshold value that this metric must surpass to generate a **`CRITICAL`** event.
+
A value between _WARNING VALUE_ and `100` must be used.
`--thresholdwarning`::
Defaults to `50`. The threshold value that this metric must surpass to generate a *`WARNING`* event.
+
A value between _GOOD VALUE_ and _WARNING VALUE_ must be used.
`--thresholdgood`::
Defaults to `0`. The threshold value that this metric must surpass to generate a *`GOOD`* event.
+
A value between `0` and _WARNING VALUE_ must be used.

[[examples]]
== Examples

*Example 1 JDBC Connection Pools Health monitoring*

Monitoring the health of JDBC connection pools is a common need. In that scenario, it is very unlikely that on-the-fly configuration changes would be made, so a very high `CRITICAL` threshold can be set. Likewise, a nonzero `GOOD` threshold is needed because an empty or unused connection pool may not be healthy either.

The following command would apply these settings to the connection pool checker:

[source, shell]
----
asadmin healthcheck-configure-service-threshold --serviceName=healthcheck-cpool --dynamic=true --thresholdCritical=95 --thresholdWarning=70 --thresholdGood=30
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-healthcheck-service-configuration.adoc[`set-healthcheck-service-configuration`]
