[[healthcheck-list-services]]
= healthcheck-list-services

Lists the names of all available Healthcheck services.

IMPORTANT: This command is deprecated and will be removed in a future release as it has been replaced by the `list-healthcheck-services` command.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] healthcheck-list-services
[--help]
----

[[description]]
== Description

Prints a detailed list of all available Healthcheck services (as in, individual services that generate healthcheck events based on performance metrics) in the current server installation.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 List current Healthcheck services*

[source, shell]
----
asadmin healthcheck-list-services

Available Health Check Services:
Name                    Description
healthcheck-mpmetrics   Provides a way to monitor and log the values of metrics exposed by MicroProfile Metrics
healthcheck-cpu         Provides ratio on cpu usage time with severity according to defined threshold values
healthcheck-gc          Provides ratio on garbage collection count with severity according to defined threshold values
healthcheck-heap        Provides ratio on used heap memory with severity according to defined threshold values
healthcheck-threads     Lists hogging threads with their id when given thresholds exceed
healthcheck-machinemem  Provides ratio on used machine memory with severity according to defined threshold values
healthcheck-cpool       Provides ratio on connection usage for a given pool name with severity according to defined threshold values
healthcheck-stuck       Provides thread name, id and stack trace for requests which reach over defined threshold values
healthcheck-mp          Checks that all instances are responding to Microprofile Healthcheck requests with an UP response

Command list-healthcheck-services executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-healthcheck-configuration.adoc[`set-healthcheck-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-healthcheck-services.adoc[`list-healthcheck-services.adoc`]
