[[healthcheck-hoggingthreads-configure]]
= healthcheck-hoggingthreads-configure

Configures the specifics of the Healthcheck hogging threads performance metric service.

IMPORTANT: This command is deprecated and will be removed in a future release as it has been replaced by the `set-healthcheck-service-configuration` command.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] healthcheck-hoggingthreads-configure
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--name=name]
[--checkername=checkerName]
[--time=time]
[--unit={DAYS|HOURS|MINUTES|SECONDS|MILLISECONDS}]
[--threshold-percentage=percentage]
[--retry-count=count]
----

[[description]]
== Description

Configures the *Hogging Threads* checker service settings. The checker  will determine which running threads are hogging the CPU by calculating a percentage  of usage with the ratio of elapsed time to the checker service execution interval and verifying if this percentage exceeds the `threshold-percentage`.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the hogging threads checker service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the healthcheck service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
`--name`::
Unused option.
`--checkername`::
Unused option.

`--time`::
Defaults to `1`. The amount of time units that the service will use to periodically monitor the metric.
`unit`::
Defaults to `MINUTES`. The time unit to set the frequency of the metric monitoring.
+
NOTE: Must correspond to a valid https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/TimeUnit.html[`java.util.concurrent.TimeUnit`]
`--threshold-percentage`::
Defaults to `95`. The threshold value that this metric will be compared to mark threads as hogging the CPU.
`--retry-count`::
Defaults to `3`. The number of retries that the checker service will execute in order to identify a hogging thread.

[[examples]]
== Examples

*Example 1 Identifying hogging threads*

Monitoring which threads hog the CPU is extremely important since this can lead to performance degradation, deadlocks and extreme bottlenecks issues that web applications can incur. In some cases the defaults are all that is needed, but imagine that in a critical system you want to set the threshold percentage to **90%**, and you want to make sure that the health check service guarantees the state of such threads with a retry count of *5*.

Additionally, you want to set the frequency of this check for every _20 seconds_.

Use this command to apply these settings:

[source, shell]
----
asadmin healthcheck-hoggingthreads-configure --dynamic=true --threshold-percentage=90 --retry-count=5 --time=20 --unit=SECONDS
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-healthcheck-service-configuration.adoc[`set-healthcheck-service-configuration`]
