[[jms-ping]]
= jms-ping

Checks if the JMS service is up and running.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] jms-ping [--help]
[-- target target]
----

[[description]]
== Description

The `jms-ping` subcommand checks if the Java Message Service (JMS) service (also known as the JMS provider) is up and running. When you
start the Payara Server, the JMS service starts by default.

The `jms-ping` subcommand pings only the default JMS host within the JMS service. It displays an error message when it is unable to ping a built-in JMS service.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target for which the operation is to be performed. Valid values are as follows: +
  `server`;;
    Pings the JMS service for the default server instance. This is the default value
  configuration-name;;
    Pings the JMS service for all clusters using the specified configuration.
  cluster-name;;
    Pings the JMS service for the specified cluster.
  instance-name;;
    Pings the JMS service for the specified server instance.

[[examples]]
== Examples

*Example 1 Verifying that the JMS service is running*

The following subcommand checks to see if the JMS service is running on the default server.

[source,shell]
----
asadmin> jms-ping
JMS-ping command executed successfully
Connector resoure test_jms_adapter created.
Command jms-ping executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jms-host.adoc#create-jms-host[`create-jms-host`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jms-host.adoc#delete-jms-host[`delete-jms-host`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jms-hosts.adoc#list-jms-hosts[`list-jms-hosts`]


