[[list-configs]]
== list-configs

Lists named configurations.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-configs [--help]
[target]
----

[[desciption]]
== Description

The `list—configs` subcommand lists named configurations in the configuration of the domain administration server (DAS). The list can be filtered by cluster, instance, or named configuration.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Filters the list of configurations. Valid values are as follows: +
  `domain`;;
    Lists all named configurations in the current domain.
  cluster-name;;
    Lists the named configuration that defines the configuration of instances in the specified cluster.
  instance-name;;
    Lists the named configuration that defines the configuration of the specified instance.
  configuration-name;;
    Lists the specified named configuration. Use this option to determine whether a named configuration exits.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing All Named Configurations in a Domain*

This example lists all named configurations in the current domain.

[source,shell]
----
asadmin> list-configs
server-config
default-config
pmdclust-config
pmdsharedconfig
pmdcpinst-config
ymlclust-config
il1-config
il2-config

Command list-configs executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/copy-config.adoc#copy-config[`copy-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-config.adoc#delete-config[`delete-config`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/Configuration.adoc#configuration[`configuration`]
