[[list-virtual-servers]]
= list-virtual-servers

Lists the existing virtual servers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-virtual-servers [--help]
[target]
----

[[description]]
== Description

The `list-virtual-servers` subcommand lists the existing virtual servers.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Restricts the listing to virtual servers for a specified target. Valid values are as follows: +
  `server`;;
    Lists the virtual servers for the default server instance. This is the default value.
  configuration-name;;
    Lists the virtual servers for the specified configuration.
  cluster-name;;
    Lists the virtual servers for all server instances in the specified cluster.
  instance-name;;
    Lists the virtual servers for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing Virtual Servers*

The following command lists all the virtual servers for the server instance:

[source,shell]
----
asadmin> list-virtual-servers
server
__asadmin
Command list-virtual-servers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-virtual-server#create-virtual-server[`create-virtual-server`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-virtual-server#delete-virtual-server[`delete-virtual-server`]


