[[list-loggers]]
= list-loggers

Lists existing loggers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-loggers [--help]
----

[[description]]
== Description

The `list-loggers` subcommand lists the existing Payara Server loggers. Internal loggers are not listed. The `list-loggers` subcommand
lists the logger name, subsystem, and description.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Listing the Loggers*

This example lists the logger name, subsystem, and description for each logger. Some lines of output are omitted from this example for readability.

[source,shell]
----
asadmin> list-loggers
Logger Name                            Subsystem         Logger Description
...
jakarta.enterprise.monitoring            Monitoring        Monitoring Logger
jakarta.enterprise.system.core.ee        AS-CORE           Java EE Core Kernel
jakarta.enterprise.system.jmx            JMX               JMX System Logger
jakarta.enterprise.system.tools.admin    ADMIN             Administration Services
...
Command list-loggers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-file-format.adoc#set-log-file-format[`set-log-file-format`]


