[[list-notifiers]]
= list-notifiers

List all available notifiers to the server.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-notifiers
[--help]
[--target target]
----

[[description]]
== Description

This command can be used to list all available notifiers.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 List current notifiers*

[source, shell]
----
asadmin>  list-notifiers
Available Notifier Services:
        cdieventbus-notifier
        eventbus-notifier
        log-notifier
        jms-notifier

Command list-notifiers executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/notification-configure.adoc#notification-configure[`notification-configure`]
