[[list-timers]]
= list-timers

Lists all persistent timers owned by server instance(s).

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-timers [--help]
[target]
----

[[description]]
== Description

The `list-timers` subcommand lists the persistent timers owned by a specific server instance or a cluster of server instances.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  The target is either a standalone server instance or a cluster. If the target is the stand-alone instance, then the number of timers owned by
  the instance is listed. If the target is a cluster, then the number of timers owned by each instance in the cluster is listed. The default
  target is `server`, the default server instance.

[[examples]]
== Examples

*Example 1 Listing Current Timers in a Server Instance*

This example lists persistent timers in a particular standalone server instance. There is one currently active timer set.

[source,shell]
----
asadmin> list-timers server
1

The list-timers command was executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/migrate-timers#migrate-timers[`migrate-timers`]
* https://jakarta.ee/specifications/platform/8/apidocs/javax/ejb/timerservice[Using the Timer Service] in The Java EE 8 Tutorial
* xref:Technical Documentation/Application Development/Using Jakarta Enterprise Beans Technology.adoc#ejb-timer-service[EJB Timer Service] in the Payara Server Application Development section


