[[list-rest-endpoints]]
= list-rest-endpoints

Lists all the rest endpoints of a deployed web application

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-rest-endpoints [--help]
[--componentname=componentname]
[appname]
----

[[description]]
== Description

Lists all the rest endpoints of a deployed web application.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
  Displays the help text for the subcommand.

`--componentname`::
Name of the REST endpoint component to list.

[[operands]]
== Operands

`appname`::
Name of the deployed application to list all of their rest endpoints.

[[examples]]
== Examples

*Example 1 Listing all the rest endpoints for a deployed application*

This example lists all the rest endpoints for the application `sse-producer`.

[source,shell]
----
asadmin list-rest-endpoints sse-producer
GET     /sse-producer/rest/application.wadl
GET     /sse-producer/rest/sse/register
Command list-rest-endpoints executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand



