[[list-resource-refs]]
= list-resource-refs

Lists existing resource references.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-resource-refs [--help] 
[target]
----

[[description]]
== Description

The `list-resource-refs` subcommand lists all resource references in a cluster or an unclustered server instance. This effectively lists all
the resources (for example, JDBC resources) available in the JNDI tree of the specified target.

The target instance or instances in the cluster need not be running or available for this subcommand to succeed.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  The target for which you are listing the resource references. Valid targets are as follows: +
  `server`;;
    Lists the resource references for the default server instance and is the default target.
  cluster_name;;
    Lists the resource references for every server instance in the cluster.
  instance_name;;
    Lists the resource references for the named unclustered server instance.

[[examples]]
== Examples

*Example 1 Listing Resource References for a Cluster*

This example lists resource references for the cluster `cluster1`.

[source,shell]
----
asadmin> list-resource-refs cluster1
jms/Topic
Command list-resource-refs executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-resource-ref.adoc#create-resource-ref[`create-resource-ref`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-resource-ref.adoc#delete-resource-ref[`delete-resource-ref`]


