[[list-http-lbs]]
= list-http-lbs

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Lists load balancers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-http-lbs [--help]
[--long={false|true}]
[--output output]
[--header={false|true}]
[name]
----

[[description]]
== Description

Use the `list-http-lbs` subcommand to list physical load balancers.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--long`::
`-l`::
  Displays detailed information about each load balancer. The default value is `false.`
`--output`::
`-o`::
  Displays specific details about each load balancer. Use a comma-separated list to specify the details you want to display and their order. For example, `list-http-lbs --output name,device-host,device-port`. The values are case-insensitive. +
  Possible values are as follows: +
  `device-host`;;
    Displays the device host or the IP address of the load balancing device. This host or IP is where the physical load balancer resides.
  `name`;;
    Displays the name of the load balancer.
  `auto-apply-enabled`;;
    Displays whether the Auto Apply feature is enabled.
  `lb-config-name`;;
    Displays the name of the load balancer configuration.
  `device-port`;;
    Displays the port used to communicate with the load balancing device.
`--header`::
`-h`::
  Specifies whether column headings are displayed when the `--long` option is used. The default value is `true`. To suppress the headings, set the `--header` option to `false`.

[[operands]]
== Operands

name::
  The name of the load balancer for which you want to display details.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing Physical Load Balancers for a Domain*

This example lists all physical load balancers defined for a domain.

[source,shell]
----
asadmin> list-http-lbs
lb1
lb2
Command list-http-lbs executed successfully.
----

[[exit-status]]
=== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb.adoc#create-http-lb[`create-http-lb`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-http-lb.adoc#delete-http-lb[`delete-http-lb`]
