[[list-jobs]]
= list-jobs

Lists information about subcommands that were started using `asadmin --detach` or that contain progress information.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jobs [--help]
[job_id]
----

[[description]]
== Description

The `list-jobs` subcommand lists information about subcommands that were started using the `asadmin` utility option `--detach` or that contain
progress information. The `--detach` option detaches long-running subcommands and executes them in the background in detach mode.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

job_id::
  The ID of the job for which you want to list information.

[[examples]]
== Examples

*Example 1 Checking Job Status*

This example provides information about subcommands that were started using `asadmin --detach` or that contain progress information.

[source,shell]
----
asadmin> list-jobs
JOB ID     COMMAND           STATE       EXIT CODE TIME OF COMPLETION
1          create-cluster    COMPLETED   SUCCESS   2013-02-15 16:16:16 PST
2          deploy            COMPLETED   FAILURE   2013-02-15 18:26:30 PST
Command list-jobs executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/attach.adoc#attach[`attach`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/configure-managed-jobs.adoc#configure-managed-jobs[`configure-managed-jobs`]


