[[list-log-attributes]]
= list-log-attributes

Lists all logging attributes defined for a specified target in a domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-log-attributes [--help]
[target]
----

[[description]]
== Description

The `list-log-attributes` subcommand lists all logging attributes currently defined for the specified Payara Server domain or target
within a domain. The values listed correspond to the values in the `logging.properties` file for the domain.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Valid values are: +
  * `server` - The default server instance. This is the default value.
  * configuration_name - The name of a specific configuration.
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

*Example 1 Listing the Logger Attributes for a Domain*

This example lists all loggers attributes for the default domain.

[source,shell]
----
asadmin> list-log-attributes
com.sun.enterprise.server.logging.GFFileHandler.alarms <false>
com.sun.enterprise.server.logging.GFFileHandler.file \
<${com.sun.aas.instanceRoot}/logs/server.log>
com.sun.enterprise.server.logging.GFFileHandler.flushFrequency <1>
com.sun.enterprise.server.logging.GFFileHandler.formatter \
<com.sun.enterprise.server.logging.UniformLogFormatter>
com.sun.enterprise.server.logging.GFFileHandler.logtoConsole <false>
com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles <0>
com.sun.enterprise.server.logging.GFFileHandler.retainErrorsStasticsForHours <0>
com.sun.enterprise.server.logging.GFFileHandler.rotationLimitInBytes <2000000>
com.sun.enterprise.server.logging.GFFileHandler.rotationTimelimitInMinutes <0>
com.sun.enterprise.server.logging.SyslogHandler.useSystemLogging <false>
handlers <java.util.logging.ConsoleHandler>
java.util.logging.ConsoleHandler.formatter \
<com.sun.enterprise.server.logging.UniformLogFormatter>
java.util.logging.FileHandler.count <1>
java.util.logging.FileHandler.formatter <java.util.logging.XMLFormatter>
java.util.logging.FileHandler.limit <50000>
java.util.logging.FileHandler.pattern <%h/java%u.log>
log4j.logger.org.hibernate.validator.util.Version <warn>

Command list-log-attributes executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/collect-log-files.adoc#collect-log-files[`collect-log-files`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/rotate-log.adoc#rotate-log[`rotate-log`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-attributes.adoc#set-log-attributes[`set-log-attributes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-levels.adoc#set-log-levels[`set-log-levels`],
* "xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Logging Service.adoc#administering-the-logging-service[Administering the Logging Service]" in Payara Server General Administration section


