[[list-cache-keys]]
= list-cache-keys

Lists all keys in a Hazelcast cache.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-cache-keys
[--help]
[--target target]
[--name name]
----

[[description]]
== Description

This command can be used to list all keys in a Hazelcast (Data Grid) cache.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are executing this operation. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
instance_name;;
Applies to a specified server instance.
`--name`::
Name of the cache to query.
+
TIP: If omitted, this command will be executed for all available caches in the corresponding target.

[[examples]]
== Examples

*Example 1 Lists all keys in all available caches.*

[source, shell]
----
asadmin> list-cache-keys
{
Cache payara-instance-map
{5d0928cf-fd3d-404f-a6c6-985293f0295f,
c7d90acc-43a3-492d-8c9c-8cd9b950fb37,
5e984e01-0c6a-4b34-b608-56b79285c36b,
9ba96a9f-d7ff-4c79-acef-8dd8091f40a6,
Cache payara.instance.store
{5d0928cf-fd3d-404f-a6c6-985293f0295f,
5e984e01-0c6a-4b34-b608-56b79285c36b,
Cache payara.micro.applications.store
{__admingui,
}

Command list-cache-keys executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc[Domain Data Grid],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-cluster-members.adoc[`list-hazelcast-cluster-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-hazelcast.adoc[`restart-hazelcast`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-caches.adoc[`list-caches`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/clear-cache.adoc[`clear-cache`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-hazelcast-configuration.adoc[`get-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/generate-encryption-key.adoc[`generate-encryption-key`]
