[[list-message-security-providers]]
= list-message-security-providers

Lists all security message providers for the given message layer.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-message-security-providers [--help]
--layer message_layer
[target]
----

[[description]]
== Description

The `list-message-security-providers` subcommand enables administrators to list all security message providers (`provider-config` sub-elements)
for the given message layer (`message-security-config` element of `domain.xml`).

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--layer`::
  The message-layer for which the provider has to be listed. The default value is `HttpServlet`.

[[operands]]
== Operands

target::
  Restricts the listing to message security providers for a specific target. Valid values include: +
  `server`;;
    Lists providers for the default server instance `server` and is the default value.
  `domain`;;
    Lists providers for the domain.
  cluster;;
    Lists providers for the server instances in the cluster.
  instance;;
    Lists providers for a particular server instance.

[[examples]]
== Examples

*Example 1 Listing message security providers*

The following example shows how to list message security providers for a message layer.

[source,shell]
----
asadmin> list-message-security-providers 
--layer SOAP 
XWS_ClientProvider
ClientProvider
XWS_ServerProvider
ServerProvider
Command list-message-security-providers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-message-security-provider.adoc#create-message-security-provider[`create-message-security-provider`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-message-security-provider.adoc#delete-message-security-provider[`delete-message-security-provider`]


