[[list-context-services]]
= list-context-services

Lists context service resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-context-services [--help]
[target]
----

[[description]]
== Description

The `list-context-services` subcommand lists context service resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Specifies the target for which context service resources are to be listed. Valid targets are:
+
  `server`;;
    Lists the resources on the default server instance. This is the default value.
  `domain`;;
    Lists the resources for the domain.
  cluster-name;;
    Lists the resources on all server instances in the specified
    cluster.
  instance-name;;
    Lists the resources on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing Context Service Resources*

This example lists context service resources on the default server instance.

[source,shell]
----
asadmin> list-context-services
concurrent/__defaultContextService
concurrent/myContextService1
concurrent/myContextService2
Command list-context-services executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-context-service.adoc#create-context-service[`create-context-service`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-context-service.adoc#delete-context-service[`delete-context-service`]
