[[list-phone-home]]
= list-phone-home

List the current status of the Phone Home service.

[[synopsis]]
== Synopsis

[source, shell]
----
asadmin> list-phone-home
----

[[description]]
== Description

The phone home data is presently used to gather usage statistics about the corresponding distribution, such as how long users typically run instances, and what versions they use.
This command shows whether the phone home service is enabled or disabled.


[[examples]]
== Examples

*Example 1 List Phone Home Service*

[source, shell]
----
asadmin>  list-phone-home
Phone Home Service is enabled

Command list-phone-home executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-phone-home.adoc#disable-phone-home[`disable-phone-home`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-phone-home.adoc#enable-phone-home[`enable-phone-home`]

