[[list-managed-thread-factories]]
= list-managed-thread-factories

Lists managed thread factory resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-managed-thread-factories [--help]
[target]
----

[[description]]
== Description

The `list-managed-thread-factories` subcommand lists managed thread factory resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[operands]]
== Operands

target::
Specifies the target for which managed thread factory resources are to be listed. Valid targets are:
+
`server`;;
Lists the resources on the default server instance. This is the default value.
`domain`;;
Lists the resources for the domain.
cluster-name;;
Lists the resources on all server instances in the specified cluster.
instance-name;;
Lists the resources on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing Managed Thread Factory Resources*

This example lists managed thread factory resources on the default server instance.

[source,shell]
----
asadmin> list-managed-thread-factories
concurrent/__defaultManagedThreadFactory
concurrent/Factory1
concurrent/Factory2
Command list-managed-thread-factories executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-managed-thread-factory.adoc#create-managed-thread-factory[`create-managed-thread-factory`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-managed-thread-factory.adoc#delete-managed-thread-factory[`delete-managed-thread-factory`]


