[[list-jndi-resources]]
= list-jndi-resources

Lists all existing JNDI resources.

[[synopsis]]
== Synopsis

[source,shell]
----
list-jndi-resources [--help] [target]
----

[[description]]
== Description

The `list-jndi-resources` subcommand identifies all existing JNDI resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  The target for which the JNDI resources are to be listed. Valid values are as follows: +
  `server`;;
    Lists the JNDI resources on the default server instance. This is the default value.
  configuration-name;;
    Lists the JNDI resources for the specified configuration.
  cluster-name;;
    Lists the JNDI resources on all server instances in the specified cluster.
  instance-name;;
    Lists the JNDI resources on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing JNDI Resources*

This example lists the JNDI resources on the default server instance.

[source,shell]
----
asadmin> list-jndi-resources
jndi_resource1
jndi_resource2
jndi_resource3
Command list-jndi-resources executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jndi-resource.adoc#create-jndi-resource[`create-jndi-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jndi-resource.adoc#delete-jndi-resource[`delete-jndi-resource`]


