[[list-auth-realms]]
= list-auth-realms

Lists the authentication realms.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-auth-realms [--help] 
[target]
----

[[description]]
== Description

The `list-auth-realms` subcommand lists the authentication realms. This
subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these
  options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  The name of the target for which you want to list the authentication
  realms. +
  `server`;;
    Lists the realms for the default server instance `server` and is the default value.
  configuration_name;;
    Lists the realms for the named configuration.
  cluster_name;;
    Lists the realms for every server instance in the cluster.
  instance_name;;
    Lists the realms for a particular server instance.

[[examples]]
== Examples

*Example 1 Listing authentication realms*

[source,shell]
----
asadmin> list-auth-realms 
file
ldap
certificate
db
Command list-auth-realms executed successfully
----

Where file, ldap, certificate, and db are the available authentication
realms.

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-auth-realm.adoc#create-auth-realm[`create-auth-realm`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-auth-realm.adoc#delete-auth-realm[`delete-auth-realm`]


