[[list-persistence-types]]
= list-persistence-types

Lists registered persistence types for HTTP sessions and SFSB instances.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-persistence-types [--help] 
--type={web|ejb}
----

[[description]]
== Description

The `list-persistence-types` subcommand lists registered persistence types for HTTP sessions and stateful session bean (SFSB) instances. The built-in persistence types are `memory`, `file`, and `hazelcast`. The`memory` type does not apply to SFSB instances.

Other persistence types can be added using the `StrategyBuilder` class.

To set the persistence type for HTTP sessions, use the `set` subcommand to set the `persistence-type` attribute. For example:

[source,shell]
----
asadmin> set c1-config.availability-service.web-container-availability.persistence-type=file
----

To set the persistence type for SFSB instances without availability enabled, use the `set` subcommand to set the `sfsb-persistence-type` attribute. For example:

[source,shell]
----
asadmin> set c1-config.availability-service.ejb-container-availability.sfsb-persistence-type=file
----

To set the persistence type for SFSB instances with availability enabled, use the `set` subcommand to set the `sfsb-ha-persistence-type` attribute. For example:

[source,shell]
----
asadmin> set 
c1-config.availability-service.ejb-container-availability.sfsb-ha-persistence-type=hazelcast
----

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--type`::
  Specifies the type of sessions for which persistence types are listed. Allowed values are as follows: +
  * `web` — Lists persistence types for HTTP sessions.
  * `ejb` — Lists persistence types for SFSB instances.

[[examples]]
== Examples

*Example 1 Listing Persistence Types for HTTP Sessions*

This example lists persistence types for HTTP sessions.

[source,shell]
----
asadmin> list-persistence-types --type=web
memory
file
hazelcast
Command list-persistence-types executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get#get[`get`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list#list[`list`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set#set[`set`],
