[[list-hazelcast-cluster-members]]
= list-hazelcast-cluster-members

List the current members of the Data Grid visible to the domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-hazelcast-cluster-members
[--help]
[--type type]
----

[[description]]
== Description

This command can be used to list the current members of the Data Grid in a formatted table.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--type`::
Specifies the type of cluster members to list, which will be either `server` or `micro`. The default value is `both`.

[[examples]]
== Examples

*Example 1 List the current members of the Data Grid visible to the domain*

[source, shell]
----
asadmin> list-hazelcast-cluster-members --type server
Instance Name  Instance Group  Instance Type  Host Name     HTTP Ports  HTTPS Ports  Admin Port  Hazelcast Port  Lite Member  Deployed Applications  Last Heartbeat
instance1      MicroShoal      INSTANCE       /172.18.64.1  28080       28181        24848       2900            false                               2024-03-26 01:23:23
server         MicroShoal      DAS            /172.18.64.1  8080        8181         4848        4900            false        __admingui             2024-03-26 01:23:20
Command list-hazelcast-cluster-members executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/High Availability/Administering the Domain Data Grid.adoc[Domain Data Grid],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-hazelcast.adoc[`restart-hazelcast`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-cache-keys.adoc[`list-cache-keys`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-caches.adoc[`list-caches`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/clear-cache.adoc[`clear-cache`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-hazelcast-configuration.adoc[`get-hazelcast-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/generate-encryption-key.adoc[`generate-encryption-key`]
