[[list-resource-adapter-configs]]
= list-resource-adapter-configs

Lists the names of the current resource adapter configurations.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-resource-adapter-configs [--help] 
[--raname raname] [--verbose {false|true}]
----

[[description]]
== Description

This command lists the configuration information in the `domain.xml` for the connector module. It lists an entry called `resource-adapter-config`
in the `domain.xml` file. If the `--raname` option is specified, only the resource adapter configurations for the specified connector module are listed.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--raname`::
  Specifies the connector module name.
`--verbose`::
  Lists the properties that are configured. Default value is false.

[[examples]]
== Examples

*Example 1 Listing the Resource Adapter Configurations*

This example lists the current resource adapter configurations.

[source,shell]
----
asadmin> list-resource-adapter-configs
ra1
ra2
Command list-resource-adapter-configs executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-resource-adapter-config.adoc#create-resource-adapter-config[`create-resource-adapter-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-resource-adapter-config.adoc#delete-resource-adapter-config[`delete-resource-adapter-config`]


