[[list-jndi-entries]]
= list-jndi-entries

Browses and queries the JNDI tree.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jndi-entries [--help]
[--context context_name]
[target]
----

[[description]]
== Description

Use this subcommand to browse and query the JNDI tree.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--context`::
  The name of the JNDI context or subcontext. If context is not specified, all entries in the naming service are returned. If context
  (such as `ejb`) is specified, all those entries are returned.

[[operands]]
== Operands

target::
  This operand specifies the JNDI tree to browse. +
  Possible values are as follows: +
  `server`;;
    Browses the JNDI tree for the default Payara Server instance (default). The default instance is the domain administration server (DAS).
  `domain`;;
    Browses the JNDI tree for the current domain.
  cluster-name;;
    Browses the JNDI tree for the specified cluster.
  instance-name;;
    Browses the JNDI tree for the specified Payara Server instance.

[[examples]]
== Examples

*Example 1 Browsing the JNDI Tree*

This example browses the JNDI tree for the default Payara Server instance.

[source,shell]
----
asadmin> list-jndi-entries
java:global: com.sun.enterprise.naming.impl.TransientContext
jdbc: com.sun.enterprise.naming.impl.TransientContext
ejb: com.sun.enterprise.naming.impl.TransientContext
com.sun.enterprise.container.common.spi.util.InjectionManager: 
com.sun.enterprise.container.common.impl.util.InjectionManagerImpl

Command list-jndi-entries executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jndi-resource.adoc#create-jndi-resource[`create-jndi-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jndi-resource.adoc#delete-jndi-resource[`delete-jndi-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-jndi-resources.adoc#list-jndi-resources[`list-jndi-resources`]


