[[list-containers]]
= list-containers

Lists application containers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-containers [--help]
----

[[description]]
== Description

The `list-containers` subcommand displays a list of application containers.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing the Application Containers*

This example lists the current application containers.

[source,shell]
----
asadmin> list-containers
List all known application containers

faulttolerance
metrics
appclient
jpa
jpa
osgi
connector
grizzly
health
jwtauth
ejb
openapi
webservices
security
payara-resources_ear
payara-resources
resources_ear
resources
web
ear
cdi
cdi
config

Command list-containers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-commands.adoc#list-commands[`list-commands`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-components.adoc#list-components[`list-components`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-modules.adoc#list-modules[`list-modules`]
