[[list-audit-modules]]
= list-audit-modules

Gets all audit modules and displays them.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-audit-modules [--help] 
[target]
----

[[description]]
== Description

The `list-audit-modules` subcommand lists all the audit modules. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Specifies the target on which you are listing the audit modules. Valid values are as follows: +
  `server`;;
    Lists the audit modules for the default server instance `server` and is the default value.
  configuration_name;;
    Lists the audit modules for the named configuration.
  cluster_name;;
    Lists the audit modules for every server instance in the cluster.
  instance_name;;
    Lists the audit modules for a particular server instance.

[[examples]]
== Examples

*Example 1 Listing Audit Modules*

[source,shell]
----
asadmin> list-audit-modules
sampleAuditModule1
sampleAuditModule2
Command list-audit-modules executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-audit-module.adoc#create-audit-module[`create-audit-module`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-audit-module.adoc#delete-audit-module[`delete-audit-module`]


