[[list-file-users]]
= list-file-users

Lists the file users.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-file-users [--help] 
[--authrealmname auth_realm_name] [target]
----

[[description]]
== Description

The `list-file-users` subcommand displays a list of file users supported by file realm authentication.

[[options]]
== Options

`--help`::
`-?`::
  Displays the help text for the subcommand.
`--authrealmname`::
  Lists only the users in the specified authentication realm.

[[operands]]
== Operands

target::
  Specifies the target for which you want to list file users. The following values are valid: +
  `server`;;
    Lists the file users on the default server instance. This is the default value.
  configuration_name;;
    Lists the file users in the specified configuration.
  cluster_name;;
    Lists the file users on all server instances in the specified
    cluster.
  instance_name;;
    Lists the file users on a specified server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing Users in a Specific File Realm*

The following example lists the users in the file realm named `sample_file_realm`.

[source,shell]
----
asadmin> list-file-users --authrealmname sample_file_realm
sample_user05
sample_user08
sample_user12
Command list-file-users executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-file-user.adoc#create-file-user[`create-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-file-user.adoc#delete-file-user[`delete-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-groups.adoc#list-file-groups[`list-file-groups`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-file-user.adoc#update-file-user[`update-file-user`]
