[[list-jmsdest]]
= list-jmsdest

Lists the existing JMS physical destinations.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jmsdest [--help]
[--desttype type]
[target]
----

[[description]]
== Description

The `list-jmsdest` subcommand lists the Java Message Service (JMS) physical destinations.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--desttype`::
  The type of JMS destination to be listed. Valid values are `topic` and `queue`.

[[operands]]
== Operands

target::
  Restricts the listing to physical destinations for a specified target. Valid values are as follows: +
  `server`;;
    Lists the physical destinations for the default server instance. This is the default value.
  configuration-name;;
    Lists the physical destinations in the specified configuration.
  cluster-name;;
    Lists the physical destinations for every server instance in the specified cluster.
  instance-name;;
    Lists the physical destinations for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing all physical destinations*

The following subcommand lists all the physical destinations.

[source,shell]
----
asadmin> list-jmsdest
PhysicalQueue
PhysicalTopic
Command list-jmsdest executed successfully.
----

*Example 2 Listing all physical destinations of a specified type*

The following subcommand lists all physical topics.

[source,shell]
----
asadmin> list-jmsdest --desttype topic
PhysicalTopic
Command list-jmsdest executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jmsdest.adoc#create-jmsdest[`create-jmsdest`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jmsdest.adoc#delete-jmsdest[`delete-jmsdest`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/flush-jmsdest.adoc#flush-jmsdest[`flush-jmsdest`]


