[[list-file-groups]]
= list-file-groups

Lists file groups.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-file-groups [--help] 
[--name username] [--authrealmname auth_realm_name] 
[--target target]
----

[[description]]
== Description

The `list-file-groups` subcommand lists the file users and groups supported by the file realm authentication. This subcommand lists available groups in the file user. If the `--name` option is not specified, all groups are listed.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--name`::
  Identifies the name of the file user for whom the groups will be listed.
`--authrealmname`::
  The name of the authentication realm for which to list available groups.
`--target`::
  This option specifies which configurations you can list. Valid targets are: +
  `server`;;
    Lists the file groups in the current server. This is the default value.
  cluster_name;;
    Lists the file groups in a cluster.
  instance_name;;
    Lists the file groups for a particular instance.

[[examples]]
== Examples

*Example 1 Listing Groups in all File Realms*

This example list all file realm groups defined for the server.

[source,shell]
----
asadmin> list-file-groups
staff
manager
Command list-file-groups executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-file-user.adoc#create-file-user[`create-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-file-user.adoc#delete-file-user[`delete-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-users.adoc#list-file-users[`list-file-users`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-file-user.adoc#update-file-user[`update-file-user`]
