[[list-http-lb-configs]]
= list-http-lb-configs

IMPORTANT: This subcommand has been retained from Oracle GlassFish's original integration with external load balancers, but it has no proper integration functionality in Payara Server. Hence, it is not intended to be used in any way. +
The documentation in this page may not be accurate.

Lists load balancer configurations.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-http-lb-configs [--help] 
[target]
----

[[description]]
== Description

The `list-http-lb-configs` subcommand lists the load balancer configurations. List them all or list them by the cluster or server instance they reference.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Lists the load balancers by target. Valid values are: +
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1Listing Load Balancer Configurations Without a Target*

This example lists all load balancer configurations defined for all Payara Server clusters and instances.

[source,shell]
----
asadmin> list-http-lb-configs

mycluster-http-lb-config
serverinstlb
Command list-http-lb-configs executed successfully.
----

[[example-2]]

*Example 2 Listing Load Balancer Configurations for a Specific Target*

This example lists the load balancer configuration defined for a cluster named `mycluster`.

[source,shell]
----
asadmin> list-http-lb-configs mycluster

mycluster-http-lb-config
Command list-http-lb-configs executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-http-lb-config.adoc#create-http-lb-config[`create-http-lb-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-http-lb-config.adoc#delete-http-lb-config[`delete-http-lb-config`]
