[[list-threadpools]]
= list-threadpools

Lists all the thread pools.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-threadpools [--help]
target
----

[[description]]
== Description

The `list-threadpools` subcommand lists the Payara Server thread pools.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  This operand specifies the target for which you are listing thread pools. This operand is required. +
  Valid values are as follows: +
  `server`;;
    Lists the thread pools for the default Payara Server instance `server`.
  configuration-name;;
    Lists the thread pools for the named configuration.
  cluster-name;;
    Lists the thread pools for every instance in the cluster.
  instance-name;;
    Lists the thread pools for a particular instance.

[[examples]]
== Examples

*Example 1 Listing Thread Pools*

This example lists the current thread pools for the default instance `server`.

[source,shell]
----
asadmin> list-threadpools server
admin-thread-pool
http-thread-pool
thread-pool-1
Command list-threadpools executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-threadpool.adoc#create-threadpool[`create-threadpool`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-threadpool.adoc#delete-threadpool[`delete-threadpool`]


