[[list-lifecycle-modules]]
= list-lifecycle-modules

Lists the lifecycle modules.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-lifecycle-modules [--help] 
[target]
----

[[description]]
== Description

The `list-lifecycle-modules` subcommand lists lifecycle modules. A lifecycle module provides a means of running a short or long duration
Java-based task at a specific stage in the server life cycle. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Indicates the location where lifecycle modules are to be listed. Valid values are +
  * `server`- Specifies the default server instance as the target for listing lifecycle modules. `server` is the name of the default server
  instance and is the default value for this operand.
  * cluster_name- Specifies a particular cluster as the target for listing lifecycle modules.
  * instance_name- Specifies a particular server instance as the target for listing lifecycle modules.

[[examples]]
== Examples

*Example 1 Listing Lifecycle Modules*

[source,shell]
----
asadmin> list-lifecycle-modules
WSTCPConnectorLCModule
Command list-lifecycle-modules executed successfully
----

`WSTCPConnectorLCModule` is the only lifecycle module listed for the default target, `server`.

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-lifecycle-module.adoc#create-lifecycle-module[`create-lifecycle-module`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-lifecycle-module.adoc#delete-lifecycle-module[`delete-lifecycle-module`]


