[[list-jms-hosts]]
= list-jms-hosts

Lists the existing JMS hosts.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jms-hosts [--help]
[--target target]
----

[[description]]
== Description

The `list-jms-hosts` subcommand lists the existing Java Message Service (JMS) hosts for the JMS service.

This subcommand is supported in remote mode only. Remote `asadmin` subcommands require a running domain administration server (DAS).

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Restricts the listing to JMS hosts for a specified target. Valid values are as follows: +
  `server`;;
    Lists the JMS hosts for the default server instance. This is the default value.
  configuration-name;;
    Lists the JMS hosts for the specified configuration.
  cluster-name;;
    Lists the JMS hosts for all server instances in the specified cluster.
  instance-name;;
    Lists the JMS hosts for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing all JMS hosts*

The following subcommand lists the JMS hosts for the JMS service.

[source,shell]
----
asadmin> list-jms-hosts server-config
default_JMS_host
MyNewHost
Command list-jms-hosts executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jms-host.adoc#create-jms-host[`create-jms-host`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jms-host.adoc#delete-jms-host[`delete-jms-host`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/jms-ping.adoc#jms-ping[`jms-ping`]


