[[list-iiop-listeners]]
= list-iiop-listeners

Lists the existing IIOP listeners.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-iiop-listeners [--help]
[target]
----

[[description]]
== Description

The `list-iiop-listeners` subcommand lists the existing IIOP listeners.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  This operand specifies the target for which the IIOP listeners are to be listed. Valid values are: +
  `server`;;
    Lists the listeners in the default server instance `server` and is the default value.
  configuration_name;;
    Lists the listeners in the specified configuration.
  cluster_name;;
    Lists the listeners in the specified cluster.
  instance_name;;
    Lists the listeners in a particular server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Using the list-iiop-listeners subcommand*

The following command lists all the IIOP listeners for the server instance:

[source,shell]
----
asadmin> list-iiop-listeners
orb-listener-1
SSL
SSL_MUTUALAUTH
sample_iiop_listener
Command list-iiop-listeners executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-iiop-listener.adoc#create-iiop-listener[`create-iiop-listener`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-iiop-listener.adoc#delete-iiop-listener[`delete-iiop-listener`]
