[[list-protocols]]
= list-protocols

Lists the existing protocols.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-protocols [--help]
[target]
----


[[description]]
== Description

The `list-protocols` subcommand lists the existing protocols.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Restricts the listing to protocols for a specified target. Valid values are as follows: +
  `server`;;
    Lists the protocols for the default server instance. This is the default value.
  configuration-name;;
    Lists the protocols for the specified configuration.
  cluster-name;;
    Lists the protocols for all server instances in the specified
    cluster.
  instance-name;;
    Lists the protocols for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing Protocols*

The following command lists all the protocols for the server instance:

[source,shell]
----
asadmin> list-protocols
admin-listener
http-1
http-listener-1
http-listener-2
Command list-protocols executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-protocol.adoc#create-protocol[`create-protocol`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-protocol.adoc#delete-protocol[`delete-protocol`]


