[[list-protocol-filters]]
= list-protocol-filters

Lists the existing protocol filters.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-protocol-filters [--help]
[--target server]
protocol-name
----

[[description]]
== Description

The `list-protocol-filters` subcommand lists the existing protocol filters. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
target::
  Restricts the listing to protocol filters for a specified target. Valid values are as follows: +
  `server`;;
    Lists the protocol filters for the default server instance. This is
    the default value.
  configuration-name;;
    Lists the protocol filters for the specified configuration.
  cluster-name;;
    Lists the protocol filters for all server instances in the specified cluster.
  instance-name;;
    Lists the protocol filters for the specified server instance.

[[operands]]
== Operands

protocol-name::
  The name of the protocol for which to list protocol filters.

[[examples]]
== Examples

*Example 1 Listing Protocol Filters*

The following command lists all the protocol filters for the server instance:

[source,shell]
----
asadmin> list-protocol-filters http1
http1-filter
https1-filter
Command list-protocol-filters executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-protocol-filter.adoc#create-protocol-filter[`create-protocol-filter`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-protocol-filter.adoc#delete-protocol-filter[`delete-protocol-filter`]


