[[list-transports]]
= list-transports

Lists the existing transports.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-transports [--help]
[target]
----

[[description]]
== Description

The `list-transports` subcommand lists the existing transports.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Restricts the listing to transports for a specified target. Valid values are as follows: +
  `server`;;
    Lists the transports for the default server instance. This is the default value.
  configuration-name;;
    Lists the transports for the specified configuration.
  cluster-name;;
    Lists the transports for all server instances in the specified cluster.
  instance-name;;
    Lists the transports for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing Transports*

The following command lists all the transports for the server instance:

[source,shell]
----
asadmin> list-transports
http1-trans
tcp
Command list-transports executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-transport#create-transport[`create-transport`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-transport#delete-transport[`delete-transport`]


