[[list-javamail-resources]]
= list-javamail-resources

Lists the existing JavaMail session resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-javamail-resources [--help] [target]
----

[[description]]
== Description

The `list-javamail-resources` subcommand lists the existing JavaMail session resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  This operand specifies the target for which the JavaMail session resources are to be listed. Valid values are: +
  `server`;;
    Lists the resources for the default server instance. This is the default value.
  `domain`;;
    Lists the resources for the domain.
  cluster_name;;
    Lists the resources for the specified cluster.
  instance_name;;
    Lists the resources for a particular server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing JavaMail Resources*

This example lists the JavaMail session resources for the server instance.

[source,shell]
----
asadmin> list-javamail-resources
mail/MyMailSession
Command list-javamail-resources executed successfuly.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-javamail-resource.adoc#create-javamail-resource[`create-javamail-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-javamail-resource.adoc#delete-javamail-resource[`delete-javamail-resource`]
