[[list-deployment-groups]]
= list-deployment-groups

List all deployment groups registered in an existing server domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-deployment-groups [--help]
----

[[description]]
== Description

The `list-deployment-groups` subcommand lists all existing deployment groups registered in the server domain.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Listing Deployment Groups*

This example lists existing deployment groups created in the domain:

[source,shell]
----
asadmin list-deployment-groups
List of Deployment Groups:
        test-dgroup1
        test-dgroup2

Command list-deployment-groups executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

See Also

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-deployment-group.adoc#create-deployment-group[`create-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-deployment-group.adoc#delete-deployment-group[`delete-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-deployment-group.adoc#start-deployment-group[`start-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-deployment-group.adoc#stop-deployment-group[`stop-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-deployment-group.adoc#restart-deployment-group[`restart-deployment-group`]
