[[list-network-listeners]]
= list-network-listeners

Lists the existing network listeners.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-network-listeners [--help]
[target]
----

[[description]]
== Description

The `list-network-listeners` subcommand lists the existing network listeners.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Restricts the listing to network listeners for a specified target. Valid values are as follows: +
  `server`;;
    Lists the network listeners for the default server instance. This is the default value.
  configuration-name;;
    Lists the network listeners for the specified configuration.
  cluster-name;;
    Lists the network listeners for all server instances in the specified cluster.
  instance-name;;
    Lists the network listeners for the specified server instance.

[[examples]]
== Examples

*Example 1 Listing Network Listeners*

The following command lists all the network listeners for the server instance:

[source,shell]
----
asadmin> list-network-listeners
admin-listener
http-listener-1
https-listener-2
Command list-network-listeners executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-network-listener.adoc#create-network-listener[`create-network-listener`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-network-listener-configuration.adoc#set-network-listener-configuration[`set-network-listener-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-network-listener.adoc#delete-network-listener[`delete-network-listener`]


