[[list-libraries]]
= list-libraries

Lists library JAR files on Payara Server.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-libraries [--help]
[--type={common|ext|app}]
----

[[description]]
== Description

The `list-libraries` subcommand lists library archive files on Payara Server.

The `--type` option specifies the library type and the Payara Server directory for which libraries are to be listed.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--type`::
  Specifies the library type and the Payara Server directory for which libraries are listed. Valid values are as follows: +
  `common`;;
    Lists the library files for the Common class loader directory, `domain-dir/lib`. This is the default.
  `ext`;;
    Lists the library files for the Java optional package directory, `domain-dir/lib/ext`.
  `app`;;
    Lists the library files for the application-specific class loader directory, `domain-dir/lib/applibs`. +
  For more information about these directories, see xref:Technical Documentation/Application Development/Class Loaders.adoc#classloading[Class Loaders] in the Payara Server Application section.

[[examples]]
== Examples

*Example 1 Listing Libraries*

This example lists the libraries in the application-specific class loader directory on the default server instance.

[source,shell]
----
asadmin> list-libraries --type app
mylib.jar
xlib.jar
ylib.jar
zlib.jar
Command list-libraries executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/add-library.adoc#add-library[`add-library`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/remove-library.adoc#remove-library[`remove-library`],
* xref:Technical Documentation/Application Development/Class Loaders.adoc#classloading[Class Loaders] in the Payara Server Application Development section


