[[list-secure-admin-principals]]
= list-secure-admin-principals

Lists the certificates for which Payara Server accepts admin requests from clients.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-secure-admin-principals [--help] 
[--long={false|true}]
[--output output]
[--header={false|true}]
[name]
----

[[description]]
== Description

The `list-secure-admin-principals` subcommand lists the certificates for which Payara Server accepts admin requests from clients.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--long`::
`-l`::
  Displays detailed information about the certificates for which Payara Server accepts admin requests from clients. The default value is `false`.
`--output`::
`-o`::
  Displays specific details about the certificates for which Payara Server accepts admin requests from clients. Use a
  comma-separated list to specify the details you want to display and their order. The values are case-insensitive. +
  Possible values are as follows: +
  `DN`;;
    Displays the distinguished name (DN) of each certificate.
`--header`::
`-h`::
  Specifies whether column headings are displayed when the `--long` option is used. The default value is `true`. To suppress the headings,
  set the `--header` option to `false`.

[[operands]]
== Operands

name::
  The distinguished name of the certificate, specified as a comma-separated list in quotes. For example:
  `"CN=system.amer.oracle.com,OU=GlassFish,O=Oracle Corporation,L=Santa Clara,ST=California,C=US"`.

[[examples]]
== Examples

*Example 1 Listing the Certificates*

This example lists the certificates for which Payara Server accepts admin requests from clients.

[source,shell]
----
asadmin> list-secure-admin-principals 
CN=localhost,OU=Payara,O==Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK
CN=localhost-instance,OU=Payara,O=Payara Foundation,L=Great Malvern,ST=Worcestershire,C=UK
Command list-secure-admin-principals executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-secure-admin.adoc#enable-secure-admin[`enable-secure-admin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-secure-admin-principal.adoc#enable-secure-admin-principal[`enable-secure-admin-principal`]


