[[list-sub-components]]
= list-sub-components

Lists EJB or servlet components in a deployed module or module of a deployed application.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-sub-components [--help]
[--type type]
[--appname appname] [--resources]
modulename
----

[[description]]
== Description

The `list-sub-components` subcommand lists EJB or servlet components in a deployed module or in a module of a deployed application. If a module
is not specified, all modules are listed. The `--appname` option functions only when the specified module is stand-alone. To display a
specific module in an application, you must specify the module name with the `--appname` option.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--type`::
  Specifies the type of component to be listed. The options are `ejbs` and `servlets`. If nothing is specified, then all of the components are listed.
`--appname`::
  Identifies the name of the application. This option is required when the desired output is the subcomponents of an embedded module of a
  deployed application. +
  The name can include an optional version identifier, which follows the name and is separated from the name by a colon (`:`). The version
  identifier must begin with a letter or number. It can contain alphanumeric characters plus underscore (`_`), dash (`-`), and period
  (`.`) characters. For more information about module and application versions, see xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc#module-and-application-versions[Module and Application Versions] in Payara Server Application Deployment section.
`--resources`::
  Lists the application-scoped resources for each subcomponent.

[[operands]]
== Operands

modulename::
  Specifies the name of the module containing the subcomponent. +
  The name can include an optional version identifier, which follows the name and is separated from the name by a colon (`:`). The version
  identifier must begin with a letter or number. It can contain   alphanumeric characters plus underscore (`_`), dash (`-`), and period (`.`) characters. For more information about module and application
  versions, see xref:Technical Documentation/Payara Server Documentation/Application Deployment/Overview.adoc#module-and-application-versions[Module and Application Versions] in Payara Server Application Deployment section.

[[examples]]
== Examples

*Example 1 Listing Subcomponents*

This example lists the subcomponents of the `MEjbApp` application within the `mejb.jar` module.

[source,shell]
----
asadmin> list-sub-components --appname MEjbApp mejb.jar
MEJBBean <StatelessSessionBean>
Command list-sub-components executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable#disable[`disable`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable#enable[`enable`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-components#list-components[`list-components`]
