[[list-connector-resources]]
= list-connector-resources

Lists all connector resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-connector-resources [--help] 
[target]
----

[[desciption]]
== Description

The `list-connector-resources` subcommand lists all connector resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  The target for which the connector resources are to be listed. Valid values are as follows: +
  `server`;;
    Lists the connector resources on the default server instance. This is the default value.
  `domain`;;
    Lists the connector resources for the domain.
  cluster-name;;
    Lists the connector resources on all server instances in the specified cluster.
  instance-name;;
    Lists the connector resources on a specified server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing Connector Resources*

This example lists all existing connector resources.

[source,shell]
----
asadmin> list-connector-resources
jms/qConnFactory
Command list-connector-resources executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-connector-resource.adoc#create-connector-resource[`create-connector-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-connector-resource.adoc#delete-connector-resource[`delete-connector-resource`]
