[[list-jacc-providers]]
= list-jacc-providers

Enables administrators to list JACC providers defined for a domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jacc-providers [--help] 
[target]
----

[[description]]
== Description

The `list-jacc-providers` subcommand enables administrators to list the JACC providers defined for a domain. JACC providers are defined as `jacc-provider` elements in the `security-service` element in the domain's `domain.xml` file.
JACC providers can be created using the Payara Server Admin Console or the `create-jacc-provider` subcommand.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Specifies the target for which you want to list JACC providers. The following values are valid: +
  `server`;;
    Lists the JACC providers on the default server instance. This is the default value.
  configuration_name;;
    Lists the JACC providers in the specified configuration.
  cluster_name;;
    Lists the JACC providers on all server instances in the specified
    cluster.
  instance_name;;
    Lists the JACC providers on a specified server instance.

[[examples]]
== Examples

[[example-1]]
*Example 1 Listing JACC providers*

The following example shows how to list JACC providers for the default domain.

[source,shell]
----
asadmin> list-jacc-providers
default
simple
testJACC
Command list-jacc-providers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jacc-provider.adoc#create-jacc-provider[`create-jacc-provider`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jacc-provider.adoc#delete-jacc-provider[`delete-jacc-provider`]
