[[list-jdbc-resources]]
= list-jdbc-resources

Lists all JDBC resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jdbc-resources [--help] 
[target target]
----

[[description]]
== Description

The `list-jdbc-resources` subcommand displays a list of the existing JDBC resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

`--target`::
  This operand specifies which JDBC resources you can list. Usage of this operand is optional. Valid values are: +
  `server`;;
    Lists the JDBC resources in the current server and is the default.
  `domain`;;
    Lists the JDBC resources in the current domain.
  cluster_name;;
    Lists the JDBC resources in a cluster.
  instance_name;;
    Lists the JDBC resources for a particular instance.

[[examples]]
== Examples

*Example 1 Listing the JDBC Resources*

This example lists the current JDBC resources.

[source,shell]
----
asadmin> list-jdbc-resources
jdbc/DerbyPool
Command list-jdbc-resources executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-jdbc-resource.adoc#create-jdbc-resource[`create-jdbc-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-jdbc-resource.adoc#delete-jdbc-resource[`delete-jdbc-resource`]


