[[list-managed-scheduled-executor-services]]
= list-managed-scheduled-executor-services

Lists managed scheduled executor service resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-managed-scheduled-executor-services [--help]
[target]
----

[[description]]
== Description

The `list-managed-scheduled-executor-services` subcommand lists managed scheduled executor service resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.

[[operands]]
== Operands

target::
Specifies the target for which managed scheduled executor service resources are to be listed. Valid targets are:
+
`server`;;
Lists the resources on the default server instance. This is the default value.
`domain`;;
Lists the resources for the domain.
cluster-name;;
Lists the resources on all server instances in the specified cluster.
instance-name;;
Lists the resources on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing Managed Scheduled Executor Service Resources*

This example lists managed scheduled executor service resources on the default server instance.

[source,shell]
----
asadmin> list-managed-scheduled-executor-services
concurrent/__defaultManagedExecutorService
concurrent/ScheduledExecutor1
concurrent/ScheduledExecutor2
Command list-managed-scheduled-executor-services executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-managed-scheduled-executor-service.adoc#create-managed-scheduled-executor-service[`create-managed-scheduled-executor-service`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-managed-scheduled-executor-service.adoc#delete-managed-scheduled-executor-service[`delete-managed-scheduled-executor-service`]


