[[list-connector-connection-pools]]
= list-connector-connection-pools

Lists the existing connector connection pools.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-connector-connection-pools [--help]
----

[[desciption]]
== Description

The `list-connector-connection-pools` subcommand list connector connection pools that have been created.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing the Connector Connection Pools*

This example lists the existing connector connection pools.

[source,shell]
----
asadmin> list-connector-connection-pools
jms/qConnPool
Command list-connector-connection-pools executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-connector-connection-pool.adoc#create-connector-connection-pool[`create-connector-connection-pool`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-connector-connection-pool.adoc#delete-connector-connection-pool[`delete-connector-connection-pool`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/ping-connection-pool.adoc#ping-connection-pool[`ping-connection-pool`]
