[[list-custom-resources]]
= list-custom-resources

Gets all custom resources.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-custom-resources [--help] 
[target]
----

[[description]]
== Description

The `list-custom-resources` subcommand lists the custom resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  This operand specifies the location of the custom resources. Valid targets are: +
  `server`;;
    Lists the resources on the default server instance. This is the default value
  `domain`;;
    Lists the resources in the domain.
  cluster_name;;
    Lists the resources for every server instance in the cluster.
  instance_name;;
    Lists the resources for a particular server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing Custom Resources*

This example lists the current custom resources.

[source,shell]
----
asadmin> list-custom-resources
sample_custom_resource01
sample_custom_resource02
Command list-custom-resources executed successfully.
----

[[example-2]]

*Example 2 Using the list-custom-resources command with a target*

The following example displays the usage of this command.

[source,shell]
----
asadmin> list-custom-resources --user admin --passwordfile 
passwords.txt --host plum --port 4848 target6 

sample_custom_resource03
sample_custom_resource04
Command list-custom-resources executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-custom-resource.adoc#create-custom-resource[`create-custom-resource`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-custom-resource.adoc#delete-custom-resource[`delete-custom-resource`]
