[[list-clusters]]
= list-clusters

Lists existing clusters in a domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-clusters [--help] 
[target]
----

[[description]]
== Description

The `list-clusters` subcommand lists existing clusters in a domain. The list can be filtered by cluster, instance, node, or configuration. For
each cluster that is listed, the subcommand indicates whether the cluster is running.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Filters the list of clusters by specifying the target for which the clusters are to be listed. Valid values are as follows: +
  `domain`;;
    Lists all clusters in the domain (default).
  cluster-name;;
    Lists only the specified cluster.
  instance-name;;
    Lists the cluster of which the specified instance is a member.
  node-name;;
    Lists the clusters that contain an instance that resides on the specified node. For example, if instance `pmdi1` in cluster `pmdc`
    and instance `ymli1` in cluster `ymlc` reside on node `n1`, `pmdc` and `ymlc` are listed.
  configuration-name;;
    Lists all clusters that contain instances whose configuration is defined by the named configuration.

[[examples]]
== Examples

*Example 1 Listing All Clusters in a Domain*

This example lists all clusters in the current domain.

[source,shell]
----
asadmin> list-clusters
pmdclust not running
ymlclust not running

Command list-clusters executed successfully.
----

*Example 2 Displaying the Status of a Cluster*

This example displays status of the cluster `ymlclust`, which is not running.

[source,shell]
----
asadmin> list-clusters ymlclust
ymlclust not running

Command list-clusters executed successfully.
----

*Example 3 Listing All Clusters That Are Associated With a Node*

This example lists the clusters that contain an instance that resides on the node `sj02`.

[source,shell]
----
asadmin> list-clusters sj02
ymlclust not running

Command list-clusters executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-cluster.adoc#create-cluster[`create-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-cluster.adoc#delete-cluster[`delete-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-cluster.adoc#start-cluster[`start-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-cluster.adoc#stop-cluster[`stop-cluster`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-cluster#restart-cluster[`restart-cluster`]
