[[logging]]
= Logging
:ordinal: 8

Capturing information on Payara Server runtime events.

[[description]]
== Description

Logging is the process by which Payara Server captures data about events that occur during Payara Server operation. Payara Server components and application components generate logging data, which is saved in the server log, typically `domain-dir/logs/server.log`.

The server log is the first source of information if Payara Server problems occur.

The server log is rotated when the file reaches the specified size in bytes, or the specified time has elapsed. The file can also be rotated manually by using the `rotate-log` subcommand.

In addition to the server log, the `domain-dir/logs` directory contains two other kinds of logs:

* HTTP service access logs, located in the `/access` subdirectory
* Transaction service logs, located in the `/tx` subdirectory

Logging levels can be configured by using the Administration Console or the `set-log-levels` subcommand.

Additional properties can be set by using the Administration Console or by editing the `logging.properties`file. The default `logging.properties` file is typically located in domain-dir`/config`.

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/rotate-log.adoc#rotate-log[`rotate-log`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-levels.adoc#set-log-levels[`set-log-levels`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Logging Service.adoc#administering-the-logging-service[Administering the Logging Service] in Payara Server General Administration section


