[[migrate-timers]]
= migrate-timers

Moves EJB timers when a clustered instance was stopped or has crashed.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] migrate-timers [--help] 
[--target target_server_name]
server_name
----

[[description]]
== Description

The `migrate-timers` subcommand moves EJB timers to a specified server when a server instance stops or crashes, if automatic timer migration is
not enabled in the cluster configuration.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This is the target server instance. If this option is not specified, then DAS will find a server instance or multiple server instances. A
  migration notification will be sent to the selected server instances.
`--destination`::
  This option is deprecated. It works exactly as the `--target` option does.

[[operands]]
== Operands

server_name::
  This is the server instance on which the timers are currently located.
  This server instance should not be running during the migration process.

[[examples]]
== Examples

*Example 1 Migrating Timers*

This example shows how to migrate timers from the server named `instance1` to a server named `instance2`.

[source,shell]
----
asadmin> migrate-timers --target instance2 instance1
This command was successfully executed.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-timers.adoc#list-timers[`list-timers`]


