[[monitoring]]
= monitoring

Reviewing the runtime state of components and services deployed in Payara Server.

[[description]]
== Description

Monitoring is the process of reviewing the statistics of a system to improve performance or solve problems. By monitoring the state of various components and services deployed in Payara Server, performance bottlenecks can be identified, failures can be anticipated, and runtime standards can be established and observed. Data gathered by monitoring can also be useful in performance tuning and capacity planning.

The Payara Server monitoring service is enabled by default, that is, the `monitoring-enabled` attribute of the `monitoring-service` element is set to true. Once the monitoring service is enabled, a deployed module can then be enabled for monitoring by setting its monitoring level to `HIGH` or `LOW` (default is `OFF`).

Monitoring can be configured dynamically by using the Administration Console or the
`enable-monitoring`/`disable-monitoring` and `set-monitoring-service-configuration` subcommands. The `set` subcommand can also be used with dotted names to enable or disable monitoring. However, a server restart is required for changes made by using the `set` subcommand to take effect.

Monitoring data can be viewed by using the Administration Console or by using the subcommands of the `asadmin` utility.

* The `monitor` subcommand displays monitoring data for a given type, similar to the UNIX `top` command. The data is presented at given intervals.
* The `list` and `get` subcommands display comprehensive data. Both use dotted names to specify monitorable objects.

Alternate tools for monitoring Payara Server components and services include JConsole and the REST interface.

The Monitoring Scripting Client or DTrace Monitoring can be used to start the available monitoring probes. Using these tools is helpful in identifying performance issues during runtime.

TIP: Monitoring Scripting Client or DTrace Monitoring are only usable if their modules are present.

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitor.adoc#monitor[`monitor`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-monitoring.adoc#enable-monitoring[`enable-monitoring`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-monitoring.adoc#disable-monitoring[`disable-monitoring`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-monitoring-service-configuration.adoc#set-monitoring-service-configuration[`set-monitoring-service-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list.adoc#list[`list`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get.adoc#get[`get`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set.adoc#set[`set`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/Dotted Names.adoc#dotted-names[`dotted-names`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Monitoring Service.adoc#administering-the-monitoring-service[Administering the Monitoring Service] in the Payara Server General Administration section
