[[notification-configure]]
= notification-configure

Configures the notification service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] notification-configure
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
----

[[description]]
== Description

This command can be used to configure the behaviour of the log notifier in Payara Server.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the notification service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the notification service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.

[[examples]]
== Examples

*Example 1 Enables the notification service*

[source, shell]
----
asadmin> notification-configure --enabled=true --dynamic=true
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-log-notifier-configuration.adoc#get-log-notifier-configuration[`get-log-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-jms-notifier-configuration.adoc#get-jms-notifier-configuration[`get-jms-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-eventbus-notifier-configuration.adoc#get-eventbus-notifier-configuration[`get-eventbus-notifier-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-cdieventbus-notifier-configuration.adoc#get-cdieventbus-notifier-configuration[`get-cdieventbus-notifier-configuration`]
