[[overview]]
= Overview

This section contains reference collection of all Asadmin CLI subcommands available for the Administration interface of Payara Server and a comprehensive detail of what each command does and how it operates.

Here's a brief description of the structure each command page section and the information it references:

Name:: This section gives the names of the commands or functions documented, followed by a brief description of what they do.

Synopsis:: This section shows the syntax of commands or functions. +
+
The following special characters are used in this section:
+
  `[ ]`;;
    Brackets. The option or argument enclosed in these brackets is optional. If the brackets are omitted, the argument must be specified.
  `|`;;
    Separator. Only one of the arguments separated by this character can be specified at a time.

Description:: This section defines the functionality and behavior of the service. Thus, it describes concisely what the command does. It does not discuss options or cite examples
.
Options:: This section lists the command options with a concise summary of what  each option does. The options are listed literally and in the order  they appear in the Synopsis section.
+
Possible arguments to options are discussed under the option, and where appropriate, default values are supplied.

Operands:: This section lists the command operands and describes how they affect the actions of the command.

Examples:: This section provides examples of usage or of how to use a command or function. Wherever possible a complete example including command-line entry and machine response is shown. Examples are followed by explanations, variable substitution rules, or returned values. Most examples illustrate concepts from the Synopsis, Description, Options, and Usage sections.

Exit Status:: This section lists the values the command returns to the calling program or shell and the conditions that cause these values to be returned. Usually, zero (`0`) is returned for successful completion, and values other than zero for various error conditions.

See Also:: This section lists references to other man pages, in-house documentation, and outside publications.

Notes:: This section lists additional information that does not belong anywhere else on the page. It takes the form of an aside to the user, covering points of special interest.
