[[ping-node-dcom]]
= ping-node-dcom

Tests if a node that is enabled for communication over DCOM is usable.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] ping-node-dcom [--help]
[--validate={false|true}] node-name
----

[[description]]
== Description

The `ping-node-dcom` subcommand tests if a node that is enabled for communication over the Distributed Component Object Model (DCOM) remote
protocol is usable. The DCOM protocol is available only on Windows systems. This subcommand requires DCOM to be configured on the machine
where the domain administration server (DAS) is running and on the machine where the node resides. You may run this command from any
machine that can contact the DAS.

If the node is usable, the subcommand displays a confirmation that the subcommand could connect to the node through DCOM. This confirmation
includes the name of the host that the node represents.

Optionally, the subcommand can also validate the node to determine if the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] utility can run on the
host that the node represents. To validate a node, the subcommand runs the xref:Technical Documentation/Payara Server Documentation/Command Reference/version.adoc#version[`version`] subcommand. If the node is
valid, the subcommand displays the version that the `version` subcommand returns.

The node that is specified as the operand of this subcommand must be enabled for communication over DCOM. If the node is not enabled for
communication over DCOM, an error occurs. To determine whether a node is enabled for communication over DCOM, use the
xref:Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc#list-nodes[`list-nodes`] subcommand.

NOTE: To test whether a node that is enabled for communication over secure
shell (SSH) is usable, use the xref:Technical Documentation/Payara Server Documentation/Command Reference/ping-node-ssh.adoc#ping-node-ssh[`ping-node-ssh`] subcommand.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--validate`::
  Specifies whether the subcommand validates the node. +
  Possible values are as follows: +
  `true`;;
    The node is validated.
  `false`;;
    The node is not validated (default).

[[operands]]
== Operands

node-name::
  The name of the node to test. The node must be enabled for communication over DCOM. Otherwise, an error occurs.

[[examples]]
== Examples

*Example 1 Testing if a DCOM-Enabled Node Is Usable*

This example tests if the DCOM-enabled node `wpmd2` is usable.

[source,shell]
----
asadmin> ping-node-dcom wpmdl2
Successfully made DCOM connection to node wpmdl2 (wpmdl2.example.com)
Command ping-node-dcom executed successfully.
----

//TODO - Review if the command output prints "GlassFish"

*Example 2 Validating a DCOM-Enabled Node*

This example validates the DCOM-enabled node `adc-node`.

[source, shell, subs=attributes+]
----
asadmin> ping-node-dcom --validate=true adc-node
Successfully made DCOM connection to node adc-node (adc-node.example.com)
GlassFish version found at C:\payara:
Using locally retrieved version string from version class.
Version = Payara Server {page-version} #badassfish (build 00)
Command version executed successfully.
Command ping-node-dcom executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-dcom.adoc#create-node-dcom[`create-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-node-dcom.adoc#delete-node-dcom[`delete-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc#list-nodes[`list-nodes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/ping-node-ssh.adoc#ping-node-ssh[`ping-node-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-node-dcom.adoc#update-node-dcom[`update-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/validate-dcom.adoc#validate-dcom[`validate-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/version.adoc#version[`version`]


