[[remove-instance-from-deployment-group]]
= remove-instance-from-deployment-group

Removes a standalone instance from an existing deployment group.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] remove-instance-from-deployment-group [--help]
[--instance instanceName]
[--deploymentgroup deploymentGroupName]
----

[[description]]
== Description

The `remove-instance-from-deployment-group` subcommand will remove the referenced instance from the referenced deployment group.

If the referenced instance doesn't belong to the deployment group the command will exit with an error.

IMPORTANT: Removing an instance from a deployment group does not delete it.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
Displays the help text for the subcommand.

`--instance`::
The name of the standalone instance that will be removed from the deployment group. The command will fail if the name doesn't match to an existing standalone instance that belongs to the deployment group.

`--deploymentGroup`::
The name of the deployment group from which the standalone instance will be removed. The command will fail if the name doesn't match to an existing deployment group.

[[examples]]
== Examples

*Example 1 Removes an instance from a Deployment Group*

This example removes the instance named `test-instance-1` from the deployment group named `test-dgroup`:

[source,shell]
----
asadmin remove-instance-from-deployment-group --instance=test-instance-1 --deploymentGroup=test-dgroup

Command remove-instance-from-deployment-group executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

See Also

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-deployment-group.adoc#create-deployment-group[`create-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-deployment-group.adoc#delete-deployment-group[`delete-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-deployment-groups.adoc#list-deployment-groups[`list-deployment-groups`]
