[[remove-library]]
= remove-library

Removes one or more library JAR files from Payara Server.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] remove-library [--help]
[--type={common|ext|app}]
library-name [library-name ... ]
----

[[description]]
== Description

The `remove-library` subcommand removes one or more library JAR files from Payara Server.

The `--type` option specifies the library type and the Payara Server directory from which the library is removed.

The library-name operand is the name of the JAR file that contains the library to be removed. To specify multiple libraries, specify multiple names separated by spaces.

NOTE: The library archive file is removed from the DAS. For common and extension libraries, you must restart the DAS so the library removals
are picked up by the server runtime. To remove the libraries from other server instances, synchronize the instances with the DAS by restarting them.

This command is not supported on the Windows operating system.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--type`::
  Specifies the library type and the Payara Server directory from which the library is removed. Valid values are as follows: +
  `common`;;
    Removes the library files from the Common class loader directory, domain-dir`/lib`. This is the default.
  `ext`;;
    Removes the library files from the Java optional package directory, domain-dir`/lib/ext`.
  `app`;;
    Removes the library files from the application-specific class loader directory, `domain-dir/lib/applibs`. +
  For more information about these directories, see xref:Technical Documentation/Application Development/Class Loaders.adoc#classloading[Class Loaders] in the Payara Server Application Development section.

[[operands]]
== Operands

library-name::
  The names of the JAR files that contain the libraries that are to be removed.

[[examples]]
== Examples

*Example 1 Removing Libraries*

This example removes the library in the archive file `mylib.jar` from the application-specific class loader directory on the default server instance.

[source,shell]
----
asadmin> remove-library --type app mylib.jar
Command remove-library executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/add-library.adoc#add-library[`add-library`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-libraries.adoc#list-libraries[`list-libraries`],
* xref:Technical Documentation/Application Development/Class Loaders.adoc#classloading[Class Loaders] in the Payara Server Application Development section.


