[[restart-domain]]
= restart-domain

Restarts the Domain Administration Server(DAS) of the specified domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] restart-domain [--help] 
[--debug ={true|false}] 
[--domaindir domaindir]
[--timeout timeout]
[--force={true|false}] [--kill={false|true}] 
[domain-name]
----

[[description]]
== Description

The `restart-domain` subcommand stops and then restarts the domain administration server (DAS) of the specified domain. If a domain is not specified, the default domain is assumed. If the domains directory contains two or more domains, the domain-name operand must be specified. If the DAS is not already running, the subcommand attempts to start it.

The `restart-domain` subcommand does not exit until the subcommand has verified that the domain has been stopped and restarted.

This subcommand is supported in local or remote mode. If you specify a host name, the subcommand assumes you are operating in remote mode, which means you must correctly authenticate to the remote server. In local mode, you normally do not need to authenticate to the server as long as you are running the subcommand as the same user who started the server.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--debug`::
  Specifies whether the domain is restarted with link:https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html/[Java Platform Debugger Architecture (JPDA)] (https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html) debugging enabled. +
  Possible values are as follows: +
  `true`;;
    The domain is restarted with JPDA debugging enabled and the port number for JPDA debugging is displayed.
  `false`;;
    The domain is restarted with JPDA debugging disabled (default). +
  The default is the current setting of this option for the domain that is being restarted.
`--domaindir`::
  The domain root directory, which contains the directory of the domain that is to be restarted. If specified, the path must be accessible in the file system. The default location of the domain root directory is as-install`/domains`.
`--force`::
  Specifies whether the domain is forcibly stopped immediately before it is restarted. +
  Possible values are as follows: +
  `true`;;
    The domain is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the domain are exited before stopping the domain.
`--kill`::
  Specifies whether the domain is killed before it is restarted by using functionality of the operating system to terminate the domain process. +
  Possible values are as follows: +
  `false`;;
    The domain is not killed. The subcommand uses functionality of the Java platform to terminate the domain process (default).
  `true`;;
    The domain is killed. The subcommand uses functionality of the operating system to terminate the domain process.
`--timeout`::
Specifies how long to take for the domains to restart in seconds. If restarting the domains takes longer than this amount then this command will fail.
+
The default value is `600`.

[[operands]]
== Operands

domain-name::
  The name of the domain you want to restart. Default is the name specified during installation, usually `domain1`.

[[examples]]
== Examples

*Example 1 Restarting a Domain*

This example restarts `mydomain4` in the default domains directory.

[source,shell]
----
asadmin> restart-domain mydomain4
Successfully restarted the domain
Command restart-domain executed successfully. 
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-domain.adoc#create-domain[`create-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-domain.adoc#delete-domain[`delete-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-domains.adoc#list-domains[`list-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domain.adoc#restart-domain[`restart-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domains.adoc#start-domains[`start-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domains.adoc#stop-domains[`stop-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-all-domains.adoc#stop-all-domains[`stop-all-domains`]`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html/[Java Platform Debugger Architecture (JPDA)]
(`https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html/)


