[[restart-domains]]
= restart-domains

Restarts the Domain Administration Server(DAS) of the specified domains.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] restart-domains [--help]
[--domainTimeout timeout]
[--timeout timeout]
[domain-name]
----

[[description]]
== Description

The `restart-domains` subcommand can be used to restart the specified list of domains in the operand. This list must be specified as a comma separated string of values.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--timeout`::
Specifies how long to take for the domains to restart in seconds. If restarting the domains takes longer than this amount then this command will fail.
+
The default value is `600`.

`--domainTimeout`::
Specifies how long to take for each domain to restart in seconds. If restarting the domain takes longer than this amount then this command will fail.
+
The default value is `600`.

[[operands]]
== Operands

domain-names::
  The name of the domains you want to restart.

[[examples]]
== Examples

*Example 1 Restarting Domains*

This example restarts `domain1` and `testy` in the default domains directory.

[source,shell]
----
asadmin restart-domains domain1,testy

Successfully restarted the domain
Restarted domain domain1

Successfully restarted the domain
Restarted domain testy

Command restart-domains executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-domains.adoc#list-domains[`list-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domain.adoc#restart-domain[`restart-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domains.adoc#start-domains[`start-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domains.adoc#stop-domains[`stop-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-all-domains.adoc#stop-all-domains[`stop-all-domains`]
* https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html/[Java Platform Debugger Architecture (JPDA)]
(`https://docs.oracle.com/javase/8/docs/technotes/guides/jpda/index.html/)


