[[restore-domain]]
= restore-domain

Restore files from backup.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] restore-domain [--help]
[--long[={false|true}]]
[--filename backup-filename]
[--domaindir domain-root-dir]
[--backupdirbackup-directory]
[--backupconfigbackup-config-name]
[--force[={false|true}]]
[domain-name]
----

[[description]]
== Description

This command restores files under the domain from a backup directory.

The `restore-domain` command is supported in local mode only.

WARNING: If a domain is restored on an already existing domain folder, all the files will be overwritten when the command is run.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::

  Displays the help text for the subcommand.

`--long`::
`-l`::
  Displays detailed information about the restore operation.
+
The default value is `false`.

`--filename`::
  Specifies the name of the backup file to use as the source.

`--domaindir`::
  Specifies the domain root directory, the parent directory of the domain to restore.
+
The default value is `as-install/domains`.

`--backupdir`::
  Specifies the directory under which the backup file is stored.
+
The default value is `as-install/domains/domain-dir/backups`. If the domain is not in the default location, the location is `domain-dir/backups`.

`--backupconfig`::
  The name of the domain backup configuration in the backup directory under which the backup file is stored.

`--force`::
  Causes the restore operation to continue even when the name of the domain to restore does not match the name of the domain stored in the backup file.
+
The default value is `false`.

[[operands]]
== Operands

domain-name::
  Specifies the name of the domain to restore.
+
This operand is optional if only one domain exists in the Payara Server installation.
+
If the specified domain name does not match the domain name stored in the backup file, an error occurs unless the `--force` option is specified.

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/backup-domain.adoc#backup-domain[`backup-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-backups.adoc#list-backups[`list-backups`]


