[[rotate-log]]
= rotate-log

Rotates the log file.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] rotate-log [--help]
----

[[description]]
== Description

The `rotate-log` subcommand rotates the server log by renaming the file with a timestamp name in the format `server.log_`date-and-time, and creating a new log file. Changes take effect dynamically, that is,server restart is not required.

The size of the log queue is configurable through the `logging.properties` file. Log rotation is based on file size or elapsed time since the last log rotation. In some circumstances, the queue might fill up, especially if the log level is set to `FINEST` and there is heavy activity on the server. In this case, the `rotate-log` subcommand can be used to rotate the server log immediately. This subcommand is also useful in creating scripts for rotating the log at convenient times.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  The server, cluster, or server instance for which logs will be rotated. If this option is omitted, logs are rotated for the default server.

[[operands]]
== Operands

target::
  Valid values are: +
  * server_name - Default target is `server`. If no target is specified then logs are rotated for the server.
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

*Example 1 Rotating the Server Log*

This example rotates the server log.

[source,shell]
----
asadmin> rotate-log
Command rotate-log executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/collect-log-files.adoc#collect-log-files[`collect-log-files`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-attributes.adoc#list-log-attributes[`list-log-attributes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-attributes.adoc#set-log-attributes[`set-log-attributes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-levels.adoc#set-log-levels[`set-log-levels`]
* "xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Logging Service.adoc#administering-the-logging-service[Administering the Logging Service]" in Payara Server General Administration section


