[[set-rest-monitoring-configuration]]
= set-rest-monitoring-configuration

Configures the REST monitoring service subsystem.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-rest-monitoring-configuration
[--help]
[--target target]
[--enabled={false|true}]
[--securityEnabled={false|true}]
[--contextRoot contextRoot]
[--applicationName name]
----

[[description]]
== Description

This command can be used to configure the settings of the REST Monitoring subsystem.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the REST monitoring service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the REST monitoring service
`--securityEnabled`::
Defaults to `false`. Whether to secure access to the REST Monitoring application is enabled.
`--contextRoot`::
Defaults to `/rest-monitoring`. The context root of the REST Monitoring application.
`--applicationName`::
Defaults to `__restmonitoring`. The name of the REST Monitoring application.

[[examples]]
== Examples

*Example 1 Enables REST monitoring service on the `/rest-mon` context root*

[source, shell]
----
asadmin set-rest-monitoring-configuration --enabled=true --contextRoot /rest-mon --target=server
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-rest-monitoring-configuration.adoc[`get-rest-monitoring-configuration`]
