[[set-jdbc-config-source-configuration]]
= set-jdbc-config-source-configuration

Configures the JDBC configuration source.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-jdbc-config-source-configuration [--help]
[--jndiname=jndiname]
[--tablename=tablename]
[--keycolumnname=keycolumnname]
[--valuecolumnname=valuecolumnname]
[--target=server]
----

[[description]]
== Description

The `set-jdbc-config-source-configuration` provides configuration options to set the properties required by JDBC config source to read the values from the configured database.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--jndiName`::
JNDI (Java Naming and Directory Interface) name under which the JDBC resource will be registered in the application server's JNDI namespace.
`--tablename`::
Name of the table in the database.
`--keycolumnname`::
Name of the column in the specified table that serves as the key for retrieving data.
`--valuecolumnname`::
Name of the column in the specified table that contains the values associated with the keys.
`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.

[[examples]]
== Example

*Example 1 Configuring the JDBC Config Source.*

This example configures the JDBC config source.

[source,shell]
----
asadmin set-jdbc-config-source-configuration --jndiName jndi-name --tableName Books --keyColumnName ISBN --valueColumnName Title
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-jdbc-config-source-configuration.adoc#get-jdbc-config-source-configuration[`get-jdbc-config-source-configuration`]
