[[set-log-notifier-configuration]]
= set-log-notifier-configuration

Configures the settings of the Log notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-log-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--filter={INFO|WARNING|SEVERE}]
[--useseparatelogfile={false|true}]
----

[[description]]
== Description

This command can be used to configure the behaviour of the log notifier in Payara Server.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the log notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--filter`::
Defaults to `WARNING`. The notifier only responds to events at or above this level. (INFO, WARNING, SEVERE)
`--useseparatelogfile`::
Defaults to `false`. Whether to use a separate log file to store notifications.

[[examples]]
== Examples

*Example 1 Enable the Log Notifier and Configure Filter level*

[source, shell]
----
asadmin> set-log-notifier-configuration --enabled=true --dynamic=true --filter=INFO
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-log-notifier-configuration.adoc#get-log-notifier-configuration[`get-log-notifier-configuration`],
