[[set-amx-enabled]]
= set-amx-enabled

Enables or disables the AMX monitoring subsystem.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-amx-enabled
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
----

[[description]]
== Description

This command can be used to configure the boot AMX at startup or independently of the JMX Monitoring service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring AMX boot. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the monitoring service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.

[[examples]]
== Examples

*Example 1 Enables the AMX subsystem immediately for the DAS*

[source, shell]
----
asadmin set-amx-enabled --enabled=true --dynamic=true --target=server
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-jmx-monitoring-configuration.adoc[`set-jmx-monitoring-configuration`]
