[[set-monitoring-service-configuration]]
= set-monitoring-service-configuration

Configures the monitoring service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-monitoring-service-configuration
[--help]
[--target target]
[--enabled={false|true}]
[--mbeansenabled={false|true}]
[--amxenabled={false|true}]
[--dtraceenabled={false|true}]
----

[[description]]
== Description

This command can be used to configure the basic settings of the Monitoring service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the monitoring service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the monitoring service
`--mbeansenabled`::
Defaults to `false`. Whether to enable or disable MBean monitoring.
`--amxenabled`::
Defaults to `false`. Whether to enable or disable the AMX subsystem on boot.
`--dtraceenabled`::
Defaults to `false`. Whether to enable or disable the DTrace monitoring.

[[examples]]
== Examples

*Example 1 Basic configuration of the monitoring service*

[source, shell]
----
asadmin set-monitoring-service-configuration --enabled=true --mbeansenabled=true --amxenabled=true --target=server
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/monitoring.adoc[Monitoring Basics]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/enable-monitoring.adoc[`enable-monitoring`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/disable-monitoring.adoc[`disable-monitoring`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-monitoring-level.adoc[`set-monitoring-level`]
