[[set-fault-tolerance-configuration]]
= set-fault-tolerance-configuration

Modifies the configuration settings of the MicroProfile Fault Tolerance service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-fault-tolerance-configuration [--help]
[--managedexecutorservicename=managedexecutorservicename]
[--managedscheduledexecutorservicename=managedscheduledexecutorservicename]
[--target=server-config]
----

[[description]]
== Description

The `set-fault-tolerance-configuration` provides a way to modify the configuration of the MicroProfile Fault Tolerance service in the specified target.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--managedexecutorservicename`::
The Logical JNDI name of the Managed Executor Service to look up. Changes to this configuration require a restart of the server to take effect.
+
Defaults to `java:comp/DefaultManagedExecutorService`

`--managedscheduledexecutorservicename`::
The Logical JNDI name of the Managed Scheduled Executor Service to look up. Changes to this configuration require a restart of the server to take effect.
+
Defaults to `java:comp/DefaultManagedScheduledExecutorService`

`--target`::
Specifies the target of this command. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Setting MicroProfile Fault Tolerance configuration*

This example sets the configuration of the MicroProfile Fault Tolerance service.

[source,shell]
----
asadmin> set-fault-tolerance-configuration --managedexecutorservicename=java:comp/DefaultManagedExecutorService --target instance1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-fault-tolerance-configuration.adoc#get-fault-tolerance-configuration[`get-fault-tolerance-configuration`]
