[[set-environment-warning-configuration]]
= set-environment-warning-configuration

Allows customization of a warning bar for clear identification of the server environment in the Admin Console.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-environment-warning-configuration [--help]
[--enabled={true|false}]
[--message=message]
[--backgroundcolour=backgroundcolour]
[--textcolour=textcolour]
----

[[description]]
== Description

The `set-environment-warning-configuration` subcommand sets the environment warning properties and can enable/disable the warning.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
--enabled::
Activates or deactivates the Environment Warning feature, enabling or disabling the display of the warning bar in the Admin Console based on the chosen setting.
--message::
Specifies the custom text message to be displayed within the Environment Warning bar, allowing for tailored alerts or reminders specific to the current server environment.
--backgroundcolour::
Sets the background color of the Environment Warning bar, providing a visual means to distinguish between different environments by color-coding the warning bar.
--textcolour::
Determines the color of the text within the Environment Warning bar, ensuring readability and contrast against the background color, enhancing the visibility of the warning message.

[[examples]]
== Examples

*Example 1*

[source, shell]
----
asadmin> set-environment-warning-configuration --enabled=true --message="Caution, this is on production" --textcolour="#00ff00" --backgroundcolour="#ff00ff"
Command set-environment-warning-configuration executed successfully.
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-environment-warning-configuration.adoc#get-environment-warning-configuration[`get-environment-warning-configuration`]



