[[set-batch-runtime-configuration]]
= set-batch-runtime-configuration

Configures the batch runtime.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-batch-runtime-configuration [--help]
[--target target]
[--datasourcelookupname datasource-lookup-name]
[--executorservicelookupname executor-service-lookup-name]
[--schemaName schema-name --tablePrefix table-prefix --tableSuffix table-suffix]
----

[[description]]
== Description

The `set-batch-runtime-configuration` subcommand configures the batch runtime. The runtime uses a data source and a managed executor service to execute batch jobs. Batch runtime configuration data is stored in the`config` element in `domain.xml`.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target for which to configure the batch runtime. Valid values are as follows: +
  `server`;;
    Configures the batch runtime for the default server instance `server` and is the default value.
  cluster-name;;
    Configures the batch runtime for every server instance in the cluster.
  instance-name;;
    Configures the batch runtime for a particular server instance.
`--datasourcelookupname`::
`-d`::
  The JNDI lookup name of the data source to be used to store job information.
+
The default data source is `jdbc/__TimerPool`.
+
NOTE: Do not change the data source after the first batch job has been submitted to the batch runtime for execution. If the data source must be changed, stop and restart the domain and then make the change before any jobs are started or restarted. However, once the data source has been changed, information stored in the previous data source becomes inaccessible.
`--executorservicelookupname`::
`-x`::
  The JNDI lookup name of the managed executor service to be used to provide threads to jobs. The default managed executor service is `concurrent/__defaultManagedExecutorService`. +
  The managed executor service can be changed after a batch job has been submitted to the batch runtime without impacting execution of the job.
`--schemaName`::
`-n`::
The database schema that holds the batch tables.
+
Defaults to `APP`
`--tablePrefix`::
The prefix to apply to the batch table name.
`--tableSuffix`::
Sets the suffix to apply to the batch table name.

[[examples]]
== Examples

*Example 1 Configuring the Batch Runtime*

The following example configures the batch runtime for the default server instance to use an existing managed executor service named `concurrent/myExecutor`.

[source,shell]
----
asadmin> set-batch-runtime-configuration --executorservicelookupname concurrent/myExecutor
Command set-batch-runtime-configuration executed successfully.
----

*Example 2 Configuring datasource and table data*

The following command will set the data source and the prefix and suffix for the DAS:

[source, shell]
----
asadmin> set-batch-runtime-configuration --target="server" --datasourcelookupname="jdbc/BatchJobsDS" --tablePrefix="BATCHJ_" --tableSuffix="_JB"
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-jobs.adoc#list-batch-jobs[`list-batch-jobs`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-job-executions.adoc#list-batch-job-executions[`list-batch-job-executions`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-job-steps.adoc#list-batch-job-steps[`list-batch-job-steps`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-batch-runtime-configuration.adoc#list-batch-runtime-configuration[`list-batch-runtime-configuration`]


