[[set-notification-configuration]]
= set-notification-configuration

Configures the notification service along with the log notifier.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-notification-configuration
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--notifierEnabled={false|true}]
[--notifierDynamic={false|true}]
[--noisy={false|true}]
[--useseparatelogfile={false|true}]
----

[[description]]
== Description

This command can be used to set the configuration of the Notification Service and the Log Notifier at the same time.

It functions as a combination of the `notification-configure` and `set-log-notifier-configuration` Asadmin commands.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the notification service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the notification service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
`--notifierEnabled`::
Defaults to `false`. Enables or disables the log notifier
`--notifierDynamic`::
Defaults to `false`. When set to `true`, applies the changes to the log notifier without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the log notifier is active even if a notification event threshold is set to `FINE`.
`--useseparatelogfile`::
Defaults to `false`. Whether to use a separate log file to store notifications.

[[examples]]
== Examples

*Example 1 Enables the notification service*

[source, shell]
----
asadmin set-notification-configuration --enabled=true --dynamic=true --notifierEnabled=true --notifierDynamic=true --useSeparateLogfile=false
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/notification-configure.adoc#notification-configure[`notification-configure`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-notifier-configuration.adoc#set-log-notifier-configuration[`set-log-notifier-configuration`]
