[[set-log-levels]]
= set-log-levels

Sets the log level for one or more loggers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-log-levels [--help]
[--target=target]
logger-name=logger-level[:logger-name=logger-level]*
----

[[description]]
== Description

The `set-log-levels` subcommand sets the log level for one or more loggers. Changes take effect dynamically. Depending on the log levels
you set, a server restart may be necessary.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  The server instance or cluster for which log levels will be set. Valid values are: +
  * `server` - The default server instance. If no target is specified then log levels are set for the default server instance.
  * cluster-name - The name of a cluster.
  * instance-name - The name of a standalone server instance.

[[operands]]
== Operands

logger-name::
  The name of the logger. The `list-log-levels` subcommand can be used to list the names of the current loggers.
logger-level::
  The level to set for the logger. Log level values are `SEVERE`, `WARNING`, `INFO`, `CONFIG`, `FINE`, `FINER`, and `FINEST`. The default setting is `INFO`.

[[examples]]
== Examples

*Example 1 Setting a Log Level for a Logger*

This example sets the log level of the web container logger to `WARNING`.

[source,shell]
----
asadmin> set-log-levels jakarta.enterprise.system.container.web=WARNING
Command set-log-level executed successfully.
----

*Example 2 Setting the Log Level for Multiple Loggers*

This example sets the log level of the web container logger to `FINE` and the log level of the EJB container logger to `SEVERE`:

[source,shell]
----
asadmin set-log-levels jakarta.enterprise.system.container.web=FINE:
jakarta.enterprise.system.container.ejb=SEVERE
Command set-log-level executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/collect-log-files.adoc#collect-log-files[`collect-log-files`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-attributes.adoc#list-log-attributes[`list-log-attributes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/rotate-log.adoc#rotate-log[`rotate-log`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-log-attributes.adoc#set-log-attributes[`set-log-attributes`],
* xref:Technical Documentation/Payara Server Documentation/General Administration/Administering the Logging Service.adoc#administering-the-logging-service[Administering the Logging Service] in the Payara Server General Administration section.
