[[set-jms-notifier-configuration]]
= set-jms-notifier-configuration

Configures the settings of the JMS notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-jms-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--contextFactoryClass className]
[--connectionFactoryName connectionFactoryName]
[--queueName queueName]
[--url url]
[--userName userName]
[--password password]
----

[[description]]
== Description

This command can be used to configure the behaviour of the JMS notifier in Payara Server Full Profile.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the JMS notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified sever instance.
`--enabled`::
Defaults to `false`. Enables or disables the notifier
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--contextFactoryClass`::
Defines the naming context factory class used to provision the JMS resources required to send the notification events.
+
NOTE: The referenced class name should point to a valid implementation of `javax.naming.spi.InitialContextFactory` and should be located in the server's classpath.
+
TIP: In most cases, using the default context factory class (`com.sun.enterprise.naming.SerialInitContextFactory`) is enough.
`--connectionFactoryName`::
Defines the JNDI name of an existing JMS connection factory which will be used to send the notification messages.
`--queueName`::
Defines the physical name of an existing JMS queue destination used to send the messages to.
`--url`::
Defines the URL of a JMS broker server that will handle the sending and reception of the notification message.
`--userName`::
Defines the user that will authentication to the JMS broker server (if required).
`--password`::
Defines the password credential of the user that will authentication to the JMS broker server (if required).

[[examples]]
== Examples

*Example 1 Enable the JMS Notifier and Configure it using OpenMQ*

This example enables the JMS notifier and sets it up to connect to the default, local OpenMQ broker server and use a queue named `testQueue`:

[source, shell]
----
asadmin set-jms-notifier-configuration --dynamic=true --enabled=true --contextFactoryClass=com.sun.enterprise.naming.SerialInitContextFactory --connectionFactoryName=jms/__defaultConnectionFactory --queueName=testQueue --url=localhost:7676 --username=testUser --password=******** --target=server-config
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-jms-notifier-configuration.adoc#get-jms-notifier-configuration[`get-jms-notifier-configuration`]
