[[set-healthcheck-configuration]]
= set-healthcheck-configuration

Configures the Healthcheck service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-healthcheck-configuration
[--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--historic-trace-enabled={false|true}]
[--historic-trace-store-size size]
[--historic-trace-store-timeout integer.value {s|m|h|d}]
[--set-notifiers notifiers]
[--enable-notifiers notifiers]
[--disable-notifiers notifiers]
----

[[description]]
== Description

Enables and disables the HealthCheck service. This includes configuration for tracing historic health check events for later inspection.

This command can also be used to configure which notifiers will be used to broadcast notification events from the Healthcheck service.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the Healthcheck service. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the healthcheck service
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
`--historic-trace-enabled`::
Defaults to `false`. Enables storing traces in a rolling store for later inspection.
`--historic-trace-store-size`::
Defaults to `20`. Sets the maximum number of health checks to store.
`--historic-trace-store-timeout`::
Sets the time period after which a historic health check event entry is removed from history.
+
The time expression should consist of a number followed by a time unit; `s` for seconds, `m` for minutes, `h` for hours or `d` for days.
+
If no time unit is given the number specifies seconds.
+
If the parameter is zero or unspecified there is no timeout for entries.
`--set-notifiers`::
Use the option to set the notifiers that will receive notifications generated by the Healthcheck Service.
+
A comma-separated list can be used to represent multiple notifiers.
+
TIP: This option will replace all the notifiers that have already been set to the HealthCheck Service.
`--enable-notifiers`::
Use the option to enable one or more notifiers for the Healthcheck service.
+
A comma-separated list can be used to represent multiple notifiers.
`--disable-notifiers`::
Use the option to disable one or more notifiers for the Healthcheck service.
+
A comma-separated list can be used to represent multiple notifiers.

[[examples]]
== Examples

*Example 1 Basic Configuration*

The following example will enable the Healthcheck service such that it will only activate from the next time the server is restarted.

It sets the log notifier and JMS notifiers and the historical trace store to retain 20 health checks.

[source, shell]
----
asadmin set-healthcheck-configuration --enabled=true --dynamic=false --historic-trace-enabled=true --historic-trace-store-size=20 --set-notifiers=log-notifier,jms-notifier
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/set-healthcheck-service-configuration.adoc[`set-healthcheck-service-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-healthcheck-configuration.adoc[`get-healthcheck-configuration`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-healthcheck-services.adoc[`list-healthcheck-services`]
