[[set-cdieventbus-notifier-configuration]]
= set-cdieventbus-notifier-configuration

Configures the settings of the CDI Event Bus notifier

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-eventbus-notifier-configuration [--help]
[--target target]
[--enabled={false|true}]
[--dynamic={false|true}]
[--noisy={false|true}]
[--loopBack={false|true}]
[--hazelcastEnabled={false|true}]
----

[[description]]
== Description

This command can be used to configure the behaviour of the CDI EventBus notifier in Payara Server.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--target`::
This option helps specify the target on which you are configuring the CDI Event Bus notifier. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.
`--enabled`::
Defaults to `false`. Enables or disables the notifier.
`--dynamic`::
Defaults to `false`. When set to `true`, applies the changes without a server restart.
+
Otherwise, a restart is required.
`--noisy`::
Defaults to `false`. Whether the notifier is active even if the notification event threshold is set to `FINE`.
`--loopBack`::
Defaults to `false`. Whether events should also be observed on the same instance that triggered the instance or not.
`--hazelcastEnabled`::
Defaults to `false`. Whether to enable the Data Grid to send notification events to external instances.

[[examples]]
== Examples

*Example 1 Enable the CDI Event Bus notifier*

[source, shell]
----
asadmin set-cdieventbus-notifier-configuration --loopBack=true --dynamic=true --enabled=true --hazelcastEnabled=true
----

[[exit-status]]
== Exit Status

0::
subcommand executed successfully
1::
error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-cdieventbus-notifier-configuration.adoc#get-cdieventbus-notifier-configuration[`get-cdieventbus-notifier-configuration`]
