[[set-metrics-configuration]]
= set-metrics-configuration

Sets the configuration of the metrics service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> set-metrics-configuration
        [--enabled=true|false]
        [--securityenabled=true|false]
        [--roles=<role-list>]
        [--dynamic=true|false]
        [--endpoint=<context-root[default:metrics]>]
        [--target=<instance-name[default:server]>]
        [--virtualservers=<virtualserver-list>]
----

[[description]]
== Description

The `set-metrics-configuration` provides a way to set the configuration of the metrics service of the targeted config.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--enabled`::
Defaults to `true`. Enables or disables the metrics service.

`--securityenabled`::
Defaults to `false`. Specifies whether secure access to the metrics endpoint is enabled or disabled.

`--roles`::
Defaults to `microprofile`. If defined, the endpoint will be assigned to a list of the role specified as a comma-separated.

`--dynamic`::
Defaults to `true`. If set to true, applies the changes instantly without a restart. Otherwise a restart is required.

`--endpoint`::
Defaults to `metrics`. Specifies the context root used to expose the metrics endpoint.

`--target`::
Defaults to `server-config`. Specifies the target server/instance configuration.

`--virtualservers`::
If defined, the endpoint will be assigned to a list of virtual servers specified as a comma-separated list of names. Otherwise, the endpoint will be assigned to all virtual servers available.

[[examples]]
== Example

*Example 1 Setting the configuration of the metrics service*

This example sets the metrics service configuration for the specified target  instance1.

[source,shell]
----
asadmin> set-metrics-configuration --enabled=true --securityenabled=true --dynamic=true --target instance1

----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-metrics-configuration.adoc#get-metrics-configuration[`get-metrics-configuration`]

