[[set-fault-tolerance-configuration]]
= set-fault-tolerance-configuration

Provides a way to set the configuration of the fault tolerance service.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> set-fault-tolerance-configuration
  [--managedexecutorservicename=managedexecutorservicename]
  [--managedscheduledexecutorservicename=managedscheduledexecutorservicename]
  [--target=server-config]
----

[[description]]
== Description

The `set-fault-tolerance-configuration` provides a way to set the configuration of the fault tolerance service of the targeted config.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--managedexecutorservicename`::
The Logical JNDI name of the Managed Executor Service to look up. Changes to this configuration require a restart of the server to take effect.
Defaults to `java:comp/DefaultManagedExecutorService`

`--managedscheduledexecutorservicename`::
The Logical JNDI name of the Managed Scheduled Executor Service to look up. Changes to this configuration require a restart of the server to take effect.
Defaults to `java:comp/DefaultManagedScheduledExecutorService`

`--target`::
Defaults to server . The target configuration object to apply the change to.

[[examples]]
== Example

*Example 1 Setting fault tolerance*

This example sets the configuration of the fault tolerance service.

[source,shell]
----
asadmin> set-fault-tolerance-configuration --managedexecutorservicename=java:comp/DefaultManagedExecutorService --target instance1
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/get-fault-tolerance-configuration.adoc#get-fault-tolerance-configuration[`get-fault-tolerance-configuration`]