[[set-config-cache]]
= set-config-cache

Provides a way to set the value of the cache duration of Eclipse MicroProfile configuration properties.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-config-cache [--help]
[--duration=<duration.in.second>]
[--target=<target[default:server]>]
----

[[description]]
== Description

The `set-config-cache` sets the value of the cache duration of Eclipse MicroProfile configuration properties in the targeted instances.

TIP: A value of zero (`0`) disables caching for MicroProfile configuration properties.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--duration`::
Duration in seconds properties are cached. Defaults to 60.
`--target`::
Specifies the target where the configuration source resides. +
Valid values are as follows: +
`server`;;
Specifies the DAS (default).
instance-name;;
Specifies a Payara Server instance.
cluster-name;;
Specifies a cluster.
configuration-name;;
Specifies a named configuration.

[[examples]]
== Example

*Example 1 Disable Caching*

This example disables caching by setting the duration to `0`.

[source,shell]
----
asadmin set-config-cache --duration=0 --target=myAppCluster
----
*Example 2 Sets the caching duration*

This example sets the cache TTL (time to live) for configuration properties to `30` seconds.

[source,shell]
----
asadmin> set-config-cache --duration=30 --target=myAppCluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
