[[set-config-cache]]
= set-config-cache

Provides a way to set a cache duration for the target instance(s).

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin> set-config-cache --duration=<duration.in.second> --target=<target[default:server]>
----

[[description]]
== Description

The `set-config-cache` sets the cache duration for the target instance(s). Any duration equal to or below zero disables the caching of MP config properties.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

`--duration`::
Duration in seconds properties are cached. Defaults to 60.
`--target`::
Defaults to server (the DAS). The target configuration where the command should be run

[[examples]]
== Example

*Example 1 Disable Caching*

This example disables the caching by setting the duration to 0.

[source,shell]
----
asadmin> set-config-cache
    --duration=0
    --target=myAppCluster
----
*Example 2 Sets the caching duration*

This example sets the cache TTL (time to live) for properties to 30 seconds.

[source,shell]
----
asadmin> set-config-cache
    --duration=30
    --target=myAppCluster
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
