[[start-instance]]
= start-instance

Starts a Payara Server instance.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] start-instance [--help] 
[--debug={false|true}] [--sync={normal|full|none}] 
[--timeout timeout] instance-name
----

[[description]]
== Description

The `start-instance` subcommand starts a Payara Server instance.This subcommand requires the Distributed Component Object Model (DCOM) remote protocol or secure shell (SSH) to be configured on the machine where the domain administration server (DAS) is running and on the machine where the instance resides.

NOTE: DCOM or SSH is not required if the instance resides on a node of type `CONFIG` that represents the local host. A node of type `CONFIG` is not enabled for remote communication over DCOM or SSH.

You may run this subcommand from any machine that can contact the DAS.

The subcommand can start any Payara Server instance, regardless of how the instance was created. For example, this subcommand can start an instance that was created by using the xref:Technical Documentation/Payara Server Documentation/Command Reference/create-local-instance.adoc#create-local-instance[`create-local-instance`] subcommand.

This command is supported in remote mode only.

[[options]]
== Options

CAUTION: These are not the same options available for the `start-local-instance` command.

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
  Displays the help text for the subcommand.

`--debug`::
  Specifies whether the instance is started with http://www.oracle.com/technetwork/java/javase/tech/jpda-141715.html[Java
  Platform Debugger Architecture (JPDA)]
  debugging enabled.
+
Possible values are as follows:

  `true`;;
    The instance is started with JPDA debugging enabled and the port number for JPDA debugging is displayed.
  `false`;;
    The instance is started with JPDA debugging disabled (default).

`--sync`::
  The type of synchronization between the DAS and the instance's file when the instance is started.
+
Possible values are as follows:

  `none`;;
    The DAS does not synchronize the instance's files with any changes.
    This type of synchronization minimizes the time that is required to start the instance.
  `normal`;;
    The DAS synchronizes the instance with changes since the last synchronization as follows:
    * For the `config` directory, the DAS synchronizes the instance with all changes.
    * For the `applications` directory and `docroot` directory, only a change to a top-level subdirectory causes the DAS to synchronize all
    files under that subdirectory.
+
If a file below a top level subdirectory is changed without a change to a file in the top level subdirectory, full synchronization is
    required. In normal operation, files below the top level subdirectories of these directories are not changed. If an
    application is deployed and undeployed, full synchronization is not necessary to update the instance with the change.
+
This value is the default.

  `full`;;
    The DAS synchronizes the instance with all of the instance's files, regardless of whether the files have changed since the last
    synchronization. This type of synchronization might delay the startup of the instance while the DAS updates all files in the instance's directories.
+
WARNING: Using full synchronization will cause the configuration to be deleted if the DAS cannot be reached.

`--timeout`::
Specifies how long to take for the instance to start in seconds. If starting the instance takes longer than this amount then this command will fail (but the instance may still continue its startup process).
+
The default value is `120`.

`--terse`::
Specifies whether information on the result is output
+
The default value is `false`.

[[operands]]
== Operands

instance-name::
  The name of the Payara Server instance to start.

[[examples]]
== Examples

*Example 1 Starting a Payara Server Instance*

This example starts the Payara Server instance `pmdsa1`.

[source,shell]
----
asadmin start-instance pmdsa1
Waiting for the server to start ..............................
Successfully started the instance: pmdsa1
instance Location: /export/payara6/glassfish/nodes/localhost/pmdsa1
Log File: /export/payara6/glassfish/nodes/localhost/pmdsa1/logs/server.log
Admin Port: 24848
Command start-local-instance executed successfully.
The instance, pmdsa1, was started on host localhost

Command start-instance executed successfully.
----

*Example 2 Starting a Payara Server Instance With JPDA Debugging Enabled*

This example starts the Payara Server instance `ymlsa1` with JPDA debugging enabled.

[source,shell]
----
asadmin start-instance --debug=true ymlsa1
Waiting for the server to start ...............................
Successfully started the instance: ymlsa1
instance Location: /export/payara6/glassfish/nodes/localhost/ymlsa1
Log File: /export/payara6/glassfish/nodes/localhost/ymlsa1/logs/server.log
Admin Port: 24849
Debugging is enabled. The debugging port is: 29010
Command start-local-instance executed successfully.
The instance, ymlsa1, was started on host localhost

Command start-instance executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-instance.adoc#create-instance[`create-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-local-instance.adoc#create-local-instance[`create-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-instance.adoc#delete-instance[`delete-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/setup-ssh.adoc#setup-ssh[`setup-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-local-instance.adoc#start-local-instance[`start-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-instance.adoc#stop-instance[`stop-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-local-instance.adoc#stop-local-instance[`stop-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/validate-dcom.adoc#validate-dcom[`validate-dcom`],
* http://www.oracle.com/technetwork/java/javase/tech/jpda-141715.html [Java Platform Debugger Architecture (JPDA)]

