[[start-domains]]
= start-domains

Starts the Domain Administration Server(DAS) of the specified domains.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin start-domains [--help]
[--domainTimeout timeout]
[--timeout timeout]
[domain-name]
----

[[description]]
== Description

The `start-domains` subcommand can be used to start the specified list of domains in the operand. This list must be specified as a comma separated string of values.

NOTE: The domains will be started assuming default values for all options you would specify when running the start-domain command against one domain (default domain directory, debug mode off, verbose mode off, etc.)

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--timeout`::
Specifies how long to take for the domains to start in seconds. If starting the domains takes longer than this amount then this command will fail.
+
The default value is `600`.

`--domainTimeout`::
Specifies how long to take for each domain to start in seconds. If starting the domains takes longer than this amount then this command will fail.
+
The default value is `600`.

[[operands]]
== Operands

domain-names::
The list of unique names of the domains you want to start.

[[examples]]
== Examples

*Example 1 Starting multiple Domains*

This example starts `domain1` and `testy` in the default domains directory.

[source,shell]
----
asadmin> start-domains domain1,testy
Waiting for domain1 to start ..............................
Successfully started the domain : domain1
domain  Location: /myhome/payara6/glassfish/domains/domain1
Log File: /myhome/payara6/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Started domain domain1
Waiting for testy to start ...............................
Successfully started the domain : testy
domain  Location: /myhome/payara6/glassfish/domains/testy
Log File: /myhome/payara6/glassfish/domains/domain1/logs/server.log
Admin Port: 6048
Started domain testy
Command start-domains executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-domains.adoc#list-domains[`list-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domain.adoc#restart-domain[`restart-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domains.adoc#restart-domains[`restart-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domains.adoc#stop-domains[`stop-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-all-domains.adoc#stop-all-domains[`stop-all-domains`]


