[[stop-instance]]
= stop-instance

Stops a running Payara Server instance.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] stop-instance [--help] 
[--force={false|true}]
[--kill={false|true}]
instance-name
----

[[description]]
== Description

The `stop-instance` subcommand stops a running Payara Server instance.

The subcommand can stop any Payara Server instance, regardless of how the instance was created. For example, this subcommand can stop an
instance that was created by using the xref:Technical Documentation/Payara Server Documentation/Command Reference/create-local-instance.adoc#create-local-instance[`create-local-instance`] subcommand.

This command is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--force`::
  Specifies whether the instance is forcibly stopped immediately. +
  Possible values are as follows: +
  `true`;;
    The instance is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the instance are exited before stopping the instance.
`--kill`::
  Specifies whether the instance is killed by using functionality of the operating system to terminate the instance process. +
  Possible values are as follows: +
  `false`;;
    The instance is not killed. The subcommand uses functionality of the Java platform to terminate the instance process (default).
  `true`;;
    The instance is killed. The subcommand uses functionality of the operating system to terminate the instance process.

[[operands]]
== Operands

instance-name::
  This is the name of the Payara Server instance to stop.

[[examples]]
== Examples

This example stops the Payara Server instance `yml-i-sj01`.

*Example 1 Stopping a Payara Server Instance*

[source,shell]
----
asadmin> stop-instance yml-i-sj01
The instance, yml-i-sj01, was stopped.
Command stop-instance executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-instance.adoc#create-instance[`create-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-local-instance.adoc#create-local-instance[`create-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-instance.adoc#delete-instance[`delete-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-instance.adoc#start-instance[`start-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-local-instance.adoc#start-local-instance[`start-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-local-instance.adoc#stop-local-instance[`stop-local-instance`]


