[[stop-domain]]
= stop-domain

Stops the Domain Administration Server(DAS) of the specified domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] stop-domain [--help] 
[--domaindir domaindir] 
[--force={true|false}]
[--kill={false|true}]
[--timeout timeout]
[domain-name]
----

[[description]]
== Description

The `stop-domain` subcommand stops the Domain Administration Server (DAS) of the specified domain. If the domain directory is not specified, the domain in the default domains directory is stopped. If there are two or more domains in the domains directory, the domain-name operand must be specified.

This subcommand is supported in local or remote mode. If you specify a host name, the subcommand assumes you are operating in remote mode, which means you must correctly authenticate to the remote server. In local mode, you normally do not need to authenticate to the server as long as you are running the subcommand as the same user who started the server.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--domaindir`::
  Specifies the directory of the domain that is to be stopped. If specified, the path must be accessible in the file system. If not
  specified, the domain in the default `as-install/domains` directory is stopped.
`--force`::
  Specifies whether the domain is forcibly stopped immediately. +
  Possible values are as follows: +
  `true`;;
    The domain is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the domain are exited before stopping the domain.
`--kill`::
  Specifies whether the domain is killed by using functionality of the operating system to terminate the domain process. +
  Possible values are as follows: +
  `false`;;
    The domain is not killed. The subcommand uses functionality of the Java platform to terminate the domain process (default).
  `true`;;
    The domain is killed. The subcommand uses functionality of the operating system to terminate the domain process.
`--timeout`::
Specifies how long to take for the domain to stop in seconds. If stopping the domain takes longer than this amount then this command will fail.
+
The default value is `600`.

[[operands]]
== Operands

domain-name::
  The name of the domain you want to stop. Default is the name specified during installation, usually `domain1`.

[[examples]]
== Examples

*Example 1 Stopping a Domain*

This example stops the domain named `sampleDomain` in the default domains directory.

[source,shell]
----
asadmin> stop-domain sampleDomain
Waiting for the domain to stop .................
Command stop-domain executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-domain.adoc#create-domain[`create-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-domain.adoc#delete-domain[`delete-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-domains.adoc#list-domains[`list-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domain.adoc#restart-domain[`restart-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-domains.adoc#restart-domains[`restart-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domains.adoc#start-domains[`start-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domains.adoc#stop-domains[`stop-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-all-domains.adoc#stop-all-domains[`stop-all-domains`]


