[[stop-local-instance]]
= stop-local-instance

Stops a Payara Server instance on the machine where the subcommand is run.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] stop-local-instance [--help]
[--nodedir node-dir] [--node node]
[--force={true|false}] [--kill={false|true}]
[instance-name]
----

[[description]]
== Description

The `stop-local-instance` subcommand stops a Payara Server instance on the machine where the subcommand is run. This subcommand does not
require secure shell (SSH) to be configured. You must run this command from the machine where the instance resides.

The subcommand can stop any Payara Server instance, regardless of how the instance was created. For example, this subcommand can stop an
instance that was created by using the xref:Technical Documentation/Payara Server Documentation/Command Reference/create-instance.adoc#create-instance[`create-instance`] subcommand.

The `stop-local-instance` subcommand does not contact the DAS to determine the node on which the instance resides. To determine the node
on which the instance resides, the subcommand searches the directory that contains the node directories. If multiple node directories exist,
the node must be specified as an option of the subcommand.

This subcommand is supported in local mode.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--nodedir`::
  Specifies the directory that contains the instance's node directory.
  The instance's files are stored in the instance's node directory. The default is as-install`/nodes`.
`--node`::
  Specifies the node on which the instance resides. This option may be omitted only if the directory that the `--nodedir` option specifies
  contains only one node directory. Otherwise, this option is required.
`--force`::
  Specifies whether the instance is forcibly stopped immediately. +
  Possible values are as follows: +
  `true`;;
    The instance is forcibly stopped immediately (default).
  `false`;;
    The subcommand waits until all threads that are associated with the instance are exited before stopping the instance.
`--kill`::
  Specifies whether the instance is killed by using functionality of the operating system to terminate the instance process. +
  Possible values are as follows: +
  `false`;;
    The instance is not killed. The subcommand uses functionality of the Java platform to terminate the instance process (default).
  `true`;;
    The instance is killed. The subcommand uses functionality of the operating system to terminate the instance process.

[[operands]]
== Operands

instance-name::
  The name of the instance to stop.

[[examples]]
== Examples

*Example 1 Stopping an Instance Locally*

This example stops the instance `yml-i-sj01` on the machine where the subcommand is run.

[source,shell]
----
asadmin> stop-local-instance --node sj01 yml-i-sj01
Waiting for the instance to stop ...
Command stop-local-instance executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-instance.adoc#create-instance[`create-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-local-instance.adoc#create-local-instance[`create-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-instance.adoc#delete-instance[`delete-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-instance.adoc#start-instance[`start-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-local-instance.adoc#start-local-instance[`start-local-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-instance.adoc#stop-instance[`stop-instance`]


