[[stop-deployment-group]]
= stop-deployment-group

Stops all the instances in a Payara Server deployment group.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] stop-deployment-group [--help]
[--instanceTimeout timeout]
[--timeout timeout]
[--kill={false|true}]
[--verbose={false|true}]
name
----

[[description]]
== Description

The `sop-deployment-group` subcommand sop all instances that belong to a Payara Server deployment group. Initially the deployment group contains no Payara Server instances, applications, or resources.

Internally this command works in the same manner that the xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-instance.adoc[`stop-instance`] subcommand.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.

`--help`::
`-?`::
Displays the help text for the subcommand.

`--verbose`::
`-v`::
Whether to stop the instances in verbose mode. Defaults to `false`.

`--timeout`::
Specifies how long to take for the instances to stop in seconds. If starting the instances takes longer than this amount then this command will fail.
+
The default value is `600`.

`--instanceTimeout`::
Specifies how long to take for each instance to stop in seconds. If stopping the instances takes longer than this amount then this command will fail.
+
The default value is `600`.
`--kill`::
Whether to kill the instance processes if they do not stop gracefully. Defaults to `false`.

[[operands]]
== Operands

name::
The name of the deployment group. If there are no deployment groups that match the name the command will exit with an error.

[[examples]]
== Examples

*Example 1 Stop a Deployment Group*

This example stops a deployment group that is named `test-dgroup` that contains one instance:

[source,shell]
----
asadmin stop-deployment-group test-dgroup
50%: stop-deployment-group: Executing stop-instance on 1 instances.
Command stop-deployment-group executed successfully.
----

*Example 2 Stop a Deployment Group with timeout*

This example stops a deployment group that is named `test-dgroup` that contains one instance, using an instance timeout of 30 seconds:

[source,shell]
----
asadmin stop-deployment-group --instanceTimeout 30 test-dgroup
50%: stop-deployment-group: Executing stop-instance on 1 instances.
Command stop-deployment-group executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

See Also

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-deployment-group.adoc#create-deployment-group[`create-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-instance.adoc#start-instance[`start-instance`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-deployment-groups.adoc#list-deployment-groups[`list-deployment-groups`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-deployment-group.adoc#stop-deployment-group[`stop-deployment-group`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/restart-deployment-group.adoc#restart-deployment-group[`restart-deployment-group`]
