[[unfreeze-transaction-service]]
= unfreeze-transaction-service

Resumes all suspended transactions.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] unfreeze-transaction-service [--help]
[--target target]
----

[[description]]
== Description

The `unfreeze-transaction-service` subcommand restarts the transaction subsystem and resumes all in-flight transactions. Invoke this subcommand
on an already frozen transaction subsystem.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are unfreezing the transaction service. Valid values are: +
  `server`;;
    Unfreezes the transaction service for the default server instance `server` and is the default value.
  configuration_name;;
    Unfreezes the transaction service for all server instances that use the named configuration.
  cluster_name;;
    Unfreezes the transaction service for every server instance in the cluster.
  instance_name;;
    Unfreezes the transaction service for a particular server instance.

[[examples]]
== Examples

*Example 1 Using unfreeze-transaction-service*

[source,shell]
----
% asadmin unfreeze-transaction-service
Command unfreeze-transaction-service executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/freeze-transaction-service.adoc#freeze-transaction-service[`freeze-transaction-service`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/recover-transactions.adoc#recover-transactions[`recover-transactions`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/rollback-transaction.adoc#rollback-transaction[`rollback-transaction`]
* xref:Technical Documentation/Payara Server Documentation/General Administration/Administering Transactions.adoc#administering-transactions[Administering Transactions] in Payara Server General Administration section
* https://jakarta.ee/specifications/transactions/2.0/[Transactions]


