[[uninstall-node-dcom]]
= uninstall-node-dcom

Uninstalls Payara Server software from specified DCOM-enabled hosts.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] uninstall-node-dcom [--help]
[--installdir as-install-parent]
[--windowsuser windows-user] [--windowsdomain windows-domain]
[--force={false|true}]
host-list
----

[[description]]
== Description

The `uninstall-node-dcom` subcommand uninstalls Payara Server software from the hosts that are specified as the operand of the
subcommand. This subcommand requires the Distributed Component Object Model (DCOM) remote protocol to be configured on the host where the
subcommand is run and on each host where the Payara Server software is being uninstalled.

NOTE: To uninstall Payara Server software on hosts that use secure shell (SSH), use the
xref:Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-ssh.adoc#uninstall-node-ssh[`uninstall-node-ssh`] subcommand.

By default, if any node except the predefined node `localhost-`domain resides on any host from which Payara Server software is being
uninstalled, the subcommand fails. To uninstall the Payara Server software from a host on which user-defined nodes reside, set the
`--force` option to `true`. If the `--force` option is `true`, the subcommand removes the entire content of the parent of the base installation directory.

If a file under the parent of the base installation directory is open, the subcommand fails.

If multiple hosts are specified, the configuration of the following items must be the same on all hosts:

* Parent of the base installation directory for the Payara Server software
* Windows user
* Windows domain

The subcommand does not modify the configuration of the domain administration server (DAS).

This subcommand is supported in local mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--installdir`::
  The absolute path to the parent of the base installation directory where the Payara Server software is installed on each host, for example, `C:\payara6`. +
  The user that is running this subcommand must have write access to the specified directory. Otherwise, an error occurs. +
  The specified directory must contain the installation of the Payara Server software on the host. Otherwise, an error occurs. +
  The default is the parent of the base installation directory of the Payara Server software on the host where this subcommand is run.
`--windowsuser`::
`-w`::
  The user on this node's host that is to run the process for connecting to the host through DCOM. The default is the user that is running the DAS process.
`--windowsdomain`::
`-d`::
  The name of the Windows domain that contains the user that the `--windowsuser` option specifies. The default is the name of the host
  on which the subcommand is run.
`--force`::
  Specifies whether the subcommand uninstalls the Payara Server software from a host even if a user-defined node resides on the host.
  Possible values are as follows: +
  `false`;;
    If a user-defined node resides on a host, the software is not uninstalled and the subcommand fails (default). +
    If the `--force` option is `false`, the subcommand removes only the Payara Server software files. Other content if the parent of the
    base installation directory, such as configuration files, are not removed.
  `true`;;
    The subcommand uninstalls the Payara Server software from the host even if a user-defined node resides on the host. +
    If the `--force` option is `true`, the subcommand removes the entire content of the parent of the base installation directory.

[[operands]]
== Operands

host-list::
  A space-separated list of the names of the hosts from which the Payara Server software is to be uninstalled.

[[examples]]
== Examples

*Example 1 Uninstalling Payara Server Software From the Default Location*

This example uninstalls Payara Server software on the hosts `wpmdl1.example.com` and `wpmdl2.example.com` from the default location.

[source,shell]
----
asadmin> uninstall-node-dcom wpmdl1 wpmdl2
Command uninstall-node-dcom executed successfully.
----

*Example 2 Forcibly Uninstalling Payara Server Software*

This example uninstalls Payara Server software on the host `xkyd.example.com`.

The software is uninstalled even if a user-defined node resides on the host. The entire content of the `C:\payara6` directory is removed.

[source,shell]
----
asadmin> uninstall-node-dcom --force --installdir C:\payara6 xkyd.example.com
Command uninstall-node-dcom executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/install-node-dcom.adoc#install-node-dcom[`install-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-ssh.adoc#uninstall-node-ssh[`uninstall-node-ssh`]


