[[unset]]
= unset

Removes one or more variables from the multimode environment.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] unset [--help] 
variable-list
----

[[description]]
== Description

The `unset` subcommand removes one or more environment variables that are set for the multimode environment. After removal, the variables and
their associated values no longer apply to the multimode environment.

To list the environment variables that are set, use the `export` subcommand without options. If the `export` subcommand lists no
environment variables, no environment variables are set.

This subcommand is supported in local mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

variable-list::
  A space-separated list of the environment variables to remove.

[[examples]]
== Examples

*Example 1 Listing the Environment Variables That Are Set*

This example uses the `export` subcommand to list the environment variables that have been set.

[source,shell]
----
asadmin> export
AS_ADMIN_USER = admin
AS_ADMIN_HOST = bluestar
AS_ADMIN_PREFIX = server1.jms-service
AS_ADMIN_PORT = 8000
Command export executed successfully
----

*Example 2 Removing an Environment Variable*

This example removes the `AS_ADMIN_PREFIX` environment variable.

[source,shell]
----
asadmin> unset AS_ADMIN_PREFIX
Command unset executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/export.adoc#export[`export`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/multimode.adoc#multimode[`multimode`]


