[[update-password-alias]]
= update-password-alias

Updates a password alias.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] update-password-alias [--help]
aliasname
----

[[description]]
== Description

This subcommand updates the password alias IDs in the named target. An alias is a token of the form `${ALIAS=password-alias-password}`. The
password corresponding to the alias name is stored in an encrypted form.The `update-password-alias` subcommand takes both a secure interactive
form (in which the user is prompted for all information) and a more script-friendly form, in which the password is propagated on the command line.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

aliasname::
  This is the name of the password as it appears in `domain.xml`.

[[examples]]
== Examples

*Example 1 Updating a Password Alias*

[source,shell]
----
asadmin> update-password-alias jmspassword-alias
Please enter the alias password>
Please enter the alias password again>
Command update-password-alias executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-password-alias.adoc#create-password-alias[`create-password-alias`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-password-alias.adoc#delete-password-alias[`delete-password-alias`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-password-aliases.adoc#list-password-aliases[`list-password-aliases`]


