[[update-node-docker]]
= update-node-docker

Updates the configuration data of a DOCKER node.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] update-node-docker [--help]
[--installdir as-install-parent]
[--nodedir node-dir]
[--dockerpasswordfile filepath]
[--dockerimage imageName]
[--dockerport port]
[--useTls={false|true}]
node-name
----

[[description]]
== Description

//TODO - There's a big question on how this command behaves if the node is already running? Does it recreate the containers and any instances living in them? What happens if a new image name is used? This should be clarified and recommendations on how to use this command should be added.

The `update-node-docker` subcommand updates the configuration data of a DOCKER node. The domain administration server (DAS) contacts a Docker node's host through the Docker engine's REST API on its specific configured host and port. By default, the subcommand fails and the node is not created if the DAS cannot reach the configured Docker engine's process.

The setup of a Docker node is more involved that other types of nodes, so it is recommended reading about the requirements and conditions for this command to work properly in xref:Technical Documentation/Payara Server Documentation/High Availability/Administering Payara Server Nodes.adoc#creating-a-docker-node[corresponding section] in Payara Server's High Availability section.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--nodehost`::
The name of the host where the Docker engine process is listening through its REST API. This option is mandatory, otherwise the command fails.
`--installdir`::
The full path to the parent of the base installation directory of the Payara Server software on the host, for example, `/export/payara/`. The default is the parent of the default base installation directory of the Payara Server software for the DAS.
+
When creating a Docker node this parameter is mostly irrelevant when using the official Payara Server Node images. Use this parameter to point to custom server installations in case of using different images.
`--nodedir`::
The path to the directory that is to contain Payara Server instances that are created on the node. The default is `as-install/nodes`, where as-install is the base installation directory of the Payara Server software on the host.
+
If a relative path is specified, the path is relative to the `as-install` directory.
`--dockerPasswordFile`::
This is the fully-qualified path of the password file that the Docker instance will use for authentication against the DAS.
+
Please note, that this path should be the path to the file on the *remote* machine where . This file should be a standard Payara Server password file as you would use with asadmin. This must be specified, as Docker instances require secure admin to be enabled to start.
`--dockerImage`::
The Docker image to use for creating the Docker container.
+
Defaults to `payara/server-node:{page-version}`.
`--dockerPort`::
The port where the Docker engine's REST API endpoint is exposed.
+
Defaults to `2376`.
`--useTls`::
Specifies whether the Docker engine's REST API endpoint is contacted through secure communication, as recommended in most environments. Defaults to `false`.

[[operands]]
== Operands

node-name::
The name of the node to update. The node must exist. Otherwise, an error occurs.

[[examples]]
== Examples

*Example 1 Updating the Host where the Docker Engine REST API is hosted*

This example updates the host where the Docker Engine's REST API is hosted for the `docker-node-1` node:

[source,shell]
----
asadmin update-node-docker --nodehost test.payara.fish docker-node-1
Command update-node-docker executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-docker.adoc#create-node-docker[`create-node-docker`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-node-docker.adoc#delete-node-docker[`delete-node-docker`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc#list-nodes[`list-nodes`]
