[[update-connector-work-security-map]]
= update-connector-work-security-map

Modifies a work security map for the specified resource adapter.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] update-connector-work-security-map [--help] 
--raname raname
[--addprincipals eis-principal1=server-principal1[, eis-principal2=server-principal2]*] 
[--addgroups eis-group1=server-group1[, eis-group2=server-group2]*]
[--removeprincipals eis-principal1[,eis-principal2]*]
[--removegroups eis-group1[, eis-group2]*]
mapname
----

[[description]]
== Description

The `update-connector-work-security-map` subcommand modifies a security map for the specified resource adapter.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--addgroups`::
  Specifies a comma-separated list of EIS groups to be added. Use either the `--addprincipals` option or the `--addgroups` option, but not both.
`--addprincipals`::
  Specifies a comma-separated list of EIS-specific principals to be added. Use either the `--addprincipals` option or the `--addgroups` option, but not both.
`--removegroups`::
  Specifies a comma-separated list of EIS groups to be removed.
`--removeprincipals`::
  Specifies a comma-separated list of EIS-specific principals to be removed.
`--raname`::
  Indicates the connector module name with which the work security map is associated.

[[operands]]
== Operands

mapname::
  The name of the work security map to be updated.

[[examples]]
== Examples

*Example 1 Updating a Connector Work Security Map*

This example updates `workSecurityMap2` by removing `eis-group-2`.

[source,shell]
----
asadmin> update-connector-work-security-map
--raname my-resource-adapter --removegroups eis-group-2 workSecurityMap2
Command update-connector-work-security-map executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-connector-work-security-map.adoc#create-connector-work-security-map[`create-connector-work-security-map`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-connector-work-security-map.adoc#delete-connector-work-security-map[`delete-connector-work-security-map`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-connector-work-security-maps.adoc#list-connector-work-security-maps[`list-connector-work-security-maps`]


