[[update-file-user]]
= update-file-user

Updates a current file user as specified.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] update-file-user [--help] 
[--groups user_groups[:user_groups]*] 
[--target target 
[--authrealmname authrealm_name] 
username
----

[[description]]
== Description

Th `update-file-user` subcommand updates an existing entry in the keyfile using the specified user name, password and groups. Multiple
groups can be entered by separating them, with a colon (:).

If a new password is not provided, this subcommand fails if secure administration is enabled and the user being updated is an administrative user.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--groups`::
  This is the name of the group to which the file user belongs.
`--authrealmname`::
  Name of the authentication realm where the user to be updated can be found.
`--target`::
  This option helps specify the target on which you are updating a file user. Valid values are: +
  `server`;;
    Updates the file user in the default server instance. This is the default value.
  cluster_name;;
    Updates the file user on every server instance in the cluster.
  instance_name;;
    Updates the file user on a specified sever instance.

[[operands]]
== Operands

username::
  This is the name of the file user to be updated.

[[examples]]
== Examples

*Example 1 Updating a User's Information in a File Realm*

The following example updates information for a file realm user named `sample_user`.

[source,shell]
----
asadmin> update-file-user 
--groups staff:manager:engineer sample_user
Command update-file-user executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-file-user.adoc#create-file-user[`create-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-file-user.adoc#delete-file-user[`delete-file-user`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-groups.adoc#list-file-groups[`list-file-groups`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-file-users.adoc#list-file-users[`list-file-users`]


