[[update-node-config]]
= update-node-config

Updates the configuration data of a node.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] update-node-config [--help]
[--nodehost node-host] 
[--installdir as-install-parent] [--nodedir node-dir] 
node-name
----

[[description]]
== Description

The `update-node-config` subcommand updates the configuration data of a node.

This subcommand can update any node, regardless of whether the node is enabled for remote communication. If a node that is enabled for remote
communication is updated, the node is not enabled for remote communication after the update.

Options of this subcommand specify the new values of the node's configuration data. The default for these options is to leave the existing value unchanged.

This subcommand does not require the Distributed Component Object Model (DCOM) remote protocol or secure shell (SSH) to be configured to update
the node. You may run this subcommand from any host that can contact the DAS.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--nodehost`::
  The name of the host that the node is to represent after the node is updated.
`--installdir`::
  The full path to the parent of the base installation directory of the Payara Server software on the host, for example, `/export/payara6`.
`--nodedir`::
  The path to the directory that is to contain Payara Server instances that are created on the node. If a relative path is
  specified, the path is relative to the as-install directory, where as-install is the base installation directory of the Payara Server software on the host.

[[operands]]
== Operands

node-name::
  The name of the node to update. The node must exist. Otherwise, an error occurs.

[[examples]]
== Examples

*Example 1 Updating the Host That a Node Represents*

This example updates the host that the node `sj04` represents to `hsj04`.

[source,shell]
----
asadmin> update-node-config --nodehost hsj04 sj04
Command update-node-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-config.adoc#create-node-config[`create-node-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-dcom.adoc#create-node-dcom[`create-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/create-node-ssh.adoc#create-node-ssh[`create-node-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-node-config.adoc#delete-node-config[`delete-node-config`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-node-dcom.adoc#delete-node-dcom[`delete-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/delete-node-ssh.adoc#delete-node-ssh[`delete-node-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/install-node.adoc#install-node[`install-node`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/install-node-dcom.adoc#install-node-dcom[`install-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/install-node-ssh.adoc#install-node-ssh[`install-node-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-nodes.adoc#list-nodes[`list-nodes`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node.adoc#uninstall-node[`uninstall-node`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-dcom.adoc#uninstall-node-dcom[`uninstall-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/uninstall-node-ssh.adoc#uninstall-node-ssh[`uninstall-node-ssh`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-node-dcom.adoc#update-node-dcom[`update-node-dcom`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/update-node-ssh.adoc#update-node-ssh[`update-node-ssh`]


