[[uptime]]
= uptime

Returns the length of time that the DAS has been running.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] uptime [--help]
----

[[description]]
== Description

The `uptime` subcommand returns the length of time that the domain administration server (DAS) has been running since it was last restarted.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Showing How Long the DAS Has Been Running*

This example shows the length of time that the DAS has been running.

[source,shell]
----
asadmin> uptime
Uptime: 2 days, 1 hours, 30 minutes, 18 seconds, Total milliseconds: 178218706
Command uptime executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-domains.adoc#list-domains[`list-domains`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/start-domain.adoc#start-domain[`start-domain`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/stop-domain.adoc#stop-domain[`stop-domain`]


