[[verify-domain-xml]]
= verify-domain-xml

Verifies the contents of the domain.xml file.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] verify-domain-xml [--help] 
[--domaindir domain-dir] [domain-name]
----

[[description]]
== Description

Verifies the content of the `domain.xml` file by checking the following details:

* That the `domain.xml` file can be parsed
* That the names for elements that have them are unique

This subcommand is supported in local mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`-h` `--help`::
  Displays the help text for the subcommand.
`--domaindir`::
  Specifies the domain root directory, where the domains are located. The path must be accessible in the file system. The default is `as-install/domains`.

[[operands]]
== Operands

domain_name::
  Specifies the name of the domain. The default is `domain1`.

[[examples]]
== Examples

*Example 1 Using verify-domain-xml*

[source,shell]
----
asadmin> verify-domain-xml
All Tests Passed.
domain.xml is valid
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`]
