[[version]]
= version

Displays version information for Payara Server.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] version [--help] 
[--verbose={false|true}] 
[--local={false|true}]
----

[[description]]
== Description

The `version` subcommand displays version information for Payara Server. By default, if the subcommand cannot contact the domain administration server (DAS), the subcommand retrieves the version information locally and displays a warning message.

This subcommand is supported in remote mode and local mode.

[[options]]
== Options

asadmin-options::
Options for the `asadmin` utility. For information about these options, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
Displays the help text for the subcommand.
`--verbose`::
`-v`::
If this option is set to `true`, the subcommand provides the version of the Java Runtime Environment (JRE) that the server is running. The default is `false`.
`--local`::
If this option is set to `true`, the subcommand obtains the version locally from the installation of Payara Server on the host where the subcommand is run.
+
If this option is set to `false` (default), the subcommand attempts to contact the DAS to obtain the version. If the attempt to contact the DAS fails, the subcommand retrieves the version locally and displays a warning message.

[[examples]]
== Examples

*Example 1 Obtaining Version Information From a Running DAS*

[source,shell, subs=attributes+]
----
asadmin> version
Version = Payara Server {page-version} #badassfish (build 00)
Command version executed successfully.
----

*Example 2 Obtaining Version Information When the DAS Cannot be Reached*

[source, shell, subs=attributes+]
----
asadmin> version
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.

Version = Payara Server {page-version} #badassfish (build 00)
Command version executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:Technical Documentation/Payara Server Documentation/Command Reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:Technical Documentation/Payara Server Documentation/Command Reference/list-modules.adoc#list-modules[`list-modules`]
