= Jaegar Tracing

Jaeger is used for monitoring and troubleshooting microservices-based distributed systems, including:

* Distributed context propagation
* Distributed transaction monitoring
* Root cause analysis
* Service dependency analysis
* Performance/latency optimization

== Version

*Version 1.0* works on  5.194 - 5.2020.7 +
*Version 1.1* works on 5.20212.1 or higher(MicroProfile 4.x)

[[using-with-payara-server]]
== Using with Payara Server

To use Jaeger Tracer you will need a wrapper for it - one is provided at https://github.com/payara/ecosystem-jaeger-tracing[Jaeger Tracing Wrapper].

. Build the project with
+
[source,shell]
----
mvn clean install
----
. Deploy the complete artifact with
+
[source,shell]
----
asadmin add-library jaeger-tracer-lib-jar-with-dependencies.jar
----
. Tracing must be enabled with
+
[source,shell]
----
asadmin set-requesttracing-configuration --enabled true --dynamic true
asadmin bootstrap-requesttracing
----

[NOTE]
--
To view the results of the trace, a Jaeger  collector must be available. One can be started easily using docker as follows:

[source,console]
----
docker run --rm -p 6831:6831/udp -p 6832:6832/udp -p 16686:16686 jaegertracing/all-in-one --log-level=debug
----
--
[[Configuration]]
== Configuration

Configuration can be done either with environment variables or programmatically in JaegerTracerWrapper

See https://github.com/jaegertracing/jaeger-client-java/blob/master/jaeger-core/README.md#configuration-via-environment[Configuration via Environment]

NOTE: Define the environment property `JAEGER_SERVICE_NAME` to override the default `jaeger-test` value. +
Define the environment property `JAEGER_AGENT_HOST` to override the default `localhost`
