[[eclipse-microprofile-opentracing]]
= Eclipse MicroProfile OpenTracing

Payara Server {page-version} provides MicroProfile OpenTracing {mpOpenTracingVersion}

[[background]]
== Background

The Open Tracing API was created to allow easier tracing of the flow of a request in microservices environment across service boundaries.

{mpOpenTracingSpecUrl}[The complete specification] can be found on the Eclipse MicroProfile website.

Breaking changes introduced in MicroProfile OpenTracing {mpOpenTracingVersion} are listed in the official specification under {mpOpenTracingSpecUrl}#_incompatible_changes[Incompatible Changes]

Support for MicroProfile Open Tracing is provided via compatibility layer for OpenTelemetry.

To achieve full compatibility in naming the spans with the spec a span convention needs to be configured as described in <<span-convention>>.

[[text-and-binary-carriers]]
== Text and Binary Carriers Support

The Payara Platform implementation of the `io.opentracing.Tracer` interface supports the following carriers:

* `TextMap` carriers with `HTTP_HEADERS` and `TEXT_MAP` formats 

[[jax-ws-support]]
== JAX-WS Support

The Payara Platform's MicroProfile implementation supports tracing of requests that are handled by SOAP Web Services implemented via the JAX-WS API. Since JAX-WS is only supported on Payara Server Full Profile, this support is not covered on Payara Micro.

[[opentracing-configuration]]
== OpenTracing Configuration

Additionally you can configure the notifiers for Request Tracing Service by using the xref:Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/Asadmin Commands.adoc[asadmin commands] and also using the xref:Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/Configuration.adoc[Administration console].

[[span-convention]]
=== Span Naming Convention

By default span names for JAX-RS endpoints follow  recommendations set forth by OpenTelemetry Semantic Conventions.
In order to have span names follow naming conventions defined by MicroProfile OpenTelemetry, following MicroProfile Config property must be set for application or globally for the server or domain:

[source, ini]
----
payara.telemetry.span-convention=opentracing-class-method
----

All valid values for the property are documented in xref:Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/OpenTelemetry and OpenTracing.adoc#span-convention-settings[OpenTelemetry Span Convention Settings]

[[alternative-implementation]]
== Using Alternate OpenTracing Implementations

It is not possible to use other OpenTracing implementations in Payara Platform 6.

It is however possible to deploy and configure other OpenTelemetry exporters (i.e. zipkin) into the server or ship them with application. Please consult xref:Technical Documentation/Payara Server Documentation/Logging and Monitoring/Request Tracing Service/OpenTelemetry and OpenTracing.adoc#using-additional-components[OpenTelemetry Configuration].


