[[eclipse-microprofile-opentracing]]
= Eclipse MicroProfile OpenTracing

Payara Platform {page-version} provides MicroProfile OpenTracing {mpOpenTracingVersion}

[[background]]
== Background

The Open Tracing API was created to allow easier tracing of the flow of a request in microservices environment across service boundaries.

{mpOpenTracingSpecUrl}[The complete specification] can be found on the Eclipse MicroProfile website.

Breaking changes introduced in MicroProfile OpenTracing {mpOpenTracingVersion} are listed in the official specification under {mpOpenTracingSpecUrl}#_incompatible_changes[Incompatible Changes]

Support for MicroProfile Open Tracing is provided via compatibility layer for OpenTelemetry.

To achieve full compatibility in naming the spans with the spec a span convention needs to be configured as described in <<span-convention>>.

[[text-and-binary-carriers]]
== Text and Binary Carriers Support

The Payara Platform implementation of the `io.opentracing.Tracer` interface supports the following carriers:

* `TextMap` carriers with `HTTP_HEADERS` and `TEXT_MAP` formats

[[jax-ws-support]]
== JAX-WS Support

The Payara Platform's MicroProfile implementation supports tracing of requests that are handled by SOAP Web Services implemented via the JAX-WS API. Since JAX-WS is only supported on Payara Server Full Profile, this support is not covered on Payara Micro.

[[opentracing-configuration]]
== OpenTracing Configuration

[[span-convention]]
=== Span Naming Convention

By default, span names for JAX-RS endpoints follow  recommendations set forth by OpenTelemetry Semantic Conventions. To have span names follow naming conventions defined by MicroProfile OpenTelemetry, following MicroProfile Config property must be set for application or globally for the server or domain:

[source, ini]
----
payara.telemetry.span-convention=opentracing-class-method
----

All valid values for the property are documented in xref:Technical Documentation/MicroProfile/OpenTelemetry and OpenTracing.adoc#span-convention-settings[OpenTelemetry Span Convention Settings]

[[alternative-implementation]]
== Using Alternate OpenTracing Implementations

Currently, it is not possible to use other OpenTracing implementations in the Payara Platform.

It is however possible to deploy and configure other OpenTelemetry exporters (i.e. Zipkin) into the server or ship them with application.

Please consult xref:Technical Documentation/MicroProfile/OpenTelemetry and OpenTracing.adoc#using-additional-components[OpenTelemetry Configuration].
