[[eclipse-microprofile]]
= Eclipse MicroProfile

[[what-is]]
== What is Eclipse MicroProfile?
The MicroProfile project was launched in June 2016 as a collaborative effort between Java application server vendors and the enterprise Java community to enable fast innovation.

MicroProfile is a specification which provides a set of APIs focused on microservices. The complete MicroProfile API is provided as a Bill Of Materials(BOM) which can be used by developers as a generic dependency provided by a vendor of their choice.

Payara has been part of the MicroProfile project from its inception and, therefore, supports all specifications of the MicroProfile Umbrella project.

== Payara Support for MicroProfile

Version 5.0::
Version 5.0 of MicroProfile is a major release that updates Config, Fault Tolerance, Health, JWT Authentication, Metrics, OpenAPI, OpenTracing and Rest Client. This release of MicroProfile enables MicroProfile APIs to be used with the Jakarta EE namespace and mainly focused on updating dependencies from `javax` to `jakarta`, as well as stability and usability improvements.

This is supported by the Payara Platform starting from release *6.2022.1*

== What does each specification contain?
[cols="1,3a,5a", options="header"]
|===
|Version
|Specifications
|Maven

| 5.0
|
* https://jakarta.ee/specifications/restful-ws/3.0/jakarta-restful-ws-spec-3.0.html[Jakarta JAX-RS 3.0]
* https://jakarta.ee/specifications/cdi/3.0/jakarta-cdi-spec-3.0.html[Jakarta CDI 3.0]
* https://jakarta.ee/specifications/annotations/2.0/annotations-spec-2.0.html[Jakarta Annotations 2.0]
* https://jakarta.ee/specifications/jsonb/2.0/jakarta-jsonb-spec-2.0.html[Jakarta JSON-B 2.0]
* https://jakarta.ee/specifications/jsonp/2.0/apidocs/[Jakarta JSON-P 2.0.1]
* https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html[Config 3.0]
* https://download.eclipse.org/microprofile/microprofile-metrics-4.0/microprofile-metrics-spec-4.0.html[Metrics 4.0]
* https://download.eclipse.org/microprofile/microprofile-health-4.0/microprofile-health-spec-4.0.html[Health Check 4.0]
* https://download.eclipse.org/microprofile/microprofile-fault-tolerance-4.0/microprofile-fault-tolerance-spec-4.0.html[Fault Tolerance 4.0]
* https://download.eclipse.org/microprofile/microprofile-jwt-auth-2.0/microprofile-jwt-auth-spec-2.0.html[JWT Authentication 2.0]
* https://download.eclipse.org/microprofile/microprofile-opentracing-3.0/microprofile-opentracing-spec-3.0.html[OpenTracing 3.0]
* https://download.eclipse.org/microprofile/microprofile-open-api-3.0/microprofile-openapi-spec-3.0.html[OpenAPI 3.0]
* https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html[Rest Client 3.0]

| [source, xml]
----
<dependency>
    <groupId>org.eclipse.microprofile</groupId>
    <artifactId>microprofile</artifactId>
    <version>5.0</version>
    <type>pom</type>
    <scope>provided</scope>
</dependency>
----
|===
