:Ordinal: 900
= AutoScale Extensions

The AutoScale extensions provide the means for users to scale Payara Server instances up and down across different environments.

You can find the code for each AutoScale extension here: https://github.com/payara/AutoScale-Groups.

[[installation]]
== Installing AutoScale Extensions

Regardless of which AutoScale extension you wish to install, it is expected that the API and the two Core module JARs are added to the server by dropping them into the `${PAYARA_HOME}/glassfish/modules` directory of your Payara Server installation.

You can then drop the implementation and admin console plugin JARs of your desired extensions into the same directory.

For example, to install the SSH Nodes AutoScale Extension, you would drop the following JARs into the `modules` directory:

* _autoscale-groups-api_
* _autoscale-groups-core_
* _autoscale-groups-console_
* _autoscale-groups-nodes-plugin-core_
* _autoscale-groups-nodes-plugin-console_

You must restart the server if it was running to see your extension activated.

IMPORTANT: Make sure that if the AutoScale extension has dependencies in order to run the dependency artifacts are also in the _modules_ directory.

[[core-downloads]]
=== Core Downloads
* link:https://nexus.payara.fish/repository/payara-artifacts/fish/payara/extensions/autoscale/groups/autoscale-groups-api/1.0/autoscale-groups-api-1.0.jar[AutoScale API 1.0]
* link:https://nexus.payara.fish/repository/payara-artifacts/fish/payara/extensions/autoscale/groups/autoscale-groups-core/1.0/autoscale-groups-core-1.0.jar[AutoScale Core 1.0]
* link:https://nexus.payara.fish/repository/payara-artifacts/fish/payara/extensions/autoscale/groups/autoscale-groups-console/1.0/autoscale-groups-console-1.0.jar[AutoScale Admin Console Plugin 1.0]