= Release notes - Payara Platform Enterprise 6.39.0

== Supported APIs and Applications

* Jakarta EE 10
* Jakarta EE 10 Applications
* MicroProfile 6.1

== Behaviour Changes
The default (undefined) value of the `fish.payara.ready-after-applications` system property will change from `false` to `true` starting from 6.42.0, aligning Payara 6 with Community and Payara 7.
The server will mark itself as ready after post-boot configuration is applied and previously deployed applications are loaded, rather than after the `server_startup` event.
This may change the timing of post-boot scripts and transaction recovery. Ahead of 6.42.0, `fish.payara.ready-after-applications` can be left unset to adopt the new default, set to `true` to test the new behaviour early, or set to `false` to keep the current behaviour.


== Security Fixes
* [FISH-13637] Fix CSRF + SSRF in Admin Console / REST Management Interface

== Bug Fixes
* [FISH-10485] Fix Payara Micro Boot Properties Not Applied With the Right Timing
* [FISH-11896] Fix Quoted-Argument Parsing in `prebootCommandFile` (asadmin) and `PREBOOT_COMMANDS` (Docker)
* [FISH-12270] Fix Misleading Log Entries Generated While Configuring Additional Properties for Virtual Servers
* [FISH-12800] Fix MicroProfile `/metrics` Endpoint Containing Duplicate Metrics
* [FISH-13058] Fix Missing `JSESSIONIDVERSION` Leading to Session Not Being Correctly Retrieved in Relaxed Mode
* [FISH-13091] Assorted Deployment Group Fixes
* [FISH-13137] Fix Prometheus Metrics to Report Histogram Times in Seconds
* [FISH-13138] Fix Payara Micro's `--outputlauncher` to Respect `payara-boot.properties`
* [FISH-13447] Fix Micro `NullPointerException` with `log-to-console` Access Log Option

== Improvements
* [FISH-13097] Add Default OpenMQ Credentials Warning
* [FISH-13707] Add Alternate Parsson to BOM

== Component Upgrades
* [FISH-13525] Upgrade `org.jetbrains.kotlin:kotlin-stdlib` from 2.3.10 to 2.3.21
* [FISH-13545] Upgrade `org.codehaus.woodstox:stax2-api` from 4.2.2 to 4.3.0
* [FISH-13546] Upgrade `org.glassfish:genericra` from 2.0-20081121 to 2.1-20100913
* [FISH-13547] Upgrade `com.fasterxml.jackson:jackson-bom` from 2.21.2 to 2.21.3
* [FISH-13548] Upgrade `org.glassfish.grizzly:grizzly-npn-osgi` from 2.0.0 to 2.0.1
* [FISH-13579] Upgrade `jline.version` from 3.30.8 to 3.30.13
* [FISH-13720] Upgrade `asm.version` from 9.9.1 to 9.10.1