= Release notes - Payara Platform Enterprise 7.0.0

== Supported APIs and Applications

* Jakarta EE 11
* Jakarta EE 11 Applications
* MicroProfile 7.1

== Bug Fixes
* [FISH-5749] Fix Asadmin Recorder Generating Invalid Commands for MicroProfile Properties at the Server Level
* [FISH-12191] Fix Admin Console Advanced Tab in Connection Pools Not Working Correctly
* [FISH-12975] Fix Broken Payara News Link in Admin Console
* [FISH-13385] Fix Admin Console Freezing After Upgrading from Payara Enterprise 6 to Enterprise 7

== Improvements
* [FISH-10287] Update `JaccProviderCompatibilityStartup` Service
* [FISH-12092] Add `warlibs` Support to Redeployment via Admin Console
* [FISH-13046] Remove Yubikey Extension
* [FISH-13126] Create New Deployment Descriptors with Deprecated Properties Removed
* [FISH-13193] Fix `@Repository` methods not throwing `UnsupportedOperationException` when no implementation logic can be injected at deploy time

== Component Upgrades
* [FISH-13424] Upgrade `org.javassist:javassist` from 3.30.2-GA to 3.31.0-GA
* [FISH-13433] Upgrade `org.eclipse.microprofile.config:microprofile-config-api` from 3.1 to 3.1.1
* [FISH-13437] Upgrade Docker JDK to 21.0.11
* [FISH-13441] Upgrade Docker JDK to 25.0.3
* [FISH-13462] Upgrade `jline.version` from 3.30.9 to 3.30.11