= Release notes - Payara Platform Enterprise 5.48.0

== Supported APIs and Applications

* Jakarta EE 8
* Jakarta EE 8 Applications
* Jakarta EE 9
* MicroProfile 4.1

== Breaking Change
=== MicroProfile OpenAPI Property Renamed
The MicroProfile OpenAPI config property was renamed from "mp.openapi.scan.lib" to "mp.openapi.extensions.scan.lib". If you are currently using this property and upgrading to Payara Community 6.2023.2 and later versions, please remember to change to this new one, otherwise your values may not be picked up.

== Improvements
* [FISH-6927] Redefine MicroProfile OpenAPI "mp.openapi.scan.lib" property
* [FISH-6963] [Community Contribution - https://github.com/pzygielo[pzygielo]] Log Alias of Expired Certificate


== Bug Fixes

* [FISH-6432] Applications Take Longer To Deploy on JDK 11 and 17
* [FISH-6815] Asadmin CLI Utility Commands [start/stop/restart-deployment-group] times out
* [FISH-6947] Command asadmin --detach list-instances is not working any more starting 5.45.0
* [FISH-6962] [Community Contribution - https://github.com/pzygielo[pzygielo]] Incorrect MBeanMetadataConfig Class Name
* [FISH-6983] Revert Removal of JobManager
