= Release notes - Payara Platform Enterprise 5.44.0

== Supported APIs and Applications

* Jakarta EE 8
* Java EE 8 Applications
* MicroProfile 4.1

== Breaking Changes
=== Disable Hazelcast and Clustering on Payara Micro Changes
WARNING: Previously the `--noCluster` option was used to disable both Hazelcast and clustering on a Payara Micro instance. In Payara Micro Enterprise Edition 5.44.0 the `--noCluster` option will have Hazelcast enabled, allowing for the use of Hazelcast dependant features such as JCache, while still disabling clustering. To disable both clustering and Hazelcast on Payara Micro Enterprise Edition 5.44.0 you should now use the `--noHazelcast` option.

== Improvement

* [FISH-372] Provide option to disable clustering functionality of Hazelcast on Payara Micro

== Security Fixes

* [FISH-6522] FIX CVE-2021-31684/Gihub Advisory - GHSA-fg2v-w576-w4v3 in Payara Platform

* [FISH-6391] Fix sonatype-2014-0173 commons-fileupload : commons-fileupload : 1.3.3

== Bug Fixes

* [FISH-6506] Environment Variable Replacement in Payara Micro Logging Properties File Does Not Work

* [FISH-6501] Commands in Postboot File Fail

* [FISH-6481] CORBA Incorrectly opening an additional TCP socket on Windows systems

* [FISH-6470] GCM Cipher Suites Not Being Recognized

* [FISH-6238] Microprofile Interceptors \[@Fallback@/CircuitBreaker\] are not getting invoked if the EJB is a @Stateless Bean