= Release notes - Payara Platform Enterprise 6.0.0

== Supported APIs and Applications

* Jakarta EE 10
* Jakarta EE 10 Applications
* MicroProfile 6.0

== Known Issues
=== ASM Warning
When deploying an application that contains a Java Record, there is a warning logged in the server logs about Records not being supported. No worries. Your application will deploy and work. This is a known issue that is being looked into.

== Breaking Changes
=== Minimum Required JDK
The minimum required JDK to run this and subsequent releases of this stream is 11.0.12

=== JakartaEE 10
Jakarta EE 10 is a major release with backwards incompatible changes, the major one being the javax to jakarta package refactoring. This major change affects all Jakarta EE 8 and below applications.

=== MicroProfile 6
MicroProfile 6 introduced some https://microprofile.io/2023/01/10/microprofile-6-0-release/[breaking changes] that you should be aware of.

=== Improvements

* [FISH-7206] Update the REST SSL Alias Extension for Payara 6
* [FISH-1366] Upgrade cacerts.jks and keystore.jks to pkcs12
* [FISH-6634] Make Notifiers Payara 6 Compatible

=== Bug Fixes

* [FISH-6479] SLF4J API fails to load an implementation
* [FISH-7016] Server Instances Zombie When Port Conflicts Are Detected During Startup
* [FISH-7076] Malformed SQL when using SecondaryTable & PrimaryKeyJoinColumn annotations
* [FISH-7077] Deploy and redeploy using local packaged file not working
* [FISH-5981] 'java.lang.LinkageError' in Payara 5.2021.10 when using Apache Santuario and SLF4J/Logback

=== Component Upgrades

* [FISH-7168] Upgrade SNMP4J in the SNMP Notifier to 3.7.5
* [FISH-7153] Upgrade Docker Image JDK 11 Version to 11.0.18
* [FISH-7155] Upgrade Docker Image JDK 17 Version to 17.0.6