= Release notes - Payara Platform Enterprise 7.1.0

== Supported APIs and Applications

* Jakarta EE 11
* Jakarta EE 11 Applications
* MicroProfile 6.1

== Security Fixes
* [FISH-13637] Investigate and Fix CSRF + SSRF in Admin Console / REST Management Interface

== Bug Fixes
* [FISH-10485] Fix Payara Micro Boot Properties Not Applied With the Right Timing
* [FISH-11896] Fix Quoted-Argument Parsing in `prebootCommandFile` (asadmin) and `PREBOOT_COMMANDS` (Docker)
* [FISH-12270] Fix Misleading Log Entries Generated While Configuring Additional Properties for Virtual Servers
* [FISH-12800] Fix MicroProfile `/metrics` Endpoint Containing Duplicate Metrics
* [FISH-13058] Fix Missing `JSESSIONIDVERSION` Leading to Session Not Being Correctly Retrieved in Relaxed Mode
* [FISH-13091] Port Assorted Deployment Group Fixes
* [FISH-13137] Fix Prometheus Metrics to Report Histogram Times in Seconds
* [FISH-13138] Fix Payara Micro's `--outputlauncher` to Respect `payara-boot.properties`
* [FISH-13400] Fix WELD-001408 Unsatisfied Dependency for Repository Injection in CDI Bean
* [FISH-13447] Fix Micro `NullPointerException` with `log-to-console` Access Log Option
* [FISH-13779] Fix Changing the Admin Password in the Admin Console Not Working


== Improvements
* [FISH-11606] Avoid Parsing Method Names on Every Jakarta Data HTTP Request
* [FISH-12426] Reintroduce Standalone OpenMQ Support for Windows
* [FISH-13097] Add Default OpenMQ Credentials Warning
* [FISH-13339] Add `warlibs` Support to `remove-library` Command
* [FISH-13340] Add `warlibs` Support to `list-libraries` Command
* [FISH-13475] Support Method-Level `@Transactional` Overrides on Repository Interfaces in Jakarta Data
* [FISH-13649] Define `jakarta.security.jacc.policy.provider` for Payara Micro
* [FISH-13707] Add Alternate Parsson to BOM

== Component Upgrades
* [FISH-12986] Upgrade EclipseLink from 5.0.0-B11 to 5.0.0
* [FISH-13427] Upgrade HK2 to 4.0.1
* [FISH-13477] Upgrade `commons-io:commons-io` from 2.21.0 to 2.22.0
* [FISH-13521] Upgrade `pfl.version` from 5.1.0 to 5.1.1
* [FISH-13522] Upgrade `payara.security-connectors.version` from 4.0.0.Alpha3 to 4.0.0
* [FISH-13523] Upgrade `org.glassfish.jaxb:codemodel` from 4.0.7 to 4.0.8
* [FISH-13540] Upgrade `org.glassfish:genericra` from 2.0-20081121 to 2.1-20100913
* [FISH-13542] Upgrade `jaxb-impl.version` from 4.0.7 to 4.0.8
* [FISH-13568] Upgrade `com.fasterxml.jackson:jackson-bom` from 2.21.2 to 2.21.3
* [FISH-13569] Upgrade `gmbal.version` from 4.1.1 to 4.1.2
* [FISH-13575] Upgrade `asm.version` from 9.9.1 to 9.10
* [FISH-13605] Upgrade `org.jetbrains.kotlin:kotlin-stdlib` from 2.3.20 to 2.3.21
* [FISH-13609] Upgrade `jline.version` from 3.30.11 to 3.30.13
* [FISH-13667] Upgrade `org.jvnet.mimepull:mimepull` from 1.10.0 to 1.11.0
* [FISH-13669] Upgrade `asm.version` from 9.10 to 9.10.1
* [FISH-13704] Upgrade `jaxb-impl.version` from 4.0.8 to 4.0.9
* [FISH-13705] Upgrade `com.fasterxml.woodstox:woodstox-core` from 7.1.1 to 7.2.0
* [FISH-13710] Upgrade `jakarta.json.bind:jakarta.json.bind-api` from 3.0.1 to 3.0.2
* [FISH-13717] Upgrade `com.fasterxml.jackson:jackson-bom` from 2.21.3 to 2.21.4
* [FISH-13744] Upgrade `org.eclipse.persistence:org.eclipse.persistence.asm` from 9.9.0 to 9.10.0
* [FISH-13747] Upgrade `org.glassfish.jaxb:codemodel` from 4.0.8 to 4.0.9
* [FISH-13748] Upgrade Jersey to 4.0.2
* [FISH-13758] Upgrade `com.fasterxml.jackson:jackson-bom` from 2.21.4 to 2.22.0
* [FISH-13759] Upgrade `org.glassfish.grizzly:grizzly-npn-osgi` from 2.0.0 to 2.0.1
* [FISH-13760] Upgrade `com.nimbusds:nimbus-jose-jwt` from 10.9 to 10.9.1
* [FISH-13761] Upgrade `org.jetbrains.kotlin:kotlin-stdlib` from 2.3.21 to 2.4.0