[[administering-the-object-request-broker-orb]]
= Administering the Object Request Broker (ORB)
:ordinal: 18

Payara Server supports a standard set of protocols and formats that ensure interoperability. Among these protocols are those defined by CORBA. The Object Request Broker (ORB) is the central component of CORBA. The ORB provides the required infrastructure to identify and locate objects, handle connection management, deliver data, and request communication. This chapter describes how to configure the ORB and the IIOP listeners.

Instructions for accomplishing the tasks in this chapter by using the Administration Console are contained in the Administration Console online help.

[[about-the-orb]]
== About the ORB

The Common Object Request Broker Architecture (CORBA) model is based on clients requesting services from distributed objects or servers through a well-defined
interface by issuing requests to the objects in the form of remote method requests. A remote method request carries information about the operation that needs to be performed, including the object name (called an object reference) of the service provider and parameters, if any, for the invoked method. CORBA automatically handles network programming tasks such as object registration, object location, object activation, request de-multiplexing, error-handling, marshalling, and operation dispatching.

[[configuring-the-orb]]
== Configuring the ORB

A CORBA object never talks directly with another. Instead, the object makes requests through a remote stub to the Internet Inter-Orb Protocol (IIOP) running on the local host. The local ORB then passes the request to an ORB on the other host using IIOP. The remote ORB then locates the appropriate object, processes the request, and returns the results.

IIOP can be used as a Remote Method Invocation (RMI) protocol by applications or objects using RMI-IIOP. Remote clients of enterprise beans (EJB modules) communicate with Payara Server by using RMI-IIOP.

[[administering-iiop-listeners]]
== Administering IIOP Listeners


An IIOP listener is a listen socket that accepts incoming connections from the remote clients of enterprise beans and from other CORBA-based clients. Multiple IIOP listeners can be configured for Payara Server. For each listener, specify a port number (optional; default 1072), a network address, and security attributes (optional). If you create multiple listeners, you must assign a different port number for each listener.

[[to-create-an-iiop-listener]]
=== To Create an IIOP Listener

Use the `create-iiop-listener` subcommand in remote mode to create an IIOP listener.

. Ensure that the server is running. Remote subcommands require a running server.
. Create an IIOP listener by using the xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/create-iiop-listener.adoc[`create-iiop-listener`] subcommand. Information about the properties for the subcommand is included in this help page.
. To apply your changes, restart Payara Server. See xref:Technical Documentation/Payara Server Documentation/General Administration/Administering Domains.adoc#to-restart-a-domain[To Restart a Domain].

==== *Example 15-1 Creating an IIOP Listener*
[source,shell]
----
asadmin> create-iiop-listener --listeneraddress 192.168.1.100
--iiopport 1400 sample_iiop_listener
Command create-iiop-listener executed successfully.
----
This example creates an IIOP listener named `sample_iiop_listener`.

[[to-list-iiop-listeners]]
=== To List IIOP Listeners

Use the `list-iiop-listeners` subcommand in remote mode to list the existing IIOP listeners.

. Ensure that the server is running. Remote subcommands require a running server.
. List the IIOP listeners by using the xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/list-iiop-listeners.adoc[`list-iiop-listeners`] subcommand.

==== *Example 15-2 Listing IIOP Listeners*
[source,shell]
----
asadmin> list-iiop-listeners
orb-listener-1
SSL
SSL_MUTUALAUTH
sample_iiop_listener
Command list-iiop-listeners executed successfully.
----
This example lists all the IIOP listeners for the server instance.

[[to-update-an-iiop-listener]]
=== To Update an IIOP Listener

. List the IIOP listeners by using the xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/list-iiop-listeners.adoc[`list-iiop-listeners`] subcommand.
. Modify the values for the specified IIOP listener by using the  xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/set.adoc[`set`] subcommand. The listener is identified by its dotted name.

==== *Example 15-3 Updating an IIOP Listener*
[source,shell]
----
asadmin> set "server.iiop-service.iiop-listener.SSL.enabled"
server.iiop-service.iiop-listener.SSL.enabled=false
Command set executed successfully.
----
This example changes SSL from enabled to disabled.

[[to-delete-an-iiop-listener]]
=== To Delete an IIOP Listener

Use the `delete-iiop-listener` subcommand in remote mode to delete an IIOP listener.

. Ensure that the server is running. Remote subcommands require a running server.
. List the IIOP listeners by using the xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/list-iiop-listeners.adoc[`list-iiop-listeners`] subcommand.
. Delete an IIOP listener by using the xref:ROOT:Technical Documentation/Payara Server Documentation/Command Reference/delete-iiop-listener.adoc[`delete-iiop-listener`] subcommand.
. To apply your changes, restart Payara Server. See xref:Technical Documentation/Payara Server Documentation/General Administration/Administering Domains.adoc#to-restart-a-domain[To Restart a Domain].

==== *Example 15-4 Deleting an IIOP Listener*
[source,shell]
----
asadmin> delete-iiop-listener sample_iiop_listener
 Command delete-iiop-listener executed successfully.
----
This example deletes the IIOP listener named `sample_iiop_listener`.


