[[classloading]]
= Classloading

Payara Server extends the default JVM classloading and provides additional classes, which are loaded by the class loaders included by default on this distribution. Understanding Payara Server class loaders can help you determine where to place supporting JAR and resource files for your modules and applications.
Documentation in this section describes:

* How classloading in Payara Server works
* How to install additional classes and libraries into Payara Server
* How to configure application deployment so that the application has access only to the desired set of classes and libraries

[[class-loaders]]
== Class Loaders

Understanding Payara Server class loaders can help you determine where to place supporting JAR and resource files for your modules and applications.

In a JVM implementation, the class loaders dynamically load a specific Java class file needed for resolving a dependency. For example, when an instance of
`java.util.Enumeration` needs to be created, one of the class loaders loads the relevant class into the environment.

For information about class loader debugging, see xref:Technical Documentation/Application Development/debugging-apps.adoc#class-loader-debugging[Class Loader Debugging].

[[standard-classloading]]
== Standard Classloading
:ordinal: 1

In a JVM implementation, the class loaders dynamically load a specific Java class file needed for resolving a dependency. For example, when an instance of
`java.util.Enumeration` needs to be created, one of the class loaders loads the relevant class into the environment.

For information about class loader debugging, see xref:Technical Documentation/Application Development/debugging-apps.adoc#class-loader-debugging[Class Loader Debugging].

Class loaders in Payara Server follow a delegation hierarchy by default. This page documents how classes are usually loaded and from which locations.

[[classloader-hierarchy]]
== The Class Loader Hierarchy

With the default classloader configuration, Payara Server will attempt to search for classes in the following locations in this order:

1. Classes provided by the JDK
2. Extension libraries in a Payara Server domain (installed as a library of the `ext` type )
3. Classes provided by Payara Server
4. Common libraries in a Payara Server domain (installed as a library of the `common` type)
5. Application-specific libraries in Payara Server (installed as a library of the `app` type)
6. Classes and libraries provided by the deployed application archive (e.g. `WAR` or `EAR`)

Classloaders that are lower in the hierarchy will first delegate searching for a class to a classloader higher in the hierarchy.

NOTE: If none of the classloaders higher in the hierarchy finds the class, the classloader will attempt to find the class itself.

Here, you can see that:

* Classes provided by Payara Server have higher priority than classes provided by an application
* Classes provided by Payara Server have higher priority than installed libraries of type `common` and `app`
* Classes in installed libraries have higher priority than classes provided by an application
* To install a library with a higher priority than classes provided by Payara Server, it should be installed with type `ext`

The delegation hierarchy can be tweaked using the xref:Technical Documentation/Application Development/class-loaders.adoc#enhanced-classloading[enhanced classloading] features. For example, it's possible to give the classes provided by an application the highest priority (by disabling classloading delegation), or completely hide (isolate) classes provided by Payara Server from a deployed application.

The Jakarta Servlet specification recommends that a web module's class loader look in the local class loader before delegating to its parent.


You can make this class loader follow the delegation inversion model in the Servlet specification by setting `delegate="false"` in the `class-loader`
element of the `payara-web.xml` file. It is safe to do this only for a web module that does not interact with any other modules. For more details,
see "xref:Technical Documentation/Payara Server Documentation/Application Deployment/dd-elements.adoc#class-loader[class-loader]" in the Payara Server Application Deployment section.

The default value is `delegate="true"`, which causes a web module's class loader to delegate in the same manner as the other class loaders.
You must use `delegate="true"` for a web application that accesses EJB components or that acts as a web service client or endpoint.

For a number of packages, including `java.\*` and `jakarta.\*`, symbol resolution is always delegated to the parent class loader regardless of the `delegate` setting. This prevents applications from overriding core Java runtime classes or changing the API versions of specifications that are part of the Jakarta EE platform.


[[install-libraries]]
== Install Libraries in a Payara Server Domain

If a deployed application requires additional classes not provided by the application, you can install a library with those classes into the Payara Server domain. This is useful if you'd like to build an application for flexible deployments and configure it with classes dropped on the classpath, or if you'd like multiple deployed applications to share the same library.

If an internal Payara Server resource, such as a JDBC connection pool, requires an additional library, you can install it into the Payara Server domain too.

To install a library into a Payara Server domain, use the asadmin xref:Technical Documentation/Payara Server Documentation/Server Configuration And Management/Asadmin Commands/Server Management Asadmin Commands.adoc#add-library-command[add-library] command. This command accepts the `--type` argument, which accepts the following options:

`common`:: The library is installed as a common library into the `lib` directory in the Payara Server domain
`ext`:: The library is installed as an extension library into the `lib/ext` directory in the Payara Server domain
`app`:: the library is installed as an application library into the `lib/applibs` directory in the Payara Server domain

[[common-libraries]]
== Common Libraries

Common libraries are available to all applications or modules deployed on servers with the same configuration. There are several levels of common libraries:

* Shared by all applications deployed on the same Payara Server installation - located in the `glassfish/lib` directory in the Payara Server installation
* Shared by all applications deployed in the same Payara Server domain - located in the `lib` directory in that Payara Server domain directory
* Shared by all applications deployed on instances that share the same configuration - located in the `config/<config-name>/lib` directory in the particular Payara Server domain directory

NOTE: Only libraries shared by applications in the same domain can be installed by the `add-library` asadmin command. All other types have to be installed manually by copying the libraries into the particular locations.

[[extension-libraries]]
== Extension Libraries

Application developers can use libraries installed as extension libraries to extend the functionality of the core Payara Server platform. For example, an Oracle Database JDBC driver should be installed as an extension library if it's going to be used via JPA to use Oracle-specific JPA features. Or a Java agent library should be installed as an extension library if the Java agent instruments classes in Payara Server to use classes from the agent library itself.

CAUTION: Classes in extension libraries will be available to all deployed applications. If you need that classes from an extension library are available also to Payara Server's internal classes (and OSGi bundles in general) as is often the case with Java agents, you also need to add the packages exported by the library into OSGi boot delegation. This is done by modifying the `glassfish/config/osgi.properties` configuration file in the Payara Server installation and adding the packages to the list in the `org.osgi.framework.bootdelegation` property. Packages exported by Oracle JDBC drivers are already added by default.

[[extension-library-support-jdk-8]]
=== Extension Libraries Support On JDK 8

When Payara Server runs on JDK 8, extension libraries are added to the JVM using the standard https://docs.oracle.com/javase/tutorial/ext/index.html[Java extension mechanism], by adding the `lib/ext` directory in the current domain as an extension directory using the `java.ext.dirs` JVM option.

[[extension-library-support-jdk-11]]
=== Extension Libraries Support On JDK 11+

When Payara Server runs on JDK 11 and newer releases, extension libraries are added to the system classpath at the beginning of the classpath, so that they have higher priority than all other classes and libraries on the classpath. This is because the Java extension mechanism isn't supported in Java 11 and newer and the official recommend way to replace it is to add the libraries to the classpath directly.

This behavior is triggered automatically if the `java.ext.dirs` property isn't defined as a JVM option, regardless of the JDK version used. Since defining the `java.ext.dirs` on Java 11+ leads to an error, this JVM option cannot be used with Java 11+ and extension libraries are automatically added as classpath elements.

TIP: It's also possible to trigger this behavior when using Java 8 by removing the `java.ext.dirs` JVM option from the Payara Server default configuration settings.

[[Application-Specific-libraries]]
== Application Specific Libraries

You can specify module or application-specific library classes in one of the following ways:

* Use the Administration Console. Open the _Applications_ component, then go to the page for the type of application or module. Select the _Deploy_ button. Type the comma-separated paths in the _Libraries_ field.

* Use the `asadmin deploy` command with the `--libraries` option and specify comma-separated paths. For more details, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/deploy.adoc[Payara Server Reference Manual].

* Use the `asadmin add-library` command with the `--type app` option. For details, see the xref:Technical Documentation/Payara Server Documentation/Command Reference/add-library.adoc[add-library].

NOTE: None of these alternatives apply to application clients. For more information, see xref:Technical Documentation/Application Development/java-clients.adoc#using-libraries-with-application-clients[Using Libraries with Application Clients].

You can update a library JAR file using dynamic reloading or by restarting (disabling and re-enabling) a module or application. To add or remove library JAR files, you can redeploy the module or application. Application libraries are included in the _Applib_ class loader. Paths to libraries can be relative or absolute.

A relative path is relative to `${domain-dir}/lib/applibs`. If the path is absolute, the path must be accessible to the domain administration server (DAS). Payara Server automatically synchronizes these libraries to all remote instances when a cluster or deployment group is restarted. However,
libraries specified by absolute paths are not guaranteed to be synchronized.

TIP: You can also use application-specific class loading to access different versions of a library from different applications.

If multiple applications or modules refer to the same libraries, classes in those libraries are automatically shared. This can reduce the memory footprint and allow sharing of static information. However, applications or modules using application-specific libraries are not portable.

NOTE: If you see an access control error message when you try to use a library, you may need to grant permission to the library in the
`server.policy` file. For more information, see xref::Technical Documentation/Application Development/securing-apps.adoc#changing-permissions-for-an-application[Changing Permissions for an Application].


[[enhanced-classloading]]
== Enhanced Classloading
:ordinal: 2

This sections below cover the enhanced class loading functionality provided by the Payara Server.

[[default-class-and-library-loading]]
== Default Class and Library Loading

Payara Server has included many standard Java libraries and packages, for example *Jackson*, *Nimbus JOSE*, *Logback*, and others to use. These libraries are located on the `${PAYARA_INSTALL_DIR}/modules` directory.

The default class loading mechanism of Payara Server works like this: When loading classes that belong to a library or framework that is included in the server, the server *will always* load those classes even if the application itself includes different versions.

In some cases, application developers will want to include a different version of the libraries that are already included on the server. Common use cases for this are:

. Use a newer version of a library that is included in the server. For example, Payara Server includes the Jackson library, and you might need
to use a newer version that includes a specific feature you want to use.
. Use an older version of a library included within the server in order to support legacy applications. For example, you are using an older version of *Icefaces* that depends on an older version of JSF.

Unfortunately, due to the way the default class loading works, this will not be possible, and all libraries included with the server libraries will take precedence.

[[disable-classloading-delegation]]
== Disable Classloading delegation

In order for the server's classloader to load classes from libraries of different versions to the ones shipped with it, it's possible to disable the *default classloader delegation*. It can be altered to allow the server to load classes from libraries located at different sources in the following order:

. Libraries on WAR applications (included on _WEB-INF/lib_)
. Libraries on EAR applications (included on _/lib_)
. Libraries from the domain (located at `${DOMAIN_DIR}/lib`)
. Libraries from the server (located at `${PAYARA_INSTALL_DIR}`/modules_)

[[disable-classloading-delegation-globally]]
=== Disable Classloading delegation globally

To disable class loading delegation globally, you can set the system property `fish.payara.classloading.delegate` to `false`. This way, any library that is included on deployed applications will override the ones that are included in the server.

Libraries included at the domain level (`${DOMAIN_DIR}/lib`) will take precedence over the libraries included at the server.

[[disable-classloading-delegation-locally]]
=== Disable Classloading delegation locally

It's possible to disable class loading delegation directly at the application level. This can be done for both WAR and EAR applications.

[[on-war-applications]]
==== On WAR Applications

For *WAR* applications, you can include `<class-loader delegate="false"/>` element in the `glassfish-web.xml` deployment descriptor. Here's an example:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app error-url="">
  <class-loader delegate="false"/>
</glassfish-web-app>
----

With this, all libraries included on the `WEB-INF/lib/` directory will take precedence.

[[on-ear-applications]]
==== On EAR Applications

For *EAR* applications, you can include the `<classloading-delegate>false</classloading-delegate>` element in the `glassfish-application.xml` deployment descriptor. Here is an example:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-application PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Java EE Application 6.0//EN" "http://glassfish.org/dtds/glassfish-application_6_0-1.dtd">
<glassfish-application>
    <classloading-delegate>false</classloading-delegate>
</glassfish-application>
----

With this, all libraries included on the EAR's `lib/` directory will take precedence.

[[use-bundled-jsf]]
== Use other JSF implementation

In order to make the server use the bundled JSF implementation within the application, you need to set an additional configuration parameter; class loading delegation alone is not enough.
You need to indicate within the _payara-web.xml_ (or glassfish-web.xml) file that the server should use the bundled JSF implementation as follows:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE payara-web-app PUBLIC "-//Payara.fish//DTD Payara Server 4 Servlet 3.0//EN" "{payaraWebDtd}">
<payara-web-app error-url="">
    <class-loader delegate="false"/>
    <property name="useBundledJsf" value="true" />
</payara-web-app>
----

By specifying these options, the bundled JSF implementation within your deployment (WAR or EAR) will be used correctly.

IMPORTANT: If using an EAR you must bundle the JSF implementation within the embedded WAR component. You cannot add the JSF implementation as an EAR library.

[[extreme-classloading-isolation]]
== Extreme Classloading Isolation

It's possible to configure an extreme isolation level on the class loading delegation for deployed applications. With this extreme isolation behavior, a deployed application can force the server to load only classes and resources from libraries included on Payara Server that belong to *whitelisted packages* defined on its deployment descriptors.

To configure whitelist packaging you can use the `<whitelist-package>` element on the _glassfish-web.xml_ (WAR artifacts) or the _glassfish-application.xml_ (EAR artifacts). This element can be included multiple times to whitelist multiple packages. Here is an example of whitelisting both the *Google Guava*, *Jackson* and *Faces Config* packages for a WAR application:

[source, xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE glassfish-web-app PUBLIC "-//GlassFish.org//DTD GlassFish Application Server 3.1 Servlet 3.0//EN" "http://glassfish.org/dtds/glassfish-web-app_3_0-1.dtd">
<glassfish-web-app error-url="">
  <whitelist-package>com.google.guava</whitelist-package>
  <whitelist-package>com.fasterxml.jackson</whitelist-package>
  <whitelist-package>com.sun.faces.spi.FacesConfigResourceProvider</whitelist-package>
</glassfish-web-app>
----

The whitelist syntax is simple: Define the name of the package which contains the classes or resources in question. For example writing `com.google` would whitelist all Google libraries included on the server, while writing `com.google.guava` would only whitelist the Google Guava library instead.

IMPORTANT: To enable this extreme isolation behavior, at least one `whitelist-package` element must be defined in the appropriate descriptor.

[[default-whitelisted-classes]]
=== Default Whitelisted Classes

Certain classes are whitelisted automatically, meaning they will always be loaded from Payara Server's libraries, even if this feature is turned on.

This is because these packages are required by Payara Server and therefore cannot be loaded from a deployed application:

* `java`
* `javax`
* `com.sun`
* `org.glassfish`
* `org.apache.jasper`
* `fish.payara`
* `com.ibm.jbatch`
* `org.hibernate.validator`
* `org.jboss.weld`
* `com.ctc.wstx`

Default whitelisted resources are:

* `META-INF/services/jakarta.`
* `META-INF/services/org.glassfish.`
* `META-INF/services/java.`

