:ordinal: 900
= Arquillian Containers

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara Community.

In version {currentVersion}, the following containers are available:

Payara Server:

* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Remote.adoc[Payara Server Remote]
* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Managed.adoc[Payara Server Managed]
* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Embedded.adoc[Payara Server Embedded]

Payara Micro:

* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Micro Managed.adoc[Payara Micro Managed]


== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----

Some containers will be either in development or an early release version. In these cases
the same process can be used, but the artifact will need to be built from source.
The containers can be found in the Payara Arquillian source code repository.

Clone the https://github.com/payara/ecosystem-arquillian-connectors[ecosystem-arquillian-connectors] Git repository:

[source,Shell]
----
git clone https://github.com/payara/ecosystem-arquillian-connectors.git
----

Build and install:

[source,Shell]
----
mvn clean install -DskipTests
----
