
= Arquillian Containers

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara Community.

In version {page-version}, the following containers are available:

Payara Server:

* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Remote.adoc[Payara Server Remote]
* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Managed.adoc[Payara Server Managed]
* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Server Embedded.adoc[Payara Server Embedded]

Payara Micro:

* xref:/Technical Documentation/Ecosystem/Connector Suites/Arquillian Containers/Payara Micro Managed.adoc[Payara Micro Managed]


== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----

Some containers will be either in development or an early release version.
The same process can be used in these cases, but the artifact will need to be built from the source.
The containers can be found in the Payara Arquillian source code repository.
Clone the https://github.com/payara/ecosystem-arquillian-connectors[ecosystem-arquillian-connectors] Git repository:

[source,Shell]
----
git clone https://github.com/payara/ecosystem-arquillian-connectors.git
----

Build and install:

[source,Shell]
----
mvn clean install -DskipTests
----

NOTE: An example application demonstrating how to create a test suite that runs the tests inside various Payara Platform distributions using Arquillian can be seen in the https://github.com/payara/Payara-Examples[Payara Examples] repository. See specifically the https://github.com/payara/Payara-Examples/tree/master/ecosystem/arquillian-example[ecosystem/arquillian-example] subproject for an example of using Arquillian