[[managing-queues]]
= Managing Queues
Queues in Amazon SQS can be managed, including actions such as creating queues, deleting queues, listing queues, fetching queue URL, retrieving queue attributes, and additional features all via the JCA and an Amazon-specific API. To utilize this API for managing queues, a resource must be defined using the JCA API – a connection factory.

The connection factory should be assigned a name, typically within the `java:app` namespace. The type of the connection factory for Amazon SQS is `fish.payara.cloud.connectors.amazonsqs.api.AmazonSQSConnectionFactory`. Specify the resource adapter name, which in this case, is `amazon-sqs-rar-0.8.0.rar`.

Finally, AWS account details need to be specified in the properties of the corresponding JMS resource definitions.

The following gives an example:

[source, java]
----
@ConnectionFactoryDefinition ( 
  name = "java:app/amazonsqs/factory",
  interfaceName = "fish.payara.cloud.connectors.amazonsqs.api.AmazonSQSConnectionFactory",
  resourceAdapter = "amazon-sqs-rar-0.8.0"
  properties = {"awsAccessKeyId=<accessKeyID>", "awsSecretKey=<secretKey>", "region=eu-west-2"}
)
----

[[create-queue]]
== Create Queue:

Creates a new Amazon SQS queue.

[source, java]
----
CreateQueueRequest createQueueRequest = new CreateQueueRequest("MyNewQueue");
CreateQueueResult createQueueResult = connection.createQueue(createQueueRequest);
System.out.println("Queue Created: " + createQueueResult);
----

[[list-queues]]
== List Queues:
With the above definition, the following code provides an example of listing queues:

[source, java]
----
@Singleton
@Startup
public class ListSQSQueues {
 
 @Resource(lookup = "java:app/amazonsqs/factory")
 private AmazonSQSConnectionFactory factory;
 
 @PostConstruct
 public void listQueues() {
    try (AmazonSQSConnection connection = factory.createConnection()) {
        // List all queues
        ListQueuesResult allQueues = connection.listQueues();
        System.out.println("All Queues:");
        for (String queueUrl : allQueues.getQueueUrls()) {
            System.out.println(" - " + queueUrl);
        }

        // List queues with a specific name prefix
        ListQueuesResult prefixedQueues = connection.listQueues("my-prefix");
        System.out.println("Prefixed Queues:");
        for (String queueUrl : prefixedQueues.getQueueUrls()) {
            System.out.println(" - " + queueUrl);
        }
    }
    catch (Exception ex) {
        ex.printStackTrace();
    }
 }  
}
----

[[delete-queue]]
== Delete Queue:

Deletes an existing Amazon SQS queue.

[source, java]
----
DeleteQueueRequest deleteQueueRequest = new DeleteQueueRequest("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue");
DeleteQueueResult deleteQueueResult = connection.deleteQueue(deleteQueueRequest);
System.out.println("Queue Deleted: " + deleteQueueResult);
----

[[list-queue-tags]]
== List Queue Tags:

Lists the tags for an Amazon SQS queue.

[source, java]
----
ListQueueTagsResult tagsResult = connection.listQueueTags("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue");
Map<String, String> tags = tagsResult.tags();
System.out.println("Queue Tags: " + tags);
----

[[purge-queue]]
== Purge Queue:

Deletes all the messages in an Amazon SQS queue.

[source, java]
----
PurgeQueueResult purgeResult = connection.purgeQueue("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue");
System.out.println("Queue Purged: " + purgeResult);
----

[[tag-untag-queue]]
== Tag and Untag Queue:

Adds and removes tags from an Amazon SQS queue.

[source, java]
----
Map<String, String> tagsToAdd = Map.of("Environment", "Production", "Team", "Dev");
TagQueueRequest tagQueueRequest = new TagQueueRequest("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue", tagsToAdd);
TagQueueResult tagQueueResult = connection.tagQueue(tagQueueRequest);
System.out.println("Queue Tagged: " + tagQueueResult);

List<String> tagKeysToRemove = List.of("Environment");
UntagQueueRequest untagQueueRequest = new UntagQueueRequest("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue", tagKeysToRemove);
UntagQueueResult untagQueueResult = connection.untagQueue(untagQueueRequest);
System.out.println("Queue Untagged: " + untagQueueResult);
----