[[managing-queues]]
= Managing Queues
Queues in Amazon SQS can be managed, including actions such as creating queues, deleting queues, listing queues, fetching queue URL, retrieving queue attributes, and additional features all via the JCA and an Amazon-specific API. To utilize this API for managing queues, a resource must be defined using the JCA API – a connection factory.

The connection factory has to be given a name, which can be any name that is valid for JNDI. The `java:app` namespace is typically recommended to be used. The type of the connection factory to be used for Amazon SQS is `fish.payara.cloud.connectors.amazonsqs.api.AmazonSQSConnectionFactory`, and we have to specify the resource adapter name which is here `amazon-sqs-rar-1.0.0.rar`.

Finally the AWS account details have to be specified in the properties of the corresponding JMS resource definitions.

The following gives an example:

[source, java]
----
@ConnectionFactoryDefinition ( 
  name = "java:app/amazonsqs/factory",
  interfaceName = "fish.payara.cloud.connectors.amazonsqs.api.AmazonSQSConnectionFactory",
  resourceAdapter = "amazon-sqs-rar-1.0.0"
  properties = {"awsAccessKeyId=<accessKeyID>", "awsSecretKey=<secretKey>", "region=eu-west-2"}
)
----

[[create-queue]]
== Create Queue:

Creates a new Amazon SQS queue.

[source, java]
----
CreateQueueRequest createQueueRequest = CreateQueueRequest.builder()
        .queueName("MyNewQueue")
        .build();

CreateQueueResponse createQueueResponse = connection.createQueue(createQueueRequest);
System.out.println("Queue Created: " + createQueueResponse);
----

[[list-queues]]
== List Queues:
With the above definition, the following code provides an example of listing queues:

[source, java]
----
@Singleton
@Startup
public class ListSQSQueues {
 
    @Resource(lookup = "java:app/amazonsqs/factory")
    private AmazonSQSConnectionFactory factory;
 
    @PostConstruct
    public void listQueues() {
        try (AmazonSQSConnection connection = factory.createConnection()) {
            // List all queues
            ListQueuesResponse allQueues = connection.listQueues();
            System.out.println("All Queues:");
            for (String queueUrl : allQueues.queueUrls()) {
                System.out.println(" - " + queueUrl);
            }

            // List queues with a specific name prefix
            ListQueuesResponse prefixedQueues = connection.listQueues(ListQueuesRequest.builder().queueNamePrefix("my-prefix").build());
            System.out.println("Prefixed Queues:");
            for (String queueUrl : prefixedQueues.queueUrls()) {
                System.out.println(" - " + queueUrl);
            }
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
    }  
}
----

[[delete-queue]]
== Delete Queue:

Deletes an existing Amazon SQS queue.

[source, java]
----
DeleteQueueRequest deleteQueueRequest = DeleteQueueRequest.builder()
        .queueUrl("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue")
        .build();

DeleteQueueResponse deleteQueueResponse = connection.deleteQueue(deleteQueueRequest);
System.out.println("Queue Deleted: " + deleteQueueResponse);
----

[[list-queue-tags]]
== List Queue Tags:

Lists the tags for an Amazon SQS queue.

[source, java]
----
ListQueueTagsRequest tagsRequest = ListQueueTagsRequest.builder()
        .queueUrl("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue")
        .build();

ListQueueTagsResponse tagsResponse = connection.listQueueTags(tagsRequest);
Map<String, String> tags = tagsResponse.tags();
System.out.println("Queue Tags: " + tags);
----

[[purge-queue]]
== Purge Queue:

Deletes all the messages in an Amazon SQS queue.

[source, java]
----
PurgeQueueRequest purgeRequest = PurgeQueueRequest.builder()
        .queueUrl("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue")
        .build();

PurgeQueueResponse purgeResponse = connection.purgeQueue(purgeRequest);
System.out.println("Queue Purged: " + purgeResponse);
----

[[tag-untag-queue]]
== Tag and Untag Queue:

Adds and removes tags from an Amazon SQS queue.

[source, java]
----
Map<String, String> tagsToAdd = Map.of("Environment", "Production", "Team", "Dev");
TagQueueRequest tagQueueRequest = TagQueueRequest.builder()
        .queueUrl("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue")
        .tags(tagsToAdd)
        .build();
TagQueueResponse tagQueueResponse = connection.tagQueue(tagQueueRequest);
System.out.println("Queue Tagged: " + tagQueueResponse);

List<String> tagKeysToRemove = List.of("Environment");
UntagQueueRequest untagQueueRequest = UntagQueueRequest.builder()
        .queueUrl("https://sqs.ap-south-1.amazonaws.com/185040379064/MyQueue")
        .tagKeys(tagKeysToRemove)
        .build();
UntagQueueResponse untagQueueResponse = connection.untagQueue(untagQueueRequest);
System.out.println("Queue Untagged: " + untagQueueResponse);
----

