= Enable Asadmin CLI Multimode Event Designators

This feature allows the use of **Bash Event Designators** when using Payara Server's Asadmin CLI in multimode.

An Event Designator is a reference to a command line entry in the history list, which makes it easy for users to refer and re-use previous asadmin subcommands entries.

IMPORTANT: This feature is disabled by default in Payara Server and has to be enabled first before being used.

WARNING: If this feature is enabled, all occurrences of the `\` character will be escaped and thus, removed before running the corresponding command. You'll have to escape these characters and turn them into `\\` for any commands to be properly parsed.

[[enabling-jline-event]]
== Enabling JLine Event Expansion

To enable support for JLine event designators just set the `AS_ADMIN_DISABLE_EVENT_EXPANSION` environment variable to `false`. Follow these steps depending on your operating system:

[[in-linux]]
=== Linux and *Nix variants
. Open the Terminal
. Type the following command
+
[source, shell]
----
export AS_ADMIN_DISABLE_EVENT_EXPANSION=false
----
+
. Check that the variable has been correctly set:
+
----
echo $AS_ADMIN_DISABLE_EVENT_EXPANSION
----

[[in-windows]]
=== Windows
. Open Command Prompt as an Administrator
. Type the following commands
+
[source, shell]
----
setx AS_ADMIN_DISABLE_EVENT_EXPANSION "false" /m
set AS_ADMIN_DISABLE_EVENT_EXPANSION=false
----
+
. Check that the variable has been correctly set:
+
----
echo %AS_ADMIN_DISABLE_EVENT_EXPANSION%
----

[[see-also]]
== See Also

* link:https://www.gnu.org/software/bash/manual/html_node/Event-Designators.html[Event Designators]