[[building-netbeans-ide-plugin]]
= Building Payara Tools NetBeans IDE Plugin

As Apache NetBeans IDE provides out-of-the-box support for Payara Platform, the source code for the Payara Platform tools is contained within the https://github.com/apache/netbeans[NetBeans Code Repository.]

Full, up-to-date build instructions for the Apache NetBeans IDE can be read on the https://github.com/apache/netbeans/tree/master#apache-netbeans[README file in the Apache NetBeans IDE repository]

[[building-netbeans-extension-prequisites]]
== Prerequisites
Before building the Apache NetBeans IDE and subsequently the Payara Platform Tools for Apache NetBeans IDE, you will need to configure your local environment. Subsequent builds will not require these steps.

Clone the Apache NetBeans Repository::
You must first clone the repository where the plugin source code is stored. https://github.com/apache/netbeans[Apache NetBeans Code Repository]

Install Apache Ant::
Apache Ant is the build tool for the Apache NetBeans IDE and must be configured locally. https://ant.apache.org/manual/install.html[Install Apache Ant]

JDK 11::
JDK 11 is required to build and run Apache NetBeans

IMPORTANT: If you are building Apache NetBeans on Windows. `Program Files` must be replaced with `PROGRA~1` and `Program Files (x86)` must be replaced with `PROGRA~2` in your `ANT_HOME` environment variable.

[[accessing-payara-tools-code]]
== Payara Tools Code

The Payara Tools plugin code is split into five modules, these are all located under the `enterprise` directory:

* https://github.com/apache/netbeans/tree/master/enterprise/payara.common[payara.common]
* https://github.com/apache/netbeans/tree/master/enterprise/payara.eecommon[payara.eecommon]
* https://github.com/apache/netbeans/tree/master/enterprise/payara.jakartaee[payara.jakartaee]
* https://github.com/apache/netbeans/tree/master/enterprise/payara.micro[payara.micro]
* https://github.com/apache/netbeans/tree/master/enterprise/payara.tooling[payara.tooling]

To test any code changes, recompile the modified module, then rerun the IDE build using `ant tryme`.