[[overview]]
= Overview

This Application Development Guide describes how to create and run Jakarta EE applications in compatible Payara Platform distributions. Topics for this guide include developer tools, security, debugging and specific features for Jakarta EE specification implementations. This document is intended for use by software developers who create, assemble, and deploy Jakarta EE applications using the Payara Platform.

[[related-documentation]]
== Related Documentation

The following tutorials explain how to develop Jakarta EE applications:

* https://github.com/eclipse-ee4j/jakartaee-firstcup[Your First Cup: An Introduction to the Jakarta EE Platform]. This is a recommended tutorial for programmers with no experience or knowledge about Jakarta EE, and it explains the entire process for developing a simple enterprise application using Eclipse Glassfish.

* https://eclipse-ee4j.github.io/jakartaee-tutorial/[The Jakarta EE Tutorial]. This comprehensive tutorial explains how to use Jakarta EE platform technologies and APIs to develop enterprise applications. This guide heavily references the contents of this tutorial to guide users in understanding the basic concepts of application development.

IMPORTANT: The Jakarta EE tutorial uses Eclipse Glassfish as its Jakarta EE runtime. Most of the concepts and instructions used in the tutorial should be directly equivalent to the Payara Platform given its similarities to Eclipse Glassfish.

The Jakarta EE specifications Javadoc documentation is listed within its specification resources under each corresponding specification site at https://jakarta.ee/specifications/.

The Jakarta EE Examples project is a collection of sample applications that demonstrate a broad range of Jakarta EE technologies. They are available to download in their own https://github.com/eclipse-ee4j/jakartaee-examples[online repository].

[[typographic-conventions]]
== Typographic Conventions

The following table describes the typographic changes that are used in this document.

[width="100%",cols="15%,35%,50% a",options="header"]
|=====
|Typeface |Meaning |Example
|`AaBbCc123` |The names of commands, files, and directories, and onscreen computer output
|
Edit your `.login` file.

Use `ls` `a` to list all files.

`machine_name% you have mail.`

|`AaBbCc123` |

What you type, contrasted with onscreen computer output
|`machine_name%` `su`

`Password:`

|AaBbCc123
|A placeholder to be replaced with a real name or value
|The command to remove a file is `rm` filename.

|=====

[[symbol-conventions]]
== Symbol Conventions

The following table explains symbols that might be used in this document.

[width="100%", cols="10%,25%,25%,40% a",options="header",]
|=======================================================================
|Symbol |Description |Example |Meaning
|`[ ]` |Contains optional arguments and command options. |`ls [-l]` |The
`-l` option is not required.

|`{ \| }` |Contains a set of choices for a required command option.
|`-d {y\|n}` |The `-d` option requires that you use either the `y`
argument or the `n` argument.

|`${ }` |Indicates a variable reference or a placeholder reference for a default path. |`${com.sun.javaRoot}`
|References the value of the `com.sun.javaRoot` variable.

|- |Joins simultaneous multiple keystrokes. |Control-A |Press the
Control key while you press the A key.

|+ + |Joins consecutive multiple keystrokes. |Ctrl+A+N |Press the
Control key, release it, and then press the subsequent keys.

|-> |Indicates menu item selection in a graphical user interface. |File >
New -> Templates |From the _File_ menu, choose New. From the _New_ submenu,
choose _Templates_.
|=======================================================================


[[default-paths-and-file-names]]
== Default Paths and File Names

The following table describes the default paths and file names that are used in this document.

[width="100%",cols="15%,35%,50% a",options="header",]
|=====
|Placeholder |Description |Default Value
|`PAYARA_INSTALL` +|
Represents the base installation directory of a Payara Server installation.

In configuration files, `as-install` is represented as follows:

`${com.sun.aas.installRoot}`
|
* Installations on the Linux operating system: `${USR_HOME}/payara/glassfish`

* Installations on the Windows operating system: `SystemDrive:\payara\glassfish`

|`DOMAIN_ROOT_DIR` + |Represents the directory in which a domain is created by default. |`${PAYARA_INSTALL}/domains/`

|`DOMAIN_DIR`|
Represents the directory in which a domain's configuration is stored.

In configuration files, it is represented as follows:

`${com.sun.aas.instanceRoot}`

|`${DOMAIN_ROOT_DIR}/domain-name`

|=====
