[[setting-up-a-development-environment]]
= Setting Up a Development Environment

This chapter gives guidelines for setting up an application development environment in the Oracle Payara Server. Setting up an environment
for creating, assembling, deploying, and debugging your code involves installing the mainstream version of the Payara Server and making use of development tools. In addition,
sample applications are available.

[[installing-and-preparing-the-server-for-development]]
== Installing and Preparing the Server for Development

The following components are included in the full installation.

* JDK
* Payara Server core

** Java Platform, Standard Edition (Java SE) 8

** Jakarta EE 8 compliant application server

** Administration Console

** `asadmin` utility

** Other development and deployment tools

** Open Message Queue software

** Apache http://db.apache.org/derby/manuals[Derby database]

** Load balancer plug-ins for web servers

The NetBeans Integrated Development Environment (IDE) bundles the Payara edition of the Payara Server, so information about this IDE is provided as well.

After you have installed Payara Server, you can further optimize the server for development in these ways:

* Locate utility classes and libraries so they can be accessed by the proper class loaders. For more information, seexref:docs:application-development-guide:class-loaders.adoc#using-the-common-class-loader[Using the Common Class Loader].
* Set up debugging. For more information, see xref:docs:application-development-guide:debugging-apps.adoc#debugging-applications[Debugging Applications].
* Configure the Virtual Machine for the Java platform (JVM software).
For more information, see "xref:docs:administration-guide:jvm.adoc#administering-the-virtual-machine-for-the-java-platform[Administering the Virtual Machine for the Java Platform]" in Payara Serve Administration Guide.

[[high-availability-features]]
== High Availability Features

High availability features such as load balancing and session failover are discussed in detail in the xref:docs:ha-administration-guide:overview.adoc[Payara Server High Availability Administration Guide]. This book describes the following features in the following sections:

* For information about HTTP session persistence, see xref:docs:application-development-guide:webapps.adoc#distributed-sessions-and-persistence[Distributed Sessions and Persistence].
* For information about checkpointing of the stateful session bean state, see xref:application-development-guide:ejb.adoc#stateful-session-bean-failover[Stateful Session Bean Failover].
* For information about failover and load balancing for Java clients, see xref:docs:application-development-guide:java-clients.adoc#developing-java-clients[Developing Java Clients].
* For information about load balancing for message-driven beans, see xref:docs:application-development-guide:jms.adoc#load-balanced-message-inflow[Load-Balanced Message Inflow].

[[development-tools]]
== Development Tools

The following general tools are provided with the Payara Server:

* xref:setting-up-dev-env.adoc#the-asadmin-command[The `asadmin` Command]
* xref:setting-up-dev-env.adoc#the-administration-console[The Administration Console]

The following development tools are provided with the Payara Server or downloadable from Oracle:

* xref:setting-up-dev-env.adoc#the-migration-tool[The Migration Tool]
* xref:setting-up-dev-env.adoc#the-netbeans-ide[The NetBeans IDE]

The following third-party tools might also be useful:

* xref:setting-up-dev-env.adoc#debugging-tools[Debugging Tools]
* xref:setting-up-dev-env.adoc#profiling-tools[Profiling Tools]

[[the-asadmin-command]]
=== The `asadmin` Command

The `asadmin` command allows you to configure a local or remote server and perform both administrative and development tasks at the command line.

The `asadmin` command is located in the as-install`/bin` directory. Type `asadmin help` for a list of subcommands.

[[the-administration-console]]
=== The Administration Console

The Administration Console lets you configure the server and perform both administrative and development tasks using a web browser.
For general information about the Administration Console, click the Help button in the Administration Console. This displays the Payara Server online help.

To access the Administration Console, type `http://`host`:4848` in your browser. The host is the name of the machine on which the Payara Server is running.
By default, the host is `localhost`. For example:

[source,text]
----
http://localhost:4848
----

[[the-migration-tool]]
=== The Migration Tool

The Migration Tool converts and reassembles Jakarta EE applications and modules developed on other application servers.
This tool also generates a report listing how many files are successfully and unsuccessfully migrated, with reasons for migration failure.
For more information and to download the Migration Tool, see `http://java.sun.com/j2ee/tools/migration/index.html`.

[[the-netbeans-ide]]
=== The NetBeans IDE

The NetBeans IDE allows you to create, assemble, and debug code from a single, easy-to-use interface. The Payara edition of the Payara Server is bundled with the NetBeans 6.1 IDE. To download the NetBeans
IDE, see `http://www.netbeans.org`. This site also provides documentation on how to use the NetBeans IDE with the bundled Payara edition of the Payara Server.

You can also use the Payara Server with the Java Studio Enterprise software, which is built on the NetBeans IDE. For more information, see
`http://developers.sun.com/jsenterprise/`.

[[debugging-tools]]
=== Debugging Tools

You can use several debugging tools with the Payara Server. For more information, see xref:docs:application-development-guide:debugging-apps.adoc#debugging-applications[Debugging Applications].

[[profiling-tools]]
=== Profiling Tools

You can use several profilers with the Payara Server. For more information, see xref:docs:application-development-guide:debugging-apps.adoc#profiling-tools[Profiling Tools].

[[sample-applications]]
== Sample Applications

Sample applications that you can examine and deploy to the Payara Server are included as part of the Jakarta EE 8 SDK bundle. The samples are also available from `https://github.com/javaee/glassfish-samples`.

Most Payara Server samples have the following directory structure:

* The `docs` directory contains instructions for how to use the sample.
* The `pom.xml` file defines Maven targets for the sample.
* The `src/` directory contains source code for the sample.


