[[microprofile]]
= MicroProfile Specification Dependencies Mapping
:ordinal: 2

This section details all dependencies related to Eclipse MicroProfile.

TIP: Overlapping dependencies with Jakarta EE can be visualized in the xref:Jakarta EE.adoc[corresponding page].

[[common]]
== `Common`

[[microprofile-common]]
=== *microprofile-common*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-common</artifactId>
    <version>5.74.0</version>
</dependency>
----


[[config]]
== `Config`

[[microprofile-config]]
=== *microprofile-config*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-config-api]]
=== *microprofile-config-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.config</groupId>
    <artifactId>microprofile-config-api</artifactId>
    <version>2.0.1</version>
</dependency>
----

[[microprofile-config-extensions]]
=== *microprofile-config-extensions*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config-extensions</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-config-service]]
=== *microprofile-config-service*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>microprofile-config-service</artifactId>
    <version>5.74.0</version>
</dependency>
----


[[fault-tolerance]]
== `Fault-Tolerance`

[[microprofile-fault-tolerance]]
=== *microprofile-fault-tolerance*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-fault-tolerance</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-fault-tolerance-api]]
=== *microprofile-fault-tolerance-api*

**Version**: 3.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.fault-tolerance</groupId>
    <artifactId>microprofile-fault-tolerance-api</artifactId>
    <version>3.0</version>
</dependency>
----


[[health]]
== `Health`

[[microprofile-health-api]]
=== *microprofile-health-api*

**Version**: 3.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.health</groupId>
    <artifactId>microprofile-health-api</artifactId>
    <version>3.1</version>
</dependency>
----

[[microprofile-healthcheck]]
=== *microprofile-healthcheck*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-healthcheck</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-healthcheck-backwards-compat]]
=== *microprofile-healthcheck-backwards-compat*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-healthcheck-backwards-compat</artifactId>
    <version>5.74.0</version>
</dependency>
----


[[jwt-propagation]]
== `JWT-Propagation`

[[gson]]
=== *gson*

**Version**: 2.12.1

[source,xml]
----
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.12.1</version>
</dependency>
----

[[jcip-annotations]]
=== *jcip-annotations*

**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----

[[microprofile-jwt-auth]]
=== *microprofile-jwt-auth*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-jwt-auth</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-jwt-auth-api]]
=== *microprofile-jwt-auth-api*

**Version**: 1.2.2

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.jwt</groupId>
    <artifactId>microprofile-jwt-auth-api</artifactId>
    <version>1.2.2</version>
</dependency>
----

[[nimbus-jose-jwt]]
=== *nimbus-jose-jwt*

**Version**: 10.0.2

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>10.0.2</version>
</dependency>
----


[[metrics]]
== `Metrics`

[[microprofile-metrics]]
=== *microprofile-metrics*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-metrics</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-metrics-api]]
=== *microprofile-metrics-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.metrics</groupId>
    <artifactId>microprofile-metrics-api</artifactId>
    <version>3.0.1</version>
</dependency>
----


[[openapi]]
== `OpenAPI`

[[microprofile-openapi]]
=== *microprofile-openapi*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-openapi</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-openapi-api]]
=== *microprofile-openapi-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>2.0.1</version>
</dependency>
----


[[opentracing]]
== `OpenTracing`

[[microprofile-opentracing]]
=== *microprofile-opentracing*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-opentracing</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-opentracing-api]]
=== *microprofile-opentracing-api*

**Version**: 2.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.opentracing</groupId>
    <artifactId>microprofile-opentracing-api</artifactId>
    <version>2.0</version>
</dependency>
----

[[microprofile-opentracing-repackaged]]
=== *microprofile-opentracing-repackaged*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>microprofile-opentracing-repackaged</artifactId>
    <version>5.74.0</version>
</dependency>
----


[[rest-client]]
== `Rest-Client`

[[microprofile-rest-client]]
=== *microprofile-rest-client*

**Version**: 5.74.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-rest-client</artifactId>
    <version>5.74.0</version>
</dependency>
----

[[microprofile-rest-client-api]]
=== *microprofile-rest-client-api*

**Version**: 2.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.rest.client</groupId>
    <artifactId>microprofile-rest-client-api</artifactId>
    <version>2.0</version>
</dependency>
----


