[[jakarta-ee]]
= Jakarta EE Specification Dependencies Mapping
:ordinal: 1

This section details all dependencies linked to Jakarta EE specifications.

[[activation]]
== `activation`

// [[angus-activation]]
=== *angus-activation*

**Version**: 1.1.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-activation</artifactId>
    <version>1.1.0</version>
</dependency>
----

// [[jakarta.activation-api]]
=== *jakarta.activation-api*

**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.1.4</version>
</dependency>
----


[[annotation]]
== `annotation`

// [[annotation-framework]]
=== *annotation-framework*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>annotation-framework</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jackson-annotations]]
=== *jackson-annotations*

**Version**: 2.21

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.21</version>
</dependency>
----

// [[jackson-jr-annotation-support]]
=== *jackson-jr-annotation-support*

**Version**: 2.15.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.jr</groupId>
    <artifactId>jackson-jr-annotation-support</artifactId>
    <version>2.15.2</version>
</dependency>
----

// [[jackson-module-jakarta-xmlbind-annotations]]
=== *jackson-module-jakarta-xmlbind-annotations*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jakarta.annotation-api]]
=== *jakarta.annotation-api*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>2.1.1</version>
</dependency>
----

// [[jcip-annotations]]
=== *jcip-annotations*

**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----

// [[jcip-annotations-repackaged]]
=== *jcip-annotations-repackaged*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jcip-annotations-repackaged</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[authentication]]
== `authentication`

// [[jakarta.authentication-api]]
=== *jakarta.authentication-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.authentication</groupId>
    <artifactId>jakarta.authentication-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[authorization]]
== `authorization`

// [[jacc.provider.inmemory]]
=== *jacc.provider.inmemory*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>jacc.provider.inmemory</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.authorization-api]]
=== *jakarta.authorization-api*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.authorization</groupId>
    <artifactId>jakarta.authorization-api</artifactId>
    <version>2.1.0</version>
</dependency>
----

// [[jaspic-servlet-utils]]
=== *jaspic-servlet-utils*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaspic-servlet-utils</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jaspic.provider.framework]]
=== *jaspic.provider.framework*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>jaspic.provider.framework</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[batch]]
== `batch`

// [[glassfish-batch-commands]]
=== *glassfish-batch-commands*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-commands</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[glassfish-batch-connector]]
=== *glassfish-batch-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.batch-api]]
=== *jakarta.batch-api*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>2.1.1</version>
</dependency>
----

// [[payara-jbatch]]
=== *payara-jbatch*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[concurrency]]
== `concurrency`

// [[concurrent-connector]]
=== *concurrent-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[concurrent-impl]]
=== *concurrent-impl*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[console-concurrent-plugin]]
=== *console-concurrent-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-concurrent-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.enterprise.concurrent]]
=== *jakarta.enterprise.concurrent*

**Version**: 3.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.enterprise.concurrent</artifactId>
    <version>3.0.2.payara-p1</version>
</dependency>
----

// [[jakarta.enterprise.concurrent-api]]
=== *jakarta.enterprise.concurrent-api*

**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>3.0.4</version>
</dependency>
----


[[connectors]]
== `connectors`

// [[connectors-admin]]
=== *connectors-admin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-admin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[connectors-inbound-runtime]]
=== *connectors-inbound-runtime*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-inbound-runtime</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[connectors-internal-api]]
=== *connectors-internal-api*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[connectors-runtime]]
=== *connectors-runtime*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-connectors-connector]]
=== *gf-connectors-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>gf-connectors-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[resources-connector]]
=== *resources-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[resources-runtime]]
=== *resources-runtime*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-runtime</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[security-connectors-api]]
=== *security-connectors-api*

**Version**: 3.1.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>3.1.2</version>
</dependency>
----


[[context-dependency-injection]]
== `context-dependency-injection`

// [[cdi-api-fragment]]
=== *cdi-api-fragment*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cdi-auth-roles]]
=== *cdi-auth-roles*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cdieventbus-notifier-console-plugin]]
=== *cdieventbus-notifier-console-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-weld-connector]]
=== *gf-weld-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[hibernate-validator-cdi]]
=== *hibernate-validator-cdi*

**Version**: 8.0.1.final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>8.0.1.final.payara-p1</version>
</dependency>
----

// [[jakarta.enterprise.cdi-api]]
=== *jakarta.enterprise.cdi-api*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>4.0.1</version>
</dependency>
----

// [[jakarta.inject-api]]
=== *jakarta.inject-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.inject</groupId>
    <artifactId>jakarta.inject-api</artifactId>
    <version>2.0.1</version>
</dependency>
----

// [[jersey-cdi1x]]
=== *jersey-cdi1x*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-cdi1x-servlet]]
=== *jersey-cdi1x-servlet*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-cdi1x-transaction]]
=== *jersey-cdi1x-transaction*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[notification-cdi-eventbus-core]]
=== *notification-cdi-eventbus-core*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[payara-micro-cdi]]
=== *payara-micro-cdi*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[soteria.spi.bean.decorator.weld]]
=== *soteria.spi.bean.decorator.weld*

**Version**: 3.0.3.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>soteria.spi.bean.decorator.weld</artifactId>
    <version>3.0.3.payara-p2</version>
</dependency>
----

// [[tyrus-container-glassfish-cdi]]
=== *tyrus-container-glassfish-cdi*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[weld-api]]
=== *weld-api*

**Version**: 5.0.sp3

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>5.0.sp3</version>
</dependency>
----

// [[weld-core-impl]]
=== *weld-core-impl*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-ejb]]
=== *weld-ejb*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-integration]]
=== *weld-integration*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[weld-integration-fragment]]
=== *weld-integration-fragment*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[weld-jsf]]
=== *weld-jsf*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-jta]]
=== *weld-jta*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-lite-extension-translator]]
=== *weld-lite-extension-translator*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-lite-extension-translator</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-osgi-bundle]]
=== *weld-osgi-bundle*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-spi]]
=== *weld-spi*

**Version**: 5.0.sp3

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>5.0.sp3</version>
</dependency>
----

// [[weld-web]]
=== *weld-web*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>5.1.7.final</version>
</dependency>
----


[[dependency-injection]]
== `dependency-injection`

// [[gf-jms-injection]]
=== *gf-jms-injection*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-weld-connector]]
=== *gf-weld-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.inject-api]]
=== *jakarta.inject-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.inject</groupId>
    <artifactId>jakarta.inject-api</artifactId>
    <version>2.0.1</version>
</dependency>
----

// [[soteria.spi.bean.decorator.weld]]
=== *soteria.spi.bean.decorator.weld*

**Version**: 3.0.3.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>soteria.spi.bean.decorator.weld</artifactId>
    <version>3.0.3.payara-p2</version>
</dependency>
----

// [[weld-api]]
=== *weld-api*

**Version**: 5.0.sp3

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>5.0.sp3</version>
</dependency>
----

// [[weld-core-impl]]
=== *weld-core-impl*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-ejb]]
=== *weld-ejb*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-integration]]
=== *weld-integration*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[weld-integration-fragment]]
=== *weld-integration-fragment*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[weld-jsf]]
=== *weld-jsf*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-jta]]
=== *weld-jta*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-lite-extension-translator]]
=== *weld-lite-extension-translator*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-lite-extension-translator</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-osgi-bundle]]
=== *weld-osgi-bundle*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>5.1.7.final</version>
</dependency>
----

// [[weld-spi]]
=== *weld-spi*

**Version**: 5.0.sp3

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>5.0.sp3</version>
</dependency>
----

// [[weld-web]]
=== *weld-web*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>5.1.7.final</version>
</dependency>
----


[[deployment]]
== `deployment`

// [[deployment-admin]]
=== *deployment-admin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-admin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-autodeploy]]
=== *deployment-autodeploy*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-autodeploy</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-client]]
=== *deployment-client*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-client</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-common]]
=== *deployment-common*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-common</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-javaee-core]]
=== *deployment-javaee-core*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-core</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-javaee-full]]
=== *deployment-javaee-full*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-full</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-transformer-api]]
=== *deployment-transformer-api*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.deployment.transformer</groupId>
    <artifactId>deployment-transformer-api</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[deployment-transformer-impl]]
=== *deployment-transformer-impl*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.deployment.transformer</groupId>
    <artifactId>deployment-transformer-impl</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.enterprise.deploy-api]]
=== *jakarta.enterprise.deploy-api*

**Version**: 1.7.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.deploy</groupId>
    <artifactId>jakarta.enterprise.deploy-api</artifactId>
    <version>1.7.2</version>
</dependency>
----


[[ee-platform]]
== `ee-platform`

// [[jakarta.enterprise.lang-model]]
=== *jakarta.enterprise.lang-model*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.lang-model</artifactId>
    <version>4.0.1</version>
</dependency>
----

// [[jakarta.resource-api]]
=== *jakarta.resource-api*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.resource</groupId>
    <artifactId>jakarta.resource-api</artifactId>
    <version>2.1.0</version>
</dependency>
----

// [[jakartaee-kernel]]
=== *jakartaee-kernel*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>jakartaee-kernel</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[enterprise-beans]]
== `enterprise-beans`

// [[cmp-ejb-mapping]]
=== *cmp-ejb-mapping*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-enhancer]]
=== *cmp-enhancer*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-enhancer</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-generator-database]]
=== *cmp-generator-database*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-generator-database</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-internal-api]]
=== *cmp-internal-api*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-internal-api</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-model]]
=== *cmp-model*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-model</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-support-ejb]]
=== *cmp-support-ejb*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-support-sqlstore]]
=== *cmp-support-sqlstore*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-sqlstore</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[cmp-utility]]
=== *cmp-utility*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-utility</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[console-ejb-lite-plugin]]
=== *console-ejb-lite-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-lite-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[console-ejb-plugin]]
=== *console-ejb-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-client]]
=== *ejb-client*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-client</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-container]]
=== *ejb-container*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-container</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-full-container]]
=== *ejb-full-container*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-full-container</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-http-admin]]
=== *ejb-http-admin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-http-admin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-internal-api]]
=== *ejb-internal-api*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-internal-api</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb-opentracing]]
=== *ejb-opentracing*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-opentracing</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb.security]]
=== *ejb.security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[entitybean-container]]
=== *entitybean-container*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>entitybean-container</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-ejb-connector]]
=== *gf-ejb-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>gf-ejb-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[hazelcast-ejb-timer]]
=== *hazelcast-ejb-timer*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-ejb-timer</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.ejb-api]]
=== *jakarta.ejb-api*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>4.0.1</version>
</dependency>
----

// [[jersey-gf-ejb]]
=== *jersey-gf-ejb*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[schema2beans]]
=== *schema2beans*

**Version**: 6.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>schema2beans</artifactId>
    <version>6.7</version>
</dependency>
----

// [[tyrus-container-glassfish-ejb]]
=== *tyrus-container-glassfish-ejb*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[weld-ejb]]
=== *weld-ejb*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>5.1.7.final</version>
</dependency>
----


[[expression-language]]
== `expression-language`

// [[expressly]]
=== *expressly*

**Version**: 5.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.expressly</groupId>
    <artifactId>expressly</artifactId>
    <version>5.0.0</version>
</dependency>
----

// [[jakarta.el-api]]
=== *jakarta.el-api*

**Version**: 5.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.el</groupId>
    <artifactId>jakarta.el-api</artifactId>
    <version>5.0.1</version>
</dependency>
----


[[faces]]
== `faces`

// [[faces-compat]]
=== *faces-compat*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>faces-compat</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.faces]]
=== *jakarta.faces*

**Version**: 3.0.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>3.0.5</version>
</dependency>
----

// [[jsf-connector]]
=== *jsf-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jsft]]
=== *jsft*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jsftemplating</groupId>
    <artifactId>jsft</artifactId>
    <version>3.0.0</version>
</dependency>
----

// [[jsftemplating]]
=== *jsftemplating*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jsftemplating</groupId>
    <artifactId>jsftemplating</artifactId>
    <version>3.0.0</version>
</dependency>
----

// [[jsftemplating-dt]]
=== *jsftemplating-dt*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jsftemplating</groupId>
    <artifactId>jsftemplating-dt</artifactId>
    <version>3.0.0</version>
</dependency>
----

// [[weld-jsf]]
=== *weld-jsf*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>5.1.7.final</version>
</dependency>
----


[[interceptors]]
== `interceptors`

// [[jakarta.interceptor-api]]
=== *jakarta.interceptor-api*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.interceptor</groupId>
    <artifactId>jakarta.interceptor-api</artifactId>
    <version>2.1.0</version>
</dependency>
----


[[json-binding]]
== `json-binding`

// [[jakarta.json.bind-api]]
=== *jakarta.json.bind-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.json.bind</groupId>
    <artifactId>jakarta.json.bind-api</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jersey-media-json-binding]]
=== *jersey-media-json-binding*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[yasson]]
=== *yasson*

**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.4</version>
</dependency>
----


[[json-processing]]
== `json-processing`

// [[everit-json-schema]]
=== *everit-json-schema*

**Version**: 1.14.3

[source,xml]
----
<dependency>
    <groupId>com.github.erosb</groupId>
    <artifactId>everit-json-schema</artifactId>
    <version>1.14.3</version>
</dependency>
----

// [[jackson-annotations]]
=== *jackson-annotations*

**Version**: 2.21

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.21</version>
</dependency>
----

// [[jackson-core]]
=== *jackson-core*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-databind]]
=== *jackson-databind*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-dataformat-toml]]
=== *jackson-dataformat-toml*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-toml</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-dataformat-xml]]
=== *jackson-dataformat-xml*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-dataformat-yaml]]
=== *jackson-dataformat-yaml*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-jr-annotation-support]]
=== *jackson-jr-annotation-support*

**Version**: 2.15.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.jr</groupId>
    <artifactId>jackson-jr-annotation-support</artifactId>
    <version>2.15.2</version>
</dependency>
----

// [[jackson-jr-objects]]
=== *jackson-jr-objects*

**Version**: 2.15.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.jr</groupId>
    <artifactId>jackson-jr-objects</artifactId>
    <version>2.15.2</version>
</dependency>
----

// [[jackson-module-jakarta-xmlbind-annotations]]
=== *jackson-module-jakarta-xmlbind-annotations*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jakarta.json]]
=== *jakarta.json*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>jakarta.json</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----

// [[jakarta.json-api]]
=== *jakarta.json-api*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.json</groupId>
    <artifactId>jakarta.json-api</artifactId>
    <version>2.1.0</version>
</dependency>
----

// [[jakarta.json.bind-api]]
=== *jakarta.json.bind-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.json.bind</groupId>
    <artifactId>jakarta.json.bind-api</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jersey-media-json-binding]]
=== *jersey-media-json-binding*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-json-jackson]]
=== *jersey-media-json-jackson*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-json-processing]]
=== *jersey-media-json-processing*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[json]]
=== *json*

**Version**: 20231013

[source,xml]
----
<dependency>
    <groupId>org.json</groupId>
    <artifactId>json</artifactId>
    <version>20231013</version>
</dependency>
----

// [[json-smart]]
=== *json-smart*

**Version**: 2.6.0

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.6.0</version>
</dependency>
----

// [[parsson]]
=== *parsson*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>parsson</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----

// [[parsson-media]]
=== *parsson-media*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>parsson-media</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----


[[mail]]
== `mail`

// [[angus-activation]]
=== *angus-activation*

**Version**: 1.1.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-activation</artifactId>
    <version>1.1.0</version>
</dependency>
----

// [[angus-core]]
=== *angus-core*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-core</artifactId>
    <version>2.0.5</version>
</dependency>
----

// [[angus-mail]]
=== *angus-mail*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>2.0.5</version>
</dependency>
----

// [[email-notifier-console-plugin]]
=== *email-notifier-console-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-console-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[email-notifier-core]]
=== *email-notifier-core*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-core</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[imap]]
=== *imap*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>imap</artifactId>
    <version>2.0.5</version>
</dependency>
----

// [[jakarta.mail-api]]
=== *jakarta.mail-api*

**Version**: 2.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta.mail</groupId>
    <artifactId>jakarta.mail-api</artifactId>
    <version>2.1.5</version>
</dependency>
----

// [[javamail-connector]]
=== *javamail-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[javamail-runtime]]
=== *javamail-runtime*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-runtime</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[logging-mailhandler]]
=== *logging-mailhandler*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>logging-mailhandler</artifactId>
    <version>2.0.5</version>
</dependency>
----

// [[pop3]]
=== *pop3*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>pop3</artifactId>
    <version>2.0.5</version>
</dependency>
----

// [[smtp]]
=== *smtp*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>smtp</artifactId>
    <version>2.0.5</version>
</dependency>
----


[[management]]
== `management`

// [[certificate-management-admin]]
=== *certificate-management-admin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-admin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[certificate-management-common]]
=== *certificate-management-common*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-common</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[certificate-management-console-plugin]]
=== *certificate-management-console-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-console-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jmx-monitoring]]
=== *jmx-monitoring*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jmx-monitoring</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jmx-monitoring-plugin]]
=== *jmx-monitoring-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jmx-monitoring-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jmxremote_optional-repackaged]]
=== *jmxremote_optional-repackaged*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmxremote_optional-repackaged</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[management-api]]
=== *management-api*

**Version**: 3.3.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.3.0.payara-p1</version>
</dependency>
----

// [[work-management]]
=== *work-management*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>work-management</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[messaging]]
== `messaging`

// [[console-jms-plugin]]
=== *console-jms-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jms-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-jms-connector]]
=== *gf-jms-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[gf-jms-injection]]
=== *gf-jms-injection*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.jms-api]]
=== *jakarta.jms-api*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>3.1.0</version>
</dependency>
----

// [[jms-admin]]
=== *jms-admin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-admin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jms-core]]
=== *jms-core*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-core</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jms-handlers]]
=== *jms-handlers*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-handlers</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jms-notifier-console-plugin]]
=== *jms-notifier-console-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jms-notifier-console-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[notification-jms-core]]
=== *notification-jms-core*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>notification-jms-core</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[pages]]
== `pages`

// [[jakarta.servlet.jsp-api]]
=== *jakarta.servlet.jsp-api*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>3.1.1</version>
</dependency>
----

// [[jakarta.servlet.jsp.jstl]]
=== *jakarta.servlet.jsp.jstl*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>jakarta.servlet.jsp.jstl</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jakarta.servlet.jsp.jstl-api]]
=== *jakarta.servlet.jsp.jstl-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>3.0.2</version>
</dependency>
----

// [[jersey-mvc-jsp]]
=== *jersey-mvc-jsp*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jspcaching-connector]]
=== *jspcaching-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jspcaching-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[persistence]]
== `persistence`

// [[gf-jpa-connector]]
=== *gf-jpa-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>gf-jpa-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[hazelcast-eclipselink-coordination]]
=== *hazelcast-eclipselink-coordination*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.persistence-api]]
=== *jakarta.persistence-api*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.persistence</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>3.1.0</version>
</dependency>
----

// [[jpa-container]]
=== *jpa-container*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>jpa-container</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[org.eclipse.persistence.asm]]
=== *org.eclipse.persistence.asm*

**Version**: 9.9.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.9.0</version>
</dependency>
----

// [[org.eclipse.persistence.core]]
=== *org.eclipse.persistence.core*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.core</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.dbws]]
=== *org.eclipse.persistence.dbws*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.jpa]]
=== *org.eclipse.persistence.jpa*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.jpa.jpql]]
=== *org.eclipse.persistence.jpa.jpql*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.jpa.modelgen.processor]]
=== *org.eclipse.persistence.jpa.modelgen.processor*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.moxy]]
=== *org.eclipse.persistence.moxy*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.moxy</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[org.eclipse.persistence.oracle]]
=== *org.eclipse.persistence.oracle*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.oracle</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[persistence-common]]
=== *persistence-common*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>persistence-common</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[restful-webservices]]
== `restful-webservices`

// [[jaxrs-client-tracing]]
=== *jaxrs-client-tracing*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaxrs-client-tracing</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jersey-bean-validation]]
=== *jersey-bean-validation*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-cdi1x]]
=== *jersey-cdi1x*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-cdi1x-servlet]]
=== *jersey-cdi1x-servlet*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-cdi1x-transaction]]
=== *jersey-cdi1x-transaction*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-client]]
=== *jersey-client*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-common]]
=== *jersey-common*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-container-grizzly2-http]]
=== *jersey-container-grizzly2-http*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-grizzly2-http</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-container-servlet]]
=== *jersey-container-servlet*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-container-servlet-core]]
=== *jersey-container-servlet-core*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-entity-filtering]]
=== *jersey-entity-filtering*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-entity-filtering</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-gf-ejb]]
=== *jersey-gf-ejb*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-hk2]]
=== *jersey-hk2*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-jaxb]]
=== *jersey-media-jaxb*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-json-binding]]
=== *jersey-media-json-binding*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-json-jackson]]
=== *jersey-media-json-jackson*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-json-processing]]
=== *jersey-media-json-processing*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-moxy]]
=== *jersey-media-moxy*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-multipart]]
=== *jersey-media-multipart*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-media-sse]]
=== *jersey-media-sse*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-mp-rest-client]]
=== *jersey-mp-rest-client*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
    <artifactId>jersey-mp-rest-client</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-mvc]]
=== *jersey-mvc*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-mvc-connector]]
=== *jersey-mvc-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jersey-mvc-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jersey-mvc-jsp]]
=== *jersey-mvc-jsp*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-proxy-client]]
=== *jersey-proxy-client*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-proxy-client</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-server]]
=== *jersey-server*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-server</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[krazo-jersey]]
=== *krazo-jersey*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-jersey</artifactId>
    <version>3.0.1</version>
</dependency>
----


[[security]]
== `security`

// [[appclient.security]]
=== *appclient.security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>appclient.security</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ejb.security]]
=== *ejb.security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[exousia]]
=== *exousia*

**Version**: 2.1.3

[source,xml]
----
<dependency>
    <groupId>org.glassfish.exousia</groupId>
    <artifactId>exousia</artifactId>
    <version>2.1.3</version>
</dependency>
----

// [[gson]]
=== *gson*

**Version**: 2.10.1

[source,xml]
----
<dependency>
    <groupId>com.google.code.gson</groupId>
    <artifactId>gson</artifactId>
    <version>2.10.1</version>
</dependency>
----

// [[jakarta.security.enterprise]]
=== *jakarta.security.enterprise*

**Version**: 3.0.3.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>jakarta.security.enterprise</artifactId>
    <version>3.0.3.payara-p2</version>
</dependency>
----

// [[jakarta.security.enterprise-api]]
=== *jakarta.security.enterprise-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.security.enterprise</groupId>
    <artifactId>jakarta.security.enterprise-api</artifactId>
    <version>3.0.0</version>
</dependency>
----

// [[jcip-annotations]]
=== *jcip-annotations*

**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----

// [[nimbus-jose-jwt]]
=== *nimbus-jose-jwt*

**Version**: 9.39.1

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>9.39.1</version>
</dependency>
----

// [[security]]
=== *security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[security-connector-oauth2-client]]
=== *security-connector-oauth2-client*

**Version**: 3.1.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>3.1.2</version>
</dependency>
----

// [[security-connector-oidc-client]]
=== *security-connector-oidc-client*

**Version**: 3.1.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>3.1.2</version>
</dependency>
----

// [[security-connectors-api]]
=== *security-connectors-api*

**Version**: 3.1.2

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>3.1.2</version>
</dependency>
----

// [[security-ee]]
=== *security-ee*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-ee</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[security-services]]
=== *security-services*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-services</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[soteria.spi.bean.decorator.weld]]
=== *soteria.spi.bean.decorator.weld*

**Version**: 3.0.3.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>soteria.spi.bean.decorator.weld</artifactId>
    <version>3.0.3.payara-p2</version>
</dependency>
----

// [[websecurity]]
=== *websecurity*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>websecurity</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[webservices.security]]
=== *webservices.security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[servlet]]
== `servlet`

// [[httpspi-servlet]]
=== *httpspi-servlet*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>httpspi-servlet</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[jakarta.servlet-api]]
=== *jakarta.servlet-api*

**Version**: 6.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>6.0.0</version>
</dependency>
----

// [[jakarta.servlet.jsp-api]]
=== *jakarta.servlet.jsp-api*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>3.1.1</version>
</dependency>
----

// [[jakarta.servlet.jsp.jstl]]
=== *jakarta.servlet.jsp.jstl*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>jakarta.servlet.jsp.jstl</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jakarta.servlet.jsp.jstl-api]]
=== *jakarta.servlet.jsp.jstl-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>3.0.2</version>
</dependency>
----

// [[jaspic-servlet-utils]]
=== *jaspic-servlet-utils*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaspic-servlet-utils</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jersey-cdi1x-servlet]]
=== *jersey-cdi1x-servlet*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-container-servlet]]
=== *jersey-container-servlet*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jersey-container-servlet-core]]
=== *jersey-container-servlet-core*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[servlet]]
=== *servlet*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>servlet</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[tyrus-container-servlet]]
=== *tyrus-container-servlet*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----


[[standard-tag-library]]
== `standard-tag-library`

// [[jakarta.servlet.jsp.jstl]]
=== *jakarta.servlet.jsp.jstl*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>jakarta.servlet.jsp.jstl</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jakarta.servlet.jsp.jstl-api]]
=== *jakarta.servlet.jsp.jstl-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>3.0.2</version>
</dependency>
----

// [[jstl-connector]]
=== *jstl-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jstl-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----


[[transaction]]
== `transaction`

// [[console-jts-plugin]]
=== *console-jts-plugin*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jts-plugin</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jakarta.transaction-api]]
=== *jakarta.transaction-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>2.0.1</version>
</dependency>
----

// [[jersey-cdi1x-transaction]]
=== *jersey-cdi1x-transaction*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[jta]]
=== *jta*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jta</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[jts]]
=== *jts*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jts</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[transaction-internal-api]]
=== *transaction-internal-api*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[weld-jta]]
=== *weld-jta*

**Version**: 5.1.7.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>5.1.7.final</version>
</dependency>
----


[[validation]]
== `validation`

// [[hibernate-validator]]
=== *hibernate-validator*

**Version**: 8.0.1.final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>8.0.1.final.payara-p1</version>
</dependency>
----

// [[hibernate-validator-cdi]]
=== *hibernate-validator-cdi*

**Version**: 8.0.1.final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>8.0.1.final.payara-p1</version>
</dependency>
----

// [[jakarta.validation-api]]
=== *jakarta.validation-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>3.0.2</version>
</dependency>
----

// [[jersey-bean-validation]]
=== *jersey-bean-validation*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----


[[webservices]]
== `webservices`

// [[httpspi-servlet]]
=== *httpspi-servlet*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>httpspi-servlet</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[jakarta.jws-api]]
=== *jakarta.jws-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.jws</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>3.0.0</version>
</dependency>
----

// [[jakarta.ws.rs-api]]
=== *jakarta.ws.rs-api*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>3.1.0</version>
</dependency>
----

// [[jakarta.xml.bind-api]]
=== *jakarta.xml.bind-api*

**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.4</version>
</dependency>
----

// [[jakarta.xml.soap-api]]
=== *jakarta.xml.soap-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.soap</groupId>
    <artifactId>jakarta.xml.soap-api</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jakarta.xml.ws-api]]
=== *jakarta.xml.ws-api*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[jaxws-rt]]
=== *jaxws-rt*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>jaxws-rt</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[jaxws-tools]]
=== *jaxws-tools*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>jaxws-tools</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[jsr109-impl]]
=== *jsr109-impl*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>jsr109-impl</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[metro-cm-api]]
=== *metro-cm-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-cm-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-cm-impl]]
=== *metro-cm-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-cm-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-commons]]
=== *metro-commons*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-commons</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-config-api]]
=== *metro-config-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-config-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-config-impl]]
=== *metro-config-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-config-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-glue]]
=== *metro-glue*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>metro-glue</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[metro-runtime-api]]
=== *metro-runtime-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-runtime-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[metro-runtime-impl]]
=== *metro-runtime-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>metro-runtime-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[opentracing-jaxws]]
=== *opentracing-jaxws*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[org.eclipse.persistence.dbws]]
=== *org.eclipse.persistence.dbws*

**Version**: 4.0.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>4.0.7.payara-p1</version>
</dependency>
----

// [[policy]]
=== *policy*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>policy</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[rt]]
=== *rt*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>rt</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[rt-fi]]
=== *rt-fi*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>rt-fi</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[saaj-impl]]
=== *saaj-impl*

**Version**: 3.0.3

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.messaging.saaj</groupId>
    <artifactId>saaj-impl</artifactId>
    <version>3.0.3</version>
</dependency>
----

// [[servlet]]
=== *servlet*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>servlet</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[soap-tcp]]
=== *soap-tcp*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>soap-tcp</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[soaptcp-api]]
=== *soaptcp-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>soaptcp-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[soaptcp-impl]]
=== *soaptcp-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>soaptcp-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[stax2-api]]
=== *stax2-api*

**Version**: 4.2.2

[source,xml]
----
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.2</version>
</dependency>
----

// [[streambuffer]]
=== *streambuffer*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.stream.buffer</groupId>
    <artifactId>streambuffer</artifactId>
    <version>2.1.0</version>
</dependency>
----

// [[webservices-api-osgi]]
=== *webservices-api-osgi*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-api-osgi</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[webservices-connector]]
=== *webservices-connector*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-connector</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[webservices-extra-jdk-packages]]
=== *webservices-extra-jdk-packages*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-extra-jdk-packages</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[webservices-osgi]]
=== *webservices-osgi*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-osgi</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[webservices.security]]
=== *webservices.security*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[ws-mex]]
=== *ws-mex*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>ws-mex</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wscompile]]
=== *wscompile*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.ws</groupId>
    <artifactId>wscompile</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[wsit-api]]
=== *wsit-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsit-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsit-impl]]
=== *wsit-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsit-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsmc-api]]
=== *wsmc-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsmc-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsmc-impl]]
=== *wsmc-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsmc-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsrm-api]]
=== *wsrm-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsrm-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsrm-impl]]
=== *wsrm-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsrm-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsrx-commons]]
=== *wsrx-commons*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsrx-commons</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wsrx-testing]]
=== *wsrx-testing*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wsrx-testing</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wssx-api]]
=== *wssx-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wssx-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wssx-impl]]
=== *wssx-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wssx-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wstx-api]]
=== *wstx-api*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wstx-api</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[wstx-impl]]
=== *wstx-impl*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wstx-impl</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[xmlfilter]]
=== *xmlfilter*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>xmlfilter</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----


[[websocket]]
== `websocket`

// [[jakarta.websocket-api]]
=== *jakarta.websocket-api*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>2.1.1</version>
</dependency>
----

// [[jakarta.websocket-client-api]]
=== *jakarta.websocket-client-api*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-client-api</artifactId>
    <version>2.1.1</version>
</dependency>
----

// [[tyrus-client]]
=== *tyrus-client*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-client</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-container-glassfish-cdi]]
=== *tyrus-container-glassfish-cdi*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-container-glassfish-ejb]]
=== *tyrus-container-glassfish-ejb*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-container-grizzly-client]]
=== *tyrus-container-grizzly-client*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-grizzly-client</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-container-servlet]]
=== *tyrus-container-servlet*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-core]]
=== *tyrus-core*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-core</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-server]]
=== *tyrus-server*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-server</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----

// [[tyrus-spi]]
=== *tyrus-spi*

**Version**: 2.1.5.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-spi</artifactId>
    <version>2.1.5.payara-p2</version>
</dependency>
----


[[xml-binding]]
== `xml-binding`

// [[codemodel]]
=== *codemodel*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>codemodel</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[dtd-parser]]
=== *dtd-parser*

**Version**: 1.5.1

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.dtd-parser</groupId>
    <artifactId>dtd-parser</artifactId>
    <version>1.5.1</version>
</dependency>
----

// [[fastinfoset]]
=== *fastinfoset*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.fastinfoset</groupId>
    <artifactId>fastinfoset</artifactId>
    <version>2.1.1</version>
</dependency>
----

// [[isorelax]]
=== *isorelax*

**Version**: 20090621

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.jaxb</groupId>
    <artifactId>isorelax</artifactId>
    <version>20090621</version>
</dependency>
----

// [[istack-commons-runtime]]
=== *istack-commons-runtime*

**Version**: 4.2.0

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>4.2.0</version>
</dependency>
----

// [[istack-commons-tools]]
=== *istack-commons-tools*

**Version**: 4.1.2

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-tools</artifactId>
    <version>4.1.2</version>
</dependency>
----

// [[jackson-dataformat-xml]]
=== *jackson-dataformat-xml*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-module-jakarta-xmlbind-annotations]]
=== *jackson-module-jakarta-xmlbind-annotations*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jakarta.xml.bind-api]]
=== *jakarta.xml.bind-api*

**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.4</version>
</dependency>
----

// [[jaxb-core]]
=== *jaxb-core*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[jaxb-jxc]]
=== *jaxb-jxc*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-jxc</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[jaxb-osgi]]
=== *jaxb-osgi*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-osgi</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[jaxb-runtime]]
=== *jaxb-runtime*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[jaxb-xjc]]
=== *jaxb-xjc*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-xjc</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[jersey-media-jaxb]]
=== *jersey-media-jaxb*

**Version**: 3.1.11.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>3.1.11.payara-p2</version>
</dependency>
----

// [[relaxng-datatype]]
=== *relaxng-datatype*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>relaxng-datatype</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[rngom]]
=== *rngom*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>rngom</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[stax-ex]]
=== *stax-ex*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>org.jvnet.staxex</groupId>
    <artifactId>stax-ex</artifactId>
    <version>2.1.0</version>
</dependency>
----

// [[txw2]]
=== *txw2*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>txw2</artifactId>
    <version>4.0.6</version>
</dependency>
----

// [[xsom]]
=== *xsom*

**Version**: 4.0.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>xsom</artifactId>
    <version>4.0.6</version>
</dependency>
----


[[xml-rpc]]
== `xml-rpc`

// [[jackson-dataformat-xml]]
=== *jackson-dataformat-xml*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jackson-module-jakarta-xmlbind-annotations]]
=== *jackson-module-jakarta-xmlbind-annotations*

**Version**: 2.21.2

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.21.2</version>
</dependency>
----

// [[jakarta.xml.bind-api]]
=== *jakarta.xml.bind-api*

**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.4</version>
</dependency>
----

// [[jakarta.xml.soap-api]]
=== *jakarta.xml.soap-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.soap</groupId>
    <artifactId>jakarta.xml.soap-api</artifactId>
    <version>3.0.1</version>
</dependency>
----

// [[jakarta.xml.ws-api]]
=== *jakarta.xml.ws-api*

**Version**: 4.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>4.0.2</version>
</dependency>
----

// [[metro-xmlsec-repackaged]]
=== *metro-xmlsec-repackaged*

**Version**: 6.38.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>metro-xmlsec-repackaged</artifactId>
    <version>6.38.0</version>
</dependency>
----

// [[xmlfilter]]
=== *xmlfilter*

**Version**: 4.0.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>xmlfilter</artifactId>
    <version>4.0.3.payara-p1</version>
</dependency>
----

// [[xmlsec]]
=== *xmlsec*

**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>org.apache.santuario</groupId>
    <artifactId>xmlsec</artifactId>
    <version>4.0.4</version>
</dependency>
----


