[[jakarta-ee]]
= Jakarta EE Specification Dependencies Mapping

This section details all dependencies linked to Jakarta EE specifications.

[[annotation]]
=== `annotation`

[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[annotation-framework]]
==== *annotation-framework*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>annotation-framework</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jcip-annotations-repackaged]]
==== *jcip-annotations-repackaged*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jcip-annotations-repackaged</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jcip-annotations]]
==== *jcip-annotations*
**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----
[[jackson-annotations]]
==== *jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[jakarta.annotation-api]]
==== *jakarta.annotation-api*
**Version**: 1.3.5

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>1.3.5</version>
</dependency>
----
[[authentication]]
=== `authentication`

[[yubikey-authentication]]
==== *yubikey-authentication*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>yubikey-authentication</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[authorization]]
=== `authorization`

[[batch]]
=== `batch`

[[glassfish-batch-connector]]
==== *glassfish-batch-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[glassfish-batch-commands]]
==== *glassfish-batch-commands*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-commands</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[payara-jbatch]]
==== *payara-jbatch*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[payara-jbatch]]
==== *payara-jbatch*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.batch-api]]
==== *jakarta.batch-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[jakarta.batch-api]]
==== *jakarta.batch-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[validation]]
=== `validation`

[[yubico-validation-client2]]
==== *yubico-validation-client2*
**Version**: 3.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>com.yubico</groupId>
    <artifactId>yubico-validation-client2</artifactId>
    <version>3.0.2.payara-p1</version>
</dependency>
----
[[hibernate-validator]]
==== *hibernate-validator*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jakarta.validation-api]]
==== *jakarta.validation-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[concurrency]]
=== `concurrency`

[[concurrent-impl]]
==== *concurrent-impl*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[concurrent-impl]]
==== *concurrent-impl*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[concurrent-connector]]
==== *concurrent-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[javax.enterprise.concurrent]]
==== *javax.enterprise.concurrent*
**Version**: 1.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.enterprise.concurrent</artifactId>
    <version>1.1.payara-p1</version>
</dependency>
----
[[jakarta.enterprise.concurrent-api]]
==== *jakarta.enterprise.concurrent-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[jakarta.enterprise.concurrent-api]]
==== *jakarta.enterprise.concurrent-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[console-concurrent-plugin]]
==== *console-concurrent-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-concurrent-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors]]
=== `connectors`

[[connectors-inbound-runtime]]
==== *connectors-inbound-runtime*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-inbound-runtime</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors-admin]]
==== *connectors-admin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-admin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors-internal-api]]
==== *connectors-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors-internal-api]]
==== *connectors-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors-runtime]]
==== *connectors-runtime*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[connectors-runtime]]
==== *connectors-runtime*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[gf-connectors-connector]]
==== *gf-connectors-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>gf-connectors-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[security-connectors-api]]
==== *security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[contextdependencyinjection]]
=== `contextdependencyinjection`

[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[gf-weld-connector]]
==== *gf-weld-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[cdi-eventbus-notifier-backwards-compatibility]]
==== *cdi-eventbus-notifier-backwards-compatibility*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>cdi-eventbus-notifier-backwards-compatibility</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-integration]]
==== *weld-integration*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-web]]
==== *weld-web*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-probe-core]]
==== *weld-probe-core*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.probe</groupId>
    <artifactId>weld-probe-core</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-api]]
==== *weld-api*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-core-impl]]
==== *weld-core-impl*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-osgi-bundle]]
==== *weld-osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-spi]]
==== *weld-spi*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-integration-fragment]]
==== *weld-integration-fragment*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[debugging]]
=== `debugging`

[[dependencyinjection]]
=== `dependencyinjection`

[[jakarta.enterprise.cdi-api]]
==== *jakarta.enterprise.cdi-api*
**Version**: 2.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>2.0.2</version>
</dependency>
----
[[asadmin-audit]]
==== *asadmin-audit*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>asadmin-audit</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-media-multipart]]
==== *jersey-media-multipart*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[gf-jms-injection]]
==== *gf-jms-injection*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[payara-micro-cdi]]
==== *payara-micro-cdi*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[cdi-api-fragment]]
==== *cdi-api-fragment*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.inject]]
==== *jakarta.inject*
**Version**: 2.6.1.payara-p8

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2.external</groupId>
    <artifactId>jakarta.inject</artifactId>
    <version>2.6.1.payara-p8</version>
</dependency>
----
[[jersey-media-moxy]]
==== *jersey-media-moxy*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[gf-weld-connector]]
==== *gf-weld-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[hibernate-validator-cdi]]
==== *hibernate-validator-cdi*
**Version**: 6.2.5.final

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>6.2.5.final</version>
</dependency>
----
[[cdi-eventbus-notifier-backwards-compatibility]]
==== *cdi-eventbus-notifier-backwards-compatibility*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>cdi-eventbus-notifier-backwards-compatibility</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-sse]]
==== *jersey-media-sse*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[discord-notifier-core]]
==== *discord-notifier-core*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>discord-notifier-core</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[discord-notifier-console-plugin]]
==== *discord-notifier-console-plugin*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>discord-notifier-console-plugin</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[cdi-auth-roles]]
==== *cdi-auth-roles*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[console-payara-enterprise-branding-plugin]]
==== *console-payara-enterprise-branding-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-payara-enterprise-branding-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cdieventbus-notifier-console-plugin]]
==== *cdieventbus-notifier-console-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[hazelcast-eclipselink-coordination]]
==== *hazelcast-eclipselink-coordination*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[opentracing-cdi]]
==== *opentracing-cdi*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-cdi</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-integration]]
==== *weld-integration*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[admin-audit-notifiers-backwards-compatibility]]
==== *admin-audit-notifiers-backwards-compatibility*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>admin-audit-notifiers-backwards-compatibility</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[notification-cdi-eventbus-core]]
==== *notification-cdi-eventbus-core*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-web]]
==== *weld-web*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-probe-core]]
==== *weld-probe-core*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.probe</groupId>
    <artifactId>weld-probe-core</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-api]]
==== *weld-api*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-core-impl]]
==== *weld-core-impl*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-osgi-bundle]]
==== *weld-osgi-bundle*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[weld-spi]]
==== *weld-spi*
**Version**: 3.1.sp4

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>3.1.sp4</version>
</dependency>
----
[[weld-integration-fragment]]
==== *weld-integration-fragment*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment]]
=== `deployment`

[[deployment-javaee-full]]
==== *deployment-javaee-full*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-full</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment-javaee-core]]
==== *deployment-javaee-core*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-core</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment-admin]]
==== *deployment-admin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-admin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment-client]]
==== *deployment-client*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-client</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment-common]]
==== *deployment-common*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-common</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[deployment-autodeploy]]
==== *deployment-autodeploy*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-autodeploy</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[eeplatform]]
=== `eeplatform`

[[enterprisebeans]]
=== `enterprisebeans`

[[ejb-full-container]]
==== *ejb-full-container*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-full-container</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-utility]]
==== *cmp-utility*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-utility</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-support-sqlstore]]
==== *cmp-support-sqlstore*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-sqlstore</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-generator-database]]
==== *cmp-generator-database*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-generator-database</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-model]]
==== *cmp-model*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-model</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[entitybean-container]]
==== *entitybean-container*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>entitybean-container</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[tyrus-container-glassfish-ejb]]
==== *tyrus-container-glassfish-ejb*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[console-ejb-plugin]]
==== *console-ejb-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[ejb-client]]
==== *ejb-client*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-client</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-internal-api]]
==== *cmp-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[ejb-http-admin]]
==== *ejb-http-admin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-http-admin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-gf-ejb]]
==== *jersey-gf-ejb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[ejb-opentracing]]
==== *ejb-opentracing*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-opentracing</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[hazelcast-ejb-timer]]
==== *hazelcast-ejb-timer*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-ejb-timer</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[jakarta.ejb-api]]
==== *jakarta.ejb-api*
**Version**: 3.2.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>3.2.6</version>
</dependency>
----
[[gf-ejb-connector]]
==== *gf-ejb-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>gf-ejb-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[ejb.security]]
==== *ejb.security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[console-ejb-lite-plugin]]
==== *console-ejb-lite-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-lite-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[ejb-container]]
==== *ejb-container*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-container</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-enhancer]]
==== *cmp-enhancer*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-enhancer</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-ejb]]
==== *weld-ejb*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[ejb-internal-api]]
==== *ejb-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[expressionlanguage]]
=== `expressionlanguage`

[[jakarta.el]]
==== *jakarta.el*
**Version**: 3.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.el</artifactId>
    <version>3.0.4.payara-p1</version>
</dependency>
----
[[interceptors]]
=== `interceptors`

[[jsonbinding]]
=== `jsonbinding`

[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonprocessing]]
=== `jsonprocessing`

[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jackson-databind]]
==== *jackson-databind*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[jackson-annotations]]
==== *jackson-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-dataformat-yaml]]
==== *jackson-dataformat-yaml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-core]]
==== *jackson-core*
**Version**: 2.12.1

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.12.1</version>
</dependency>
----
[[mail]]
=== `mail`

[[email-notifier-core]]
==== *email-notifier-core*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-core</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[email-notifier-console-plugin]]
==== *email-notifier-console-plugin*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-console-plugin</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[email-notifier-backwards-compatibility]]
==== *email-notifier-backwards-compatibility*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-backwards-compatibility</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[javamail-runtime]]
==== *javamail-runtime*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-runtime</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.mail]]
==== *jakarta.mail*
**Version**: 1.6.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>com.sun.mail</groupId>
    <artifactId>jakarta.mail</artifactId>
    <version>1.6.7.payara-p1</version>
</dependency>
----
[[javamail-connector]]
==== *javamail-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[managedbeans]]
=== `managedbeans`

[[jsf-connector]]
==== *jsf-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jsft]]
==== *jsft*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsft</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[jsftemplating]]
==== *jsftemplating*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsftemplating</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[management]]
=== `management`

[[jmx-monitoring-plugin]]
==== *jmx-monitoring-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jmx-monitoring-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[certificate-management-admin]]
==== *certificate-management-admin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extras.certificate-management</groupId>
    <artifactId>certificate-management-admin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jmx-monitoring]]
==== *jmx-monitoring*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jmx-monitoring</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[certificate-management-common]]
==== *certificate-management-common*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extras.certificate-management</groupId>
    <artifactId>certificate-management-common</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.management.j2ee-api]]
==== *jakarta.management.j2ee-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.management.j2ee</groupId>
    <artifactId>jakarta.management.j2ee-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[work-management]]
==== *work-management*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>work-management</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[management-api]]
==== *management-api*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[management-api]]
==== *management-api*
**Version**: 3.2.3.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.2.3.payara-p1</version>
</dependency>
----
[[jmxremote_optional-repackaged]]
==== *jmxremote_optional-repackaged*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmxremote_optional-repackaged</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[certificate-management-console-plugin]]
==== *certificate-management-console-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extras.certificate-management</groupId>
    <artifactId>certificate-management-console-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[messaging]]
=== `messaging`

[[jms-handlers]]
==== *jms-handlers*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-handlers</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[gf-jms-connector]]
==== *gf-jms-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[gf-jms-injection]]
==== *gf-jms-injection*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[console-jms-plugin]]
==== *console-jms-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jms-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[jakarta.jms-api]]
==== *jakarta.jms-api*
**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>2.0.3</version>
</dependency>
----
[[jms-notifier-backwards-compatibility]]
==== *jms-notifier-backwards-compatibility*
**Version**: 1.0.1-enterprise

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>jms-notifier-backwards-compatibility</artifactId>
    <version>1.0.1-enterprise</version>
</dependency>
----
[[notification-jms-core]]
==== *notification-jms-core*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>notification-jms-core</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jms-admin]]
==== *jms-admin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-admin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jms-core]]
==== *jms-core*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-core</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jms-notifier-console-plugin]]
==== *jms-notifier-console-plugin*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jms-notifier-console-plugin</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[persistence]]
=== `persistence`

[[persistence-common]]
==== *persistence-common*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>persistence-common</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[org.eclipse.persistence.asm]]
==== *org.eclipse.persistence.asm*
**Version**: 9.4.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.4.0</version>
</dependency>
----
[[cmp-utility]]
==== *cmp-utility*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-utility</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-support-sqlstore]]
==== *cmp-support-sqlstore*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-sqlstore</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-generator-database]]
==== *cmp-generator-database*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-generator-database</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-model]]
==== *cmp-model*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-model</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[gf-jpa-connector]]
==== *gf-jpa-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>gf-jpa-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jpa-container]]
==== *jpa-container*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>jpa-container</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-internal-api]]
==== *cmp-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[osgi-jpa-extension]]
==== *osgi-jpa-extension*
**Version**: 1.0.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.fighterfish</groupId>
    <artifactId>osgi-jpa-extension</artifactId>
    <version>1.0.4</version>
</dependency>
----
[[cmp-support-ejb]]
==== *cmp-support-ejb*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-support-ejb</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[hazelcast-eclipselink-coordination]]
==== *hazelcast-eclipselink-coordination*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-enhancer]]
==== *cmp-enhancer*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-enhancer</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[cmp-ejb-mapping]]
==== *cmp-ejb-mapping*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence.cmp</groupId>
    <artifactId>cmp-ejb-mapping</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[restfulwebservice]]
=== `restfulwebservice`

[[jersey-media-multipart]]
==== *jersey-media-multipart*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-multipart</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-jackson]]
==== *jersey-media-json-jackson*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-jackson</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-mvc]]
==== *jersey-mvc*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-mvc-connector]]
==== *jersey-mvc-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jersey-mvc-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-mvc-jsp]]
==== *jersey-mvc-jsp*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-hk2]]
==== *jersey-hk2*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-client]]
==== *jersey-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x]]
==== *jersey-cdi1x*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-binding]]
==== *jersey-media-json-binding*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jaxrs-client-tracing]]
==== *jaxrs-client-tracing*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaxrs-client-tracing</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jersey-media-moxy]]
==== *jersey-media-moxy*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-mp-rest-client]]
==== *jersey-mp-rest-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
    <artifactId>jersey-mp-rest-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-proxy-client]]
==== *jersey-proxy-client*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-proxy-client</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-json-processing]]
==== *jersey-media-json-processing*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jsonp-jaxrs]]
==== *jsonp-jaxrs*
**Version**: 1.1.6

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jsonp-jaxrs</artifactId>
    <version>1.1.6</version>
</dependency>
----
[[jersey-common]]
==== *jersey-common*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-server]]
==== *jersey-server*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-server</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-gf-ejb]]
==== *jersey-gf-ejb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-bean-validation]]
==== *jersey-bean-validation*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-bean-validation</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-media-sse]]
==== *jersey-media-sse*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-entity-filtering]]
==== *jersey-entity-filtering*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-entity-filtering</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-container-servlet]]
==== *jersey-container-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-container-servlet-core]]
==== *jersey-container-servlet-core*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-container-grizzly2-http]]
==== *jersey-container-grizzly2-http*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-grizzly2-http</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[security]]
=== `security`

[[jakarta.security.auth.message-api]]
==== *jakarta.security.auth.message-api*
**Version**: 1.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta.security.auth.message</groupId>
    <artifactId>jakarta.security.auth.message-api</artifactId>
    <version>1.1.3</version>
</dependency>
----
[[appclient.security]]
==== *appclient.security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>appclient.security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[javax.security.enterprise]]
==== *javax.security.enterprise*
**Version**: 1.1-b01.payara-p5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>javax.security.enterprise</artifactId>
    <version>1.1-b01.payara-p5</version>
</dependency>
----
[[websecurity]]
==== *websecurity*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>websecurity</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.security.enterprise-api]]
==== *jakarta.security.enterprise-api*
**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.security.enterprise</groupId>
    <artifactId>jakarta.security.enterprise-api</artifactId>
    <version>1.0.2</version>
</dependency>
----
[[jcip-annotations]]
==== *jcip-annotations*
**Version**: 1.0-1

[source,xml]
----
<dependency>
    <groupId>com.github.stephenc.jcip</groupId>
    <artifactId>jcip-annotations</artifactId>
    <version>1.0-1</version>
</dependency>
----
[[nimbus-jose-jwt]]
==== *nimbus-jose-jwt*
**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>9.10.1</version>
</dependency>
----
[[security-connector-oidc-client]]
==== *security-connector-oidc-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[accessors-smart]]
==== *accessors-smart*
**Version**: 2.4.7

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>accessors-smart</artifactId>
    <version>2.4.7</version>
</dependency>
----
[[json-smart]]
==== *json-smart*
**Version**: 2.4.7

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.4.7</version>
</dependency>
----
[[security-connector-oauth2-client]]
==== *security-connector-oauth2-client*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[security-ee]]
==== *security-ee*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-ee</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[security]]
==== *security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.security.jacc-api]]
==== *jakarta.security.jacc-api*
**Version**: 1.6.1

[source,xml]
----
<dependency>
    <groupId>jakarta.security.jacc</groupId>
    <artifactId>jakarta.security.jacc-api</artifactId>
    <version>1.6.1</version>
</dependency>
----
[[security-services]]
==== *security-services*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-services</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[webservices.security]]
==== *webservices.security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[ejb.security]]
==== *ejb.security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[security-connectors-api]]
==== *security-connectors-api*
**Version**: 2.4.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>2.4.0</version>
</dependency>
----
[[serverfaces]]
=== `serverfaces`

[[jsf-connector]]
==== *jsf-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.faces]]
==== *jakarta.faces*
**Version**: 2.3.14.payara-p3

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>2.3.14.payara-p3</version>
</dependency>
----
[[jsft]]
==== *jsft*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsft</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[jsftemplating]]
==== *jsftemplating*
**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>com.sun.jsftemplating</groupId>
    <artifactId>jsftemplating</artifactId>
    <version>2.1.4</version>
</dependency>
----
[[weld-jsf]]
==== *weld-jsf*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[serverpages]]
=== `serverpages`

[[javax.servlet.jsp]]
==== *javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[jersey-mvc-jsp]]
==== *jersey-mvc-jsp*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[jspcaching-connector]]
==== *jspcaching-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jspcaching-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.servlet.jsp-api]]
==== *jakarta.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[servlet]]
=== `servlet`

[[jaspic-servlet-utils]]
==== *jaspic-servlet-utils*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaspic-servlet-utils</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.4</version>
</dependency>
----
[[jakarta.servlet-api]]
==== *jakarta.servlet-api*
**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.4</version>
</dependency>
----
[[javax.servlet.jsp]]
==== *javax.servlet.jsp*
**Version**: 2.3.4

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp</artifactId>
    <version>2.3.4</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[tyrus-container-servlet]]
==== *tyrus-container-servlet*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-servlet]]
==== *jersey-cdi1x-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jakarta.servlet.jsp-api]]
==== *jakarta.servlet.jsp-api*
**Version**: 2.3.6.payara-p1

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>2.3.6.payara-p1</version>
</dependency>
----
[[jersey-container-servlet]]
==== *jersey-container-servlet*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-container-servlet-core]]
==== *jersey-container-servlet-core*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet-core</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[standardtaglibrary]]
=== `standardtaglibrary`

[[jstl-connector]]
==== *jstl-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jstl-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[jakarta.servlet.jsp.jstl-api]]
==== *jakarta.servlet.jsp.jstl-api*
**Version**: 1.2.7

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>1.2.7</version>
</dependency>
----
[[javax.servlet.jsp.jstl]]
==== *javax.servlet.jsp.jstl*
**Version**: 1.2.5

[source,xml]
----
<dependency>
    <groupId>org.glassfish.web</groupId>
    <artifactId>javax.servlet.jsp.jstl</artifactId>
    <version>1.2.5</version>
</dependency>
----
[[transaction]]
=== `transaction`

[[jta]]
==== *jta*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jta</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jakarta.transaction-api]]
==== *jakarta.transaction-api*
**Version**: 1.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>1.3.3</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[jersey-cdi1x-transaction]]
==== *jersey-cdi1x-transaction*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[transaction-internal-api]]
==== *transaction-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[transaction-internal-api]]
==== *transaction-internal-api*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[weld-jta]]
==== *weld-jta*
**Version**: 3.1.9.final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>3.1.9.final</version>
</dependency>
----
[[webservices]]
=== `webservices`

[[jackson-module-jaxb-annotations]]
==== *jackson-module-jaxb-annotations*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jaxb-annotations</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[opentracing-jaxws]]
==== *opentracing-jaxws*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.ws.rs-api]]
==== *jakarta.ws.rs-api*
**Version**: 2.1.6

[source,xml]
----
<dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>2.1.6</version>
</dependency>
----
[[jersey-media-jaxb]]
==== *jersey-media-jaxb*
**Version**: 2.37.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-jaxb</artifactId>
    <version>2.37.payara-p1</version>
</dependency>
----
[[webservices-connector]]
==== *webservices-connector*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-connector</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[jakarta.jws-api]]
==== *jakarta.jws-api*
**Version**: 1.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.jws</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>1.1.1</version>
</dependency>
----
[[webservices-osgi]]
==== *webservices-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[stax2-api]]
==== *stax2-api*
**Version**: 4.2.1

[source,xml]
----
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.2.1</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jaxb-runtime]]
==== *jaxb-runtime*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-runtime</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[txw2]]
==== *txw2*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>txw2</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-xjc]]
==== *jaxb-xjc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-xjc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[codemodel]]
==== *codemodel*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>codemodel</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[xsom]]
==== *xsom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>xsom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[jaxb-jxc]]
==== *jaxb-jxc*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jaxb</groupId>
    <artifactId>jaxb-jxc</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[istack-commons-runtime]]
==== *istack-commons-runtime*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[istack-commons-tools]]
==== *istack-commons-tools*
**Version**: 3.0.12

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-tools</artifactId>
    <version>3.0.12</version>
</dependency>
----
[[relaxng-datatype]]
==== *relaxng-datatype*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>relaxng-datatype</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[rngom]]
==== *rngom*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind.external</groupId>
    <artifactId>rngom</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[dtd-parser]]
==== *dtd-parser*
**Version**: 1.4.5

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.dtd-parser</groupId>
    <artifactId>dtd-parser</artifactId>
    <version>1.4.5</version>
</dependency>
----
[[fastinfoset]]
==== *fastinfoset*
**Version**: 1.2.18

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.fastinfoset</groupId>
    <artifactId>fastinfoset</artifactId>
    <version>1.2.18</version>
</dependency>
----
[[stax-ex]]
==== *stax-ex*
**Version**: 1.8.3

[source,xml]
----
<dependency>
    <groupId>org.jvnet.staxex</groupId>
    <artifactId>stax-ex</artifactId>
    <version>1.8.3</version>
</dependency>
----
[[jaxb-osgi]]
==== *jaxb-osgi*
**Version**: 2.3.7

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-osgi</artifactId>
    <version>2.3.7</version>
</dependency>
----
[[webservices.security]]
==== *webservices.security*
**Version**: 5.46.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>5.46.0</version>
</dependency>
----
[[webservices-extra-jdk-packages]]
==== *webservices-extra-jdk-packages*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-extra-jdk-packages</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[webservices-api-osgi]]
==== *webservices-api-osgi*
**Version**: 2.4.3.payara-p6

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-api-osgi</artifactId>
    <version>2.4.3.payara-p6</version>
</dependency>
----
[[websocket]]
=== `websocket`

[[tyrus-core]]
==== *tyrus-core*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-core</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-container-glassfish-ejb]]
==== *tyrus-container-glassfish-ejb*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-container-servlet]]
==== *tyrus-container-servlet*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-container-glassfish-cdi]]
==== *tyrus-container-glassfish-cdi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-server]]
==== *tyrus-server*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-server</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[jakarta.websocket-api]]
==== *jakarta.websocket-api*
**Version**: 1.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>1.1.2</version>
</dependency>
----
[[tyrus-client]]
==== *tyrus-client*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-client</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-spi]]
==== *tyrus-spi*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-spi</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[tyrus-container-grizzly-client]]
==== *tyrus-container-grizzly-client*
**Version**: 1.20.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-grizzly-client</artifactId>
    <version>1.20.payara-p1</version>
</dependency>
----
[[xmlregistries]]
=== `xmlregistries`

[[jakarta.xml.registry-api]]
==== *jakarta.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.registry</groupId>
    <artifactId>jakarta.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[xmlrpc]]
=== `xmlrpc`

[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jackson-dataformat-xml]]
==== *jackson-dataformat-xml*
**Version**: 2.13.4

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-xml</artifactId>
    <version>2.13.4</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.ws-api]]
==== *jakarta.xml.ws-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.registry-api]]
==== *jakarta.xml.registry-api*
**Version**: 1.0.10

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.registry</groupId>
    <artifactId>jakarta.xml.registry-api</artifactId>
    <version>1.0.10</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.bind-api]]
==== *jakarta.xml.bind-api*
**Version**: 2.3.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>2.3.3</version>
</dependency>
----
[[jakarta.xml.rpc-api]]
==== *jakarta.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.rpc</groupId>
    <artifactId>jakarta.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
[[jakarta.xml.rpc-api]]
==== *jakarta.xml.rpc-api*
**Version**: 1.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.rpc</groupId>
    <artifactId>jakarta.xml.rpc-api</artifactId>
    <version>1.1.4</version>
</dependency>
----
