[[domain-and-node-directories-upgrade-method]]
= Domain and Node Directories Upgrade Method
:ordinal: 2

An alternative to backing up and restoring the domain, then recreating the instances, would be to create the domain and node directories in a location separate to the installation. For example, if you download _Payara Server 6.2022.1.Alpha3_, created a domain, and then wanted to use _Payara Server 6.2022.1_, you would use the following process:

[source, shell]
----
/opt/payara/payara-6.2022.1.Alpha3/payara6 bin/asadmin create-domain --domaindir /tmp myTempDomain
/opt/payara/payara-6.2022.1.Alpha3/payara6 cd ../../payara-6.2022.1.Alpha3/payara6
/opt/payara/payara-6.2022.1/payara6 bin/asadmin start-domain --domaindir /tmp myTempDomain
----

This will use the _6.2022.1.Alpha3_ installation to create a new domain, and then run it with the _6.2022.1_ installation.

Nodes can also be created in a separate directory by using the `--nodedir` property when creating a node.

[source, shell]
----
/opt/payara/payara-6.2022.1.Alpha3/payara6 bin/asadmin create-node --nodedir /tmp myLocalNode
----

In this way, the user configuration is always kept separate to the installation, and rollback is as simple as using the previous installation directory.

If you are using Payara Server on *Linux*, you could take advantage of _"symbolic links"_ to make life easier. When your domain directory is in a non-standard location, it means that you need to specify its location with each `start`/`stop`/`restart` command. If you were to create a symbolic link to the domain directory inside the default domains directory, then all of your existing scripts will carry on as normal.

This means that any rollback is as simple as stopping the server, updating a symbolic link and starting it again.

If you choose not to use symbolic links, the asadmin start-domain subcommand has a `--domaindir` option which allows you to specify the location of a domain directory. So you could have a directory structure like the following:

----
/opt/payara/6.2022.1.Alpha3/payara6/...
/opt/payara/6.2022.1.Alpha4/payara6/...
/opt/payara/6.2022.1/payara6/....
/opt/payara/domains/myDomain
/opt/payara/nodes/myLocalNode
----

Then you could start your domain with whatever version of Payara Server you wanted by running the start-domain command from the corresponding Payara installation directory.

[source, shell]
----
/opt/payara/6.2022.1.Alpha3/payara6/bin/asadmin start-domain --domaindir /opt/payara/domains myDomain
/opt/payara/6.2022.1.Alpha4/payara6/bin/asadmin start-domain --domaindir /opt/payara/domains myDomain
/opt/payara/6.2022.1/payara6/bin/asadmin start-domain --domaindir /opt/payara/domains myDomain
----

Just as you can create nodes by using the `--domaindir` property, you can also start nodes in the same way.

[source, shell]
----
/opt/payara/6.2022.1.Alpha3/payara6/bin/asadmin start-local-instance --nodedir /opt/payara/nodes myLocalNode
/opt/payara/6.2022.1.Alpha4/payara6/bin/asadmin start-local-instance --nodedir /opt/payara/nodes myLocalNode
/opt/payara/6.2022.1/payara6/bin/asadmin start-local-instance --nodedir /opt/payara/nodes myLocalNode
----