[[upgrade-payara-server]]
= Upgrading Payara Server

There are two valid methods of fully upgrading to a new release of Payara Community Edition. Either of the following two methods would work in most circumstances:

IMPORTANT: These methods should not be used for upgrading from Payara 5 to Payara 6 and will not update your installation correctly. You should instead use a clean install of Payara 6

. Backing up and restoring the existing configuration to a new installation.
xref:Technical Documentation/Payara Server Documentation/Upgrade Payara/Backup and Restore Method.adoc[Read Backup and Restore Method]

. Maintaining completely separate domain and node directories and pointing the new version to the existing directories.
xref:Technical Documentation/Payara Server Documentation/Upgrade Payara/Domain and Node Directories Method.adoc[Read Domain and Node Directories Method]

== Payara 5 to Payara 6 Migration Considerations
Package names for Corba classes have changed from `com.sun` to `org.glassfish`, therefore if you use the `java.naming.factory.initial` system property you should set it to `org.glassfish.jndi.cosnaming.CNCtxFactory` for Payara 6.