= Amazon SQS Versioning

[[amazon-sqs-connector-version-1]]
== Amazon SQS Connector version 1

This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. Please check xref:/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/Amazon SQS.adoc[Amazon SQS connector] for more information about how the connector works.

[[amazon-sqs-connector-version-2]]
== Amazon SQS Connector version 2

This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2].

[[how-to-use]]
=== How to use it?

This new SQS Connector use the last version of the Amazon SDK. In order to use, clone the following branch https://github.com/payara/Cloud-Connectors/tree/cloud-connectors-v2[Cloud Connectors V2] then build and install the connector:

Build and install the connectors:

[source, shell]
----
cd Cloud-Connectors/
mvn clean install
----

The connector can be found in the following location as JCA RAR:

[source, shell]
----
./AmazonSQS/AmazonSQSRAR/target/amazon-sqs-rar-1.0.0.rar
----

In order to make use of this connector in an application, the following two maven dependencies are needed:

[source, xml]
----
<dependency>
    <groupId>fish.payara.cloud.connectors.amazonsqs</groupId>
    <artifactId>amazon-sqs-jca-api</artifactId>
    <version>1.0.0</version>
    <type>jar</type>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>sqs</artifactId>
    <version>2.18.17</version>
    <type>jar</type>
    <scope>provided</scope>
</dependency>
----



