= Amazon SQS Versioning

== Amazon SQS Connector version 1

This is the first version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html[Amazon SDK 1]. To view how to use, please check the following link xref:/Technical Documentation/Ecosystem/Connector Suites/Cloud Connectors/AmazonSQS.adoc[Amazon SQS connector] .

== Amazon SQS Connector version 2

This is the second version of the connector that is based on https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html[Amazon SDK 2]. This version is based on a major rewrite of the version 1.x code base and built on top of java 8+ .


=== How to use it?

This new SQS Connector use the last version of the Amazon SDK. In order to use, clone the following branch https://github.com/payara/Cloud-Connectors/tree/cloud-connectors-v2 [Cloud Connectors V2] then build and install the connector:

Build and install the connectors:

[source, shell]
----
cd Cloud-Connectors/
mvn clean install
----

The connector can be found in the following location as JCA rar:

* Amazon SQS - ./AmazonSQS/AmazonSQSRAR/target/amazon-sqs-rar-0.9.0-SNAPSHOT.rar

In order to make use of this connector in an application, the following two maven dependencies are needed:

[source, xml]
----
<dependency>
    <groupId>fish.payara.cloud.connectors.amazonsqs</groupId>
    <artifactId>amazon-sqs-jca-api</artifactId>
    <version>0.9.0-SNAPSHOT</version>
    <type>jar</type>
    <scope>provided</scope>
</dependency>

<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>sqs</artifactId>
    <version>2.18.17</version>
    <type>jar</type>
    <scope>provided</scope>
</dependency>
----

Note that these dependencies have scope provided since the types within this dependency are globally available to every application deployed to Payara Micro after the `amazon-sqs-rar-0.9.0-SNAPSHOT.rar` was deployed.


