[[delete-http-lb-config]]
== delete-http-lb-config

deletes a load balancer configuration

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-lb-config [--help] 
config_name
----

[[description]]
== Description

Use the `delete-http-lb-config` subcommand to delete a load balancer configuration. The load balancer configuration must not reference any clusters or server instances enabled for load balancing. In addition, the load balancer configuration must not be referenced by any physical load balancers.


[NOTE]
====
This subcommand is only applicable to Oracle GlassFish Server. This subcommand is not applicable to GlassFish Server Open Source Edition.
====


[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

config_name::
  The name of the load balancer configuration to delete. The configuration must not reference any clusters or server instances enabled for load balancing, or be used by any physical load balancers.

[[examples]]
== Examples

[[example-1]]
Example 1 Deleting a Load Balancer Configuration

This example deletes a load balancer configuration named `mylbconfig`

[source,shell]
----
asadmin> delete-http-lb-config mylbconfig
Command delete-http-lb-config executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

xref:asadmin.adoc#asadmin[`asadmin`]

xref:create-http-lb-config.adoc#create-http-lb-config[`create-http-lb-config`],
xref:list-http-lb-configs.adoc#list-http-lb-configs[`list-http-lb-configs`]


