[[delete-node-dcom]]
= delete-node-dcom

deletes a node that is enabled for communication over DCOM

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-node-dcom [--help] 
[--uninstall={false|true}] [--force={false|true}]
node-name
----

[[description]]
== Description

The `delete-node-dcom` subcommand deletes a node that is enabled for communication over the Distributed Component Object Model (DCOM) remote protocol from the domain. The DCOM protocol is available only on Windows systems. This subcommand does not require DCOM to be configured.

This subcommand can delete only a node that is enabled for communication over DCOM. The subcommand for deleting other types of nodes depends on the type of the node:

* A node that is enabled for communication over secure shell (SSH) must be deleted by using the xref:delete-node-ssh.adoc#delete-node-ssh[`delete-node-ssh`] subcommand.
* A node that is not enabled for communication must be deleted by using the xref:delete-node-config.adoc#delete-node-config[`delete-node-config`] subcommand.

To determine whether a node is enabled for communication over DCOM, use the xref:list-nodes.adoc#list-nodes[`list-nodes`] subcommand.

No \{product---name} instances must reside on the node that is being deleted. Otherwise, the subcommand fails. Before running this subcommand, delete any instances that reside on the node by using, for example, the xref:delete-instance.adoc#delete-instance[`delete-instance`] subcommand or the xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`]
subcommand.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--uninstall`::
  Specifies whether the \{product---name} software is uninstalled from host that the node represents. +
  Possible values are as follows: +
  `false`;;
    The \{product---name} software is not uninstalled from the host (default).
  `true`;;
    The \{product---name} software is uninstalled from the host. By default, if any node except the predefined node `localhost` domain resides on any host from which \{product---name} software is being uninstalled, the subcommand fails. To uninstall the \{product---name} software from a host on which user-defined nodes reside, set the `--force` option to `true`. If the `--force` option is `true`, the subcommand removes the entire content of the parent of the base installation directory.
`--force`::
  If `--uninstall` is true, specifies whether the subcommand uninstalls the \{product---name} software from a host even if a user-defined node resides on the host. Possible values are as follows: +
  `false`;;
    If a user-defined node resides on a host, the software is not uninstalled and the subcommand fails (default). +
    If the `--force` option is `false`, the subcommand removes only the \{product---name} software files. Other content if the parent of the base installation directory, such as configuration files, are not removed.
  `true`;;
    The subcommand uninstalls the \{product---name} software from the host even if a user-defined node resides on the host. +
    If the `--force` option is `true`, the subcommand removes the entire content of the parent of the base installation directory.

[[operands]]
== Operands

node-name::
  The name of the node to delete. The node must be enabled for communication over DCOM. Otherwise, an error occurs.

[[examples]]
== Examples

[[example-1]]
=== Example 1 Deleting a Node That Is Enabled for Communication Over DCOM

This example deletes the node `xkyd`, which is enabled for communication over DCOM.

[source,shell]
----
asadmin> delete-node-dcom xkyd
Command delete-node-dcom executed successfully.
----

[[exit-status]]
Exit Status

0::
  command executed successfully
1::
  error in executing the command

[[see-also]]
*See Also*

xref:asadmin.adoc#asadmin[`asadmin`]

xref:create-node-dcom.adoc#create-node-dcom[`create-node-dcom`],
xref:delete-instance.adoc#delete-instance[`delete-instance`],
xref:delete-local-instance.adoc#delete-local-instance[`delete-local-instance`],
xref:delete-node-config.adoc#delete-node-config[`delete-node-config`],
xref:delete-node-ssh.adoc#delete-node-ssh[`delete-node-ssh`],
xref:install-node-dcom.adoc#install-node-dcom[`install-node-dcom`],
xref:list-nodes.adoc#list-nodes[`list-nodes`],
xref:uninstall-node-dcom.adoc#uninstall-node-dcom[`uninstall-node-dcom`],
xref:update-node-ssh.adoc#update-node-dcom[`update-node-dcom`]


