[[delete-domain]]
= delete-domain

Deletes a domain.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-domain [--help] 
[--domaindir domaindir] domain-name
----

[[description]]
== Description

The `delete-domain` subcommand deletes the specified domain. The domain must already exist and must be stopped.

This subcommand is supported in local mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--domaindir`::
  The directory where the domain to be deleted is located. If specified, the path must be accessible in the file system. If not specified, the domain under the domain root directory, which defaults to as-install`/domains`, is deleted.

[[operands]]
== Operands

domain-name::
  The unique name of the domain you want to delete.

[[examples]]
== Examples

*Example 1 Deleting a Domain*

This example deletes a domain named `mydomain4` from the default domains directory.

[source,shell]
----
asadmin> delete-domain mydomain4
Domain mydomain4 deleted.
Command delete-domain executed successfully.
----

*Example 2 deleting a Domain From an Alternate Location*

This example deletes a domain named `sampleDomain` from the `/home/someuser/domains` directory.

[source,shell]
----
asadmin> delete-domain --domaindir /home/someuser/domains sampleDomain
Domain sampleDomain deleted
Command delete-domain executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-domain.adoc#create-domain[`create-domain`],
* xref:list-domains.adoc#list-domains[`list-domains`],
* xref:start-domain.adoc#start-domain[`start-domain`],
* xref:stop-domain.adoc#stop-domain[`stop-domain`]


