[[delete-http-lb]]
= delete-http-lb

deletes a load balancer

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-lb [--help] 
load_balancer_name
----

[[description]]
== Description

Use the `delete-http-lb` subcommand to delete a physical load balancer.

NOTE: This subcommand is only applicable to Payara Server. This subcommand is not applicable to Payara Server Open Source Edition.


[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

load_balancer_name::
  The name of the load balancer to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Load Balancer Configuration*

This example deletes the load balancer configuration named `mylb`.

[source,shell]
----
asadmin> delete-http-lb mylb

Command delete-http-lb executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-http-lb.adoc#create-http-lb[`create-http-lb`],
* xref:list-http-lbs.adoc#list-http-lbs[`list-http-lbs`]


