[[delete-managed-executor-service]]
= delete-managed-executor-service

removes a managed executor service resource with the specified JNDI name

[[synopsis]]
== Synopsis

[source,oac_no_warn]
----
asadmin [asadmin-options] delete-managed-executor-service [--help]
[--target target]
managed_executor_service_name
----

[[description]]
== Description

The `delete-managed-executor-service` subcommand removes a managed executor service resource with the specified JNDI name.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  Specifies the target from which you are deleting the resource. Valid targets are: +
  `server`;;
    Deletes the resource from the default server instance. This is the default value.
  `domain`;;
    Deletes the resource from the domain.
  cluster_name;;
    Deletes the resource from every server instance in the specified cluster.
  instance_name;;
    Deletes the resource from the specified server instance.

[[operands]]
== Operands

managed_executor_service_name::
  The JNDI name of the resource to be deleted.

[[examples]]
== Examples

*Example 1 Deleting a Managed Executor Service Resource*

This example deletes the managed executor service resource named `concurrent/myExecutor`.

[source,shell]
----
asadmin> delete-managed-executor-service concurrent/myExecutor
Managed executor service concurrent/myExecutor deleted successfully.
Command delete-managed-executor-service executed successfully.
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-managed-executor-service.adoc#create-managed-executor-service[`create-managed-executor-service`],
* xref:list-managed-executor-services.adoc#list-managed-executor-services[`list-managed-executor-services`]


