[[delete-http-health-checker]]
= delete-http-health-checker

deletes the health-checker for a specified load balancer configuration

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-http-health-checker [--help] 
[--config config_name]
 target
----

[[description]]
== Description

The `delete-http-health-checker` subcommand deletes the health checker from a load balancer configuration. A health checker is unique for the combination of target and load balancer configuration.

NOTE: This subcommand is only applicable to Oracle GlassFish Server. This subcommand is not applicable to GlassFish Server Open Source Edition.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--config`::
  The load balancer configuration from which you delete the health-checker.

[[operands]]
== Operands

target::
  Specifies the target from which you are deleting the health checker. +
  Valid values are: +
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

[[example-1]]

*Example 1 Deleting a Health Checker from a Load Balancer Configuration*

This example deletes the health checker for load balancer configuration named `mycluster-http-lb-config` on a cluster named `mycluster`.

[source,shell]
----
asadmin> delete-http-health-checker --user admin 
--passwordfile password.txt --config mycluster-http-lb-config mycluster

Command delete-http-health-checker executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-http-health-checker.adoc#create-http-health-checker[`create-http-health-checker`]


