[[delete-password-alias]]
= delete-password-alias

deletes a password alias

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] delete-password-alias [--help]
aliasname
----

[[description]]
== Description

This subcommand deletes a password alias.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

aliasname::
  This is the name of the substitute password as it appears in
  `domain.xml`.

[[examples]]
== Examples

*Example 1 Deleting a Password Alias*

[source,shell]
----
asadmin>delete-password-alias
jmspassword-alias
----

Command delete-password-alias executed successfully

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-password-alias.adoc#create-password-alias[`create-password-alias`],
* xref:list-password-aliases.adoc#list-password-aliases[`list-password-aliases`],
* xref:update-password-alias.adoc#update-password-alias[`update-password-alias`]


