[[enable-http-lb-server]]
== enable-http-lb-server

enables a previously disabled sever or cluster managed by a load balancer

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] enable-http-lb-server [--help] 
target
----

[[desceiption]]
== Description

The `enable-http-lb-server` subcommand enables a standalone server instance or cluster for load balancing. By default, load balancing is enabled for instances and clusters.

NOTE: This subcommand is only applicable to Oracle GlassFish Server. This subcommand is not applicable to GlassFish Server Open Source Edition.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  This operand specifies which server instances and clusters to enable. Valid values are: +
  * cluster_name- The name of a target cluster.
  * instance_name- The name of a target server instance.

[[examples]]
== Examples

Example 1 Enabling a Cluster for Load Balancing

This example enables load balancing for a cluster named `mycluster`.

[source,shell]
----
asadmin> enable-http-lb-server mycluster

Command enable-http-lb-server executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`(1M)]
* xref:create-http-lb-ref.adoc#create-http-lb-ref[`create-http-lb-ref`(1)],
* xref:disable-http-lb-server.adoc#disable-http-lb-server[`disable-http-lb-server`(1)]


