[[freeze-transaction-service]]
= freeze-transaction-service

freezes the transaction subsystem

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] freeze-transaction-service [--help] 
[--target target]
----

[[descroiption]]
== Description

The `freeze-transaction-service` subcommand freezes the transaction subsystem, preventing the transaction manager from starting, completing, or changing the state of all in-flight transactions. Invoke this command before rolling back any in-flight transactions. Invoking this subcommand on an already frozen transaction subsystem has no effect. Restarting the server unfreezes the transaction subsystem. This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  This option specifies the target on which you are freezing the transaction service. Valid values are: +
  `server`;;
    Freezes the transaction service for the default server instance `server` and is the default value.
  configuration_name;;
    Freezes the transaction service for all server instances that use the named configuration.
  cluster_name;;
    Freezes the transaction service for every server instance in the cluster.
  instance_name;;
    Freezes the transaction service for a particular server instance.

[[examples]]
== Examples

[[GSRFM616]][[sthref1197]]

Example 1   Using freeze-transaction-service

[source,oac_no_warn]
----
% asadmin freeze-transaction-service
Command freeze-transaction-service executed successfully
----

[[sthref1198]]

Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

xref:asadmin.adoc#asadmin[`asadmin`]

xref:recover-transactions.adoc#recover-transactions[`recover-transactions`],
xref:rollback-transaction.adoc#rollback-transaction[`rollback-transaction`],
xref:unfreeze-transaction-service.adoc#unfreeze-transaction-service-1[`unfreeze-transaction-service`]

"xref:docs:administration-guide:transactions.adoc[Administering Transactions]" in Payara Server Administration Guide

"http://docs.oracle.com/javaee/7/tutorial/doc/transactions.html[Transactions]"
in The Java EE 8 Tutorial


