[[list-http-lb-configs]]
= list-http-lb-configs

lists load balancer configurations

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-http-lb-configs [--help] 
[target]
----

[[description]]
== Description

The `list-http-lb-configs` subcommand lists the load balancer configurations. List them all or list them by the cluster or server instance they reference.


[NOTE]
====
This subcommand is only applicable to Oracle GlassFish Server. This subcommand is not applicable to GlassFish Server Open Source Edition.
====


[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Lists the load balancers by target. Valid values are: +
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.

[[examples]]
== Examples

[[example-1]]
=== Example 1Listing Load Balancer Configurations Without a Target

This example lists all load balancer configurations defined for all \{product---name} clusters and instances.

[source,shell]
----
asadmin> list-http-lb-configs

mycluster-http-lb-config
serverinstlb
Command list-http-lb-configs executed successfully.
----

[[example-2]]
Example 2 Listing Load Balancer Configurations for a Specific Target

This example lists the load balancer configuration defined for a cluster named `mycluster`.

[source,shell]
----
asadmin> list-http-lb-configs mycluster

mycluster-http-lb-config
Command list-http-lb-configs executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

xref:asadmin.adoc#asadmin[`asadmin`]

xref:create-http-lb-config.adoc#create-http-lb-config[`create-http-lb-config`],
xref:delete-http-lb-config.adoc#delete-http-lb-config[`delete-http-lb-config`]


