[[list-modules]]
= list-modules

Lists Payara Server modules.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-modules [--help]
----

[[description]]
== Description

The `list-modules` subcommand displays a list of modules that are accessible to the Payara Server module subsystem. The version of each module is shown.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

*Example 1 Listing Payara Server Modules*

This example provides a partial listing of modules that are accessible to the Payara Server module subsystem

[source,shell]
----
asadmin> list-modules
List Of Modules
Module Status Report Begins
Module : org.glassfish.transaction.jts:3.0.0.b66
    Module Characteristics : List of Jars implementing the module
        Jar : file:/home/gfuser/GlassFish/glassfishv3/glassfish/modules/jts.jar
    Module Characteristics : Provides to following services
    Module Characteristics : List of imported modules
        Imports : org.glassfish.transaction.jts:3.0.0.b66
Module : com.sun.enterprise.tiger-types-osgi:0.3.96
Module : org.glassfish.bean-validator:3.0.0.JBoss-400Beta3A
Module : org.glassfish.core.kernel:3.0.0.b66
    Module Characteristics : Provides to following services
    Module Characteristics : List of imported modules
        Imports : org.glassfish.core.kernel:3.0.0.b66
    Module Characteristics : List of Jars implementing the module
        Jar : file:/home/gfuser/GlassFish/glassfishv3/glassfish/modules/kernel.jar
Module : org.glassfish.common.util:3.0.0.b66
    Module Characteristics : List of Jars implementing the module
        Jar : file:/home/gfuser/GlassFish/glassfishv3/glassfish/modules/common-util.jar
    Module Characteristics : Provides to following services
    Module Characteristics : List of imported modules
        Imports : org.glassfish.common.util:3.0.0.b66
...
Command list-modules executed successfully
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`],
* xref:list-commands.adoc#list-commands[`list-commands`],
* xref:list-components.adoc#list-components[`list-components`],
* xref:list-containers.adoc#list-containers[`list-containers`]


