[[list-jdbc-connection-pools]]
= list-jdbc-connection-pools

lists all JDBC connection pools

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-jdbc-connection-pools [--help]
----

[[description]]
== Description

The `list-jdbc-connection-pools` subcommand lists the current JDBC connection pools.

This subcommand is supported in the remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

[[example-1]]
=== Example 1 Listing the JDBC Connection Pools

This example lists the existing JDBC connection pools.

[source,shell]
----
asadmin> list-jdbc-connection-pools
sample_derby_pool
__TimerPool
Command list-jdbc-connection-pools executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

xref:asadmin.adoc#asadmin[`asadmin`]

xref:create-jdbc-connection-pool.adoc#create-jdbc-connection-pool[`create-jdbc-connection-pool`],
xref:delete-jdbc-connection-pool.adoc#delete-jdbc-connection-pool[`delete-jdbc-connection-pool`]


