[[list-containers]]
= list-containers

Lists application containers.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-containers [--help]
----

[[description]]
== Description

The `list-containers` subcommand displays a list of application containers.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

[[example-1]]

*Example 1 Listing the Application Containers*

This example lists the current application containers.

[source,shell]
----
asadmin> list-containers
List all known application containers
Container : grizzly
Container : ejb
Container : webservices
Container : ear
Container : appclient
Container : connector
Container : jpa
Container : web
Container : osgi
Container : security
Container : webbeans

Command list-containers executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`],
* xref:list-commands.adoc#list-commands[`list-commands`],
* xref:list-components.adoc#list-components[`list-components`],
* xref:list-modules.adoc#list-modules[`list-modules`]