[[list-password-aliases]]
= list-password-aliases

lists all password aliases

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-password-aliases [--help]
----

[[description]]
== Description

This subcommand lists all of the password aliases.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`(1M)] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[examples]]
== Examples

Example 1 Listing all password aliases

[source,shell]
----
asadmin> list-password-aliases 
jmspassword-alias
Command list-password-aliases executed successfully
----

[[exit-status]]
== Exit Status

0::
  command executed successfully
1::
  error in executing the command

*See Also*

* xref:asadmin.html#asadmin-1m[`asadmin`(1M)]
* xref:create-password-alias.html#create-password-alias[`create-password-alias`(1)],
* xref:delete-password-alias.html#delete-password-alias-1[`delete-password-alias`(1)],
* xref:update-password-alias.html#update-password-alias-1[`update-password-alias`(1)]


