[[list-managed-executor-services]]
= list-managed-executor-services

lists managed executor service resources

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-managed-executor-services [--help]
[target]
----

[[description]]
== Description

The `list-managed-executor-services` subcommand lists managed executor service resources.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.

[[operands]]
== Operands

target::
  Specifies the target for which managed executor service resources are to be listed. Valid targets are: +
  `server`;;
    Lists the resources on the default server instance. This is the default value.
  `domain`;;
    Lists the resources for the domain.
  cluster-name;;
    Lists the resources on all server instances in the specified cluster.
  instance-name;;
    Lists the resources on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing Managed Executor Service Resources*

This example lists managed executor service resources on the default server instance.

[source,shell]
----
asadmin> list-managed-executor-services
concurrent/__defaultManagedExecutorService
concurrent/myExecutor1
concurrent/myExecutor2
Command list-managed-executor-services executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-managed-executor-service.adoc#create-managed-executor-service[`create-managed-executor-service`],
* xref:delete-managed-executor-service.adoc#delete-managed-executor-service[`delete-managed-executor-service`]


