[[logging]]
= logging

Capturing information on Payara Server runtime events.

[[description]]
== Description

Logging is the process by which Payara Server captures data about events that occur during Payara Server operation. Payara Server
components and application components generate logging data, which is saved in the server log, typically `domain-dir/logs/server.log`. The
server log is the first source of information if Payara Server problems occur.

The server log is rotated when the file reaches the specified size in bytes, or the specified time has elapsed. The file can also be rotated
manually by using the `rotate-log` subcommand.

In addition to the server log, the domain-dir`/logs` directory contains two other kinds of logs:

* HTTP service access logs, located in the `/access` subdirectory
* Transaction service logs, located in the `/tx` subdirectory

Logging levels can be configured by using the Administration Console or the `set-log-levels` subcommand. Additional properties can be set by
using the Administration Console or by editing the `logging.properties`file. The default `logging.properties` file is typically located in domain-dir`/config`.

Although application components can use the Apache Commons Logging Library to record messages, the platform standard JSR 047 API is recommended for better log configuration.

*See Also*

* xref:list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:rotate-log.adoc#rotate-log[`rotate-log`],
* xref:set-log-levels.adoc#set-log-levels[`set-log-levels`]
* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:docs:administration-guide:logging.adoc#administering-the-logging-service[Administering the Logging Service] in Payara Server Administration Guide


