[[set-log-attributes]]
= set-log-attributes

sets the logging attributes for one or more loggers

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] set-log-attributes [--help] 
[--target=target] 
attribute-name=attribute-value[:attribute-name=attribute-value]*
----

[[description]]
== Description

The `set-log-attributes` subcommand sets logging attributes for one or more loggers. The attributes you can set correspond to the attributes
that are available in the `logging.properties` file for the domain.Depending on the attributes you set, a server restart may be necessary.

This subcommand is supported in remote mode only.

[[options]]
== Options

asadmin-options::
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
`--help`::
`-?`::
  Displays the help text for the subcommand.
`--target`::
  The server domain, instance, or cluster for which logger attributes will be set. If this option is omitted, attributes are set for the default server.

[[operands]]
== Operands

target::
  Valid values are: +
  * server_name - Default target is `server`. If no target is specified then log attributes are set for the server.
  * cluster_name - The name of a target cluster.
  * instance_name - The name of a target server instance.
attribute-name::
  The fully scoped name of the logging attribute. The `list-log-attributes` subcommand can be used to list the names of all currently defined attributes.
attribute-value::
  The value to apply to the specified attribute. +
  The attribute values that can be specified include the following.
  Refer to "xref:docs:administration-guide:logging.adoc#administering-the-logging-service[Administering the Logging Service]" in
  Payara Server Open Source Edition Administration Guide for complete explanations of each of these values. +
  `com.sun.enterprise.server.logging.GFFileHandler.alarms`;;
    Default is `false`.
  `com.sun.enterprise.server.logging.GFFileHandler.excludeFields`;;
    Default is an empty string.
  `com.sun.enterprise.server.logging.GFFileHandler.file`;;
    Default is `${com.sun.aas.instanceRoot}/logs/server.log`.
  `com.sun.enterprise.server.logging.GFFileHandler.flushFrequency`;;
    Default is `1`.
  `com.sun.enterprise.server.logging.GFFileHandler.formatter`;;
    Default is `com.sun.enterprise.server.logging.UniformLogFormatter`.
  `com.sun.enterprise.server.logging.GFFileHandler.logtoConsole`;;
    Default is `false`.
  `com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles`;;
    Default is `0`.
  `com.sun.enterprise.server.logging.GFFileHandler.multiLineMode`;;
    Default is `true`.
  `com.sun.enterprise.server.logging.GFFileHandler.retainErrorsStasticsForHours`;;
    Default is `0`.
  `com.sun.enterprise.server.logging.GFFileHandler.rotationLimitInBytes`;;
    Default is `2000000`.
  `com.sun.enterprise.server.logging.GFFileHandler.rotationTimelimitInMinutes`;;
    Default is `0`.
  `com.sun.enterprise.server.logging.SyslogHandler.useSystemLogging`;;
    Default is `false`.
  `handlers`;;
    Default is `java.util.logging.ConsoleHandler`.
  `java.util.logging.ConsoleHandler.formatter`;;
    Default is `com.sun.enterprise.server.logging.UniformLogFormatter`.
  `java.util.logging.FileHandler.count`;;
    Default is `1`.
  `java.util.logging.FileHandler.formatter`;;
    Default is `java.util.logging.XMLFormatter`.
  `java.util.logging.FileHandler.limit`;;
    Default is `50000`.
  `java.util.logging.FileHandler.pattern`;;
    Default is `%h/java%u.log`.
  `log4j.logger.org.hibernate.validator.util.Version`;;
    Default is `warn`.

[[examples]]
== Examples

*Example 1 Setting the Maximum Number of Log History Files to Maintain*

This example sets to 8 the maximum number of log history files for the server as a whole.

[source,shell]
----
asadmin> set-log-attributes --target=server \
com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles=8
com.sun.enterprise.server.logging.GFFileHandler.maxHistoryFiles logging 
attribute set with value 8.
These logging attributes are set for server.
Command set-log-attributes executed successfully.
----

[[exit-status]]
== Exit Status

0::
  subcommand executed successfully
1::
  error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:collect-log-files.adoc#collect-log-files[`collect-log-files`],
* xref:list-log-attributes.adoc#list-log-attributes[`list-log-attributes`],
* xref:list-log-levels.adoc#list-log-levels[`list-log-levels`],
* xref:rotate-log.adoc#rotate-log[`rotate-log`],
* xref:set-log-levels.adoc#set-log-levels[`set-log-levels`]
* "xref:docs:administration-guide:logging.adoc#administering-the-logging-service[Administering the Logging Service]" in Payara
Server Open Source Edition Administration Guide


