= Release notes - Payara Platform Community 6.2022.1 Alpha 3

Milestone release that is intended for certification against Jakarta EE 10 Core Profile.
Known issues include the admin console being broken by the Jakarta Faces upgrade, and the MicroProfile integration being broken by the CDI upgrade.

== Improvements

https://github.com/payara/Payara/pull/5782[[FISH-6203]] Upgrade Jakarta Standard Tag Library to 3.0

[FISH-6201] Upgrade Jakarta XML Web Services to 4.0

https://github.com/payara/Payara/pull/5770[[FISH-6199]] Upgrade Transaction to 2.0.1

https://github.com/payara/Payara/pull/5748[[FISH-6197]] Upgrade Jakarta Server Pages to 3.1

https://github.com/payara/Payara/pull/5738[[FISH-6137]] Upgrade to Expression Language 5

https://github.com/payara/Payara/pull/5803[[FISH-6084]] Upgrade Jakarta Security 3.0

https://github.com/payara/jakartaee-10-tck-runners/pull/9[[FISH-6083]] Upgrade Jakarta RESTful Web Services to 3.1

https://github.com/payara/Payara/pull/5771[[FISH-6082]] Upgrade Jakarta Batch 2.1.1

https://github.com/payara/Payara/pull/5819[[FISH-6081]] Upgrade Jakarta CDI 4.0 and latest version of Weld

https://github.com/payara/Payara/pull/5668[[FISH-6069]] Implement @ManagedScheduledExecutorDefinition

https://github.com/payara/Payara/pull/5760[[FISH-6065]] Upgrade Jakarta Interceptors to 2.1

https://github.com/payara/Payara/pull/5776[[FISH-6064]] Upgrade Jakarta SOAP with Attachments to 3.0

https://github.com/payara/Payara/pull/5776[[FISH-6063]] Upgrade Jakarta WebSocket to 2.1

https://github.com/payara/Payara/pull/5682[[FISH-6061]] Upgrade Jakarta JSON Processing to 2.1

https://github.com/payara/Payara/pull/5650[[FISH-6040]] Implement support for ThreadContextProvider

https://github.com/payara/Payara/pull/5658[[FISH-6039]] Implement @ContextServiceDefinition

https://github.com/payara/Payara/pull/5656[[FISH-6037]] Implement @ManagedExecutorDefinition

https://github.com/payara/Payara/pull/5656[[FISH-6021]] Cleanup file based JACC connector

https://github.com/payara/Payara/pull/5596[[FISH-6013]] Upgrade Jakarta Annotations to 2.1

https://github.com/payara/Payara/pull/5779[[FISH-6012]] Update Connectors to 2.1

https://github.com/payara/Payara/pull/5590[[FISH-6011]] Upgrade JBatch to 2.1.0

https://github.com/payara/Payara/pull/5757[[FISH-6007]] Upgrade Jakarta Authorization to 3.0

https://github.com/payara/Payara/pull/5786[[FISH-6006]] Upgrade Payara's Authentication to 3.0

https://github.com/payara/Payara/pull/5689[[FISH-5989]] Upgrade Jakarta Activation to 2.1.0

https://github.com/payara/Payara/pull/5666[[FISH-5987]] Remove SSL2, SSL3, TLS 1.0, and TLS 1.1 Configuration options

https://github.com/payara/Payara/pull/5675[[FISH-5978]] Set TLS 1.3 as Default Protocol

https://github.com/payara/Payara/pull/5616[[FISH-5970]] Support for the new CronTrigger of Jakarta Concurrency 3.0

https://github.com/payara/Payara/pull/5616[[FISH-5969]] Implement Java SE 8 Date and Time Support for Jakarta Concurrency 3.0

https://github.com/payara/Payara/pull/5680[[FISH-5968]] Propagation of Custom Context Providers With Jakarta Concurrency 3.0

[FISH-5967] CompletionStage Backed by a ContextService within Jakarta Concurrency 3.0

https://github.com/payara/Payara/pull/5696[[FISH-5966]] CompletionStage Backed by ManagedExecutorService Within Jakarta Concurrency 3.0

https://github.com/payara/Payara/pull/5616[[FISH-5965]]  ForkJoinWorkerThreadFactory for Parallel Stream Support in Jakarta Concurrency 3.0

https://github.com/payara/Payara/pull/5661[[FISH-5964]] Add Jakarta Concurrency 3.0 within Web Profile

https://github.com/payara/Payara/pull/5633[[FISH-5963]] Implement Jakarta Concurrency 3.0 @Asynchronous Annotation

https://github.com/payara/Payara/pull/5755[[FISH-5955]] Support lib/ext libraries on JDK 11\+

https://github.com/payara/Payara/pull/5637[[FISH-5927]] Update Installation Directory Tooltip for Docker Nodes

https://github.com/payara/Payara/pull/5720[[FISH-5893]] Allow to Specify the Timeout Options for Starting an Instance with Admin Console.

https://github.com/payara/Payara/pull/5624[[FISH-5803]] Add Autocomplete for Local 'asadmin' Commands

https://github.com/payara/Payara/pull/5693[[FISH-898]] Add '--timeout' Option to All the Commands that Manage the Lifecycle of an Instance


== Security Fixes

https://github.com/payara/Payara/pull/5686[[FISH-6208]] CVE-2022-22965 - Spring Framework RCE via Data Binding on JDK 9\+

== Bug Fixes

https://github.com/payara/Payara/pull/5749FISH-6260[[(FISH-6260]] Looking Up An MDB using AppClient Causes 'java.lang.NoSuchFieldException: parent' on JDK 17

https://github.com/payara/Payara/pull/5785[[FISH-6259]] Looking Up A Remote EJB Using AppClient Gets A NPE on JNDI Lookup on JDK 17.

https://github.com/payara/Payara/pull/5648[[FISH-6043]] Configuring Payara Notification Logging Service causes NullPointerException

https://github.com/payara/Payara/pull/5804[[FISH-6041]] Microprofile Config getOptionalValue Method throws NoSuchElementException if the environment value does not exist

https://github.com/payara/Payara/pull/5664[[FISH-6027]] Remote EJB \+ JDK 17 does not work

https://github.com/payara/Payara/pull/5692[[[FISH-6024]] The 'restart-deployment-group --rolling=false' command does not work with custom Node Directory

https://github.com/payara/ecosystem-rest-ssl-configuration/pull/3[[FISH-6023]] Reduce the log level in our JAX-RS extension as it is causing log file pollution

https://github.com/payara/Payara/pull/5615[[FISH-6019]] Fix XML Schema Issue

https://github.com/payara/Payara/pull/5631[[FISH-6009]] Kubernetes Discovery Mode on Payara Server Doesn't Work Anymore

https://github.com/payara/Payara/pull/5663[[FISH-5990]] Make DnsContextFactory JNDI DirContext instantiable on JDK 17

https://github.com/payara/Payara/pull/5626[[FISH-5939]] Application Redeployment Breaks virtual server When Using it as Default Module

https://github.com/payara/Payara/pull/5623[[FISH-5898]] Unable to Deploy Application on Payara 5 Which is Developed using Jakarta EE 9.1  and Primefaces 10

https://github.com/payara/Notifiers/pull/22[[FISH-5787]] Microsoft Teams Notifier cannot be Configured on User-Created Instance due to an Invalid Command Option

https://github.com/payara/Payara/pull/5606[[FISH-5676]] Cannot Apply Default Values in @DataSourceDefinition URL via Variable Expansion

== Component Upgrades

https://github.com/payara/Payara/pull/5784[[FISH-6321]] Upgrade EclipseLink to 4.0.0-M3

https://github.com/payara/Payara/pull/5777[[FISH-6283]] Port Upgrade Felix to 7.0.1 to Payara 6

https://github.com/payara/Payara-Community-Documentation/pull/309[[FISH-6263]] Smack 4.3.4

https://github.com/payara/Payara/pull/5734[[FISH-6262]] Json-smart 2.4.8

[FISH-6251] Update Hibernate-Validator to 8.0.0.Alpha3

https://github.com/payara/Payara/pull/5659[[[FISH-6211]] https://github.com/lprimak[[Community Contribution - Lenny Primak]] ASM 9.2

https://github.com/payara/Payara/pull/5778[[FISH-6109]] Upgrade to latest Hazelcast 5

https://github.com/payara/Payara/pull/5760[[FISH-6080]] Upgrade Jakarta XML Binding 4.0

https://github.com/payara/Payara/pull/5778[[FISH-6079]] Upgrade to Jakarta JSON-B 3.0 and latest Yasson

https://github.com/payara/Payara/pull/5702[[FISH-6078]] Upgrade to Jakarta Mail 2.1

https://github.com/payara/Payara/pull/5671[[FISH-6077]] Upgrade Jakarta Messaging 3.1 and integrate latest OpenMQ

https://github.com/payara/Payara/pull/5836[[FISH-6398]] Update Docker Images to JDK Versions 11.0.15, 17.0.3, and 8u332
