[[upgrade-advisor-tool]]
= Upgrade Advisor Tool

This is a CLI (Command Line Interface) tool to advise about changes made in Jakarta EE 10 that affect applications based on Jakarta EE 8. The purpose of the tool is to summarize all changes that affect your application from the different Jakarta EE Specs with messages on the logs indicating what code was removed or changed for the different specs listed here: https://jakarta.ee/specifications/

[[how-to-use]]
== How to use

You can use the tool directly from the command line without configuring anything on your local environment. The tool is deployed to Maven Central and so no extra repositories should need to be configured: https://mvnrepository.com/artifact/fish.payara.advisor/advisor-maven-plugin[Upgrade Advisor Tool on Maven Central]. 

You must go to the root of your project folder and execute the following command:

[source, shell]
----
mvn fish.payara.advisor:advisor-maven-plugin:1.0:advise
----

Then you will see results from logs:

[source, shell]
----
[INFO] Showing Advisories
[INFO] ***************
[INFO] Line of code: 14 | Expression: public String registerConfigProvider(String s, Map map, String s1, String s2, String s3)
Source file: TestAuthConfigFactory.java
Jakarta Authentication 3.0 Issue # 87
 jakarta.security.auth.message.config.AuthConfigFactory.registerConfigProvider was changed from
 String registerConfigProvider(String className, Map properties, String layer, String appContext, String description)
 to
 String registerConfigProvider(String className, Map<String, String> properties, String layer, String appContext, String description)
This issue won't affect your application.
 The recommendation is to take care of the generic version.
[INFO] Line of code: 20 | Expression: public Class[] getSupportedMessageTypes()
Source file: TestAuthModule.java
Jakarta Authentication 3.0 Issue # 87
 jakarta.security.auth.message.module.ServerAuthModule.getSupportedMessageTypes was changed from
 Class[] getSupportedMessageTypes()
 to
 Class<?>[] getSupportedMessageTypes()
----

[[structure-of-advisor-logs]]
=== Structure of the Upgrade Advisor logs

The structure of the advisor messages include the following:

|===
|Structure | Description

|line 1
|[Type of message] + [Line of code] + [Expression]

|Type of message
|This can be INFO, WARNING or ERROR

|Line of code
|To indicate where to locate the occurrence of the advisory

|Expression
|The Code Expression that cause the ocurrence of the advisory, for example: method declaration, method call, annotation property, etc.

|
|

|line 2
|[Source file]

|Source file
|The file name where to locate the advisory

|
|

|line 3
|[Issue message]

|Issue message
|Message to indicate what issue is causing the advisory

|
|

|line 4
|[How to proceed message]

|How to proceed message
|Message to indicate what is the recommended way to proceed with the advisory to make the application compatible with Jakarta 10

|===

The following are examples of the different severity levels output by the tool.

[[example-1-info-message]]
==== Example INFO message

[source, shell]
----
[INFO] Line of code: 3 | Expression: jakarta.ws.rs.ext.ContextResolver
Source file: CustomResolverWithMapper.java
Jakarta RESTful 3.1
 JSON-B entity providers must favor Jsonb instances provided by ContextResolver<Jsonb>
----

[[example-2-warning-message]]
==== Example WARNING message

[source, shell]
----
[WARNING] Line of code: 32 | Expression: new NewCookie(cookie)
Source file: HelloResource.java
Jakarta RESTful 3.1
 Constructors for NewCookie class were deprecated.
----

[[example-3-error-message]]
==== Example ERROR message

[source, shell]
----
[ERROR] Line of code: 23 | Expression: myMethodExpression.isParmetersProvided()
Source file: TestBatchlet.java
Jakarta Expression Language 5.0 issue 117
 MethodExpression.isParmetersProvided() has been removed.
----


=== Code Example

To exemplify this better, suppose you have the following code:

[source, java]
----
package jsonb;                                      

import jakarta.json.bind.annotation.JsonbProperty;

public class JsonBeanTest {
    
    @JsonbProperty(nillable = true)
    private String name;
}
----

For Jakarta EE 10 the property nillable was marked as deprecated, as a modification for Jakarta JSON Binding 3.0, you can check here: https://jakarta.ee/specifications/jsonb/3.0/[Jakarta JSON Binding 3.0]

Now with the use of the Upgrade Advisor Tool we can get the advice related to this change as follows:

[source, shell]
----
[WARNING] Line of code: 7 | Expression: @JsonbProperty(nillable = true)
Source file: JsonBeanTest.java
Jakarta JSON Binding 3.0
 property nillable from the JsonbProperty annotation was deprecated.
This issue won't affect your application.
 and the recommendation is to stop use of the deprecated property nillable and
 start to use the JsonbNillable annotation.
----

From the message we can see that the recommendation is to start to use the new annotation `JsonbNillable`. Then we can have the following code by applying the advise from the tool:

[source, java]
----
package jsonb;

import jakarta.json.bind.annotation.JsonbNillable;
import jakarta.json.bind.annotation.JsonbProperty;

public class JsonBeanTest {
    
    @JsonbProperty
    @JsonbNillable
    private String name;
}
----

In conclusion this tool will help us to make our old Jakarta EE 8 applications compatible with the lastest changes made in Jakarta EE 10.


