[[eclipse-microprofile]]
= Eclipse MicroProfile Dependencies Mapping
:ordinal: 2

This section details all dependencies linked to Eclipse MicroProfile specifications.

[[io-opentracing]]
== `io.opentracing`

// [[opentracing-api]]
=== *opentracing-api*

**Version**: 0.33.0

[source,xml]
----
<dependency>
    <groupId>io.opentracing</groupId>
    <artifactId>opentracing-api</artifactId>
    <version>0.33.0</version>
</dependency>
----


[[org-eclipse-microprofile-config]]
== `org.eclipse.microprofile.config`

// [[microprofile-config-api]]
=== *microprofile-config-api*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.config</groupId>
    <artifactId>microprofile-config-api</artifactId>
    <version>3.1.1</version>
</dependency>
----


[[org-eclipse-microprofile-fault-tolerance]]
== `org.eclipse.microprofile.fault-tolerance`

// [[microprofile-fault-tolerance-api]]
=== *microprofile-fault-tolerance-api*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.fault-tolerance</groupId>
    <artifactId>microprofile-fault-tolerance-api</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-eclipse-microprofile-health]]
== `org.eclipse.microprofile.health`

// [[microprofile-health-api]]
=== *microprofile-health-api*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.health</groupId>
    <artifactId>microprofile-health-api</artifactId>
    <version>4.0.1</version>
</dependency>
----


[[org-eclipse-microprofile-jwt]]
== `org.eclipse.microprofile.jwt`

// [[microprofile-jwt-auth-api]]
=== *microprofile-jwt-auth-api*

**Version**: 2.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.jwt</groupId>
    <artifactId>microprofile-jwt-auth-api</artifactId>
    <version>2.1</version>
</dependency>
----


[[org-eclipse-microprofile-metrics]]
== `org.eclipse.microprofile.metrics`

// [[microprofile-metrics-api]]
=== *microprofile-metrics-api*

**Version**: 5.1.2

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.metrics</groupId>
    <artifactId>microprofile-metrics-api</artifactId>
    <version>5.1.2</version>
</dependency>
----


[[org-eclipse-microprofile-openapi]]
== `org.eclipse.microprofile.openapi`

// [[microprofile-openapi-api]]
=== *microprofile-openapi-api*

**Version**: 3.1.2

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.openapi</groupId>
    <artifactId>microprofile-openapi-api</artifactId>
    <version>3.1.2</version>
</dependency>
----


[[org-eclipse-microprofile-opentracing]]
== `org.eclipse.microprofile.opentracing`

// [[microprofile-opentracing-api]]
=== *microprofile-opentracing-api*

**Version**: 3.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.opentracing</groupId>
    <artifactId>microprofile-opentracing-api</artifactId>
    <version>3.0</version>
</dependency>
----


[[org-eclipse-microprofile-rest-client]]
== `org.eclipse.microprofile.rest.client`

// [[microprofile-rest-client-api]]
=== *microprofile-rest-client-api*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.microprofile.rest.client</groupId>
    <artifactId>microprofile-rest-client-api</artifactId>
    <version>3.0.1</version>
</dependency>
----


