[[internal-dependencies]]
= Internal Dependencies
:ordinal: 3

This section details all Payara Platform internal dependencies.

[[fish-payara-api]]
== `fish.payara.api`

// [[payara-api]]
=== *payara-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.api</groupId>
    <artifactId>payara-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-extensions-certificate-management]]
== `fish.payara.extensions.certificate-management`

// [[certificate-management-admin]]
=== *certificate-management-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[certificate-management-cli]]
=== *certificate-management-cli*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-cli</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[certificate-management-common]]
=== *certificate-management-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[certificate-management-console-plugin]]
=== *certificate-management-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.certificate-management</groupId>
    <artifactId>certificate-management-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-extensions-notifiers]]
== `fish.payara.extensions.notifiers`

// [[datadog-notifier-core]]
=== *datadog-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>datadog-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[discord-notifier-core]]
=== *discord-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>discord-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[email-notifier-core]]
=== *email-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>email-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[newrelic-notifier-core]]
=== *newrelic-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>newrelic-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[slack-notifier-core]]
=== *slack-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>slack-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[snmp-notifier-core]]
=== *snmp-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>snmp-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[snmp4j-repackaged]]
=== *snmp4j-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>snmp4j-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[teams-notifier-core]]
=== *teams-notifier-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extensions.notifiers</groupId>
    <artifactId>teams-notifier-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-extras]]
== `fish.payara.extras`

// [[payara-diagnostics-tool]]
=== *payara-diagnostics-tool*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-diagnostics-tool</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-upgrade-tool]]
=== *payara-upgrade-tool*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-upgrade-tool</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-monitoring-console]]
== `fish.payara.monitoring-console`

// [[monitoring-console-api]]
=== *monitoring-console-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.monitoring-console</groupId>
    <artifactId>monitoring-console-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


// [[monitoring-console-process]]
=== *monitoring-console-process*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.monitoring-console</groupId>
    <artifactId>monitoring-console-process</artifactId>
    <version>3.0.0</version>
</dependency>
----


// [[monitoring-console-webapp]]
=== *monitoring-console-webapp*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.monitoring-console</groupId>
    <artifactId>monitoring-console-webapp</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[fish-payara-security-connectors]]
== `fish.payara.security.connectors`

// [[security-connector-oauth2-client]]
=== *security-connector-oauth2-client*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oauth2-client</artifactId>
    <version>4.0.0</version>
</dependency>
----


// [[security-connector-oidc-client]]
=== *security-connector-oidc-client*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connector-oidc-client</artifactId>
    <version>4.0.0</version>
</dependency>
----


// [[security-connectors-api]]
=== *security-connectors-api*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.security.connectors</groupId>
    <artifactId>security-connectors-api</artifactId>
    <version>4.0.0</version>
</dependency>
----


[[fish-payara-server-appclient]]
== `fish.payara.server.appclient`

// [[acc-config]]
=== *acc-config*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>acc-config</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appclient-scripts]]
=== *appclient-scripts*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>appclient-scripts</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-client]]
=== *gf-client*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>gf-client</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-client-l10n]]
=== *gf-client-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>gf-client-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-client-module]]
=== *gf-client-module*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>gf-client-module</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-client-module-l10n]]
=== *gf-client-module-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.appclient</groupId>
    <artifactId>gf-client-module-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-admin]]
== `fish.payara.server.internal.admin`

// [[admin-cli]]
=== *admin-cli*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>admin-cli</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[admin-core]]
=== *admin-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>admin-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[admin-util]]
=== *admin-util*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>admin-util</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appserver-cli]]
=== *appserver-cli*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>appserver-cli</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appserver-domain]]
=== *appserver-domain*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>appserver-domain</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appserver-domain-web]]
=== *appserver-domain-web*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>appserver-domain-web</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[backup]]
=== *backup*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>backup</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[backup-l10n]]
=== *backup-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>backup-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cli-optional]]
=== *cli-optional*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>cli-optional</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cli-optional-l10n]]
=== *cli-optional-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>cli-optional-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[config-api]]
=== *config-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>config-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[launcher]]
=== *launcher*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>launcher</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[monitoring-core]]
=== *monitoring-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>monitoring-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[monitoring-core-l10n]]
=== *monitoring-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>monitoring-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[production-domain]]
=== *production-domain*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>production-domain</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[production-domain-web]]
=== *production-domain-web*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>production-domain-web</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[server-mgmt]]
=== *server-mgmt*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admin</groupId>
    <artifactId>server-mgmt</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-admingui]]
== `fish.payara.server.internal.admingui`

// [[cdieventbus-notifier-console-plugin]]
=== *cdieventbus-notifier-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cdieventbus-notifier-console-plugin-l10n]]
=== *cdieventbus-notifier-console-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>cdieventbus-notifier-console-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-cluster-plugin]]
=== *console-cluster-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-cluster-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-cluster-plugin-l10n]]
=== *console-cluster-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-cluster-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-common]]
=== *console-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-common-full-plugin]]
=== *console-common-full-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-common-full-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-common-full-plugin-l10n]]
=== *console-common-full-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-common-full-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-common-l10n]]
=== *console-common-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-common-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-concurrent-plugin]]
=== *console-concurrent-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-concurrent-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-concurrent-plugin-l10n]]
=== *console-concurrent-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-concurrent-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-corba-plugin]]
=== *console-corba-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-corba-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-corba-plugin-l10n]]
=== *console-corba-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-corba-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-core-l10n]]
=== *console-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-ejb-lite-plugin]]
=== *console-ejb-lite-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-lite-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-ejb-lite-plugin-l10n]]
=== *console-ejb-lite-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-lite-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-ejb-plugin]]
=== *console-ejb-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-ejb-plugin-l10n]]
=== *console-ejb-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-ejb-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jca-plugin]]
=== *console-jca-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jca-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jca-plugin-l10n]]
=== *console-jca-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jca-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jdbc-plugin]]
=== *console-jdbc-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jdbc-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jdbc-plugin-l10n]]
=== *console-jdbc-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jdbc-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jms-plugin]]
=== *console-jms-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jms-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jms-plugin-l10n]]
=== *console-jms-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jms-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jts-plugin]]
=== *console-jts-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jts-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-jts-plugin-l10n]]
=== *console-jts-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-jts-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-payara-branding-plugin-l10n]]
=== *console-payara-branding-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-payara-branding-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-payara-enterprise-branding-plugin]]
=== *console-payara-enterprise-branding-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-payara-enterprise-branding-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-plugin-service]]
=== *console-plugin-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-plugin-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-reference-manual-plugin]]
=== *console-reference-manual-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-reference-manual-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-web-plugin]]
=== *console-web-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-web-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[console-web-plugin-l10n]]
=== *console-web-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>console-web-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[dataprovider]]
=== *dataprovider*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>dataprovider</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[dist-fragment]]
=== *dist-fragment*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>dist-fragment</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[eventbus-notifier-console-plugin]]
=== *eventbus-notifier-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>eventbus-notifier-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[eventbus-notifier-console-plugin-l10n]]
=== *eventbus-notifier-console-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>eventbus-notifier-console-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[faces-compat]]
=== *faces-compat*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>faces-compat</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-admingui-connector]]
=== *gf-admingui-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>gf-admingui-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-service-console-plugin]]
=== *healthcheck-service-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>healthcheck-service-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-service-console-plugin-l10n]]
=== *healthcheck-service-console-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>healthcheck-service-console-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmx-monitoring-plugin]]
=== *jmx-monitoring-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jmx-monitoring-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmx-monitoring-plugin-l10n]]
=== *jmx-monitoring-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>jmx-monitoring-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-console-plugin]]
=== *microprofile-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>microprofile-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-console-plugin-l10n]]
=== *microprofile-console-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>microprofile-console-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-console-extras]]
=== *payara-console-extras*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>payara-console-extras</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-console-extras-l10n]]
=== *payara-console-extras-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>payara-console-extras-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-insight-console-plugin]]
=== *payara-insight-console-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>payara-insight-console-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[rest-monitoring-plugin]]
=== *rest-monitoring-plugin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>rest-monitoring-plugin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webui-jsf-plugin-l10n]]
=== *webui-jsf-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>webui-jsf-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webui-jsf-suntheme-plugin-l10n]]
=== *webui-jsf-suntheme-plugin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.admingui</groupId>
    <artifactId>webui-jsf-suntheme-plugin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-appclient-server]]
== `fish.payara.server.internal.appclient.server`

// [[appclient-connector]]
=== *appclient-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.appclient.server</groupId>
    <artifactId>appclient-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appclient-server-core]]
=== *appclient-server-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.appclient.server</groupId>
    <artifactId>appclient-server-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appclient-server-core-l10n]]
=== *appclient-server-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.appclient.server</groupId>
    <artifactId>appclient-server-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-batch]]
== `fish.payara.server.internal.batch`

// [[batch-databases]]
=== *batch-databases*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>batch-databases</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-batch-commands]]
=== *glassfish-batch-commands*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-commands</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-batch-connector]]
=== *glassfish-batch-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>glassfish-batch-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-jbatch]]
=== *payara-jbatch*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.batch</groupId>
    <artifactId>payara-jbatch</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-cluster]]
== `fish.payara.server.internal.cluster`

// [[cluster-admin]]
=== *cluster-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.cluster</groupId>
    <artifactId>cluster-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cluster-cli]]
=== *cluster-cli*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.cluster</groupId>
    <artifactId>cluster-cli</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cluster-common]]
=== *cluster-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.cluster</groupId>
    <artifactId>cluster-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cluster-ssh]]
=== *cluster-ssh*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.cluster</groupId>
    <artifactId>cluster-ssh</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cluster-ssh-l10n]]
=== *cluster-ssh-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.cluster</groupId>
    <artifactId>cluster-ssh-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-common]]
== `fish.payara.server.internal.common`

// [[amx-core]]
=== *amx-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>amx-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[amx-javaee]]
=== *amx-javaee*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>amx-javaee</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[annotation-framework]]
=== *annotation-framework*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>annotation-framework</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[annotation-framework-l10n]]
=== *annotation-framework-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>annotation-framework-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[common-util]]
=== *common-util*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>common-util</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[container-common]]
=== *container-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>container-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[container-common-l10n]]
=== *container-common-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>container-common-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-api]]
=== *glassfish-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>glassfish-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ee-api]]
=== *glassfish-ee-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>glassfish-ee-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-mbeanserver]]
=== *glassfish-mbeanserver*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>glassfish-mbeanserver</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-naming]]
=== *glassfish-naming*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>glassfish-naming</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-naming-l10n]]
=== *glassfish-naming-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>glassfish-naming-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[internal-api]]
=== *internal-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>internal-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[scattered-archive-api]]
=== *scattered-archive-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>scattered-archive-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[simple-glassfish-api]]
=== *simple-glassfish-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>simple-glassfish-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[stats77]]
=== *stats77*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>stats77</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[stats77-l10n]]
=== *stats77-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.common</groupId>
    <artifactId>stats77-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-concurrent]]
== `fish.payara.server.internal.concurrent`

// [[concurrent-connector]]
=== *concurrent-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[concurrent-connector-l10n]]
=== *concurrent-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[concurrent-impl]]
=== *concurrent-impl*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[concurrent-impl-l10n]]
=== *concurrent-impl-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.concurrent</groupId>
    <artifactId>concurrent-impl-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-connectors]]
== `fish.payara.server.internal.connectors`

// [[connectors-admin]]
=== *connectors-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-admin-l10n]]
=== *connectors-admin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-admin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-inbound-runtime]]
=== *connectors-inbound-runtime*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-inbound-runtime</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-inbound-runtime-l10n]]
=== *connectors-inbound-runtime-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-inbound-runtime-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-internal-api]]
=== *connectors-internal-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-internal-api-l10n]]
=== *connectors-internal-api-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-internal-api-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-runtime]]
=== *connectors-runtime*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[connectors-runtime-l10n]]
=== *connectors-runtime-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>connectors-runtime-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[descriptors]]
=== *descriptors*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>descriptors</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-connectors-connector]]
=== *gf-connectors-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>gf-connectors-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[work-management]]
=== *work-management*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>work-management</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[work-management-l10n]]
=== *work-management-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.connectors</groupId>
    <artifactId>work-management-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-core]]
== `fish.payara.server.internal.core`

// [[api-exporter]]
=== *api-exporter*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>api-exporter</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish]]
=== *glassfish*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>glassfish</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jakartaee-kernel]]
=== *jakartaee-kernel*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>jakartaee-kernel</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[kernel]]
=== *kernel*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>kernel</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[logging]]
=== *logging*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.core</groupId>
    <artifactId>logging</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-data]]
== `fish.payara.server.internal.data`

// [[data-core]]
=== *data-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.data</groupId>
    <artifactId>data-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-deployment]]
== `fish.payara.server.internal.deployment`

// [[deployment-admin]]
=== *deployment-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-autodeploy]]
=== *deployment-autodeploy*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-autodeploy</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-client]]
=== *deployment-client*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-client</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-client-l10n]]
=== *deployment-client-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-client-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-common]]
=== *deployment-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-javaee-core]]
=== *deployment-javaee-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-javaee-core-l10n]]
=== *deployment-javaee-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-javaee-full]]
=== *deployment-javaee-full*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-full</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[deployment-javaee-full-l10n]]
=== *deployment-javaee-full-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>deployment-javaee-full-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[dol]]
=== *dol*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>dol</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[dol-l10n]]
=== *dol-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>dol-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[dtds]]
=== *dtds*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>dtds</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[schemas]]
=== *schemas*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>schemas</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[sun-as-jsr88-dm-frag]]
=== *sun-as-jsr88-dm-frag*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.deployment</groupId>
    <artifactId>sun-as-jsr88-dm-frag</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-docker]]
== `fish.payara.server.internal.docker`

// [[docker]]
=== *docker*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.docker</groupId>
    <artifactId>docker</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-ejb]]
== `fish.payara.server.internal.ejb`

// [[ejb-client]]
=== *ejb-client*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-client</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-container]]
=== *ejb-container*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-container</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-container-l10n]]
=== *ejb-container-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-container-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-full-container]]
=== *ejb-full-container*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-full-container</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-http-admin]]
=== *ejb-http-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-http-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-internal-api]]
=== *ejb-internal-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-internal-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-opentracing]]
=== *ejb-opentracing*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-opentracing</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-timer-databases]]
=== *ejb-timer-databases*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-timer-databases</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-timer-service-app]]
=== *ejb-timer-service-app*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>ejb-timer-service-app</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-ejb-connector]]
=== *gf-ejb-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>gf-ejb-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-ejb-connector-l10n]]
=== *gf-ejb-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ejb</groupId>
    <artifactId>gf-ejb-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-extras]]
== `fish.payara.server.internal.extras`

// [[appserv-rt-frag]]
=== *appserv-rt-frag*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>appserv-rt-frag</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-embedded-shell-frag]]
=== *glassfish-embedded-shell-frag*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>glassfish-embedded-shell-frag</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-embedded-static-shell-frag]]
=== *glassfish-embedded-static-shell-frag*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>glassfish-embedded-static-shell-frag</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[javaee-frag]]
=== *javaee-frag*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>javaee-frag</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-micro-boot]]
=== *payara-micro-boot*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>payara-micro-boot</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-micro-core]]
=== *payara-micro-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.extras</groupId>
    <artifactId>payara-micro-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-featuresets]]
== `fish.payara.server.internal.featuresets`

// [[minnow]]
=== *minnow*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>minnow</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[minnow-ml]]
=== *minnow-ml*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>minnow-ml</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-featureset]]
=== *payara-featureset*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>payara-featureset</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-ml-featureset]]
=== *payara-ml-featureset*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>payara-ml-featureset</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-web-featureset]]
=== *payara-web-featureset*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>payara-web-featureset</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-web-ml-featureset]]
=== *payara-web-ml-featureset*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.featuresets</groupId>
    <artifactId>payara-web-ml-featureset</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-flashlight]]
== `fish.payara.server.internal.flashlight`

// [[flashlight-framework]]
=== *flashlight-framework*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.flashlight</groupId>
    <artifactId>flashlight-framework</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-grizzly]]
== `fish.payara.server.internal.grizzly`

// [[glassfish-grizzly-container]]
=== *glassfish-grizzly-container*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.grizzly</groupId>
    <artifactId>glassfish-grizzly-container</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-grizzly-extra-all]]
=== *glassfish-grizzly-extra-all*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.grizzly</groupId>
    <artifactId>glassfish-grizzly-extra-all</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[grizzly-config]]
=== *grizzly-config*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.grizzly</groupId>
    <artifactId>grizzly-config</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[nucleus-grizzly-all]]
=== *nucleus-grizzly-all*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.grizzly</groupId>
    <artifactId>nucleus-grizzly-all</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-ha]]
== `fish.payara.server.internal.ha`

// [[ha-file-store]]
=== *ha-file-store*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ha</groupId>
    <artifactId>ha-file-store</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ha-hazelcast-store]]
=== *ha-hazelcast-store*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.ha</groupId>
    <artifactId>ha-hazelcast-store</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-hk2]]
== `fish.payara.server.internal.hk2`

// [[config-types]]
=== *config-types*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.hk2</groupId>
    <artifactId>config-types</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[hk2-config]]
=== *hk2-config*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.hk2</groupId>
    <artifactId>hk2-config</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-jdbc]]
== `fish.payara.server.internal.jdbc`

// [[jdbc-admin]]
=== *jdbc-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jdbc-admin-l10n]]
=== *jdbc-admin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-admin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jdbc-config]]
=== *jdbc-config*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-config</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jdbc-config-l10n]]
=== *jdbc-config-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-config-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jdbc-runtime]]
=== *jdbc-runtime*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-runtime</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jdbc-runtime-l10n]]
=== *jdbc-runtime-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>jdbc-runtime-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[templates]]
=== *templates*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc</groupId>
    <artifactId>templates</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-jdbc-jdbc-ra-jdbc-ra-distribution]]
== `fish.payara.server.internal.jdbc.jdbc-ra.jdbc-ra-distribution`

// [[jdbc-ra]]
=== *jdbc-ra*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jdbc.jdbc-ra.jdbc-ra-distribution</groupId>
    <artifactId>jdbc-ra</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-jms]]
== `fish.payara.server.internal.jms`

// [[gf-jms-connector]]
=== *gf-jms-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-jms-connector-l10n]]
=== *gf-jms-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-jms-injection]]
=== *gf-jms-injection*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-jms-injection-l10n]]
=== *gf-jms-injection-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>gf-jms-injection-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jms-admin]]
=== *jms-admin*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-admin</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jms-admin-l10n]]
=== *jms-admin-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-admin-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jms-core]]
=== *jms-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jms-core-l10n]]
=== *jms-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jms-handlers]]
=== *jms-handlers*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.jms</groupId>
    <artifactId>jms-handlers</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-monitoring-console]]
== `fish.payara.server.internal.monitoring-console`

// [[monitoring-console-core]]
=== *monitoring-console-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.monitoring-console</groupId>
    <artifactId>monitoring-console-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-orb]]
== `fish.payara.server.internal.orb`

// [[orb-connector]]
=== *orb-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.orb</groupId>
    <artifactId>orb-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[orb-connector-l10n]]
=== *orb-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.orb</groupId>
    <artifactId>orb-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[orb-enabler]]
=== *orb-enabler*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.orb</groupId>
    <artifactId>orb-enabler</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[orb-iiop]]
=== *orb-iiop*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.orb</groupId>
    <artifactId>orb-iiop</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-packager]]
== `fish.payara.server.internal.packager`

// [[ant]]
=== *ant*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>ant</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appserver-base]]
=== *appserver-base*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>appserver-base</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[appserver-core]]
=== *appserver-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>appserver-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[asadmin-recorder]]
=== *asadmin-recorder*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>asadmin-recorder</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cdi-auth-roles]]
=== *cdi-auth-roles*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[certificate-management]]
=== *certificate-management*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>certificate-management</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cpu-core-reporting-package]]
=== *cpu-core-reporting-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>cpu-core-reporting-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[data]]
=== *data*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>data</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[diagnostics-tool]]
=== *diagnostics-tool*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>diagnostics-tool</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[docker]]
=== *docker*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>docker</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[environment-warning]]
=== *environment-warning*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>environment-warning</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[felix]]
=== *felix*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>felix</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-appclient]]
=== *glassfish-appclient*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-appclient</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-appclient-l10n]]
=== *glassfish-appclient-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-appclient-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-cluster]]
=== *glassfish-cluster*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-cluster</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-cluster-l10n]]
=== *glassfish-cluster-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-cluster-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common]]
=== *glassfish-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common-full]]
=== *glassfish-common-full*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common-full</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common-full-l10n]]
=== *glassfish-common-full-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common-full-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common-l10n]]
=== *glassfish-common-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common-web]]
=== *glassfish-common-web*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common-web</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-common-web-l10n]]
=== *glassfish-common-web-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-common-web-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-corba]]
=== *glassfish-corba*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-corba</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-corba-base]]
=== *glassfish-corba-base*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-corba-base</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ejb]]
=== *glassfish-ejb*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-ejb</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ejb-l10n]]
=== *glassfish-ejb-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-ejb-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ejb-lite]]
=== *glassfish-ejb-lite*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-ejb-lite</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ejb-lite-l10n]]
=== *glassfish-ejb-lite-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-ejb-lite-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-entitybeans-container]]
=== *glassfish-entitybeans-container*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-entitybeans-container</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-grizzly]]
=== *glassfish-grizzly*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-grizzly</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-grizzly-full]]
=== *glassfish-grizzly-full*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-grizzly-full</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-gui]]
=== *glassfish-gui*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-gui</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-gui-l10n]]
=== *glassfish-gui-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-gui-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-ha]]
=== *glassfish-ha*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-ha</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-hk2]]
=== *glassfish-hk2*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-hk2</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jca]]
=== *glassfish-jca*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jca</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jca-l10n]]
=== *glassfish-jca-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jca-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jcdi]]
=== *glassfish-jcdi*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jcdi</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jdbc]]
=== *glassfish-jdbc*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jdbc</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jdbc-l10n]]
=== *glassfish-jdbc-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jdbc-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jms]]
=== *glassfish-jms*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jms</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jms-l10n]]
=== *glassfish-jms-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jms-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jmx]]
=== *glassfish-jmx*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jmx</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jpa]]
=== *glassfish-jpa*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jpa</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jpa-l10n]]
=== *glassfish-jpa-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jpa-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jsf]]
=== *glassfish-jsf*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jsf</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jta]]
=== *glassfish-jta*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jta</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jta-l10n]]
=== *glassfish-jta-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jta-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jts]]
=== *glassfish-jts*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jts</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-jts-l10n]]
=== *glassfish-jts-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-jts-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-management]]
=== *glassfish-management*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-management</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-management-l10n]]
=== *glassfish-management-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-management-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-nucleus]]
=== *glassfish-nucleus*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-nucleus</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-nucleus-l10n]]
=== *glassfish-nucleus-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-nucleus-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-osgi]]
=== *glassfish-osgi*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-osgi</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-web]]
=== *glassfish-web*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-web</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-web-l10n]]
=== *glassfish-web-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>glassfish-web-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[h2db]]
=== *h2db*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>h2db</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[h2db-repackaged]]
=== *h2db-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>h2db-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[hazelcast]]
=== *hazelcast*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>hazelcast</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[hazelcast-l10n]]
=== *hazelcast-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>hazelcast-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck]]
=== *healthcheck*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>healthcheck</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-package]]
=== *healthcheck-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>healthcheck-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jakarta-ee11-shim]]
=== *jakarta-ee11-shim*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jakarta-ee11-shim</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jakarta-ee9-shim]]
=== *jakarta-ee9-shim*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jakarta-ee9-shim</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jakarta-data-api]]
=== *jakarta.data-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jakarta.data-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jcip-annotations-repackaged]]
=== *jcip-annotations-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jcip-annotations-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jersey]]
=== *jersey*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jersey</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmsra]]
=== *jmsra*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmsra</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmx-monitoring-package]]
=== *jmx-monitoring-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmx-monitoring-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmxremote-optional-repackaged]]
=== *jmxremote_optional-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>jmxremote_optional-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[json]]
=== *json*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>json</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[legal-fragment]]
=== *legal-fragment*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>legal-fragment</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[libpam4j-repackaged]]
=== *libpam4j-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>libpam4j-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[metro]]
=== *metro*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>metro</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[metro-l10n]]
=== *metro-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>metro-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[metro-xmlsec-repackaged]]
=== *metro-xmlsec-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>metro-xmlsec-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-package]]
=== *microprofile-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>microprofile-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[monitoring-console]]
=== *monitoring-console*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>monitoring-console</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[mq]]
=== *mq*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>mq</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification]]
=== *notification*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-datadog]]
=== *notification-datadog*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-datadog</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-discord]]
=== *notification-discord*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-discord</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-email]]
=== *notification-email*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-email</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-jms]]
=== *notification-jms*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-jms</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-newrelic]]
=== *notification-newrelic*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-newrelic</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-package]]
=== *notification-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-slack]]
=== *notification-slack*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-slack</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-snmp]]
=== *notification-snmp*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-snmp</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-teams]]
=== *notification-teams*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>notification-teams</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[opentelemetry-repackaged]]
=== *opentelemetry-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>opentelemetry-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[opentracing-jaxws-package]]
=== *opentracing-jaxws-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>opentracing-jaxws-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[opentracing-repackaged]]
=== *opentracing-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>opentracing-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-api]]
=== *payara-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-api-package]]
=== *payara-api-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-api-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-executor-service]]
=== *payara-executor-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-executor-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-micro-package]]
=== *payara-micro-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-micro-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-mvc]]
=== *payara-mvc*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-mvc</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-rest-endpoints]]
=== *payara-rest-endpoints*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>payara-rest-endpoints</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[phonehome]]
=== *phonehome*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>phonehome</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[requesttracing]]
=== *requesttracing*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>requesttracing</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[requesttracing-package]]
=== *requesttracing-package*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>requesttracing-package</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[rest-monitoring]]
=== *rest-monitoring*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>rest-monitoring</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[tiger-types]]
=== *tiger-types*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>tiger-types</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[trilead-ssh2-repackaged]]
=== *trilead-ssh2-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>trilead-ssh2-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[upgrade-tool]]
=== *upgrade-tool*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.packager</groupId>
    <artifactId>upgrade-tool</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-payara-appserver-modules]]
== `fish.payara.server.internal.payara-appserver-modules`

// [[cdi-auth-roles]]
=== *cdi-auth-roles*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cdi-auth-roles</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[cpu-core-reporting]]
=== *cpu-core-reporting*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>cpu-core-reporting</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[environment-warning]]
=== *environment-warning*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>environment-warning</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[hazelcast-eclipselink-coordination]]
=== *hazelcast-eclipselink-coordination*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-eclipselink-coordination</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[hazelcast-ejb-timer]]
=== *hazelcast-ejb-timer*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>hazelcast-ejb-timer</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-checker]]
=== *healthcheck-checker*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>healthcheck-checker</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-metrics]]
=== *healthcheck-metrics*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>healthcheck-metrics</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jaspic-servlet-utils]]
=== *jaspic-servlet-utils*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaspic-servlet-utils</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jaxrs-client-tracing]]
=== *jaxrs-client-tracing*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jaxrs-client-tracing</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jmx-monitoring]]
=== *jmx-monitoring*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>jmx-monitoring</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-common]]
=== *microprofile-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-config]]
=== *microprofile-config*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-config-extensions]]
=== *microprofile-config-extensions*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-config-extensions</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-connector]]
=== *microprofile-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-fault-tolerance]]
=== *microprofile-fault-tolerance*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-fault-tolerance</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-healthcheck]]
=== *microprofile-healthcheck*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-healthcheck</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-jwt-auth]]
=== *microprofile-jwt-auth*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-jwt-auth</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-metrics]]
=== *microprofile-metrics*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-metrics</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-openapi]]
=== *microprofile-openapi*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-openapi</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-opentracing]]
=== *microprofile-opentracing*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-opentracing</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-rest-client]]
=== *microprofile-rest-client*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-rest-client</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-telemetry]]
=== *microprofile-telemetry*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>microprofile-telemetry</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-jms-core]]
=== *notification-jms-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>notification-jms-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[opentracing-jaxws]]
=== *opentracing-jaxws*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>opentracing-jaxws</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-jsr107]]
=== *payara-jsr107*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-jsr107</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-micro-cdi]]
=== *payara-micro-cdi*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-cdi</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-micro-service]]
=== *payara-micro-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-micro-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-rest-endpoints]]
=== *payara-rest-endpoints*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>payara-rest-endpoints</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[rest-client-ssl]]
=== *rest-client-ssl*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>rest-client-ssl</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[rest-monitoring-service]]
=== *rest-monitoring-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-appserver-modules</groupId>
    <artifactId>rest-monitoring-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-payara-modules]]
== `fish.payara.server.internal.payara-modules`

// [[hazelcast-bootstrap]]
=== *hazelcast-bootstrap*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>hazelcast-bootstrap</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-core]]
=== *healthcheck-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>healthcheck-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-cpool]]
=== *healthcheck-cpool*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>healthcheck-cpool</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[healthcheck-stuck]]
=== *healthcheck-stuck*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>healthcheck-stuck</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jsr107-repackaged]]
=== *jsr107-repackaged*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>jsr107-repackaged</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[microprofile-config-service]]
=== *microprofile-config-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>microprofile-config-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-cdi-eventbus-core]]
=== *notification-cdi-eventbus-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-cdi-eventbus-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-core]]
=== *notification-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[notification-eventbus-core]]
=== *notification-eventbus-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>notification-eventbus-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[opentracing-adapter]]
=== *opentracing-adapter*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>opentracing-adapter</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[payara-executor-service]]
=== *payara-executor-service*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>payara-executor-service</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[requesttracing-core]]
=== *requesttracing-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.payara-modules</groupId>
    <artifactId>requesttracing-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-persistence]]
== `fish.payara.server.internal.persistence`

// [[eclipselink-wrapper]]
=== *eclipselink-wrapper*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>eclipselink-wrapper</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-jpa-connector]]
=== *gf-jpa-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>gf-jpa-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[glassfish-oracle-jdbc-driver-packages]]
=== *glassfish-oracle-jdbc-driver-packages*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>glassfish-oracle-jdbc-driver-packages</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jpa-container]]
=== *jpa-container*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>jpa-container</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jpa-container-l10n]]
=== *jpa-container-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>jpa-container-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[persistence-common]]
=== *persistence-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.persistence</groupId>
    <artifactId>persistence-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-resourcebase-resources]]
== `fish.payara.server.internal.resourcebase.resources`

// [[nucleus-resources]]
=== *nucleus-resources*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resourcebase.resources</groupId>
    <artifactId>nucleus-resources</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-resources]]
== `fish.payara.server.internal.resources`

// [[javamail-connector]]
=== *javamail-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[javamail-connector-l10n]]
=== *javamail-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[javamail-runtime]]
=== *javamail-runtime*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>javamail-runtime</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[resources-connector]]
=== *resources-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[resources-connector-l10n]]
=== *resources-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[resources-runtime]]
=== *resources-runtime*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.resources</groupId>
    <artifactId>resources-runtime</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-security]]
== `fish.payara.server.internal.security`

// [[appclient-security]]
=== *appclient.security*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>appclient.security</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ejb-security]]
=== *ejb.security*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ejb.security</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jacc-provider-inmemory]]
=== *jacc.provider.inmemory*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>jacc.provider.inmemory</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[realm-stores]]
=== *realm-stores*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>realm-stores</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[security]]
=== *security*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[security-ee]]
=== *security-ee*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-ee</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[security-ee-l10n]]
=== *security-ee-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-ee-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[security-l10n]]
=== *security-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[security-services]]
=== *security-services*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>security-services</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[ssl-impl]]
=== *ssl-impl*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>ssl-impl</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[websecurity]]
=== *websecurity*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>websecurity</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webservices-security]]
=== *webservices.security*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webservices-security-l10n]]
=== *webservices.security-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.security</groupId>
    <artifactId>webservices.security-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-transaction]]
== `fish.payara.server.internal.transaction`

// [[jta]]
=== *jta*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jta</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jta-l10n]]
=== *jta-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jta-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jts]]
=== *jts*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jts</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jts-l10n]]
=== *jts-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>jts-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[transaction-internal-api]]
=== *transaction-internal-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[transaction-internal-api-l10n]]
=== *transaction-internal-api-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.transaction</groupId>
    <artifactId>transaction-internal-api-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-web]]
== `fish.payara.server.internal.web`

// [[cdi-api-fragment]]
=== *cdi-api-fragment*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>cdi-api-fragment</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-web-connector]]
=== *gf-web-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-web-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[gf-weld-connector]]
=== *gf-weld-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>gf-weld-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jersey-mvc-connector]]
=== *jersey-mvc-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jersey-mvc-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jsf-connector]]
=== *jsf-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jsf-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jspcaching-connector]]
=== *jspcaching-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jspcaching-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jstl-connector]]
=== *jstl-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>jstl-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[war-util]]
=== *war-util*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>war-util</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[war-util-l10n]]
=== *war-util-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>war-util-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-cli]]
=== *web-cli*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-cli</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-cli-l10n]]
=== *web-cli-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-cli-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-core]]
=== *web-core*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-core</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-core-l10n]]
=== *web-core-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-core-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-embed-api]]
=== *web-embed-api*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-embed-api</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-glue]]
=== *web-glue*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-glue</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-glue-l10n]]
=== *web-glue-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-glue-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-gui-plugin-common]]
=== *web-gui-plugin-common*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-gui-plugin-common</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-gui-plugin-common-l10n]]
=== *web-gui-plugin-common-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-gui-plugin-common-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-ha]]
=== *web-ha*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-ha</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-naming]]
=== *web-naming*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-naming</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-naming-l10n]]
=== *web-naming-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-naming-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[web-sse]]
=== *web-sse*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>web-sse</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[weld-integration]]
=== *weld-integration*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[weld-integration-fragment]]
=== *weld-integration-fragment*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.web</groupId>
    <artifactId>weld-integration-fragment</artifactId>
    <version>7.1.0</version>
</dependency>
----


[[fish-payara-server-internal-webservices]]
== `fish.payara.server.internal.webservices`

// [[jsr109-impl]]
=== *jsr109-impl*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>jsr109-impl</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[jsr109-impl-l10n]]
=== *jsr109-impl-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>jsr109-impl-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[metro-fragments]]
=== *metro-fragments*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>metro-fragments</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[metro-glue]]
=== *metro-glue*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>metro-glue</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[soap-tcp]]
=== *soap-tcp*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>soap-tcp</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webservices-connector]]
=== *webservices-connector*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-connector</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webservices-connector-l10n]]
=== *webservices-connector-l10n*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-connector-l10n</artifactId>
    <version>7.1.0</version>
</dependency>
----


// [[webservices-scripts]]
=== *webservices-scripts*

**Version**: 7.1.0

[source,xml]
----
<dependency>
    <groupId>fish.payara.server.internal.webservices</groupId>
    <artifactId>webservices-scripts</artifactId>
    <version>7.1.0</version>
</dependency>
----


