[[jakarta-ee]]
= Jakarta EE Specification Dependencies Mapping
:ordinal: 1

This section details all dependencies linked to Jakarta EE specifications.

[[com-fasterxml]]
== `com.fasterxml`

// [[classmate]]
=== *classmate*

**Version**: 1.7.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml</groupId>
    <artifactId>classmate</artifactId>
    <version>1.7.0</version>
</dependency>
----


[[com-fasterxml-jackson-core]]
== `com.fasterxml.jackson.core`

// [[jackson-annotations]]
=== *jackson-annotations*

**Version**: 2.22

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-annotations</artifactId>
    <version>2.22</version>
</dependency>
----


// [[jackson-core]]
=== *jackson-core*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-core</artifactId>
    <version>2.22.0</version>
</dependency>
----


// [[jackson-databind]]
=== *jackson-databind*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.core</groupId>
    <artifactId>jackson-databind</artifactId>
    <version>2.22.0</version>
</dependency>
----


[[com-fasterxml-jackson-dataformat]]
== `com.fasterxml.jackson.dataformat`

// [[jackson-dataformat-toml]]
=== *jackson-dataformat-toml*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-toml</artifactId>
    <version>2.22.0</version>
</dependency>
----


// [[jackson-dataformat-yaml]]
=== *jackson-dataformat-yaml*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.dataformat</groupId>
    <artifactId>jackson-dataformat-yaml</artifactId>
    <version>2.22.0</version>
</dependency>
----


[[com-fasterxml-jackson-module]]
== `com.fasterxml.jackson.module`

// [[jackson-module-jakarta-xmlbind-annotations]]
=== *jackson-module-jakarta-xmlbind-annotations*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.jackson.module</groupId>
    <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
    <version>2.22.0</version>
</dependency>
----


[[com-fasterxml-woodstox]]
== `com.fasterxml.woodstox`

// [[woodstox-core]]
=== *woodstox-core*

**Version**: 7.2.0

[source,xml]
----
<dependency>
    <groupId>com.fasterxml.woodstox</groupId>
    <artifactId>woodstox-core</artifactId>
    <version>7.2.0</version>
</dependency>
----


[[com-hazelcast]]
== `com.hazelcast`

// [[hazelcast]]
=== *hazelcast*

**Version**: 5.3.8-payara-1

[source,xml]
----
<dependency>
    <groupId>com.hazelcast</groupId>
    <artifactId>hazelcast</artifactId>
    <version>5.3.8-payara-1</version>
</dependency>
----


[[com-ibm-jbatch]]
== `com.ibm.jbatch`

// [[com-ibm-jbatch-container]]
=== *com.ibm.jbatch.container*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>com.ibm.jbatch</groupId>
    <artifactId>com.ibm.jbatch.container</artifactId>
    <version>2.1.1</version>
</dependency>
----


// [[com-ibm-jbatch-spi]]
=== *com.ibm.jbatch.spi*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>com.ibm.jbatch</groupId>
    <artifactId>com.ibm.jbatch.spi</artifactId>
    <version>2.1.1</version>
</dependency>
----


[[com-nimbusds]]
== `com.nimbusds`

// [[nimbus-jose-jwt]]
=== *nimbus-jose-jwt*

**Version**: 10.9.1

[source,xml]
----
<dependency>
    <groupId>com.nimbusds</groupId>
    <artifactId>nimbus-jose-jwt</artifactId>
    <version>10.9.1</version>
</dependency>
----


[[com-squareup-okhttp3]]
== `com.squareup.okhttp3`

// [[okhttp]]
=== *okhttp*

**Version**: 4.12.0

[source,xml]
----
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>4.12.0</version>
</dependency>
----


[[com-squareup-okio]]
== `com.squareup.okio`

// [[okio]]
=== *okio*

**Version**: 3.6.0

[source,xml]
----
<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio</artifactId>
    <version>3.6.0</version>
</dependency>
----


// [[okio-jvm]]
=== *okio-jvm*

**Version**: 3.6.0

[source,xml]
----
<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio-jvm</artifactId>
    <version>3.6.0</version>
</dependency>
----


[[com-sun-istack]]
== `com.sun.istack`

// [[istack-commons-runtime]]
=== *istack-commons-runtime*

**Version**: 4.2.0

[source,xml]
----
<dependency>
    <groupId>com.sun.istack</groupId>
    <artifactId>istack-commons-runtime</artifactId>
    <version>4.2.0</version>
</dependency>
----


[[com-sun-pkg]]
== `com.sun.pkg`

// [[pkg-client]]
=== *pkg-client*

**Version**: 1.122-57.2889

[source,xml]
----
<dependency>
    <groupId>com.sun.pkg</groupId>
    <artifactId>pkg-client</artifactId>
    <version>1.122-57.2889</version>
</dependency>
----


[[com-sun-xml-bind]]
== `com.sun.xml.bind`

// [[jaxb-extra-osgi]]
=== *jaxb-extra-osgi*

**Version**: 2.3.0

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-extra-osgi</artifactId>
    <version>2.3.0</version>
</dependency>
----


// [[jaxb-osgi]]
=== *jaxb-osgi*

**Version**: 4.0.9

[source,xml]
----
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-osgi</artifactId>
    <version>4.0.9</version>
</dependency>
----


[[commons-codec]]
== `commons-codec`

// [[commons-codec]]
=== *commons-codec*

**Version**: 1.18.0

[source,xml]
----
<dependency>
    <groupId>commons-codec</groupId>
    <artifactId>commons-codec</artifactId>
    <version>1.18.0</version>
</dependency>
----


[[commons-io]]
== `commons-io`

// [[commons-io]]
=== *commons-io*

**Version**: 2.22.0

[source,xml]
----
<dependency>
    <groupId>commons-io</groupId>
    <artifactId>commons-io</artifactId>
    <version>2.22.0</version>
</dependency>
----


[[h2db]]
== `h2db`

// [[h2db]]
=== *h2db*

**Version**: 2.2.224

[source,xml]
----
<dependency>
    <groupId>h2db</groupId>
    <artifactId>h2db</artifactId>
    <version>2.2.224</version>
</dependency>
----


[[io-projectreactor]]
== `io.projectreactor`

// [[reactor-core]]
=== *reactor-core*

**Version**: 3.8.5

[source,xml]
----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.8.5</version>
</dependency>
----


[[jakarta-activation]]
== `jakarta.activation`

// [[jakarta-activation-api]]
=== *jakarta.activation-api*

**Version**: 2.1.4

[source,xml]
----
<dependency>
    <groupId>jakarta.activation</groupId>
    <artifactId>jakarta.activation-api</artifactId>
    <version>2.1.4</version>
</dependency>
----


[[jakarta-annotation]]
== `jakarta.annotation`

// [[jakarta-annotation-api]]
=== *jakarta.annotation-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.annotation</groupId>
    <artifactId>jakarta.annotation-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[jakarta-authentication]]
== `jakarta.authentication`

// [[jakarta-authentication-api]]
=== *jakarta.authentication-api*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.authentication</groupId>
    <artifactId>jakarta.authentication-api</artifactId>
    <version>3.1.0</version>
</dependency>
----


[[jakarta-authorization]]
== `jakarta.authorization`

// [[jakarta-authorization-api]]
=== *jakarta.authorization-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.authorization</groupId>
    <artifactId>jakarta.authorization-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[jakarta-batch]]
== `jakarta.batch`

// [[jakarta-batch-api]]
=== *jakarta.batch-api*

**Version**: 2.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.batch</groupId>
    <artifactId>jakarta.batch-api</artifactId>
    <version>2.1.1</version>
</dependency>
----


[[jakarta-data]]
== `jakarta.data`

// [[jakarta-data-api]]
=== *jakarta.data-api*

**Version**: 1.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.data</groupId>
    <artifactId>jakarta.data-api</artifactId>
    <version>1.0.1</version>
</dependency>
----


[[jakarta-ejb]]
== `jakarta.ejb`

// [[jakarta-ejb-api]]
=== *jakarta.ejb-api*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.ejb</groupId>
    <artifactId>jakarta.ejb-api</artifactId>
    <version>4.0.1</version>
</dependency>
----


[[jakarta-el]]
== `jakarta.el`

// [[jakarta-el-api]]
=== *jakarta.el-api*

**Version**: 6.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.el</groupId>
    <artifactId>jakarta.el-api</artifactId>
    <version>6.0.1</version>
</dependency>
----


[[jakarta-enterprise]]
== `jakarta.enterprise`

// [[jakarta-enterprise-cdi-api]]
=== *jakarta.enterprise.cdi-api*

**Version**: 4.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-api</artifactId>
    <version>4.1.0</version>
</dependency>
----


// [[jakarta-enterprise-cdi-el-api]]
=== *jakarta.enterprise.cdi-el-api*

**Version**: 4.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.cdi-el-api</artifactId>
    <version>4.1.0</version>
</dependency>
----


// [[jakarta-enterprise-lang-model]]
=== *jakarta.enterprise.lang-model*

**Version**: 4.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise</groupId>
    <artifactId>jakarta.enterprise.lang-model</artifactId>
    <version>4.1.0</version>
</dependency>
----


[[jakarta-enterprise-concurrent]]
== `jakarta.enterprise.concurrent`

// [[jakarta-enterprise-concurrent-api]]
=== *jakarta.enterprise.concurrent-api*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.concurrent</groupId>
    <artifactId>jakarta.enterprise.concurrent-api</artifactId>
    <version>3.1.1</version>
</dependency>
----


[[jakarta-enterprise-deploy]]
== `jakarta.enterprise.deploy`

// [[jakarta-enterprise-deploy-api]]
=== *jakarta.enterprise.deploy-api*

**Version**: 1.7.2

[source,xml]
----
<dependency>
    <groupId>jakarta.enterprise.deploy</groupId>
    <artifactId>jakarta.enterprise.deploy-api</artifactId>
    <version>1.7.2</version>
</dependency>
----


[[jakarta-faces]]
== `jakarta.faces`

// [[jakarta-faces-api]]
=== *jakarta.faces-api*

**Version**: 4.1.2

[source,xml]
----
<dependency>
    <groupId>jakarta.faces</groupId>
    <artifactId>jakarta.faces-api</artifactId>
    <version>4.1.2</version>
</dependency>
----


[[jakarta-inject]]
== `jakarta.inject`

// [[jakarta-inject-api]]
=== *jakarta.inject-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.inject</groupId>
    <artifactId>jakarta.inject-api</artifactId>
    <version>2.0.1</version>
</dependency>
----


[[jakarta-interceptor]]
== `jakarta.interceptor`

// [[jakarta-interceptor-api]]
=== *jakarta.interceptor-api*

**Version**: 2.2.0

[source,xml]
----
<dependency>
    <groupId>jakarta.interceptor</groupId>
    <artifactId>jakarta.interceptor-api</artifactId>
    <version>2.2.0</version>
</dependency>
----


[[jakarta-jms]]
== `jakarta.jms`

// [[jakarta-jms-api]]
=== *jakarta.jms-api*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.jms</groupId>
    <artifactId>jakarta.jms-api</artifactId>
    <version>3.1.0</version>
</dependency>
----


[[jakarta-json]]
== `jakarta.json`

// [[jakarta-json-api]]
=== *jakarta.json-api*

**Version**: 2.1.3

[source,xml]
----
<dependency>
    <groupId>jakarta.json</groupId>
    <artifactId>jakarta.json-api</artifactId>
    <version>2.1.3</version>
</dependency>
----


[[jakarta-json-bind]]
== `jakarta.json.bind`

// [[jakarta-json-bind-api]]
=== *jakarta.json.bind-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.json.bind</groupId>
    <artifactId>jakarta.json.bind-api</artifactId>
    <version>3.0.2</version>
</dependency>
----


[[jakarta-jws]]
== `jakarta.jws`

// [[jakarta-jws-api]]
=== *jakarta.jws-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.jws</groupId>
    <artifactId>jakarta.jws-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[jakarta-mail]]
== `jakarta.mail`

// [[jakarta-mail-api]]
=== *jakarta.mail-api*

**Version**: 2.1.5

[source,xml]
----
<dependency>
    <groupId>jakarta.mail</groupId>
    <artifactId>jakarta.mail-api</artifactId>
    <version>2.1.5</version>
</dependency>
----


[[jakarta-mvc]]
== `jakarta.mvc`

// [[jakarta-mvc-api]]
=== *jakarta.mvc-api*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.mvc</groupId>
    <artifactId>jakarta.mvc-api</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[jakarta-persistence]]
== `jakarta.persistence`

// [[jakarta-persistence-api]]
=== *jakarta.persistence-api*

**Version**: 3.2.0

[source,xml]
----
<dependency>
    <groupId>jakarta.persistence</groupId>
    <artifactId>jakarta.persistence-api</artifactId>
    <version>3.2.0</version>
</dependency>
----


[[jakarta-platform]]
== `jakarta.platform`

// [[jakarta-jakartaee-api]]
=== *jakarta.jakartaee-api*

**Version**: 11.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-api</artifactId>
    <version>11.0.0</version>
</dependency>
----


// [[jakarta-jakartaee-core-api]]
=== *jakarta.jakartaee-core-api*

**Version**: 11.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-core-api</artifactId>
    <version>11.0.0</version>
</dependency>
----


// [[jakarta-jakartaee-web-api]]
=== *jakarta.jakartaee-web-api*

**Version**: 11.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.platform</groupId>
    <artifactId>jakarta.jakartaee-web-api</artifactId>
    <version>11.0.0</version>
</dependency>
----


[[jakarta-resource]]
== `jakarta.resource`

// [[jakarta-resource-api]]
=== *jakarta.resource-api*

**Version**: 2.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.resource</groupId>
    <artifactId>jakarta.resource-api</artifactId>
    <version>2.1.0</version>
</dependency>
----


[[jakarta-security-enterprise]]
== `jakarta.security.enterprise`

// [[jakarta-security-enterprise-api]]
=== *jakarta.security.enterprise-api*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.security.enterprise</groupId>
    <artifactId>jakarta.security.enterprise-api</artifactId>
    <version>4.0.0</version>
</dependency>
----


[[jakarta-servlet]]
== `jakarta.servlet`

// [[jakarta-servlet-api]]
=== *jakarta.servlet-api*

**Version**: 6.1.0

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>6.1.0</version>
</dependency>
----


[[jakarta-servlet-jsp]]
== `jakarta.servlet.jsp`

// [[jakarta-servlet-jsp-api]]
=== *jakarta.servlet.jsp-api*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp</groupId>
    <artifactId>jakarta.servlet.jsp-api</artifactId>
    <version>4.0.0</version>
</dependency>
----


[[jakarta-servlet-jsp-jstl]]
== `jakarta.servlet.jsp.jstl`

// [[jakarta-servlet-jsp-jstl-api]]
=== *jakarta.servlet.jsp.jstl-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.servlet.jsp.jstl</groupId>
    <artifactId>jakarta.servlet.jsp.jstl-api</artifactId>
    <version>3.0.2</version>
</dependency>
----


[[jakarta-transaction]]
== `jakarta.transaction`

// [[jakarta-transaction-api]]
=== *jakarta.transaction-api*

**Version**: 2.0.1

[source,xml]
----
<dependency>
    <groupId>jakarta.transaction</groupId>
    <artifactId>jakarta.transaction-api</artifactId>
    <version>2.0.1</version>
</dependency>
----


[[jakarta-validation]]
== `jakarta.validation`

// [[jakarta-validation-api]]
=== *jakarta.validation-api*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>jakarta.validation</groupId>
    <artifactId>jakarta.validation-api</artifactId>
    <version>3.1.1</version>
</dependency>
----


[[jakarta-websocket]]
== `jakarta.websocket`

// [[jakarta-websocket-api]]
=== *jakarta.websocket-api*

**Version**: 2.2.0

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-api</artifactId>
    <version>2.2.0</version>
</dependency>
----


// [[jakarta-websocket-client-api]]
=== *jakarta.websocket-client-api*

**Version**: 2.2.0

[source,xml]
----
<dependency>
    <groupId>jakarta.websocket</groupId>
    <artifactId>jakarta.websocket-client-api</artifactId>
    <version>2.2.0</version>
</dependency>
----


[[jakarta-ws-rs]]
== `jakarta.ws.rs`

// [[jakarta-ws-rs-api]]
=== *jakarta.ws.rs-api*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>
    <version>4.0.0</version>
</dependency>
----


[[jakarta-xml-bind]]
== `jakarta.xml.bind`

// [[jakarta-xml-bind-api]]
=== *jakarta.xml.bind-api*

**Version**: 4.0.5

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.bind</groupId>
    <artifactId>jakarta.xml.bind-api</artifactId>
    <version>4.0.5</version>
</dependency>
----


[[jakarta-xml-soap]]
== `jakarta.xml.soap`

// [[jakarta-xml-soap-api]]
=== *jakarta.xml.soap-api*

**Version**: 3.0.2

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.soap</groupId>
    <artifactId>jakarta.xml.soap-api</artifactId>
    <version>3.0.2</version>
</dependency>
----


[[jakarta-xml-ws]]
== `jakarta.xml.ws`

// [[jakarta-xml-ws-api]]
=== *jakarta.xml.ws-api*

**Version**: 4.0.3

[source,xml]
----
<dependency>
    <groupId>jakarta.xml.ws</groupId>
    <artifactId>jakarta.xml.ws-api</artifactId>
    <version>4.0.3</version>
</dependency>
----


[[javax-cache]]
== `javax.cache`

// [[cache-api]]
=== *cache-api*

**Version**: 1.1.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>javax.cache</groupId>
    <artifactId>cache-api</artifactId>
    <version>1.1.1.payara-p1</version>
</dependency>
----


[[net-java-dev-jna]]
== `net.java.dev.jna`

// [[jna]]
=== *jna*

**Version**: 5.18.1

[source,xml]
----
<dependency>
    <groupId>net.java.dev.jna</groupId>
    <artifactId>jna</artifactId>
    <version>5.18.1</version>
</dependency>
----


[[net-minidev]]
== `net.minidev`

// [[accessors-smart]]
=== *accessors-smart*

**Version**: 2.5.2

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>accessors-smart</artifactId>
    <version>2.5.2</version>
</dependency>
----


// [[json-smart]]
=== *json-smart*

**Version**: 2.5.2

[source,xml]
----
<dependency>
    <groupId>net.minidev</groupId>
    <artifactId>json-smart</artifactId>
    <version>2.5.2</version>
</dependency>
----


[[org-apache-bcel]]
== `org.apache.bcel`

// [[bcel]]
=== *bcel*

**Version**: 6.12.0

[source,xml]
----
<dependency>
    <groupId>org.apache.bcel</groupId>
    <artifactId>bcel</artifactId>
    <version>6.12.0</version>
</dependency>
----


[[org-apache-commons]]
== `org.apache.commons`

// [[commons-lang3]]
=== *commons-lang3*

**Version**: 3.20.0

[source,xml]
----
<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.20.0</version>
</dependency>
----


[[org-apache-felix]]
== `org.apache.felix`

// [[org-apache-felix-eventadmin]]
=== *org.apache.felix.eventadmin*

**Version**: 1.6.4

[source,xml]
----
<dependency>
    <groupId>org.apache.felix</groupId>
    <artifactId>org.apache.felix.eventadmin</artifactId>
    <version>1.6.4</version>
</dependency>
----


[[org-apache-santuario]]
== `org.apache.santuario`

// [[xmlsec]]
=== *xmlsec*

**Version**: 4.0.4

[source,xml]
----
<dependency>
    <groupId>org.apache.santuario</groupId>
    <artifactId>xmlsec</artifactId>
    <version>4.0.4</version>
</dependency>
----


[[org-codehaus-woodstox]]
== `org.codehaus.woodstox`

// [[stax2-api]]
=== *stax2-api*

**Version**: 4.3.0

[source,xml]
----
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>4.3.0</version>
</dependency>
----


[[org-connectbot]]
== `org.connectbot`

// [[jbcrypt]]
=== *jbcrypt*

**Version**: 1.0.2

[source,xml]
----
<dependency>
    <groupId>org.connectbot</groupId>
    <artifactId>jbcrypt</artifactId>
    <version>1.0.2</version>
</dependency>
----


[[org-crac]]
== `org.crac`

// [[crac]]
=== *crac*

**Version**: 1.5.0

[source,xml]
----
<dependency>
    <groupId>org.crac</groupId>
    <artifactId>crac</artifactId>
    <version>1.5.0</version>
</dependency>
----


[[org-eclipse]]
== `org.eclipse`

// [[yasson]]
=== *yasson*

**Version**: 3.0.4

[source,xml]
----
<dependency>
    <groupId>org.eclipse</groupId>
    <artifactId>yasson</artifactId>
    <version>3.0.4</version>
</dependency>
----


[[org-eclipse-angus]]
== `org.eclipse.angus`

// [[angus-activation]]
=== *angus-activation*

**Version**: 2.0.3

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-activation</artifactId>
    <version>2.0.3</version>
</dependency>
----


// [[angus-mail]]
=== *angus-mail*

**Version**: 2.0.5

[source,xml]
----
<dependency>
    <groupId>org.eclipse.angus</groupId>
    <artifactId>angus-mail</artifactId>
    <version>2.0.5</version>
</dependency>
----


[[org-eclipse-krazo]]
== `org.eclipse.krazo`

// [[krazo-core]]
=== *krazo-core*

**Version**: 4.0.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-core</artifactId>
    <version>4.0.1.payara-p1</version>
</dependency>
----


// [[krazo-jersey]]
=== *krazo-jersey*

**Version**: 4.0.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.krazo</groupId>
    <artifactId>krazo-jersey</artifactId>
    <version>4.0.1.payara-p1</version>
</dependency>
----


[[org-eclipse-parsson]]
== `org.eclipse.parsson`

// [[jakarta-json]]
=== *jakarta.json*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>jakarta.json</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----


// [[parsson]]
=== *parsson*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>parsson</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----


// [[parsson-media]]
=== *parsson-media*

**Version**: 1.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.parsson</groupId>
    <artifactId>parsson-media</artifactId>
    <version>1.1.7.payara-p1</version>
</dependency>
----


[[org-eclipse-persistence]]
== `org.eclipse.persistence`

// [[org-eclipse-persistence-asm]]
=== *org.eclipse.persistence.asm*

**Version**: 9.10.0

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.asm</artifactId>
    <version>9.10.0</version>
</dependency>
----


// [[org-eclipse-persistence-core]]
=== *org.eclipse.persistence.core*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.core</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-dbws]]
=== *org.eclipse.persistence.dbws*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.dbws</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-jpa]]
=== *org.eclipse.persistence.jpa*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-jpa-jpql]]
=== *org.eclipse.persistence.jpa.jpql*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa.jpql</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-jpa-modelgen-processor]]
=== *org.eclipse.persistence.jpa.modelgen.processor*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-json]]
=== *org.eclipse.persistence.json*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.json</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-moxy]]
=== *org.eclipse.persistence.moxy*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.moxy</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[org-eclipse-persistence-oracle]]
=== *org.eclipse.persistence.oracle*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.eclipse.persistence</groupId>
    <artifactId>org.eclipse.persistence.oracle</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


[[org-glassfish]]
== `org.glassfish`

// [[jakarta-faces]]
=== *jakarta.faces*

**Version**: 4.1.7.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>jakarta.faces</artifactId>
    <version>4.1.7.payara-p1</version>
</dependency>
----


[[org-glassfish-annotations]]
== `org.glassfish.annotations`

// [[logging-annotation-processor]]
=== *logging-annotation-processor*

**Version**: 1.10

[source,xml]
----
<dependency>
    <groupId>org.glassfish.annotations</groupId>
    <artifactId>logging-annotation-processor</artifactId>
    <version>1.10</version>
</dependency>
----


[[org-glassfish-concurro]]
== `org.glassfish.concurro`

// [[concurro]]
=== *concurro*

**Version**: 3.1.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.concurro</groupId>
    <artifactId>concurro</artifactId>
    <version>3.1.0</version>
</dependency>
----


[[org-glassfish-corba]]
== `org.glassfish.corba`

// [[glassfish-corba-csiv2-idl]]
=== *glassfish-corba-csiv2-idl*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-csiv2-idl</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[glassfish-corba-internal-api]]
=== *glassfish-corba-internal-api*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-internal-api</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[glassfish-corba-omgapi]]
=== *glassfish-corba-omgapi*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-omgapi</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[glassfish-corba-orb]]
=== *glassfish-corba-orb*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>glassfish-corba-orb</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


// [[rmic]]
=== *rmic*

**Version**: 5.0.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.corba</groupId>
    <artifactId>rmic</artifactId>
    <version>5.0.0.payara-p1</version>
</dependency>
----


[[org-glassfish-epicyro]]
== `org.glassfish.epicyro`

// [[epicyro]]
=== *epicyro*

**Version**: 3.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.epicyro</groupId>
    <artifactId>epicyro</artifactId>
    <version>3.1.1</version>
</dependency>
----


[[org-glassfish-exousia]]
== `org.glassfish.exousia`

// [[exousia]]
=== *exousia*

**Version**: 3.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.exousia</groupId>
    <artifactId>exousia</artifactId>
    <version>3.0.1</version>
</dependency>
----


[[org-glassfish-expressly]]
== `org.glassfish.expressly`

// [[expressly]]
=== *expressly*

**Version**: 6.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.expressly</groupId>
    <artifactId>expressly</artifactId>
    <version>6.0.0</version>
</dependency>
----


[[org-glassfish-external]]
== `org.glassfish.external`

// [[management-api]]
=== *management-api*

**Version**: 3.3.0.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>management-api</artifactId>
    <version>3.3.0.payara-p1</version>
</dependency>
----


// [[schema2beans]]
=== *schema2beans*

**Version**: 6.7

[source,xml]
----
<dependency>
    <groupId>org.glassfish.external</groupId>
    <artifactId>schema2beans</artifactId>
    <version>6.7</version>
</dependency>
----


[[org-glassfish-gmbal]]
== `org.glassfish.gmbal`

// [[gmbal]]
=== *gmbal*

**Version**: 4.1.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.gmbal</groupId>
    <artifactId>gmbal</artifactId>
    <version>4.1.2</version>
</dependency>
----


// [[gmbal-api-only]]
=== *gmbal-api-only*

**Version**: 4.1.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.gmbal</groupId>
    <artifactId>gmbal-api-only</artifactId>
    <version>4.1.2</version>
</dependency>
----


[[org-glassfish-grizzly]]
== `org.glassfish.grizzly`

// [[grizzly-comet]]
=== *grizzly-comet*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-comet</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-framework]]
=== *grizzly-framework*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-framework</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-http]]
=== *grizzly-http*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-http</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-http-ajp]]
=== *grizzly-http-ajp*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-http-ajp</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-http-server]]
=== *grizzly-http-server*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-http-server</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-http-servlet]]
=== *grizzly-http-servlet*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-http-servlet</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-http2]]
=== *grizzly-http2*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-http2</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-portunif]]
=== *grizzly-portunif*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-portunif</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[grizzly-websockets]]
=== *grizzly-websockets*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>grizzly-websockets</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


// [[tls-sni]]
=== *tls-sni*

**Version**: 4.1.0-M1.payara-p2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.grizzly</groupId>
    <artifactId>tls-sni</artifactId>
    <version>4.1.0-M1.payara-p2</version>
</dependency>
----


[[org-glassfish-ha]]
== `org.glassfish.ha`

// [[ha-api]]
=== *ha-api*

**Version**: 3.1.13

[source,xml]
----
<dependency>
    <groupId>org.glassfish.ha</groupId>
    <artifactId>ha-api</artifactId>
    <version>3.1.13</version>
</dependency>
----


[[org-glassfish-hk2]]
== `org.glassfish.hk2`

// [[class-model]]
=== *class-model*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>class-model</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[core]]
=== *core*

**Version**: 2.4.0-b14

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>core</artifactId>
    <version>2.4.0-b14</version>
</dependency>
----


// [[hk2]]
=== *hk2*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-api]]
=== *hk2-api*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-api</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-core]]
=== *hk2-core*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-core</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-extras]]
=== *hk2-extras*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-extras</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-locator]]
=== *hk2-locator*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-locator</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-metadata-generator]]
=== *hk2-metadata-generator*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-metadata-generator</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-runlevel]]
=== *hk2-runlevel*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-runlevel</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[hk2-utils]]
=== *hk2-utils*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>hk2-utils</artifactId>
    <version>4.0.1</version>
</dependency>
----


// [[osgi-resource-locator]]
=== *osgi-resource-locator*

**Version**: 3.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2</groupId>
    <artifactId>osgi-resource-locator</artifactId>
    <version>3.0.0</version>
</dependency>
----


[[org-glassfish-hk2-external]]
== `org.glassfish.hk2.external`

// [[aopalliance-repackaged]]
=== *aopalliance-repackaged*

**Version**: 4.0.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.hk2.external</groupId>
    <artifactId>aopalliance-repackaged</artifactId>
    <version>4.0.1</version>
</dependency>
----


[[org-glassfish-jersey-containers]]
== `org.glassfish.jersey.containers`

// [[jersey-container-servlet]]
=== *jersey-container-servlet*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers</groupId>
    <artifactId>jersey-container-servlet</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-containers-glassfish]]
== `org.glassfish.jersey.containers.glassfish`

// [[jersey-gf-ejb]]
=== *jersey-gf-ejb*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.containers.glassfish</groupId>
    <artifactId>jersey-gf-ejb</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-core]]
== `org.glassfish.jersey.core`

// [[jersey-client]]
=== *jersey-client*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-client</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-common]]
=== *jersey-common*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-common</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-server]]
=== *jersey-server*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.core</groupId>
    <artifactId>jersey-server</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-ext]]
== `org.glassfish.jersey.ext`

// [[jersey-entity-filtering]]
=== *jersey-entity-filtering*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-entity-filtering</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-mvc]]
=== *jersey-mvc*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-mvc-jsp]]
=== *jersey-mvc-jsp*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-mvc-jsp</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-proxy-client]]
=== *jersey-proxy-client*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-proxy-client</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-ext-cdi]]
== `org.glassfish.jersey.ext.cdi`

// [[jersey-cdi1x]]
=== *jersey-cdi1x*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-cdi1x-servlet]]
=== *jersey-cdi1x-servlet*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-servlet</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-cdi1x-transaction]]
=== *jersey-cdi1x-transaction*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.cdi</groupId>
    <artifactId>jersey-cdi1x-transaction</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-ext-microprofile]]
== `org.glassfish.jersey.ext.microprofile`

// [[jersey-mp-rest-client]]
=== *jersey-mp-rest-client*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.ext.microprofile</groupId>
    <artifactId>jersey-mp-rest-client</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-inject]]
== `org.glassfish.jersey.inject`

// [[jersey-hk2]]
=== *jersey-hk2*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.inject</groupId>
    <artifactId>jersey-hk2</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-jersey-media]]
== `org.glassfish.jersey.media`

// [[jersey-media-json-binding]]
=== *jersey-media-json-binding*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-binding</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-media-json-processing]]
=== *jersey-media-json-processing*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-json-processing</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-media-moxy]]
=== *jersey-media-moxy*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


// [[jersey-media-sse]]
=== *jersey-media-sse*

**Version**: 4.0.2.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-sse</artifactId>
    <version>4.0.2.payara-p1</version>
</dependency>
----


[[org-glassfish-metro]]
== `org.glassfish.metro`

// [[webservices-api-osgi]]
=== *webservices-api-osgi*

**Version**: 4.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-api-osgi</artifactId>
    <version>4.0.4.payara-p1</version>
</dependency>
----


// [[webservices-extra-jdk-packages]]
=== *webservices-extra-jdk-packages*

**Version**: 4.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-extra-jdk-packages</artifactId>
    <version>4.0.4.payara-p1</version>
</dependency>
----


// [[webservices-osgi]]
=== *webservices-osgi*

**Version**: 4.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>webservices-osgi</artifactId>
    <version>4.0.4.payara-p1</version>
</dependency>
----


// [[wstx-services]]
=== *wstx-services*

**Version**: 4.0.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.metro</groupId>
    <artifactId>wstx-services</artifactId>
    <version>4.0.4.payara-p1</version>
</dependency>
----


[[org-glassfish-mq]]
== `org.glassfish.mq`

// [[mq-distribution]]
=== *mq-distribution*

**Version**: 6.8.0.payara-p3

[source,xml]
----
<dependency>
    <groupId>org.glassfish.mq</groupId>
    <artifactId>mq-distribution</artifactId>
    <version>6.8.0.payara-p3</version>
</dependency>
----


[[org-glassfish-pfl]]
== `org.glassfish.pfl`

// [[pfl-basic]]
=== *pfl-basic*

**Version**: 5.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-basic</artifactId>
    <version>5.1.1</version>
</dependency>
----


// [[pfl-basic-tools]]
=== *pfl-basic-tools*

**Version**: 5.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-basic-tools</artifactId>
    <version>5.1.1</version>
</dependency>
----


// [[pfl-dynamic]]
=== *pfl-dynamic*

**Version**: 5.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-dynamic</artifactId>
    <version>5.1.1</version>
</dependency>
----


// [[pfl-tf]]
=== *pfl-tf*

**Version**: 5.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-tf</artifactId>
    <version>5.1.1</version>
</dependency>
----


// [[pfl-tf-tools]]
=== *pfl-tf-tools*

**Version**: 5.1.1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.pfl</groupId>
    <artifactId>pfl-tf-tools</artifactId>
    <version>5.1.1</version>
</dependency>
----


[[org-glassfish-soteria]]
== `org.glassfish.soteria`

// [[soteria]]
=== *soteria*

**Version**: 4.0.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>soteria</artifactId>
    <version>4.0.1.payara-p1</version>
</dependency>
----


// [[soteria-spi-bean-decorator-weld]]
=== *soteria.spi.bean.decorator.weld*

**Version**: 4.0.1.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.glassfish.soteria</groupId>
    <artifactId>soteria.spi.bean.decorator.weld</artifactId>
    <version>4.0.1.payara-p1</version>
</dependency>
----


[[org-glassfish-tyrus]]
== `org.glassfish.tyrus`

// [[tyrus-client]]
=== *tyrus-client*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-client</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-container-glassfish-cdi]]
=== *tyrus-container-glassfish-cdi*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-cdi</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-container-glassfish-ejb]]
=== *tyrus-container-glassfish-ejb*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-glassfish-ejb</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-container-grizzly-client]]
=== *tyrus-container-grizzly-client*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-grizzly-client</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-container-servlet]]
=== *tyrus-container-servlet*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-container-servlet</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-core]]
=== *tyrus-core*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-core</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-server]]
=== *tyrus-server*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-server</artifactId>
    <version>2.2.2</version>
</dependency>
----


// [[tyrus-spi]]
=== *tyrus-spi*

**Version**: 2.2.2

[source,xml]
----
<dependency>
    <groupId>org.glassfish.tyrus</groupId>
    <artifactId>tyrus-spi</artifactId>
    <version>2.2.2</version>
</dependency>
----


[[org-glassfish-wasp]]
== `org.glassfish.wasp`

// [[wasp]]
=== *wasp*

**Version**: 4.0.0

[source,xml]
----
<dependency>
    <groupId>org.glassfish.wasp</groupId>
    <artifactId>wasp</artifactId>
    <version>4.0.0</version>
</dependency>
----


[[org-hibernate-validator]]
== `org.hibernate.validator`

// [[hibernate-validator]]
=== *hibernate-validator*

**Version**: 9.0.1.Final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator</artifactId>
    <version>9.0.1.Final.payara-p1</version>
</dependency>
----


// [[hibernate-validator-cdi]]
=== *hibernate-validator-cdi*

**Version**: 9.0.1.Final.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.hibernate.validator</groupId>
    <artifactId>hibernate-validator-cdi</artifactId>
    <version>9.0.1.Final.payara-p1</version>
</dependency>
----


[[org-javassist]]
== `org.javassist`

// [[javassist]]
=== *javassist*

**Version**: 3.31.0-GA

[source,xml]
----
<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.31.0-GA</version>
</dependency>
----


[[org-jboss-classfilewriter]]
== `org.jboss.classfilewriter`

// [[jboss-classfilewriter]]
=== *jboss-classfilewriter*

**Version**: 1.3.1.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.classfilewriter</groupId>
    <artifactId>jboss-classfilewriter</artifactId>
    <version>1.3.1.Final</version>
</dependency>
----


[[org-jboss-jdeparser]]
== `org.jboss.jdeparser`

// [[jdeparser]]
=== *jdeparser*

**Version**: 2.0.3.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.jdeparser</groupId>
    <artifactId>jdeparser</artifactId>
    <version>2.0.3.Final</version>
</dependency>
----


[[org-jboss-logging]]
== `org.jboss.logging`

// [[jboss-logging]]
=== *jboss-logging*

**Version**: 3.6.3.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging</artifactId>
    <version>3.6.3.Final</version>
</dependency>
----


// [[jboss-logging-annotations]]
=== *jboss-logging-annotations*

**Version**: 3.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging-annotations</artifactId>
    <version>3.0.4.Final</version>
</dependency>
----


// [[jboss-logging-processor]]
=== *jboss-logging-processor*

**Version**: 3.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.logging</groupId>
    <artifactId>jboss-logging-processor</artifactId>
    <version>3.0.4.Final</version>
</dependency>
----


[[org-jboss-weld]]
== `org.jboss.weld`

// [[weld-api]]
=== *weld-api*

**Version**: 6.0.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-api</artifactId>
    <version>6.0.Final</version>
</dependency>
----


// [[weld-core-impl]]
=== *weld-core-impl*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-core-impl</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-lite-extension-translator]]
=== *weld-lite-extension-translator*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-lite-extension-translator</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-osgi-bundle]]
=== *weld-osgi-bundle*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-osgi-bundle</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-spi]]
=== *weld-spi*

**Version**: 6.0.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld</groupId>
    <artifactId>weld-spi</artifactId>
    <version>6.0.Final</version>
</dependency>
----


[[org-jboss-weld-environment]]
== `org.jboss.weld.environment`

// [[weld-environment-common]]
=== *weld-environment-common*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.environment</groupId>
    <artifactId>weld-environment-common</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


[[org-jboss-weld-module]]
== `org.jboss.weld.module`

// [[weld-ejb]]
=== *weld-ejb*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-ejb</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-jsf]]
=== *weld-jsf*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jsf</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-jta]]
=== *weld-jta*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-jta</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


// [[weld-web]]
=== *weld-web*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.module</groupId>
    <artifactId>weld-web</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


[[org-jboss-weld-se]]
== `org.jboss.weld.se`

// [[weld-se-shaded]]
=== *weld-se-shaded*

**Version**: 6.0.4.Final

[source,xml]
----
<dependency>
    <groupId>org.jboss.weld.se</groupId>
    <artifactId>weld-se-shaded</artifactId>
    <version>6.0.4.Final</version>
</dependency>
----


[[org-jetbrains]]
== `org.jetbrains`

// [[annotations]]
=== *annotations*

**Version**: 13.0

[source,xml]
----
<dependency>
    <groupId>org.jetbrains</groupId>
    <artifactId>annotations</artifactId>
    <version>13.0</version>
</dependency>
----


[[org-jetbrains-kotlin]]
== `org.jetbrains.kotlin`

// [[kotlin-stdlib]]
=== *kotlin-stdlib*

**Version**: 1.8.21

[source,xml]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib</artifactId>
    <version>1.8.21</version>
</dependency>
----


// [[kotlin-stdlib-common]]
=== *kotlin-stdlib-common*

**Version**: 1.9.10

[source,xml]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib-common</artifactId>
    <version>1.9.10</version>
</dependency>
----


// [[kotlin-stdlib-jdk7]]
=== *kotlin-stdlib-jdk7*

**Version**: 1.8.21

[source,xml]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib-jdk7</artifactId>
    <version>1.8.21</version>
</dependency>
----


// [[kotlin-stdlib-jdk8]]
=== *kotlin-stdlib-jdk8*

**Version**: 1.8.21

[source,xml]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib-jdk8</artifactId>
    <version>1.8.21</version>
</dependency>
----


[[org-jline]]
== `org.jline`

// [[jline]]
=== *jline*

**Version**: 3.30.13

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline</artifactId>
    <version>3.30.13</version>
</dependency>
----


// [[jline-native]]
=== *jline-native*

**Version**: 3.30.13

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-native</artifactId>
    <version>3.30.13</version>
</dependency>
----


// [[jline-terminal]]
=== *jline-terminal*

**Version**: 3.30.13

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal</artifactId>
    <version>3.30.13</version>
</dependency>
----


// [[jline-terminal-jna]]
=== *jline-terminal-jna*

**Version**: 3.30.13

[source,xml]
----
<dependency>
    <groupId>org.jline</groupId>
    <artifactId>jline-terminal-jna</artifactId>
    <version>3.30.13</version>
</dependency>
----


[[org-jspecify]]
== `org.jspecify`

// [[jspecify]]
=== *jspecify*

**Version**: 1.0.0

[source,xml]
----
<dependency>
    <groupId>org.jspecify</groupId>
    <artifactId>jspecify</artifactId>
    <version>1.0.0</version>
</dependency>
----


[[org-jvnet]]
== `org.jvnet`

// [[tiger-types]]
=== *tiger-types*

**Version**: 1.4.payara-p1

[source,xml]
----
<dependency>
    <groupId>org.jvnet</groupId>
    <artifactId>tiger-types</artifactId>
    <version>1.4.payara-p1</version>
</dependency>
----


[[org-jvnet-mimepull]]
== `org.jvnet.mimepull`

// [[mimepull]]
=== *mimepull*

**Version**: 1.11.0

[source,xml]
----
<dependency>
    <groupId>org.jvnet.mimepull</groupId>
    <artifactId>mimepull</artifactId>
    <version>1.11.0</version>
</dependency>
----


[[org-osgi]]
== `org.osgi`

// [[osgi-core]]
=== *osgi.core*

**Version**: 8.0.0

[source,xml]
----
<dependency>
    <groupId>org.osgi</groupId>
    <artifactId>osgi.core</artifactId>
    <version>8.0.0</version>
</dependency>
----


[[org-ow2-asm]]
== `org.ow2.asm`

// [[asm]]
=== *asm*

**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm</artifactId>
    <version>9.10.1</version>
</dependency>
----


// [[asm-analysis]]
=== *asm-analysis*

**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm-analysis</artifactId>
    <version>9.10.1</version>
</dependency>
----


// [[asm-commons]]
=== *asm-commons*

**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm-commons</artifactId>
    <version>9.10.1</version>
</dependency>
----


// [[asm-tree]]
=== *asm-tree*

**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm-tree</artifactId>
    <version>9.10.1</version>
</dependency>
----


// [[asm-util]]
=== *asm-util*

**Version**: 9.10.1

[source,xml]
----
<dependency>
    <groupId>org.ow2.asm</groupId>
    <artifactId>asm-util</artifactId>
    <version>9.10.1</version>
</dependency>
----


[[org-reactivestreams]]
== `org.reactivestreams`

// [[reactive-streams]]
=== *reactive-streams*

**Version**: 1.0.4

[source,xml]
----
<dependency>
    <groupId>org.reactivestreams</groupId>
    <artifactId>reactive-streams</artifactId>
    <version>1.0.4</version>
</dependency>
----


[[org-snmp4j]]
== `org.snmp4j`

// [[snmp4j]]
=== *snmp4j*

**Version**: 3.8.2

[source,xml]
----
<dependency>
    <groupId>org.snmp4j</groupId>
    <artifactId>snmp4j</artifactId>
    <version>3.8.2</version>
</dependency>
----


[[org-yaml]]
== `org.yaml`

// [[snakeyaml]]
=== *snakeyaml*

**Version**: 2.6

[source,xml]
----
<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>2.6</version>
</dependency>
----


