= Hot Deploy and Auto Deploy

IMPORTANT: To enable these features, the relevant ecosystem plugin to your IDE of choice must be installed.

The Payara Platform IDE ecosystem integrations fully support Hot Deployment and AutoDeployment of applications on a pre-configured Payara Server installation. Once enabled on your IDE of choice, you can simply deploy web applications to Payara Server (and Micro) and modify the source code of any Java class that belong to the application in question, upon save, any changed files within the application will be redeployed.

CAUTION: Both features are not available yet in the IntelliJ IDEA ecosystem integrations.

[[hot-deployment]]
== Hot Deployment

The Payara Platform provides the *Hot Deployment* capability, which boosts the performance of the application redeployment operation and dynamically replaces the classloader of the application on each redeployment when the feature is turned on.

TIP: Hot deploy is significantly faster than a vanilla redeployment, boosting developer productivity.

[[auto-deployment]]
== Auto Deployment

The Payara Platform also allows for a full redeployment of the application automatically via the *Auto Deployment* feature. It will un-deploy the application (if already deployed) and redeploy the new version of the application on every save action after making changes to the source code on your IDE of choice.

WARNING: As the Auto Deploy feature performs a full redeploy of an application, it is slower than hot redeploy, which redeploys only the relevant updated components of the application in question.

[[configuration]]
== Configuration

To configure the settings of these features on your IDE of choice, follow the instructions on the corresponding sections of each integration's documentation:

* Eclipse IDE:
** xref:Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Payara Server.adoc#hot-deploy-and-auto-deploy-settings[Payara Server]
** xref:Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Payara Micro.adoc#hot-deploy-and-auto-deploy-settings[Payara Micro]

* Apache Netbeans:
** xref:Technical Documentation/Ecosystem/IDE Integration/Apache NetBeans IDE/Payara Server.adoc#hot-deploy-and-auto-deploy-settings[Payara Server]
** xref:Technical Documentation/Ecosystem/IDE Integration/Apache NetBeans IDE/Payara Micro.adoc#hot-deploy-and-auto-deploy-settings[Payara Micro]

* Visual Studio Code:
** xref:Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Payara Server.adoc#hot-deploy-and-auto-deploy-settings[Payara Server]
// TODO: Payara Micro VS Code documentation is missing on this branch!
** xref:Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Payara Micro.adoc#hot-deploy-and-auto-deploy-settings[Payara Micro]
