[[maven-support]]
= Maven Support

This section describes Apache Maven support for Payara Micro.

[[artifacts-in-maven-central]]
== Maven Central Artifacts

Payara Micro is available in Maven Central, allowing you to include it as a dependency in your project's POM. This allows you to easily add the required Payara Micro classes and methods to your application to use Payara Micro programmatically.

To do this, use the following GAV coordinates:

[source, xml, subs=attributes+]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-micro</artifactId>
    <version>{currentVersion}</version>
</dependency>
----

IMPORTANT: The xref:/Technical Documentation/Public API/Overview.adoc[Public API] dependency must be also added to the project's POM when developing applications that use proprietary features (`@Clustered` or `@NamedCache` for example).

[[run-payara-micro-using-the-maven-plugin]]
== Run Payara Micro using the Maven Plugin

There is a maven plugin built specifically for use with Payara Micro. It has goals to `bundle` the application into an Uber JAR, `start` and `stop` Payara Micro. This plugin is xref:/Technical Documentation/Ecosystem/Project Management Tools/Maven Archetype.adoc[fully documented in the Ecosystem section].

[[run-payara-micro-using-netbeans]]
== Run Payara Micro using the NetBeans IDE

There is a https://github.com/payara/ecosystem-netbeans-plugin/tree/master/payara.micro[NetBeans IDE plugin module] built specifically for Payara Micro to create and manage the application actions (e.g run, reload & debug). This plugin is xref:/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Micro.adoc[fully documented in the Ecosystem - Payara Plugin section].