[[maven-support]]
= Maven Support

This section describes Apache Maven support for Payara Micro.

[[artifacts-in-maven-central]]
<<<<<<< HEAD
== Maven Central Artifacts

Payara Micro is available in Maven Central, allowing you to include it as a dependency in your project's POM. This allows you to easily add the required Payara Micro classes and methods to your application to use Payara Micro programmatically.

To do this, use the following GAV coordinates:
=======
== Artifacts in Maven Central

Payara Micro Community has been uploaded to Maven Central, allowing you to include
it as a dependency in your POM.

This allows you to easily add the required Payara Micro classes and
methods to your application to use Payara Micro Community programmatically.

In your project's POM, include the following dependency:
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98

[source, xml, subs=attributes+]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-micro</artifactId>
    <version>{currentVersion}</version>
</dependency>
----

<<<<<<< HEAD
<<<<<<< HEAD:docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support/maven.adoc
IMPORTANT: The xref:/Technical Documentation/Public API/Overview.adoc[Public API] dependency must be also added to the project's POM when developing applications that use proprietary features (`@Clustered` or `@NamedCache` for example).
=======
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98
`${payara.version}` is a Maven property, which specifies the version of the Maven
artifact, e.g. {currentVersion}.

[[Public API-reference]]
=== Public API Reference

_Since Payara Micro 4.1.1.171_

Starting from this release, you need to add a dependency to
the xref:/Technical Documentation/Public API/Overview.adoc[Public API]
when developing applications that use proprietary features (`@Clustered` or
`@NamedCache` for example)
<<<<<<< HEAD
>>>>>>> 7722c9e9 (Fixing broken links):docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support.adoc
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98

[[run-payara-micro-using-the-maven-plugin]]
== Run Payara Micro using the Maven Plugin

<<<<<<< HEAD
<<<<<<< HEAD:docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support/maven.adoc
There is a maven plugin built specifically for use with Payara Micro. It has goals to `bundle` the application into an Uber JAR, `start` and `stop` Payara Micro. This plugin is xref:/Technical Documentation/Ecosystem/Project Management Tools/Maven Plugin.adoc[fully documented in its own section].
=======
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98
There is a maven plugin built specifically for use with Payara Micro. It has
goals to `bundle` the application into an Uber JAR, `start` and `stop` Payara
Micro. This plugin is xref:/Technical Documentation/Ecosystem/Project Management Tools/Maven Archetype.adoc[fully
documented in the Ecosystem section.]
<<<<<<< HEAD
>>>>>>> 7722c9e9 (Fixing broken links):docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support.adoc
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98

[[run-payara-micro-using-the-netbeans-ide]]
== Run Payara Micro using the NetBeans IDE

<<<<<<< HEAD
<<<<<<< HEAD:docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support/maven.adoc
There is a https://github.com/payara/ecosystem-netbeans-plugin/tree/master/payara.micro[NetBeans IDE plugin - payara.micro module] built specifically for Payara Micro to create and manage the application actions (e.g run, reload & debug). This plugin is xref:/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Micro.adoc[fully documented in its own section].
=======
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98
There is a https://github.com/payara/ecosystem-netbeans-plugin/tree/master/payara.micro[NetBeans IDE plugin - payara.micro module]
built specifically for Payara Micro to create and manage the application actions (e.g run, reload & debug).
This plugin is xref:/Technical Documentation/Ecosystem/IDE Integration/NetBeans Plugin/Payara Micro.adoc[fully
documented in the Ecosystem - Payara Plugin section.]
<<<<<<< HEAD
>>>>>>> 7722c9e9 (Fixing broken links):docs/modules/ROOT/pages/Technical Documentation/Payara Micro Documentation/Maven Support.adoc
=======
>>>>>>> 7722c9e93387852daff94f2343cb58d1504fac98
