[[logging-to-a-file]]
= Logging to a file
:ordinal: 1

This section describes how to print all the Payara Micro log messages into a file.

[[logging-to-a-file-from-the-command-line]]
== Logging to a file from the Command Line

To print all of the Payara Micro log messages into a file from the command line,  you will need to use the `--logToFile` option, followed by either a path to where you want to put the log file or by giving the name of a file you want to print the logs into. If a file name is not given, a default file called _payara-server.log_ is generated.

[source, shell]
----
java -jar payara-micro.jar --logToFile /home/user/PayaraMicro.log
----

[[logging-to-a-file-programmatically]]
== Logging to a file Programmatically

To print all the Payara Micro log messages into a file programmatically, you will need to use `setUserLogFile(String filePath)` method.

[source, java]
----
import fish.payara.micro.PayaraMicro;
import fish.payara.micro.BootstrapException;

public class EmbeddedPayara{
    public static void main(String[] args) throws BootstrapException{
         PayaraMicro.getInstance().setUserLogFile("/home/user/PayaraMicro.log").bootStrap();
    }
}
----

[[configuration]]
== Configuration

You can specify a `Logging Properties File` to configure the JUL logger for Payara Micro.

[cols="4,2,3,1,1",options="header"]
|===
|Options | Type | Description | Default | Mandatory
| `--logProperties`| `String` | File with logging configuration| | No
| `--enableDynamicLogging`| `Boolean` | Enable dynamic reloading of configuration| False | No
|===

[[example]]
=== Example

You can provide a logging configuration file that uses the standard JUL notation https://docs.oracle.com/cd/E57471_01/bigData.100/data_processing_bdd/src/rdp_logging_config.html[RDP Logging Config]

[source, shell]
----
java -jar payara-micro.jar --logProperties micro-logging.properties --enableDynamicLogging --deploy myapplication.war
----
