[[supported-platforms]]
= Supported Platforms
:ordinal: 2

Though it is always possible for new versions to be supported, this page details the JVMs currently supported by the Payara Platform (both Payara Server and Payara Micro).

== Supported Java Virtual Machines

The Payara Platform currently runs on the following Java Virtual Machines:

* Azul Zulu JDK: 11 (11.0.12+), 17 (17.34/17.0.3+), 21 (21.30/21.0.1+)
* Oracle JDK: 11 (11.0.12+), 17 (17.0.3+), 21 (21.0.1+)
* Amazon Corretto: 11 (11.0.12+), 17 (17.0.3+), 21 (21.0.1+)
* Adopt Open JDK: 11 (11.0.12+), 17 (17.0.3+), 21 (21.0.1+)
* Adopt Open JDK with Eclipse Open J9: 11 (11.0.12+), 17 (17.0.3+), 21 (21.0.1+)
* Any other JVM based on OpenJDK 11.0.12+ or 17.0.3+ or 21.0.1+

The Payara Platform runs on the `x64` and `arm64` variants of the above JVMs.

== Supported Operating Systems

The Payara Platform currently runs on the following Operating Systems in all the versions listed below and all their newer versions:

* Windows
** Windows 7+
** Windows Server 2008+
* Linux
** Ubuntu 14.04 (Trusty Tahr) LTS+
** Debian 7 (Wheezy)+
** CentOS 6+
** RHEL 5+
** OpenSUSE 42.2+
** SUSE 11.4, 12.2+, 15.0+
** Amazon Linux (all versions)
* Other
** MacOS(OSX) 10.10.5 (Yosemite)+
** IBM AIX 7.1+

In general, any Payara Platform distribution runs on any system supported by at least one of the JVMs it runs on.
