[[diagnostics-tool]]
= Diagnostics Tool

A tool that collects the following information from the specified target.

* Domain.xml
* Server Log
* Thread Dump
* Heap Dump
* JVM Report

Collection can be targeted towards specific a specific Instance, Deployment Group or Cluster. By default, everything is collected from the DAS, each Instance, Deployment Group and Cluster.

If the target is offline, only the domain.xml configuration file and Server Log will be collected.

NOTE: If you are not using the default _domain1_, you must specify the domain to collect diagnostics from.

[[instance-collection]]
== Instance Collection
Diagnostics can be collected directly from an instance if not local to the DAS by specifying the admin port of the target instance.

[[instance-example-self]]
=== Example

[source, shell]
----
asadmin> -p 24848 collect-diagnostics --target deploymentGroup1 mydomain
----

[[collect-diagnostics]]
== `collect-diagnostics`

Usage::
`asadmin> collect-diagnostics --serverlog={true|false}
--domainxml={true|false} --threaddump={true|false}
--heapdump={true|false} --jvmreport={true|false}
--domaindir domaindir --nodedir nodedir --dir dir
--target target-name domainname`

Aim::
This command will collect useful information for diagnosing issues with Payara.

The items collected are stored in a zip file in your user home directory, the output directory can be changed via the `dir` parameter.

[[command-options-self]]
=== Command Options

[cols="3,1,5,1,1",options="header"]
|===
|Option
|Type
|Description
|Default
|Mandatory

|`--serverlog`
|Boolean
|Whether to collect server logs. 
|true
|no

|`--domainxml`
|Boolean
|Whether to collect the domain.xml. 
|true
|no

|`--threaddump`
|Boolean
|Whether to collect the thread dump. 
|true
|no

|`--heapdump`
|Boolean
|Whether to collect the heap dump. 
|true
|no

|`--jvmreport`
|Boolean
|Whether to collect the jvm report. 
|true
|no

|`--domaindir`
|String
|The path to the directory containing the target domain.
|`${installDir}/glassfish/domains`
|no

|`--nodedir`
|String
|The path to the node directory containing the target instance.
|`${installDir}/glassfish/nodes`
|no

|`--dir`
|String
|The path where the resultant zip file should be stored.
|`{user.home}`
|no

|`--target`
|String
|The name of an Instance, Cluster or Deployment Group.
|domain
|no

|`--domainname` (primary)
|String
|The name of the domain you would like to collect diagnostics for.
|domain1
|no

|===

[[example-self]]
=== Example

[source, shell]
----
asadmin> collect-diagnostics --target deploymentGroup1 mydomain

Directory selected C:\Users\Payara\payara-diagnostics-mydomain-2024-04-15T11-42-36Z
Collecting domain.xml from instance2
Attempting to create missing path at C:\Users\Payara\payara-diagnostics-mydomain-2024-04-15T11-42-36Z\deploymentGroup1\instance2
Collecting logs from instance2
Collecting jvm report from instance2
Collecting thread dump from instance2
Collecting Heap Dump from instance2
This version of Payara does not support heap dump generation.
Collecting domain.xml from instance1
Attempting to create missing path at C:\Users\Payara\payara-diagnostics-mydomain-2024-04-15T11-42-36Z\deploymentGroup1\instance1
Collecting logs from instance1
Collecting jvm report from instance1
Collecting thread dump from instance1
Collecting Heap Dump from instance1
This version of Payara does not support heap dump generation.
Command collect-diagnostics executed successfully.
----

==== Resultant Zip Structure
[source, shell]
----

deploymentGroup1
├── instance1
│   ├── instance1-domain.xml
│   ├── instance1-jvm-report.txt
│   ├── instance1-server.log
│   └── instance1-thread-dump.txt
└── instance2
    ├── instance2-domain.xml
    ├── instance2-jvm-report.txt
    ├── instance2-server.log
    └── instance2-thread-dump.txt
----