= Overview of Payara Server Deployment Planning

The Deployment Planning Guide explains how to build a production deployment of Payara Server

This preface contains information about and conventions for the entire Payara Server documentation set.

[[symbol-conventions]]
== Symbol Conventions

The following table explains symbols that might be used in this book.

[width="100%",cols="<10%,<26%,<28%,<36%",options="header",]
|===
|Symbol |Description |Example |Meaning

|`[ ]`
|Contains optional arguments and command options.
|`ls [-l]`
|The `-l` option is not required.

|`{ \| }`
|Contains a set of choices for a required command option.
|`-d {y\|n}`
|The `-d` option requires that you use either the `y` argument or the `n` argument.

|`${ }`
|Indicates a variable reference.
|`${com.sun.javaRoot}`
|References the value of the `com.sun.javaRoot` variable.

|-
|Joins simultaneous multiple keystrokes.
|Control-A
|Press the Control key while you press the A key.

|+ +
|Joins consecutive multiple keystrokes.
|Ctrl+A+N
|Press the Control key, release it, and then press the subsequent keys.

|>
|Indicates menu item selection in a graphical user interface.
|File > New > Templates
|From the File menu, choose New. From the New submenu, choose Templates.
|===

[[default-paths-and-file-names]]
== Default Paths and File Names

The following table describes the default paths and file names that are used in this book.

[width="100%",cols="<14%,<34%,<52%",options="header",]
|===
|Placeholder
|Description
|Default Value

|as-install
a| Represents the base installation directory for Payara Server.

In configuration files, as-install is represented as follows:

`${com.sun.aas.installRoot}`

a| Installations on the Oracle Solaris operating system, Linux operating system, and macOS operating system:

user's-home-directory`/payara6/glassfish`

Installations on the Windows operating system:

SystemDrive`:\payara6\glassfish`

|as-install-parent
|Represents the parent of the base installation directory for Payara Server.
a| Installations on the Oracle Solaris operating system, Linux operating system, and Mac operating system:

user's-home-directory`/payara6`

Installations on the Windows operating system:

SystemDrive`:\payara6`

|domain-root-dir
|Represents the directory in which a domain is created by default.
|as-install`/domains/`

|domain-dir
a| Represents the directory in which a domain's configuration is stored.

In configuration files, domain-dir is represented as follows:

`${com.sun.aas.instanceRoot}`
|domain-root-dir`/`domain-name

|instance-dir
|Represents the directory for a server instance.
|domain-dir`/`instance-name
|===
