= Payara Platform Third-Party Licensing Information
:toc: left
:toclevels: 2
:sectanchors:
:sectnums:
:icons: font

== Introduction

The Payara Platform incorporates third-party licensed software packages. Some of these packages have distribution restrictions and some have only reporting requirements. This document lists the third-party licensed software packages distributed with The Payara Platform and the full text of each applicable license.

[NOTE]
====
DO NOT TRANSLATE OR LOCALIZE.
====

== Components

[cols="3,4,3",options="header",frame=all,grid=rows]
|===
| Component | Maven Coordinates / URL | License

| AntLR Parser Generator
| `antlr:antlr:2.7.7` +
http://www.antlr.org/
| <<bsd2,BSD 2-Clause License>>

| AOP alliance
| `aopalliance:aopalliance:1.0` +
http://aopalliance.sourceforge.net
| <<publicdomain,Public Domain>>

| reload4j
| `ch.qos.reload4j:reload4j:1.2.22` +
https://reload4j.qos.ch
| <<apache2,Apache License, Version 2.0>>

| EdDSA-Java_BloxBean_patch
| `com.bloxbean.cardano:net-i2p-crypto-eddsa:0.3.1` +
https://github.com/bloxbean/ed25519-java
| <<cc0,CC0 1.0 Universal>>

| ClassMate
| `com.fasterxml:classmate:1.7.0` +
https://github.com/FasterXML/java-classmate
| <<apache2,Apache License, Version 2.0>>

| ClassMate
| `com.fasterxml:classmate:1.7.3` +
https://github.com/FasterXML/java-classmate
| <<apache2,Apache License, Version 2.0>>

| Jackson-annotations
| `com.fasterxml.jackson.core:jackson-annotations:2.21` +
https://github.com/FasterXML/jackson
| <<apache2,Apache License, Version 2.0>>

| Jackson-core
| `com.fasterxml.jackson.core:jackson-core:2.21.2` +
https://github.com/FasterXML/jackson-core
| <<apache2,Apache License, Version 2.0>>

| jackson-databind
| `com.fasterxml.jackson.core:jackson-databind:2.21.2` +
https://github.com/FasterXML/jackson
| <<apache2,Apache License, Version 2.0>>

| Jackson-dataformat-TOML
| `com.fasterxml.jackson.dataformat:jackson-dataformat-toml:2.21.2` +
https://github.com/FasterXML/jackson-dataformats-text
| <<apache2,Apache License, Version 2.0>>

| Jackson-dataformat-XML
| `com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.21.2` +
https://github.com/FasterXML/jackson-dataformat-xml
| <<apache2,Apache License, Version 2.0>>

| Jackson-dataformat-YAML
| `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.21.2` +
https://github.com/FasterXML/jackson-dataformats-text
| <<apache2,Apache License, Version 2.0>>

| Jackson module: Jakarta XML Bind Annotations (jakarta.xml.bind)
| `com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:2.21.2` +
https://github.com/FasterXML/jackson-modules-base
| <<apache2,Apache License, Version 2.0>>

| Woodstox
| `com.fasterxml.woodstox:woodstox-core:7.1.1` +
https://github.com/FasterXML/woodstox
| <<apache2,Apache License, Version 2.0>>

| docker-java-api
| `com.github.docker-java:docker-java-api:3.7.1` +
https://github.com/docker-java/docker-java
| <<apache2,Apache License, Version 2.0>>

| docker-java-transport
| `com.github.docker-java:docker-java-transport:3.7.1` +
https://github.com/docker-java/docker-java
| <<apache2,Apache License, Version 2.0>>

| docker-java-transport-zerodep
| `com.github.docker-java:docker-java-transport-zerodep:3.7.1` +
https://github.com/docker-java/docker-java
| <<apache2,Apache License, Version 2.0>>

| FindBugs-jsr305
| `com.google.code.findbugs:jsr305:3.0.2` +
http://findbugs.sourceforge.net/
| <<apache2,Apache License, Version 2.0>>

| Gson
| `com.google.code.gson:gson:2.13.2` +
https://github.com/google/gson
| <<apache2,Apache License, Version 2.0>>

| error-prone annotations
| `com.google.errorprone:error_prone_annotations:2.41.0` +
https://errorprone.info/error_prone_annotations
| <<apache2,Apache License, Version 2.0>>

| Guava InternalFutureFailureAccess and InternalFutures
| `com.google.guava:failureaccess:1.0.3` +
https://github.com/google/guava/failureaccess
| <<apache2,Apache License, Version 2.0>>

| Guava: Google Core Libraries for Java
| `com.google.guava:guava:33.5.0-jre` +
https://github.com/google/guava
| <<apache2,Apache License, Version 2.0>>

| Google Guice - Core Library
| `com.google.inject:guice:5.1.0` +
https://github.com/google/guice/guice
| <<apache2,Apache License, Version 2.0>>

| Google Guice - Core Library
| `com.google.inject:guice:6.0.0` +
https://github.com/google/guice/guice
| <<apache2,Apache License, Version 2.0>>

| hazelcast
| `com.hazelcast:hazelcast:5.3.8-payara-1` +
http://www.hazelcast.com/hazelcast/
| <<apache2,Apache License, Version 2.0>>

| Jakarta Batch jbatch Implementation
| `com.ibm.jbatch:com.ibm.jbatch.container:2.1.1` +
https://github.com/WASdev/standards.jsr352.jbatch/com.ibm.jbatch.container
| <<apache2,Apache License, Version 2.0>>

| Jakarta Batch jbatch SPI For Host Environments
| `com.ibm.jbatch:com.ibm.jbatch.spi:2.1.1` +
https://github.com/WASdev/standards.jsr352.jbatch/com.ibm.jbatch.spi
| <<apache2,Apache License, Version 2.0>>

| Nimbus JOSE+JWT
| `com.nimbusds:nimbus-jose-jwt:10.9` +
https://bitbucket.org/connect2id/nimbus-jose-jwt
| <<apache2,Apache License, Version 2.0>>

| okhttp
| `com.squareup.okhttp3:okhttp:4.12.0` +
https://square.github.io/okhttp/
| <<apache2,Apache License, Version 2.0>>

| okio
| `com.squareup.okio:okio:3.6.0` +
https://github.com/square/okio/
| <<apache2,Apache License, Version 2.0>>

| okio
| `com.squareup.okio:okio-jvm:3.6.0` +
https://github.com/square/okio/
| <<apache2,Apache License, Version 2.0>>

| ldapbp
| `com.sun:ldapbp:1.0`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| istack common utility code runtime
| `com.sun.istack:istack-commons-runtime:4.2.0` +
https://projects.eclipse.org/projects/ee4j/istack-commons/istack-commons-runtime
| <<edl1,Eclipse Distribution License, Version 1.0>>

| pkg(5) Java Client
| `com.sun.pkg:pkg-client:1.122-57.2889` +
http://java.net/projects/updatecenter2
| <<TODO_cddl_gpl,TODO: CDDL + GPL Combination — requires legal review>>

| btrace-agent
| `com.sun.tools.btrace:btrace-agent:1.2.3` +
http://nexus.sonatype.org/oss-repository-hosting.html/btrace-agent
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| btrace-boot
| `com.sun.tools.btrace:btrace-boot:1.2.3` +
http://nexus.sonatype.org/oss-repository-hosting.html/btrace-boot
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| Dataprovider
| `com.sun.woodstock.dependlibs:dataprovider:1.0` +
https://woodstock.dev.java.net/
| <<cddl1,Common Development and Distribution License (CDDL), Version 1.0>>

| Dataprovider
| `com.sun.woodstock.dependlibs:json:2.0` +
https://woodstock.dev.java.net/
| <<cddl1,Common Development and Distribution License (CDDL), Version 1.0>>

| JAXB extra OSGI
| `com.sun.xml.bind:jaxb-extra-osgi:2.3.0` +
http://jaxb.java.net/jaxb-bundles/jaxb-osgi/jaxb-extra-osgi
| <<TODO_cddl_gpl,TODO: CDDL + GPL Combination — requires legal review>>

| JAXB OSGI
| `com.sun.xml.bind:jaxb-osgi:4.0.7` +
https://eclipse-ee4j.github.io/jaxb-ri/
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Apache Commons Codec
| `commons-codec:commons-codec:1.18.0` +
https://commons.apache.org/proper/commons-codec/
| <<apache2,Apache License, Version 2.0>>

| Apache Commons Codec
| `commons-codec:commons-codec:1.19.0` +
https://commons.apache.org/proper/commons-codec/
| <<apache2,Apache License, Version 2.0>>

| Apache Commons IO
| `commons-io:commons-io:2.21.0` +
https://commons.apache.org/proper/commons-io/
| <<apache2,Apache License, Version 2.0>>

| eu.maveniverse.maven.mima:context
| `eu.maveniverse.maven.mima:context:2.4.39` +
https://www.maveniverse.eu/mima/context
| <<epl2,Eclipse Public License, Version 2.0>>

| eu.maveniverse.maven.mima.runtime:embedded-maven
| `eu.maveniverse.maven.mima.runtime:embedded-maven:2.4.39` +
https://www.maveniverse.eu/mima/runtime/embedded-maven
| <<epl2,Eclipse Public License, Version 2.0>>

| eu.maveniverse.maven.mima.runtime:standalone-shared
| `eu.maveniverse.maven.mima.runtime:standalone-shared:2.4.39` +
https://www.maveniverse.eu/mima/runtime/standalone-shared
| <<epl2,Eclipse Public License, Version 2.0>>

| eu.maveniverse.maven.mima.runtime:standalone-static
| `eu.maveniverse.maven.mima.runtime:standalone-static:2.4.39` +
https://www.maveniverse.eu/mima/runtime/standalone-static
| <<epl2,Eclipse Public License, Version 2.0>>

| h2db
| `h2db:h2db:2.2.224`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-api:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-api-events:1.29.0-alpha` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-context:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-exporter-common:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-exporter-otlp:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-exporter-otlp-common:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-exporter-sender-okhttp:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-extension-incubator:1.29.0-alpha` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-opentracing-shim:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-common:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-extension-autoconfigure:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-extension-autoconfigure-spi:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-logs:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-metrics:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-sdk-trace:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Java
| `io.opentelemetry:opentelemetry-semconv:1.29.0-alpha` +
https://github.com/open-telemetry/opentelemetry-java
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Instrumentation for Java
| `io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java-instrumentation
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Instrumentation for Java
| `io.opentelemetry.instrumentation:opentelemetry-instrumentation-annotations-support:1.29.0-alpha` +
https://github.com/open-telemetry/opentelemetry-java-instrumentation
| <<apache2,Apache License, Version 2.0>>

| OpenTelemetry Instrumentation for Java
| `io.opentelemetry.instrumentation:opentelemetry-instrumentation-api:1.29.0` +
https://github.com/open-telemetry/opentelemetry-java-instrumentation
| <<apache2,Apache License, Version 2.0>>

| OpenTracing API
| `io.opentracing:opentracing-api:0.33.0` +
https://github.com/opentracing/opentracing-java/opentracing-api
| <<apache2,Apache License, Version 2.0>>

| OpenTracing-noop
| `io.opentracing:opentracing-noop:0.33.0` +
https://github.com/opentracing/opentracing-java/opentracing-noop
| <<apache2,Apache License, Version 2.0>>

| OpenTracing-util
| `io.opentracing:opentracing-util:0.33.0` +
https://github.com/opentracing/opentracing-java/opentracing-util
| <<apache2,Apache License, Version 2.0>>

| Non-Blocking Reactive Foundation for the JVM
| `io.projectreactor:reactor-core:3.8.5` +
https://github.com/reactor/reactor-core
| <<apache2,Apache License, Version 2.0>>

| Jakarta Activation API
| `jakarta.activation:jakarta.activation-api:2.1.4` +
https://github.com/jakartaee/jaf-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Jakarta Annotations API
| `jakarta.annotation:jakarta.annotation-api:3.0.0` +
https://projects.eclipse.org/projects/ee4j.ca
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Authentication
| `jakarta.authentication:jakarta.authentication-api:3.1.0` +
https://github.com/jakartaee/authentication
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Authorization
| `jakarta.authorization:jakarta.authorization-api:3.0.0` +
https://github.com/jakartaee/authorization
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Batch API
| `jakarta.batch:jakarta.batch-api:2.1.1` +
https://github.com/eclipse-ee4j/batch-api/jakarta.batch-api
| <<apache2,Apache License, Version 2.0>>

| Jakarta Data API
| `jakarta.data:jakarta.data-api:1.0.1` +
www.eclipse.org/ee4j/data/jakarta.data-api
| <<apache2,Apache License, Version 2.0>>

| Jakarta Enterprise Beans API
| `jakarta.ejb:jakarta.ejb-api:4.0.1` +
https://github.com/jakartaee/enterprise-beans
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Expression Language API
| `jakarta.el:jakarta.el-api:6.0.1` +
https://projects.eclipse.org/projects/ee4j.el
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| CDI APIs
| `jakarta.enterprise:jakarta.enterprise.cdi-api:4.1.0` +
http://cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| CDI EL integration API
| `jakarta.enterprise:jakarta.enterprise.cdi-el-api:4.1.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.enterprise.cdi-parent/jakarta.enterprise.cdi-el-api
| <<apache2,Apache License, Version 2.0>>

| CDI Language Model
| `jakarta.enterprise:jakarta.enterprise.lang-model:4.1.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.enterprise.cdi-parent/jakarta.enterprise.lang-model
| <<apache2,Apache License, Version 2.0>>

| Jakarta Concurrency
| `jakarta.enterprise.concurrent:jakarta.enterprise.concurrent-api:3.1.1` +
https://github.com/jakartaee/concurrency
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| javax.enterprise.deploy API
| `jakarta.enterprise.deploy:jakarta.enterprise.deploy-api:1.7.2` +
http://jcp.org/en/jsr/detail?id=88
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Faces
| `jakarta.faces:jakarta.faces-api:4.1.2` +
https://github.com/eclipse-ee4j/faces-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Dependency Injection
| `jakarta.inject:jakarta.inject-api:2.0.1` +
https://github.com/eclipse-ee4j/injection-api
| <<apache2,Apache License, Version 2.0>>

| Jakarta Interceptors
| `jakarta.interceptor:jakarta.interceptor-api:2.2.0` +
https://github.com/jakartaee/interceptors
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Messaging API
| `jakarta.jms:jakarta.jms-api:3.1.0` +
https://projects.eclipse.org/projects/ee4j.jms
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta JSON Processing API
| `jakarta.json:jakarta.json-api:2.1.3` +
https://github.com/eclipse-ee4j/jsonp
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| JSON-B API
| `jakarta.json.bind:jakarta.json.bind-api:3.0.1` +
https://jakartaee.github.io/jsonb-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Web Services Metadata API
| `jakarta.jws:jakarta.jws-api:3.0.0` +
https://github.com/eclipse-ee4j/jws-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Jakarta Mail API
| `jakarta.mail:jakarta.mail-api:2.1.5` +
https://projects.eclipse.org/projects/ee4j/jakarta.mail-api
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta MVC API
| `jakarta.mvc:jakarta.mvc-api:3.0.0` +
https://www.mvc-spec.org/
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Persistence API
| `jakarta.persistence:jakarta.persistence-api:3.2.0` +
https://github.com/jakartaee/persistence
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| jakarta.jakartaee-api
| `jakarta.platform:jakarta.jakartaee-api:11.0.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.jakartaee-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jakarta.jakartaee-core-api
| `jakarta.platform:jakarta.jakartaee-core-api:11.0.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.jakartaee-core-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jakarta.jakartaee-web-api
| `jakarta.platform:jakarta.jakartaee-web-api:11.0.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.jakartaee-web-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jakarta.resource API
| `jakarta.resource:jakarta.resource-api:2.1.0` +
https://github.com/eclipse-ee4j/jca-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Security
| `jakarta.security.enterprise:jakarta.security.enterprise-api:4.0.0` +
https://projects.eclipse.org/projects/ee4j/jakarta.security.enterprise-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Servlet
| `jakarta.servlet:jakarta.servlet-api:6.1.0` +
https://projects.eclipse.org/projects/ee4j.servlet
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Server Pages API
| `jakarta.servlet.jsp:jakarta.servlet.jsp-api:4.0.0` +
https://projects.eclipse.org/projects/ee4j.jsp
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Standard Tag Library API
| `jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:3.0.2` +
https://projects.eclipse.org/projects/ee4j.jstl
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jakarta.transaction API
| `jakarta.transaction:jakarta.transaction-api:2.0.1` +
https://projects.eclipse.org/projects/ee4j.jta
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta Validation API
| `jakarta.validation:jakarta.validation-api:3.1.1` +
https://beanvalidation.org
| <<apache2,Apache License, Version 2.0>>

| Jakarta WebSocket - Server API
| `jakarta.websocket:jakarta.websocket-api:2.2.0` +
https://projects.eclipse.org/projects/ee4j.websocket
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta WebSocket - Client API
| `jakarta.websocket:jakarta.websocket-client-api:2.2.0` +
https://projects.eclipse.org/projects/ee4j.websocket
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta RESTful WS API
| `jakarta.ws.rs:jakarta.ws.rs-api:4.0.0` +
https://github.com/jakartaee/rest/jakarta.ws.rs-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Jakarta XML Binding API
| `jakarta.xml.bind:jakarta.xml.bind-api:4.0.5` +
https://github.com/jakartaee/jaxb-api/jakarta.xml.bind-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Jakarta SOAP with Attachments API
| `jakarta.xml.soap:jakarta.xml.soap-api:3.0.2` +
https://github.com/jakartaee/saaj-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Jakarta XML Web Services API
| `jakarta.xml.ws:jakarta.xml.ws-api:4.0.3` +
https://github.com/jakartaee/jax-ws-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| JSR107 API and SPI
| `javax.cache:cache-api:1.1.1.payara-p1` +
https://github.com/jsr107/jsr107spec
| <<apache2,Apache License, Version 2.0>>

| JavaHelp API
| `javax.help:javahelp:2.0.05` +
https://javahelp.dev.java.net/
| <<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| javax.inject
| `javax.inject:javax.inject:1` +
http://code.google.com/p/atinject/
| <<apache2,Apache License, Version 2.0>>

| JUnit
| `junit:junit:4.13.2` +
http://junit.org
| <<epl1,Eclipse Public License, Version 1.0>>

| Byte Buddy (without dependencies)
| `net.bytebuddy:byte-buddy:1.17.5` +
https://bytebuddy.net/byte-buddy
| <<apache2,Apache License, Version 2.0>>

| Byte Buddy (without dependencies)
| `net.bytebuddy:byte-buddy:1.17.7` +
https://bytebuddy.net/byte-buddy
| <<apache2,Apache License, Version 2.0>>

| Byte Buddy agent
| `net.bytebuddy:byte-buddy-agent:1.17.7` +
https://bytebuddy.net/byte-buddy-agent
| <<apache2,Apache License, Version 2.0>>

| EdDSA-Java
| `net.i2p.crypto:eddsa:0.3.0` +
https://github.com/str4d/ed25519-java
| <<cc0,CC0 1.0 Universal>>

| Java Native Access
| `net.java.dev.jna:jna:5.18.1` +
https://github.com/java-native-access/jna
| <<apache2,Apache License, Version 2.0>> + 
<<lgpl21,GNU Lesser General Public License, Version 2.1>>

| ASM based accessors helper used by json-smart
| `net.minidev:accessors-smart:2.5.2` +
https://urielch.github.io/
| <<apache2,Apache License, Version 2.0>>

| ASM based accessors helper used by json-smart
| `net.minidev:accessors-smart:2.6.0` +
https://urielch.github.io/
| <<apache2,Apache License, Version 2.0>>

| JSON Small and Fast Parser
| `net.minidev:json-smart:2.5.2` +
https://urielch.github.io/
| <<apache2,Apache License, Version 2.0>>

| JSON Small and Fast Parser
| `net.minidev:json-smart:2.6.0` +
https://urielch.github.io/
| <<apache2,Apache License, Version 2.0>>

| Apache Ant Core
| `org.apache.ant:ant:1.10.17` +
https://ant.apache.org/
| <<apache2,Apache License, Version 2.0>>

| Apache Ant Launcher
| `org.apache.ant:ant-launcher:1.10.17` +
https://ant.apache.org/
| <<apache2,Apache License, Version 2.0>>

| Apache Commons BCEL
| `org.apache.bcel:bcel:6.12.0` +
https://commons.apache.org/proper/commons-bcel
| <<apache2,Apache License, Version 2.0>>

| Apache Commons Compress
| `org.apache.commons:commons-compress:1.28.0` +
https://commons.apache.org/proper/commons-compress/
| <<apache2,Apache License, Version 2.0>>

| Apache Commons Lang
| `org.apache.commons:commons-lang3:3.18.0` +
https://commons.apache.org/proper/commons-lang/
| <<apache2,Apache License, Version 2.0>>

| Apache Commons Lang
| `org.apache.commons:commons-lang3:3.20.0` +
https://commons.apache.org/proper/commons-lang/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Configuration Admin Service
| `org.apache.felix:org.apache.felix.configadmin:1.9.26` +
http://felix.apache.org/org.apache.felix.configadmin/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix EventAdmin
| `org.apache.felix:org.apache.felix.eventadmin:1.6.4` +
https://felix.apache.org/org.apache.felix.eventadmin/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix File Install
| `org.apache.felix:org.apache.felix.fileinstall:3.7.4.payara-p1` +
http://felix.apache.org/site/apache-felix-file-install.html
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Gogo Command
| `org.apache.felix:org.apache.felix.gogo.command:1.1.2` +
http://felix.apache.org/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Gogo Runtime
| `org.apache.felix:org.apache.felix.gogo.runtime:1.1.6` +
http://felix.apache.org/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Gogo Shell
| `org.apache.felix:org.apache.felix.gogo.shell:1.1.4` +
http://felix.apache.org/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Declarative Services
| `org.apache.felix:org.apache.felix.scr:2.2.18` +
https://felix.apache.org/org.apache.felix.scr/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Shell Service
| `org.apache.felix:org.apache.felix.shell:1.4.3` +
http://felix.apache.org/org.apache.felix.shell/
| <<apache2,Apache License, Version 2.0>>

| Apache Felix Web Management Console
| `org.apache.felix:org.apache.felix.webconsole:5.0.18` +
https://felix.apache.org/org.apache.felix.webconsole/
| <<apache2,Apache License, Version 2.0>>

| Apache HttpClient
| `org.apache.httpcomponents:httpclient:4.5.14` +
http://hc.apache.org/httpcomponents-client-ga
| <<apache2,Apache License, Version 2.0>>

| Apache HttpCore
| `org.apache.httpcomponents:httpcore:4.4.16` +
http://hc.apache.org/httpcomponents-core-ga
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact
| `org.apache.maven:maven-artifact:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-artifact/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact
| `org.apache.maven:maven-artifact:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-artifact/
| <<apache2,Apache License, Version 2.0>>

| Maven Builder Support
| `org.apache.maven:maven-builder-support:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-builder-support/
| <<apache2,Apache License, Version 2.0>>

| Maven Builder Support
| `org.apache.maven:maven-builder-support:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-builder-support/
| <<apache2,Apache License, Version 2.0>>

| Maven Core
| `org.apache.maven:maven-core:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-core/
| <<apache2,Apache License, Version 2.0>>

| Maven Model
| `org.apache.maven:maven-model:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-model/
| <<apache2,Apache License, Version 2.0>>

| Maven Model
| `org.apache.maven:maven-model:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-model/
| <<apache2,Apache License, Version 2.0>>

| Maven Model Builder
| `org.apache.maven:maven-model-builder:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-model-builder/
| <<apache2,Apache License, Version 2.0>>

| Maven Model Builder
| `org.apache.maven:maven-model-builder:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-model-builder/
| <<apache2,Apache License, Version 2.0>>

| Maven Plugin API
| `org.apache.maven:maven-plugin-api:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-plugin-api/
| <<apache2,Apache License, Version 2.0>>

| Maven Repository Metadata Model
| `org.apache.maven:maven-repository-metadata:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-repository-metadata/
| <<apache2,Apache License, Version 2.0>>

| Maven Repository Metadata Model
| `org.apache.maven:maven-repository-metadata:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-repository-metadata/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Provider
| `org.apache.maven:maven-resolver-provider:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-resolver-provider/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Provider
| `org.apache.maven:maven-resolver-provider:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-resolver-provider/
| <<apache2,Apache License, Version 2.0>>

| Maven Settings
| `org.apache.maven:maven-settings:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-settings/
| <<apache2,Apache License, Version 2.0>>

| Maven Settings
| `org.apache.maven:maven-settings:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-settings/
| <<apache2,Apache License, Version 2.0>>

| Maven Settings Builder
| `org.apache.maven:maven-settings-builder:3.9.12` +
https://maven.apache.org/ref/3.9.12/maven-settings-builder/
| <<apache2,Apache License, Version 2.0>>

| Maven Settings Builder
| `org.apache.maven:maven-settings-builder:3.9.15` +
https://maven.apache.org/ref/3.9.15/maven-settings-builder/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver API
| `org.apache.maven.resolver:maven-resolver-api:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-api/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver API
| `org.apache.maven.resolver:maven-resolver-api:1.9.27` +
https://maven.apache.org/resolver/maven-resolver-api/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Connector Basic
| `org.apache.maven.resolver:maven-resolver-connector-basic:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-connector-basic/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Implementation
| `org.apache.maven.resolver:maven-resolver-impl:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-impl/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Implementation
| `org.apache.maven.resolver:maven-resolver-impl:1.9.27` +
https://maven.apache.org/resolver/maven-resolver-impl/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Named Locks
| `org.apache.maven.resolver:maven-resolver-named-locks:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-named-locks/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Named Locks
| `org.apache.maven.resolver:maven-resolver-named-locks:1.9.27` +
https://maven.apache.org/resolver/maven-resolver-named-locks/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver SPI
| `org.apache.maven.resolver:maven-resolver-spi:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-spi/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver SPI
| `org.apache.maven.resolver:maven-resolver-spi:1.9.27` +
https://maven.apache.org/resolver/maven-resolver-spi/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Instance Supplier
| `org.apache.maven.resolver:maven-resolver-supplier:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-supplier/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Transport File
| `org.apache.maven.resolver:maven-resolver-transport-file:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-transport-file/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Transport HTTP
| `org.apache.maven.resolver:maven-resolver-transport-http:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-transport-http/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Utilities
| `org.apache.maven.resolver:maven-resolver-util:1.9.25` +
https://maven.apache.org/resolver/maven-resolver-util/
| <<apache2,Apache License, Version 2.0>>

| Maven Artifact Resolver Utilities
| `org.apache.maven.resolver:maven-resolver-util:1.9.27` +
https://maven.apache.org/resolver/maven-resolver-util/
| <<apache2,Apache License, Version 2.0>>

| Apache Maven Shared Utils
| `org.apache.maven.shared:maven-shared-utils:3.4.2` +
https://maven.apache.org/shared/maven-shared-utils/
| <<apache2,Apache License, Version 2.0>>

| Apache XML Security for Java
| `org.apache.santuario:xmlsec:4.0.4` +
https://santuario.apache.org/
| <<apache2,Apache License, Version 2.0>>

| org.apiguardian:apiguardian-api
| `org.apiguardian:apiguardian-api:1.1.2` +
https://github.com/apiguardian-team/apiguardian
| <<apache2,Apache License, Version 2.0>>

| AssertJ Core
| `org.assertj:assertj-core:3.27.7` +
https://assertj.github.io/doc/#assertj-core
| <<apache2,Apache License, Version 2.0>>

| Awaitility
| `org.awaitility:awaitility:4.3.0` +
http://awaitility.org
| <<apache2,Apache License, Version 2.0>>

| Bouncy Castle PKIX, CMS, EAC, TSP, PKCS, OCSP, CMP, and CRMF APIs
| `org.bouncycastle:bcpkix-jdk15on:1.70` +
https://www.bouncycastle.org/java.html
| <<TODO_bouncy,TODO: Bouncy Castle Licence — requires legal review>>

| Bouncy Castle Provider
| `org.bouncycastle:bcprov-jdk15on:1.70` +
https://www.bouncycastle.org/java.html
| <<TODO_bouncy,TODO: Bouncy Castle Licence — requires legal review>>

| Bouncy Castle ASN.1 Extension and Utility APIs
| `org.bouncycastle:bcutil-jdk15on:1.70` +
https://www.bouncycastle.org/java.html
| <<TODO_bouncy,TODO: Bouncy Castle Licence — requires legal review>>

| Animal Sniffer Annotations
| `org.codehaus.mojo:animal-sniffer-annotations:1.9` +
http://mojo.codehaus.org/animal-sniffer/animal-sniffer-annotations
| <<mit,MIT License>>

| Plexus Cipher: encryption/decryption Component
| `org.codehaus.plexus:plexus-cipher:2.0` +
https://codehaus-plexus.github.io/plexus-cipher/
| <<apache2,Apache License, Version 2.0>>

| Plexus Classworlds
| `org.codehaus.plexus:plexus-classworlds:2.9.0` +
https://codehaus-plexus.github.io/plexus-classworlds/
| <<apache2,Apache License, Version 2.0>>

| Plexus Compiler Api
| `org.codehaus.plexus:plexus-compiler-api:2.16.2` +
https://codehaus-plexus.github.io/plexus-pom/plexus-compiler/plexus-compiler-api/
| <<apache2,Apache License, Version 2.0>>

| Plexus Javac Component
| `org.codehaus.plexus:plexus-compiler-javac:2.16.2` +
https://codehaus-plexus.github.io/plexus-pom/plexus-compiler/plexus-compilers/plexus-compiler-javac/
| <<apache2,Apache License, Version 2.0>>

| Plexus :: Component Annotations
| `org.codehaus.plexus:plexus-component-annotations:2.1.0` +
http://codehaus-plexus.github.io/plexus-containers/plexus-component-annotations/
| <<apache2,Apache License, Version 2.0>>

| Plexus :: Component Annotations (deprecated)
| `org.codehaus.plexus:plexus-component-annotations:2.2.0` +
https://codehaus-plexus.github.io/plexus-containers/plexus-component-annotations/
| <<apache2,Apache License, Version 2.0>>

| Plexus Interpolation API
| `org.codehaus.plexus:plexus-interpolation:1.29` +
https://codehaus-plexus.github.io/plexus-pom/plexus-interpolation/
| <<apache2,Apache License, Version 2.0>>

| Plexus Security Dispatcher Component
| `org.codehaus.plexus:plexus-sec-dispatcher:2.0` +
https://codehaus-plexus.github.io/plexus-sec-dispatcher/
| <<apache2,Apache License, Version 2.0>>

| Plexus Common Utilities
| `org.codehaus.plexus:plexus-utils:3.6.0` +
https://codehaus-plexus.github.io/plexus-utils/
| <<apache2,Apache License, Version 2.0>>

| Plexus Common Utilities
| `org.codehaus.plexus:plexus-utils:3.6.1` +
https://codehaus-plexus.github.io/plexus-utils/
| <<apache2,Apache License, Version 2.0>>

| Stax2 API
| `org.codehaus.woodstox:stax2-api:4.3.0` +
http://github.com/FasterXML/stax2-api
| <<bsd2,BSD 2-Clause License>>

| jBCrypt
| `org.connectbot:jbcrypt:1.0.2` +
https://github.com/kruton/jbcrypt
| <<isc,ISC License>>

| crac
| `org.crac:crac:1.5.0` +
https://github.com/crac/org.crac
| <<bsd2,BSD 2-Clause License>>

| EasyMock
| `org.easymock:easymock:5.6.0` +
http://easymock.org/easymock
| <<apache2,Apache License, Version 2.0>>

| Yasson
| `org.eclipse:yasson:3.0.4` +
https://projects.eclipse.org/projects/ee4j.yasson
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| Angus Activation Registries
| `org.eclipse.angus:angus-activation:2.0.3` +
https://github.com/eclipse-ee4j/angus-activation/angus-activation
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Angus Mail Provider
| `org.eclipse.angus:angus-mail:2.0.5` +
http://eclipse-ee4j.github.io/angus-mail/angus-mail
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Eclipse Krazo Core
| `org.eclipse.krazo:krazo-core:4.0.1.payara-p1` +
https://projects.eclipse.org/projects/ee4j.krazo/krazo-core
| <<apache2,Apache License, Version 2.0>>

| Eclipse Krazo Jersey
| `org.eclipse.krazo:krazo-jersey:4.0.1.payara-p1` +
https://projects.eclipse.org/projects/ee4j.krazo/krazo-jersey
| <<apache2,Apache License, Version 2.0>>

| MicroProfile Config API
| `org.eclipse.microprofile.config:microprofile-config-api:3.1.1` +
https://microprofile.io/project/eclipse/microprofile-config/microprofile-config-api
| <<apache2,Apache License, Version 2.0>>

| microProfile-fault-tolerance-api
| `org.eclipse.microprofile.fault-tolerance:microprofile-fault-tolerance-api:4.0.2.payara-p1` +
http://microprofile.io/microprofile-fault-tolerance-parent/microprofile-fault-tolerance-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile Health API
| `org.eclipse.microprofile.health:microprofile-health-api:4.0.1` +
https://microprofile.io/project/eclipse/microprofile-health/microprofile-health-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile JWT Auth API
| `org.eclipse.microprofile.jwt:microprofile-jwt-auth-api:2.1` +
https://github.com/eclipse/microprofile-jwt-auth/microprofile-jwt-auth-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile Metrics API
| `org.eclipse.microprofile.metrics:microprofile-metrics-api:5.1.2` +
http://microprofile.io/microprofile-metrics-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile OpenAPI API
| `org.eclipse.microprofile.openapi:microprofile-openapi-api:3.1.2` +
http://microprofile.io/microprofile-openapi-parent/microprofile-openapi-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile OpenTracing API
| `org.eclipse.microprofile.opentracing:microprofile-opentracing-api:3.0` +
http://microprofile.io/microprofile-opentracing-api
| <<apache2,Apache License, Version 2.0>>

| MicroProfile Rest Client API
| `org.eclipse.microprofile.rest.client:microprofile-rest-client-api:3.0.1` +
http://microprofile.io/microprofile-rest-client-api
| <<apache2,Apache License, Version 2.0>>

| JSON-P with Parsson Provider
| `org.eclipse.parsson:jakarta.json:1.1.7.payara-p1` +
https://github.com/eclipse-ee4j/parsson/parsson-bundles/jakarta.json
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Eclipse Parsson
| `org.eclipse.parsson:parsson:1.1.7` +
https://github.com/eclipse-ee4j/parsson/parsson
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Eclipse Parsson Media for Jakarta RESTful Web Services
| `org.eclipse.parsson:parsson-media:1.1.7.payara-p1` +
https://github.com/eclipse-ee4j/parsson/parsson-media
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| EclipseLink ASM
| `org.eclipse.persistence:org.eclipse.persistence.asm:9.9.0` +
http://www.eclipse.org/eclipselink
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink Core
| `org.eclipse.persistence:org.eclipse.persistence.core:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/foundation/org.eclipse.persistence.core
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink DBWS
| `org.eclipse.persistence:org.eclipse.persistence.dbws:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/dbws/org.eclipse.persistence.dbws
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink JPA
| `org.eclipse.persistence:org.eclipse.persistence.jpa:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/jpa/org.eclipse.persistence.jpa
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink Hermes Parser
| `org.eclipse.persistence:org.eclipse.persistence.jpa.jpql:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/jpa/org.eclipse.persistence.jpa.jpql
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink JPA Model Generator
| `org.eclipse.persistence:org.eclipse.persistence.jpa.modelgen.processor:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/org.eclipse.persistence.jpa.modelgen.processor
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink JSON Extension
| `org.eclipse.persistence:org.eclipse.persistence.json:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/foundation/org.eclipse.persistence.json
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink MOXy
| `org.eclipse.persistence:org.eclipse.persistence.moxy:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/moxy/org.eclipse.persistence.moxy
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| EclipseLink Oracle Extension
| `org.eclipse.persistence:org.eclipse.persistence.oracle:5.0.0-B11.payara-p1` +
http://www.eclipse.org/eclipselink/foundation/org.eclipse.persistence.oracle
| <<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>>

| org.eclipse.sisu:org.eclipse.sisu.inject
| `org.eclipse.sisu:org.eclipse.sisu.inject:0.9.0.M4` +
https://eclipse.dev/sisu/org.eclipse.sisu.inject/
| <<epl2,Eclipse Public License, Version 2.0>>

| org.eclipse.sisu:org.eclipse.sisu.inject
| `org.eclipse.sisu:org.eclipse.sisu.inject:1.0.0` +
https://eclipse.dev/sisu/org.eclipse.sisu.inject/
| <<epl2,Eclipse Public License, Version 2.0>>

| org.eclipse.sisu:org.eclipse.sisu.plexus
| `org.eclipse.sisu:org.eclipse.sisu.plexus:0.9.0.M4` +
https://eclipse.dev/sisu/org.eclipse.sisu.plexus/
| <<epl2,Eclipse Public License, Version 2.0>>

| org.eclipse.sisu:org.eclipse.sisu.plexus
| `org.eclipse.sisu:org.eclipse.sisu.plexus:1.0.0` +
https://eclipse.dev/sisu/org.eclipse.sisu.plexus/
| <<epl2,Eclipse Public License, Version 2.0>>

| Mojarra 4.1.7.payara-p1
| `org.glassfish:jakarta.faces:4.1.7.payara-p1` +
https://github.com/eclipse-ee4j/mojarra
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| GlassFish Logging Annotation Processor
| `org.glassfish.annotations:logging-annotation-processor:1.10` +
https://projects.eclipse.org/projects/ee4j/logging-annotation-processor
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Eclipse Concurro
| `org.glassfish.concurro:concurro:3.1.0` +
https://projects.eclipse.org/projects/ee4j.glassfish
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Generated CSIv2 APIs
| `org.glassfish.corba:glassfish-corba-csiv2-idl:5.0.0.payara-p1` +
https://projects.eclipse.org/proposals/eclipse-orb/glassfish-corba-csiv2-idl
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Exposed Internal APIs
| `org.glassfish.corba:glassfish-corba-internal-api:5.0.0.payara-p1` +
https://projects.eclipse.org/proposals/eclipse-orb/glassfish-corba-internal-api
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Generated OMG APIs
| `org.glassfish.corba:glassfish-corba-omgapi:5.0.0.payara-p1` +
https://projects.eclipse.org/proposals/eclipse-orb/glassfish-corba-omgapi
| <<edl1,Eclipse Distribution License, Version 1.0>>

| GlassFish Corba ORB
| `org.glassfish.corba:glassfish-corba-orb:5.0.0.payara-p1` +
https://projects.eclipse.org/proposals/eclipse-orb/glassfish-corba-orb
| <<edl1,Eclipse Distribution License, Version 1.0>>

| RMIC compiler
| `org.glassfish.corba:rmic:5.0.0.payara-p1` +
https://projects.eclipse.org/proposals/eclipse-orb/rmic
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Epicyro
| `org.glassfish.epicyro:epicyro:3.1.1` +
https://projects.eclipse.org/projects/ee4j.epicyro
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Exousia
| `org.glassfish.exousia:exousia:3.0.1` +
https://projects.eclipse.org/projects/ee4j.exousia
| <<epl2,Eclipse Public License, Version 2.0>>

| Eclipse Expressly
| `org.glassfish.expressly:expressly:6.0.0` +
https://projects.eclipse.org/projects/ee4j.expressly
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| management-api
| `org.glassfish.external:management-api:3.3.0.payara-p1` +
https://github.com/eclipse-ee4j/orb-gmbal-commons
| <<edl1,Eclipse Distribution License, Version 1.0>>

| opendmk_jmxremote_optional_jar
| `org.glassfish.external:opendmk_jmxremote_optional_jar:1.0-b01-ea`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| Schema2beans repackaged as an OSGI bundle
| `org.glassfish.external:schema2beans:6.7` +
https://projects.eclipse.org/projects/ee4j/schema2beans
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| GMBAL (Implementation)
| `org.glassfish.gmbal:gmbal:4.1.1` +
https://projects.eclipse.org/projects/ee4j.orb/gmbal
| <<edl1,Eclipse Distribution License, Version 1.0>>

| GMBAL (API only)
| `org.glassfish.gmbal:gmbal-api-only:4.1.1` +
https://projects.eclipse.org/projects/ee4j.orb/gmbal-api-only
| <<edl1,Eclipse Distribution License, Version 1.0>>

| grizzly-comet
| `org.glassfish.grizzly:grizzly-comet:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-comet
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-framework
| `org.glassfish.grizzly:grizzly-framework:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-framework
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-http
| `org.glassfish.grizzly:grizzly-http:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-http
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-http-ajp
| `org.glassfish.grizzly:grizzly-http-ajp:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-http-server
| `org.glassfish.grizzly:grizzly-http-server:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-http-server
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-http-servlet
| `org.glassfish.grizzly:grizzly-http-servlet:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-http-servlet
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-http2
| `org.glassfish.grizzly:grizzly-http2:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-http2
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-npn-api
| `org.glassfish.grizzly:grizzly-npn-api:2.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-npn-api
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-npn-osgi
| `org.glassfish.grizzly:grizzly-npn-osgi:2.0.0` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-npn-osgi
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-portunif
| `org.glassfish.grizzly:grizzly-portunif:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-portunif
| <<epl2,Eclipse Public License, Version 2.0>>

| grizzly-websockets
| `org.glassfish.grizzly:grizzly-websockets:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/grizzly-websockets
| <<epl2,Eclipse Public License, Version 2.0>>

| tls-sni
| `org.glassfish.grizzly:tls-sni:4.1.0-M1.payara-p2` +
https://projects.eclipse.org/projects/ee4j.grizzly/tls-sni
| <<epl2,Eclipse Public License, Version 2.0>>

| GlassFish High Availability APIs and SPI
| `org.glassfish.ha:ha-api:3.1.13` +
https://projects.eclipse.org/projects/ee4j/ha-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Class Model for Hk2
| `org.glassfish.hk2:class-model:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/class-model
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 core module
| `org.glassfish.hk2:core:2.4.0-b14` +
https://hk2.java.net/core
| <<TODO_cddl_gpl,TODO: CDDL + GPL Combination — requires legal review>>

| HK2 module of HK2 itself
| `org.glassfish.hk2:hk2:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 API module
| `org.glassfish.hk2:hk2-api:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-api
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 core module
| `org.glassfish.hk2:hk2-core:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-core
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 extras module
| `org.glassfish.hk2:hk2-extras:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-extras
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 Junit Runner
| `org.glassfish.hk2:hk2-junitrunner:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-junitrunner
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| ServiceLocator Default Implementation
| `org.glassfish.hk2:hk2-locator:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-locator
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 Metadata Generator
| `org.glassfish.hk2:hk2-metadata-generator:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-metadata-generator-parent/hk2-metadata-generator
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Run Level Service
| `org.glassfish.hk2:hk2-runlevel:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-runlevel
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 Implementation Utilities
| `org.glassfish.hk2:hk2-utils:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/hk2-utils
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 OSGi Adapter
| `org.glassfish.hk2:osgi-adapter:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/osgi/osgi-adapter
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| HK2 OSGi resource locator
| `org.glassfish.hk2:osgi-resource-locator:3.0.0` +
https://projects.eclipse.org/projects/ee4j/hk2-extra-parent/osgi-resource-locator
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| aopalliance version 1.0 repackaged as a module
| `org.glassfish.hk2.external:aopalliance-repackaged:4.0.0-M3.payara-p2` +
https://github.com/eclipse-ee4j/glassfish-hk2/external/aopalliance-repackaged
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Codemodel Core
| `org.glassfish.jaxb:codemodel:4.0.7` +
https://eclipse-ee4j.github.io/jaxb-ri/
| <<edl1,Eclipse Distribution License, Version 1.0>>

| jersey-container-grizzly2-http
| `org.glassfish.jersey.containers:jersey-container-grizzly2-http:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-container-grizzly2-http
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-container-servlet
| `org.glassfish.jersey.containers:jersey-container-servlet:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-container-servlet
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-gf-ejb
| `org.glassfish.jersey.containers.glassfish:jersey-gf-ejb:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/project/jersey-gf-ejb
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-core-client
| `org.glassfish.jersey.core:jersey-client:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/jersey-client
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-core-common
| `org.glassfish.jersey.core:jersey-common:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/jersey-common
| <<apache2,Apache License, Version 2.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<publicdomain,Public Domain>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jersey-core-server
| `org.glassfish.jersey.core:jersey-server:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/jersey-server
| <<apache2,Apache License, Version 2.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<bsd3,BSD 3-Clause License>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jersey-ext-bean-validation
| `org.glassfish.jersey.ext:jersey-bean-validation:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-bean-validation
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-entity-filtering
| `org.glassfish.jersey.ext:jersey-entity-filtering:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-entity-filtering
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-mvc
| `org.glassfish.jersey.ext:jersey-mvc:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-mvc
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-mvc-jsp
| `org.glassfish.jersey.ext:jersey-mvc-jsp:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-mvc-jsp
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-proxy-client
| `org.glassfish.jersey.ext:jersey-proxy-client:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-proxy-client
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-cdi1x
| `org.glassfish.jersey.ext.cdi:jersey-cdi1x:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/project/jersey-cdi1x
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-cdi1x-servlet
| `org.glassfish.jersey.ext.cdi:jersey-cdi1x-servlet:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/project/jersey-cdi1x-servlet
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-cdi1x-transaction
| `org.glassfish.jersey.ext.cdi:jersey-cdi1x-transaction:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/project/jersey-cdi1x-transaction
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-ext-mp-rest-client
| `org.glassfish.jersey.ext.microprofile:jersey-mp-rest-client:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/project/jersey-mp-rest-client
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-inject-hk2
| `org.glassfish.jersey.inject:jersey-hk2:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-hk2
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-jaxb
| `org.glassfish.jersey.media:jersey-media-jaxb:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-jaxb
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-json-binding
| `org.glassfish.jersey.media:jersey-media-json-binding:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-json-binding
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-json-jackson
| `org.glassfish.jersey.media:jersey-media-json-jackson:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-json-jackson
| <<apache2,Apache License, Version 2.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jersey-media-json-processing
| `org.glassfish.jersey.media:jersey-media-json-processing:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-json-processing
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-moxy
| `org.glassfish.jersey.media:jersey-media-moxy:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-moxy
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-multipart
| `org.glassfish.jersey.media:jersey-media-multipart:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-multipart
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jersey-media-sse
| `org.glassfish.jersey.media:jersey-media-sse:4.0.0.payara-p1` +
https://projects.eclipse.org/projects/ee4j.jersey/project/jersey-media-sse
| <<apache2,Apache License, Version 2.0>> + 
<<bsd2,BSD 2-Clause License>> + 
<<edl1,Eclipse Distribution License, Version 1.0>> + 
<<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>> + 
<<mit,MIT License>> + 
<<bsd3,BSD 3-Clause License>> + 
<<publicdomain,Public Domain>> + 
<<TODO_w3c,TODO: W3C License — requires legal review>> + 
<<TODO_jquery,TODO: jQuery License — requires legal review>>

| jsftemplating
| `org.glassfish.jsftemplating:jsftemplating:4.2.0` +
https://projects.eclipse.org/projects/ee4j/jsftemplating-parent/jsftemplating
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| jsftemplating-dt
| `org.glassfish.jsftemplating:jsftemplating-dt:4.2.0` +
https://projects.eclipse.org/projects/ee4j/jsftemplating-parent/jsftemplating-dt
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Metro Web Services API OSGi Bundle
| `org.glassfish.metro:webservices-api-osgi:4.0.4.payara-p1` +
https://github.com/eclipse-ee4j/metro-wsit/bundles/webservices-api-osgi
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Extra JDK packages required by Metro Web Services OSGi bundle
| `org.glassfish.metro:webservices-extra-jdk-packages:4.0.4.payara-p1` +
https://github.com/eclipse-ee4j/metro-wsit/bundles/webservices-extra-jdk-packages
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Metro Web Services Runtime OSGi Bundle
| `org.glassfish.metro:webservices-osgi:4.0.4.payara-p1` +
https://github.com/eclipse-ee4j/metro-wsit/bundles/webservices-osgi
| <<edl1,Eclipse Distribution License, Version 1.0>>

| WS-TX Protocol Web Services
| `org.glassfish.metro:wstx-services:4.0.4.payara-p1` +
https://github.com/eclipse-ee4j/metro-wsit/wstx-project/wstx-services
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Message Queue
| `org.glassfish.mq:mq-distribution:6.8.0.payara-p2` +
https://github.com/eclipse-ee4j/openmq
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| PFL Basic
| `org.glassfish.pfl:pfl-basic:5.1.0` +
https://github.com/eclipse-ee4j/orb-gmbal-pfl/pfl-basic
| <<edl1,Eclipse Distribution License, Version 1.0>>

| PFL Basic Tools
| `org.glassfish.pfl:pfl-basic-tools:5.1.0` +
https://github.com/eclipse-ee4j/orb-gmbal-pfl/pfl-basic-tools
| <<edl1,Eclipse Distribution License, Version 1.0>>

| PFL Dynamic
| `org.glassfish.pfl:pfl-dynamic:5.1.0` +
https://github.com/eclipse-ee4j/orb-gmbal-pfl/pfl-dynamic
| <<edl1,Eclipse Distribution License, Version 1.0>>

| PFL TF
| `org.glassfish.pfl:pfl-tf:5.1.0` +
https://github.com/eclipse-ee4j/orb-gmbal-pfl/pfl-tf
| <<edl1,Eclipse Distribution License, Version 1.0>>

| PFL TF TOOLS
| `org.glassfish.pfl:pfl-tf-tools:5.1.0` +
https://github.com/eclipse-ee4j/orb-gmbal-pfl/pfl-tf-tools
| <<edl1,Eclipse Distribution License, Version 1.0>>

| Soteria 4.0.1.payara-p1
| `org.glassfish.soteria:soteria:4.0.1.payara-p1` +
https://projects.eclipse.org/projects/ee4j/soteria
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Soteria SPI : Bean Decorator : Weld
| `org.glassfish.soteria:soteria.spi.bean.decorator.weld:4.0.1.payara-p1` +
https://projects.eclipse.org/projects/ee4j/parent/spi/spi-bean-decorator/soteria.spi.bean.decorator.weld
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Client
| `org.glassfish.tyrus:tyrus-client:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-client
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus CDI Component Provider
| `org.glassfish.tyrus:tyrus-container-glassfish-cdi:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-containers-project/tyrus-containers-glassfish-project/tyrus-container-glassfish-cdi
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus EJB Component Provider
| `org.glassfish.tyrus:tyrus-container-glassfish-ejb:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-containers-project/tyrus-containers-glassfish-project/tyrus-container-glassfish-ejb
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Grizzly Client Container
| `org.glassfish.tyrus:tyrus-container-grizzly-client:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-containers-project/tyrus-container-grizzly-client
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Servlet Bundle
| `org.glassfish.tyrus:tyrus-container-servlet:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-containers-project/tyrus-container-servlet
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Core
| `org.glassfish.tyrus:tyrus-core:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-core
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Server
| `org.glassfish.tyrus:tyrus-server:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-server
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Tyrus Container SPI
| `org.glassfish.tyrus:tyrus-spi:2.2.2` +
https://projects.eclipse.org/projects/ee4j.tyrus/tyrus-spi
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| WaSP
| `org.glassfish.wasp:wasp:4.0.0` +
https://projects.eclipse.org/projects/ee4j.wasp
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Woodstock WebUI Jakarta Faces
| `org.glassfish.woodstock:woodstock-webui-jsf:6.0.3.payara-p1` +
https://projects.eclipse.org/projects/ee4j/woodstock-parent/woodstock-webui-jsf
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Woodstock WebUI Jakarta Faces Suntheme
| `org.glassfish.woodstock:woodstock-webui-jsf-suntheme:6.0.3.payara-p1` +
https://projects.eclipse.org/projects/ee4j/woodstock-parent/woodstock-webui-jsf-suntheme
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Dojo JS Repackaged
| `org.glassfish.woodstock.external:dojo:6.0.3` +
https://projects.eclipse.org/projects/ee4j/woodstock-parent/woodstock-external/dojo
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Prototype JS Repackaged
| `org.glassfish.woodstock.external:prototype:6.0.3` +
https://projects.eclipse.org/projects/ee4j/woodstock-parent/woodstock-external/prototype
| <<epl2,Eclipse Public License, Version 2.0>> + 
<<gpl2cpe,GNU General Public License, Version 2 with Classpath Exception>>

| Hamcrest
| `org.hamcrest:hamcrest:3.0` +
http://hamcrest.org/JavaHamcrest/
| <<bsd3,BSD 3-Clause License>>

| Hamcrest Core
| `org.hamcrest:hamcrest-core:1.3` +
https://github.com/hamcrest/JavaHamcrest/hamcrest-core
| <<bsd3,BSD 3-Clause License>>

| Hibernate Validator Engine
| `org.hibernate.validator:hibernate-validator:9.0.1.Final.payara-p1` +
https://hibernate.org/validator
| <<apache2,Apache License, Version 2.0>>

| Hibernate Validator Portable Extension
| `org.hibernate.validator:hibernate-validator-cdi:9.0.1.Final.payara-p1` +
https://hibernate.org/validator
| <<apache2,Apache License, Version 2.0>>

| Smack
| `org.igniterealtime.smack:smack-core:4.4.8` +
http://www.igniterealtime.org/projects/smack/
| <<apache2,Apache License, Version 2.0>>

| Smack
| `org.igniterealtime.smack:smack-xmlparser:4.4.8` +
http://www.igniterealtime.org/projects/smack/
| <<apache2,Apache License, Version 2.0>>

| Javassist
| `org.javassist:javassist:3.31.0-GA` +
https://www.javassist.org/
| <<apache2,Apache License, Version 2.0>> + 
<<lgpl21,GNU Lesser General Public License, Version 2.1>> + 
<<TODO_mpl11,TODO: Mozilla Public License 1.1 — requires legal review>>

| classfilewriter
| `org.jboss.classfilewriter:jboss-classfilewriter:1.3.1.Final` +
https://github.com/jbossas/jboss-classfilewriter
| <<apache2,Apache License, Version 2.0>>

| jdeparser
| `org.jboss.jdeparser:jdeparser:2.0.3.Final` +
http://www.jboss.org/jdeparser
| <<publicdomain,Public Domain>>

| JBoss Logging 3
| `org.jboss.logging:jboss-logging:3.6.1.Final` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| JBoss Logging 3
| `org.jboss.logging:jboss-logging:3.6.3.Final` +
https://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| JBoss Logging I18n Annotations
| `org.jboss.logging:jboss-logging-annotations:3.0.4.Final` +
https://jboss.org
| <<apache2,Apache License, Version 2.0>>

| JBoss Logging I18n Annotation Processor
| `org.jboss.logging:jboss-logging-processor:3.0.4.Final` +
https://jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap API
| `org.jboss.shrinkwrap:shrinkwrap-api:1.2.6` +
http://www.jboss.org/shrinkwrap-api
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Implementation Base
| `org.jboss.shrinkwrap:shrinkwrap-impl-base:1.2.6` +
http://www.jboss.org/shrinkwrap-impl-base
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap SPI
| `org.jboss.shrinkwrap:shrinkwrap-spi:1.2.6` +
http://www.jboss.org/shrinkwrap-spi
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver API
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven API
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven Archive API
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-api-maven-archive:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven Implementation
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven Archive Implementation
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-impl-maven-archive:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver SPI
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven SPI
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| ShrinkWrap Resolver Maven Archive SPI
| `org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-spi-maven-archive:3.3.5` +
http://www.jboss.org
| <<apache2,Apache License, Version 2.0>>

| Weld APIs
| `org.jboss.weld:weld-api:6.0.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld Implementation (Core)
| `org.jboss.weld:weld-core-impl:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| CDI Lite Extension Translator
| `org.jboss.weld:weld-lite-extension-translator:6.0.4.Final` +
http://weld.cdi-spec.org/weld-core-parent/weld-lite-extension-translator
| <<apache2,Apache License, Version 2.0>>

| Weld OSGi Bundle
| `org.jboss.weld:weld-osgi-bundle:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld SPIs for container integration
| `org.jboss.weld:weld-spi:6.0.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld Environment Common
| `org.jboss.weld.environment:weld-environment-common:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld EJB
| `org.jboss.weld.module:weld-ejb:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld JSF
| `org.jboss.weld.module:weld-jsf:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld JTA
| `org.jboss.weld.module:weld-jta:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld Web
| `org.jboss.weld.module:weld-web:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| Weld SE (Uber Jar)
| `org.jboss.weld.se:weld-se-shaded:6.0.4.Final` +
http://weld.cdi-spec.org
| <<apache2,Apache License, Version 2.0>>

| jcommander
| `org.jcommander:jcommander:1.83` +
https://jcommander.org
| <<apache2,Apache License, Version 2.0>>

| Ganymed SSH2 for Java
| `org.jenkins-ci:trilead-ssh2:build-217-jenkins-16` +
http://svn.svnkit.com/repos/3rdparty/com.trilead.ssh2/tags/1.0.0-build217/trilead-ssh2/
| <<TODO_bsd_style,TODO: BSD Style License — requires legal review>>

| IntelliJ IDEA Annotations
| `org.jetbrains:annotations:13.0` +
http://www.jetbrains.org
| <<apache2,Apache License, Version 2.0>>

| JetBrains Java Annotations
| `org.jetbrains:annotations:17.0.0` +
https://github.com/JetBrains/java-annotations
| <<apache2,Apache License, Version 2.0>>

| Kotlin Stdlib
| `org.jetbrains.kotlin:kotlin-stdlib:1.8.21` +
https://kotlinlang.org/
| <<apache2,Apache License, Version 2.0>>

| Kotlin Stdlib
| `org.jetbrains.kotlin:kotlin-stdlib:2.3.20` +
https://kotlinlang.org/
| <<apache2,Apache License, Version 2.0>>

| Kotlin Stdlib Common
| `org.jetbrains.kotlin:kotlin-stdlib-common:1.9.10` +
https://kotlinlang.org/
| <<apache2,Apache License, Version 2.0>>

| Kotlin Stdlib Jdk7
| `org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.21` +
https://kotlinlang.org/
| <<apache2,Apache License, Version 2.0>>

| Kotlin Stdlib Jdk8
| `org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.21` +
https://kotlinlang.org/
| <<apache2,Apache License, Version 2.0>>

| JLine Bundle
| `org.jline:jline:3.30.11` +
https://github.com/jline/jline3/jline
| <<bsd3,BSD 3-Clause License>>

| JLine Native Library
| `org.jline:jline-native:3.30.11` +
https://github.com/jline/jline3/jline-native
| <<bsd3,BSD 3-Clause License>>

| JLine Terminal
| `org.jline:jline-terminal:3.30.11` +
https://github.com/jline/jline3/jline-terminal
| <<bsd3,BSD 3-Clause License>>

| JLine JNA Terminal
| `org.jline:jline-terminal-jna:3.30.11` +
https://github.com/jline/jline3/jline-terminal-jna
| <<bsd3,BSD 3-Clause License>>

| JMockit
| `org.jmockit:jmockit:1.40` +
http://jmockit.github.io
| <<mit,MIT License>>

| JSpecify annotations
| `org.jspecify:jspecify:1.0.0` +
http://jspecify.org/
| <<apache2,Apache License, Version 2.0>>

| JUnit Jupiter API
| `org.junit.jupiter:junit-jupiter-api:5.14.3` +
https://junit.org/
| <<epl2,Eclipse Public License, Version 2.0>>

| JUnit Jupiter Engine
| `org.junit.jupiter:junit-jupiter-engine:5.14.3` +
https://junit.org/
| <<epl2,Eclipse Public License, Version 2.0>>

| JUnit Platform Commons
| `org.junit.platform:junit-platform-commons:1.14.3` +
https://junit.org/
| <<epl2,Eclipse Public License, Version 2.0>>

| JUnit Platform Engine API
| `org.junit.platform:junit-platform-engine:1.14.3` +
https://junit.org/
| <<epl2,Eclipse Public License, Version 2.0>>

| tiger-types
| `org.jvnet:tiger-types:1.4.payara-p1`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| MIME streaming extension
| `org.jvnet.mimepull:mimepull:1.10.0` +
https://github.com/eclipse-ee4j/metro-mimepull
| <<edl1,Eclipse Distribution License, Version 1.0>>

| JXMPP
| `org.jxmpp:jxmpp-core:1.0.3` +
http://www.igniterealtime.org/projects/jxmpp/
| <<apache2,Apache License, Version 2.0>>

| JXMPP
| `org.jxmpp:jxmpp-jid:1.0.3` +
http://www.igniterealtime.org/projects/jxmpp/
| <<apache2,Apache License, Version 2.0>>

| JXMPP
| `org.jxmpp:jxmpp-util-cache:1.0.3` +
http://www.igniterealtime.org/projects/jxmpp/
| <<apache2,Apache License, Version 2.0>>

| Java binding for libpam.so
| `org.kohsuke:libpam4j:1.11` +
http://kohsuke.org/libpam4j/
| <<mit,MIT License>>

| META-INF/services generator
| `org.kohsuke.metainf-services:metainf-services:1.11` +
http://metainf-services.kohsuke.org/
| <<mit,MIT License>>

| minidns
| `org.minidns:minidns-core:1.0.5` +
https://github.com/minidns/minidns
| <<apache2,Apache License, Version 2.0>>

| mockito-core
| `org.mockito:mockito-core:5.23.0` +
https://github.com/mockito/mockito
| <<mit,MIT License>>

| Objenesis
| `org.objenesis:objenesis:3.3` +
http://objenesis.org/objenesis
| <<apache2,Apache License, Version 2.0>>

| Objenesis
| `org.objenesis:objenesis:3.4` +
https://objenesis.org/objenesis
| <<apache2,Apache License, Version 2.0>>

| org.opentest4j:opentest4j
| `org.opentest4j:opentest4j:1.3.0` +
https://github.com/ota4j-team/opentest4j
| <<apache2,Apache License, Version 2.0>>

| org.osgi.compendium
| `org.osgi:org.osgi.compendium:4.0.0`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| org.osgi.core
| `org.osgi:org.osgi.core:4.1.0`
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| org.osgi:org.osgi.namespace.extender
| `org.osgi:org.osgi.namespace.extender:1.0.1` +
http://www.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:org.osgi.service.component
| `org.osgi:org.osgi.service.component:1.5.1` +
https://docs.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:org.osgi.util.function
| `org.osgi:org.osgi.util.function:1.2.0` +
https://docs.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:org.osgi.util.promise
| `org.osgi:org.osgi.util.promise:1.3.0` +
https://docs.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:osgi.annotation
| `org.osgi:osgi.annotation:8.1.0` +
https://docs.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:osgi.cmpn
| `org.osgi:osgi.cmpn:7.0.0` +
https://www.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:osgi.core
| `org.osgi:osgi.core:8.0.0` +
https://www.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| org.osgi:osgi.enterprise
| `org.osgi:osgi.enterprise:7.0.0` +
https://www.osgi.org/
| <<apache2,Apache License, Version 2.0>>

| asm
| `org.ow2.asm:asm:9.9.1` +
http://asm.ow2.io/
| <<bsd3,BSD 3-Clause License>>

| asm-analysis
| `org.ow2.asm:asm-analysis:9.9.1` +
http://asm.ow2.io/
| <<bsd3,BSD 3-Clause License>>

| asm-commons
| `org.ow2.asm:asm-commons:9.9.1` +
http://asm.ow2.io/
| <<bsd3,BSD 3-Clause License>>

| asm-tree
| `org.ow2.asm:asm-tree:9.9.1` +
http://asm.ow2.io/
| <<bsd3,BSD 3-Clause License>>

| asm-util
| `org.ow2.asm:asm-util:9.9.1` +
http://asm.ow2.io/
| <<bsd3,BSD 3-Clause License>>

| reactive-streams
| `org.reactivestreams:reactive-streams:1.0.4` +
http://www.reactive-streams.org/
| <<mit0,MIT No Attribution (MIT-0)>>

| Duct Tape
| `org.rnorth.duct-tape:duct-tape:1.0.8` +
https://github.com/rnorth/duct-tape
| <<mit,MIT License>>

| JCL 1.2 implemented over SLF4J
| `org.slf4j:jcl-over-slf4j:1.7.36` +
http://www.slf4j.org
| <<apache2,Apache License, Version 2.0>>

| SLF4J API Module
| `org.slf4j:slf4j-api:1.7.36` +
http://www.slf4j.org
| <<mit,MIT License>>

| SLF4J API Module
| `org.slf4j:slf4j-api:2.0.16` +
http://www.slf4j.org
| <<mit,MIT License>>

| SLF4J API Module
| `org.slf4j:slf4j-api:2.0.17` +
http://www.slf4j.org
| <<mit,MIT License>>

| SLF4J Reload4j Provider
| `org.slf4j:slf4j-reload4j:2.0.9` +
http://reload4j.qos.ch
| <<mit,MIT License>>

| SNMP4J
| `org.snmp4j:snmp4j:3.8.2` +
https://snmp4j.org
| <<apache2,Apache License, Version 2.0>>

| Testcontainers :: JUnit Jupiter Extension
| `org.testcontainers:junit-jupiter:1.21.4` +
https://java.testcontainers.org
| <<mit,MIT License>>

| Testcontainers Core
| `org.testcontainers:testcontainers:2.0.5` +
https://java.testcontainers.org
| <<mit,MIT License>>

| testng
| `org.testng:testng:7.12.0` +
https://testng.org
| <<apache2,Apache License, Version 2.0>>

| VirtualBox Client API 4.2.8
| `org.virtualbox:vboxjws:4.2.8` +
https://www.virtualbox.org
| <<lgpl21,GNU Lesser General Public License, Version 2.1>>

| jquery
| `org.webjars:jquery:3.7.1` +
http://webjars.org
| <<mit,MIT License>>

| SnakeYAML
| `org.yaml:snakeyaml:2.6` +
https://bitbucket.org/snakeyaml/snakeyaml
| <<apache2,Apache License, Version 2.0>>

| StAX
| `stax:stax:1.2.0` +
http://stax.codehaus.org/
| <<TODO_unknown,TODO: Unknown License — requires legal review>>

| StAX API
| `stax:stax-api:1.0.1` +
http://stax.codehaus.org/
| <<apache2,Apache License, Version 2.0>>

|===

== License Texts

[#bsd2]
=== BSD 2-Clause License

----
BSD 2-Clause License

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----

[#publicdomain]
=== Public Domain

----
Public Domain

This software has been released into the public domain by its author(s).
Anyone is free to copy, modify, publish, use, compile, sell, or distribute
this software, either in source code form or as a compiled binary, for any
purpose, commercial or non-commercial, and by any means.
----

[#apache2]
=== Apache License, Version 2.0

----
                                 Apache License
                           Version 2.0, January 2004
                        http://www.apache.org/licenses/

   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION

   1. Definitions.

      "License" shall mean the terms and conditions for use, reproduction,
      and distribution as defined by Sections 1 through 9 of this document.

      "Licensor" shall mean the copyright owner or entity authorized by
      the copyright owner that is granting the License.

      "Legal Entity" shall mean the union of the acting entity and all
      other entities that control, are controlled by, or are under common
      control with that entity. For the purposes of this definition,
      "control" means (i) the power, direct or indirect, to cause the
      direction or management of such entity, whether by contract or
      otherwise, or (ii) ownership of fifty percent (50%) or more of the
      outstanding shares, or (iii) beneficial ownership of such entity.

      "You" (or "Your") shall mean an individual or Legal Entity
      exercising permissions granted by this License.

      "Source" form shall mean the preferred form for making modifications,
      including but not limited to software source code, documentation
      source, and configuration files.

      "Object" form shall mean any form resulting from mechanical
      transformation or translation of a Source form, including but
      not limited to compiled object code, generated documentation,
      and conversions to other media types.

      "Work" shall mean the work of authorship made available under
      the License, as indicated by a copyright notice that is included in
      or attached to the work.

      "Derivative Works" shall mean any work, whether in Source or Object
      form, that is based on (or derived from) the Work and for which the
      editorial revisions, annotations, elaborations, or other modifications
      represent, as a whole, an original work of authorship.

      "Contribution" shall mean, as submitted to the Licensor for inclusion
      in the Work by the copyright owner or by an individual or Legal Entity
      authorized to submit on behalf of the copyright owner.

      "Contributor" shall mean Licensor and any Legal Entity on behalf of
      whom a Contribution has been received by the Licensor and subsequently
      incorporated within the Work.

   2. Grant of Copyright License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      copyright license to reproduce, prepare Derivative Works of,
      publicly display, publicly perform, sublicense, and distribute the
      Work and such Derivative Works in Source or Object form.

   3. Grant of Patent License. Subject to the terms and conditions of
      this License, each Contributor hereby grants to You a perpetual,
      worldwide, non-exclusive, no-charge, royalty-free, irrevocable
      (except as stated in this section) patent license to make, have made,
      use, offer to sell, sell, import, and otherwise transfer the Work,
      where such license applies only to those patent claims licensable
      by such Contributor that are necessarily infringed by their
      Contribution(s) alone or by combination of their Contribution(s)
      with the Work to which such Contribution(s) was submitted.

   4. Redistribution. You may reproduce and distribute copies of the Work
      or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form, provided that You
      meet the following conditions:

      (a) You must give any other recipients of the Work or Derivative
          Works a copy of this License; and

      (b) You must cause any modified files to carry prominent notices
          stating that You changed the files; and

      (c) You must retain, in the Source form of any Derivative Works
          that You distribute, all copyright, patent, trademark, and
          attribution notices from the Source form of the Work; and

      (d) If the Work includes a "NOTICE" text file as part of its
          distribution, You must include a readable copy of the attribution
          notices contained within such NOTICE file in at least one of
          the following places: within a NOTICE text provided with the
          Derivative Works; within the Source form or documentation; or,
          within a display generated by the Derivative Works.

   5. Submission of Contributions. Unless You explicitly state otherwise,
      any Contribution intentionally submitted for inclusion in the Work
      by You to the Licensor shall be under the terms and conditions of
      this License, without any additional terms or conditions.

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work.

   7. Disclaimer of Warranty. Unless required by applicable law or agreed
      to in writing, Licensor provides the Work on an "AS IS" BASIS,
      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
      implied, including, without limitation, any warranties or conditions
      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A
      PARTICULAR PURPOSE.

   8. Limitation of Liability. In no event and under no legal theory,
      whether in tort (including negligence), contract, or otherwise,
      unless required by applicable law, shall any Contributor be liable
      to You for damages, including any direct, indirect, special,
      incidental, or exemplary damages of any character arising as a
      result of this License or out of the use or inability to use the Work.

   9. Accepting Warranty or Additional Liability. While redistributing
      the Work or Derivative Works thereof, You may choose to offer,
      and charge a fee for, acceptance of support, warranty, indemnity,
      or other liability obligations and/or rights consistent with this
      License.

   END OF TERMS AND CONDITIONS
----

[#cc0]
=== CC0 1.0 Universal

----
CC0 1.0 Universal

CREATIVE COMMONS CORPORATION IS NOT A LAW FIRM AND DOES NOT PROVIDE LEGAL
SERVICES. DISTRIBUTION OF THIS DOCUMENT DOES NOT CREATE AN ATTORNEY-CLIENT
RELATIONSHIP. CREATIVE COMMONS PROVIDES THIS INFORMATION ON AN "AS-IS" BASIS.
CREATIVE COMMONS MAKES NO WARRANTIES REGARDING THE USE OF THIS DOCUMENT OR
THE INFORMATION OR WORKS PROVIDED HEREUNDER, AND DISCLAIMS LIABILITY FOR
DAMAGES RESULTING FROM THE USE OF THIS DOCUMENT OR THE INFORMATION OR WORKS
PROVIDED HEREUNDER.

Statement of Purpose

The laws of most jurisdictions throughout the world automatically confer
exclusive Copyright and Related Rights upon the creator and subsequent owner(s)
of an original work of authorship and/or a database. The person associating
CC0 with a Work (the "Affirmer"), to the extent that he or she is an owner of
Copyright and Related Rights in the Work, voluntarily elects to apply CC0 to
the Work and publicly distribute the Work under its terms, with knowledge of
his or her Copyright and Related Rights in the Work and the meaning and
intended legal effect of CC0 on those rights.

1. Copyright and Related Rights. A Work made available under CC0 may be
protected by copyright and related or neighboring rights ("Copyright and
Related Rights"). Copyright and Related Rights include, but are not limited to:
reproduction and distribution; making available to the public; derivative works;
and performance/broadcasting rights.

2. Waiver. To the greatest extent permitted by, but not in contravention of,
applicable law, Affirmer hereby overtly, fully, permanently, irrevocably and
unconditionally waives, abandons, and surrenders all of Affirmer's Copyright
and Related Rights and associated claims and causes of action.

3. Public License Fallback. Should any part of the Waiver for any reason be
judged legally invalid or ineffective, then the Waiver shall be preserved to
the maximum extent permitted taking into account Affirmer's express Statement
of Purpose.

4. Limitations and Disclaimers. No trademark or patent rights held by Affirmer
are waived, abandoned, surrendered, licensed or otherwise affected by this
document. CC0 imposes no conditions or limitations on use of the Work other
than those imposed by applicable law.
----

[#TODO_unknown]
=== TODO: Unknown License — requires legal review

[WARNING]
====
License text for *TODO: Unknown License — requires legal review* requires legal review and must be added before publication.
====

[#edl1]
=== Eclipse Distribution License, Version 1.0

----
Eclipse Distribution License - v 1.0

Copyright (c) 2007, Eclipse Foundation, Inc. and its licensors.

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

  Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

  Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

  Neither the name of the Eclipse Foundation, Inc. nor the names of its
  contributors may be used to endorse or promote products derived from this
  software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGE.
----

[#TODO_cddl_gpl]
=== TODO: CDDL + GPL Combination — requires legal review

[WARNING]
====
License text for *TODO: CDDL + GPL Combination — requires legal review* requires legal review and must be added before publication.
====

[#cddl1]
=== Common Development and Distribution License (CDDL), Version 1.0

----
COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL) Version 1.0

1. Definitions.

1.1. "Contributor" means each individual or entity that creates or contributes
     to the creation of Modifications.

1.2. "Contributor Version" means the combination of the Original Software,
     prior Modifications used by a Contributor (if any), and the Modifications
     made by that particular Contributor.

1.3. "Covered Software" means (a) the Original Software, or (b) Modifications,
     or (c) the combination of files containing Original Software with files
     containing Modifications, in each case including portions thereof.

1.4. "Executable" means the Covered Software in any form other than Source Code.

1.5. "Initial Developer" means the individual or entity that first makes
     Original Software available under this License.

2. License Grants.

2.1. The Initial Developer Grant. Conditioned upon Your compliance with
     Section 3.1 below and subject to third party intellectual property claims,
     the Initial Developer hereby grants You a world-wide, royalty-free,
     non-exclusive license to use, reproduce, modify, display, perform,
     sublicense and distribute the Original Software (or portions thereof),
     with or without Modifications, and/or as part of a Larger Work.

3. Distribution Obligations.

3.1. Availability of Source Code. Any Covered Software that You distribute or
     otherwise make available in Executable form must also be made available in
     Source Code form.

4. Versions of the License.

4.1. New Versions. Sun Microsystems, Inc. is the initial license steward and
     may publish revised and/or new versions of this License from time to time.

5. DISCLAIMER OF WARRANTY.

COVERED SOFTWARE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT
WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT
LIMITATION, WARRANTIES THAT THE COVERED SOFTWARE IS FREE OF DEFECTS,
MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE OR NON-INFRINGING.

6. TERMINATION.

6.1. This License and the rights granted hereunder will terminate automatically
     if You fail to comply with terms herein and fail to cure such breach within
     30 days of becoming aware of the breach.
----

[#epl2]
=== Eclipse Public License, Version 2.0

----
Eclipse Public License - v 2.0

    THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE
    PUBLIC LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION
    OF THE PROGRAM CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT.

1. DEFINITIONS

"Contribution" means:
  a) in the case of the initial Contributor, the initial content
     Distributed under this Agreement, and
  b) in the case of each subsequent Contributor:
     i)  changes to the Program, and
     ii) additions to the Program;
  where such changes and/or additions to the Program originate from
  and are Distributed by that particular Contributor.

"Modified Works" means any work in Source Code or other form that results
from an addition to, deletion from, or modification of the contents of
the Program.

"Distribute" means the acts of a) distributing or b) making available in
any manner that enables the transfer of a copy.

"Source Code" means the form of a Program preferred for making
modifications, including but not limited to software source code,
documentation source, and configuration files.

2. GRANT OF RIGHTS

  a) Subject to the terms of this Agreement, each Contributor hereby
     grants Recipient a non-exclusive, worldwide, royalty-free copyright
     license to reproduce, prepare Derivative Works of, publicly display,
     publicly perform, Distribute and sublicense the Contribution of such
     Contributor, if any, and such Derivative Works.

  b) Subject to the terms of this Agreement, each Contributor hereby
     grants Recipient a non-exclusive, worldwide, royalty-free patent
     license under Licensed Patents to make, use, sell, offer to sell,
     import and otherwise transfer the Contribution of such Contributor,
     if any, in Source Code or other form.

  c) Recipient understands that although each Contributor grants the
     licenses to its Contributions set forth herein, no assurances are
     provided by any Contributor that the Program does not infringe the
     patent or other intellectual property rights of any other entity.

3. REQUIREMENTS

3.1 If a Contributor Distributes the Program in any form, then:
  a) the Program must also be made available as Source Code, and
  b) a Contributor may Distribute the Program under a license different
     from this Agreement, provided that such license is compatible with
     the terms of this Agreement.

3.2 When the Program is Distributed as Source Code:
  a) it must be made available under this Agreement, and
  b) a copy of this Agreement must be included with each copy of the Program.

3.3 Contributors may not remove or alter any copyright, patent, trademark,
    attribution notices, disclaimers of warranty, or limitations of
    liability ("notices") contained within the Program from any copy of
    the Program which they Distribute.

4. COMMERCIAL DISTRIBUTION

Commercial distributors of software may accept certain responsibilities
with respect to end users, business partners and the like. While this
license is intended to facilitate the commercial use of the Program, the
Contributor who includes the Program in a commercial product offering
should do so in a manner which does not create potential liability for
other Contributors.

5. NO WARRANTY

EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, AND TO THE EXTENT
PERMITTED BY APPLICABLE LAW, THE PROGRAM IS PROVIDED ON AN "AS IS"
BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR
IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF
TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR
PURPOSE.

6. DISCLAIMER OF LIABILITY

EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, AND TO THE EXTENT
PERMITTED BY APPLICABLE LAW, NEITHER RECIPIENT NOR ANY CONTRIBUTORS
SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION LOST
PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.
----

[#gpl2cpe]
=== GNU General Public License, Version 2 with Classpath Exception

----
GNU General Public License, Version 2 with the Classpath Exception

Copyright (C) 1989, 1991 Free Software Foundation, Inc.
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

                            Preamble

The GNU General Public License is a free, copyleft license for software and
other kinds of works.

  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION

  0. This License applies to any program or other work which contains a notice
placed by the copyright holder saying it may be distributed under the terms of
this General Public License.

  1. You may copy and distribute verbatim copies of the Program's source code
as you receive it, in any medium, provided that you conspicuously and
appropriately publish on each copy an appropriate copyright notice and
disclaimer of warranty.

  2. You may modify your copy or copies of the Program or any portion of it,
thus forming a work based on the Program, and copy and distribute such
modifications or work under the terms of Section 1 above.

  3. You may copy and distribute the Program (or a work based on it, under
Section 2) in object code or executable form under the terms of Sections 1
and 2 above provided that you also accompany it with the complete
corresponding machine-readable source code.

  CLASSPATH EXCEPTION

Linking this library statically or dynamically with other modules is making a
combined work based on this library. Thus, the terms and conditions of the GNU
General Public License cover the whole combination.

As a special exception, the copyright holders of this library give you
permission to link this library with independent modules to produce an
executable, regardless of the license terms of these independent modules, and
to copy and distribute the resulting executable under terms of your choice,
provided that you also meet, for each linked independent module, the terms and
conditions of the license of that module.

  NO WARRANTY

  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.

  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING
WILL ANY COPYRIGHT HOLDER BE LIABLE TO YOU FOR DAMAGES.
----

[#epl1]
=== Eclipse Public License, Version 1.0

----
Eclipse Public License - v 1.0

THE ACCOMPANYING PROGRAM IS PROVIDED UNDER THE TERMS OF THIS ECLIPSE PUBLIC
LICENSE ("AGREEMENT"). ANY USE, REPRODUCTION OR DISTRIBUTION OF THE PROGRAM
CONSTITUTES RECIPIENT'S ACCEPTANCE OF THIS AGREEMENT.

1. DEFINITIONS

"Contribution" means:
a) in the case of the initial Contributor, the initial code and documentation
   distributed under this Agreement, and
b) in the case of each subsequent Contributor:
   i) changes to the Program, and
   ii) additions to the Program;
where such changes and/or additions to the Program originate from and are
distributed by that particular Contributor.

2. GRANT OF RIGHTS

a) Subject to the terms of this Agreement, each Contributor hereby grants
   Recipient a non-exclusive, worldwide, royalty-free copyright license to
   reproduce, prepare derivative works of, publicly display, publicly perform,
   distribute and sublicense the Contribution of such Contributor, if any,
   and such derivative works, in source code and object code form.

b) Subject to the terms of this Agreement, each Contributor hereby grants
   Recipient a non-exclusive, worldwide, royalty-free patent license to make,
   use, sell, offer to sell, import and otherwise transfer the Contribution of
   such Contributor, if any, in source code and object code form.

3. REQUIREMENTS

A Contributor may choose to distribute the Program in object code form under
its own license agreement, provided that the license agreement substantially
complies with the terms of this Agreement and includes language that limits
the Contributor's liability consistent with Section 5 of this Agreement.

4. COMMERCIAL DISTRIBUTION

Commercial distributors of software may accept certain responsibilities with
respect to end users, business partners and the like. While this license is
intended to facilitate the commercial use of the Program, the Contributor who
includes the Program in a commercial product offering should do so in a manner
which does not create potential liability for other Contributors.

5. NO WARRANTY

EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, THE PROGRAM IS PROVIDED ON
AN "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS
OR IMPLIED INCLUDING, WITHOUT LIMITATION, ANY WARRANTIES OR CONDITIONS OF
TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.

6. DISCLAIMER OF LIABILITY

EXCEPT AS EXPRESSLY SET FORTH IN THIS AGREEMENT, NEITHER RECIPIENT NOR ANY
CONTRIBUTORS SHALL HAVE ANY LIABILITY FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING WITHOUT LIMITATION
LOST PROFITS), HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OR DISTRIBUTION OF THE PROGRAM OR THE
EXERCISE OF ANY RIGHTS GRANTED HEREUNDER, EVEN IF ADVISED OF THE POSSIBILITY
OF SUCH DAMAGES.
----

[#lgpl21]
=== GNU Lesser General Public License, Version 2.1

----
GNU Lesser General Public License, Version 2.1

Copyright (C) 1991, 1999 Free Software Foundation, Inc.
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

                     GNU LESSER GENERAL PUBLIC LICENSE
                       Version 2.1, February 1999

  0. This License Agreement applies to any software library or other program
which contains a notice placed by the copyright holder or other authorized
party saying it may be distributed under the terms of this Lesser General
Public License (also called "this License").

  1. You may copy and distribute verbatim copies of the Library's complete
source code as you receive it, in any medium, provided that you conspicuously
and appropriately publish on each copy an appropriate copyright notice and
disclaimer of warranty.

  2. You may modify your copy or copies of the Library or any portion of it,
thus forming a work based on the Library, and copy and distribute such
modifications or work under the terms of Section 1 above.

  NO WARRANTY

  15. BECAUSE THE LIBRARY IS LICENSED FREE OF CHARGE, THERE IS NO WARRANTY
FOR THE LIBRARY, TO THE EXTENT PERMITTED BY APPLICABLE LAW.
----

[#TODO_bouncy]
=== TODO: Bouncy Castle Licence — requires legal review

[WARNING]
====
License text for *TODO: Bouncy Castle Licence — requires legal review* requires legal review and must be added before publication.
====

[#mit]
=== MIT License

----
MIT License

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
----

[#isc]
=== ISC License

----
ISC License

Copyright (c) <year> <copyright holder>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
PERFORMANCE OF THIS SOFTWARE.
----

[#bsd3]
=== BSD 3-Clause License

----
BSD 3-Clause License

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors
   may be used to endorse or promote products derived from this software
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
----

[#TODO_w3c]
=== TODO: W3C License — requires legal review

[WARNING]
====
License text for *TODO: W3C License — requires legal review* requires legal review and must be added before publication.
====

[#TODO_jquery]
=== TODO: jQuery License — requires legal review

[WARNING]
====
License text for *TODO: jQuery License — requires legal review* requires legal review and must be added before publication.
====

[#TODO_mpl11]
=== TODO: Mozilla Public License 1.1 — requires legal review

[WARNING]
====
License text for *TODO: Mozilla Public License 1.1 — requires legal review* requires legal review and must be added before publication.
====

[#TODO_bsd_style]
=== TODO: BSD Style License — requires legal review

[WARNING]
====
License text for *TODO: BSD Style License — requires legal review* requires legal review and must be added before publication.
====

[#mit0]
=== MIT No Attribution (MIT-0)

----
MIT No Attribution (MIT-0)

Copyright <year> <copyright holder>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so.
----
