[[administering-payara-server-nodes]]
= Administering Payara Server Nodes

A node represents a host on which the Payara Server software is installed. A node must exist for every host on which Payara Server instances reside.
A node's configuration contains information about the host such as the name of the host and the location where the Payara Server is installed on the host.

The following topics are addressed here:

* xref:types-of-payara-server-nodes[Types of Payara Server Nodes]
* xref:creating-listing-and-deleting-config-nodes[Creating, Listing, Testing, and Deleting SSH Nodes]
* xref:creating-listing-testing-and-deleting-ssh-nodes[Creating, Listing, and Deleting CONFIG Nodes]
* xref:updating-and-changing-the-type-of-a-node[Updating and Changing the Type of a Node]

[[types-of-payara-server-nodes]]
== Types of payara Server Nodes

Each Payara Server node is one of the following types of node:

`SSH`::
  An `SSH` node supports communication over secure shell (SSH). If SSH
  is set up and you plan to administer your Payara Server instances
  centrally, the instances must reside on `SSH` nodes. +
  An `SSH` node's configuration contains the information that is
  required to connect to the host through SSH. This information
  includes, for example, the user name of the SSH user and the port
  number for SSH connections to the host.
`CONFIG`::
  A `CONFIG` node does not support remote communication. If SSH is set up and you plan to administer your instances locally,
  the instances can reside on `CONFIG` nodes. You cannot use `CONFIG`
  nodes for instances that you plan to administer centrally. +
  Each domain contains a predefined `CONFIG` node that is named
  `localhost-`domain, where domain is the name of the domain. On the
  host where the domain administration server (DAS) is running, this
  node represents the local host.

[[creating-listing-testing-and-deleting-ssh-nodes]]
== Creating, Listing, Testing, and Deleting `SSH` Nodes

An `SSH` node supports communication over SSH. If SSH is set up and you plan to administer your Payara Server instances centrally, the
instances must reside on `SSH` nodes. For information about setting up SSH, see xref:ssh-setup.adoc#enabling-centralized-administration-of-payara-server-instances[Enabling Centralized Administration of Payara Server Instances].

Payara Server enables you to create `SSH` nodes for use by instances, obtain information about `SSH` nodes, test if `SSH` nodes are reachable, and delete `SSH` nodes that are no longer required.

The following topics are addressed here:

* xref:to-create-an-ssh-node[To Create an SSH Node]
* xref:to-list-ssh-nodes-in-a-domain[To List SSH Nodes in a Domain]
* xref:to-test-if-an-ssh-node-is-reachable[To Test if an SSH Node is Reachable]
* xref:to-delete-an-ssh-node[To Delete an SSH Node]

[[to-create-an-ssh-node]]
=== To Create an `SSH` Node

Use the `create-node-ssh` subcommand in remote mode to create an `SSH` node.

*Before You Begin*

Ensure that the SSH user can use SSH to log in to the host that the node will represent. By default, the `create-node-ssh` subcommand validates the node's parameters and the SSH connection to the host.
If the SSH user cannot use SSH to log in to the host, the validation fails.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the `create-node-ssh` subcommand.
+
NOTE: Only the options that are required to complete this task are provided in this step. For information about all the options for configuring the node, see the xref:docs:reference-manual:create-node-ssh.adoc[`create-node-ssh`] help page. +
If you are using password authentication for the SSH user, you must specify a password file through the `--passwordfile` option of the
xref:docs:reference-manual:asadmin.adoc[`asadmin`] utility. For more information about SSH user authentication, see link:ssh-setup.adoc#setting-up-ssh-user-authentication[Setting Up SSH User Authentication].

[source,shell]
----
asadmin> create-node-ssh --nodehost node-host [--installdir install-dir ]
node-name
----
node-host::
  The name of the host that the node represents. The name of the host must be specified. Otherwise, an error occurs.
install-dir::
  The full path to the parent of the base installation directory of the Payara Server software on the host, for example,
  `/export/payara/`. If the Payara Server software is installed in the same directory on the node's host and the DAS host, you can omit this option.
node-name::
  Your choice of name for the node that you are creating.

[[example-3-6]]
*_Example 3-6 Creating an `SSH` Node_*

This example creates the `SSH` node `sj01` to represent the host `sj01.example.com`. The Payara Server software is installed in the same directory on the DAS host and on the host `sj01.example.com`.

[source,shell]
----
asadmin> create-node-ssh --nodehost sj01.example.com sj01
Command create-node-ssh executed successfully.
----

*Troubleshooting*

The `create-node-ssh` subcommand might fail to create the node and report the error `Illegal sftp packet len`. If this error occurs, ensure
that no the startup file on the remote host displays text for noninteractive shells. Examples of startup files are `.bashrc`, `.cshrc`, `.login`, and `.profile`.

The SSH session interprets any text message that is displayed during login as a file-transfer protocol packet. Therefore, any statement in a
startup file that displays text messages corrupts the SSH session, causing this error.

*See also*

xref:docs:reference-manual:create-node-ssh.adoc[`create-node-ssh`]

You can also view the full syntax and options of the subcommand by typing `asadmin help create-node-ssh` at the command line.

*Next Steps*

After creating a node, you can create instances on the node as explained in the following sections:

* xref:instances.adoc#to-create-an-instance-centrally[To Create an Instance Centrally]
* xref:instances.adoc#to-create-an-instance-locally[To Create an Instance Locally]

[[to-list-ssh-nodes-in-a-domain]]
=== To List `SSH` Nodes in a Domain

Use the `list-nodes-ssh` subcommand in remote mode to obtain information about existing `SSH` nodes in a domain.

NOTE: To obtain information about all existing nodes in a domain, use the xref:docs:reference-manual:list-nodes.adoc[`list-nodes`] subcommand.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the xref:docs:reference-manual:list-nodes-ssh.adoc[`list-nodes-ssh`] subcommand.
+
[source,shell]
----
asadmin> list-nodes-ssh
----

[[example-3-7]]
*_Example 3-7 Listing Basic Information About All `SSH` Nodes in a Domain_*

This example lists the name, type, and host of all `SSH` nodes in the current domain.

[source,shell]
----
asadmin> list-nodes-ssh
sj01  SSH  sj01.example.com
sj02  SSH  sj02.example.com
Command list-nodes-ssh executed successfully.
----

[[example-3-8]]
*_Example 3-8 Listing Detailed Information About All `SSH` Nodes in a Domain_*

This example lists detailed information about all `SSH` nodes in the current domain.

[source,shell]
----
asadmin> list-nodes-ssh --long=true
NODE NAME   TYPE   NODE HOST          INSTALL DIRECTORY    REFERENCED BY
sj01        SSH    sj01.example.com   /export/payara   pmd-i1
sj02        SSH    sj02.example.com   /export/payara   pmd-i2
Command list-nodes-ssh executed successfully.
----

*See also*

* xref:docs:reference-manual:list-nodes.adoc[`list-nodes`]
* xref:docs:reference-manual:list-nodes-ssh.adoc[`list-nodes-ssh`]

You can also view the full syntax and options of the subcommands by typing the following commands at the command line:

* `asadmin help list-nodes`
* `asadmin help list-nodes-ssh`

[[to-test-if-an-ssh-node-is-reachable]]
=== To Test if an `SSH` Node is Reachable

Use the `ping-node-ssh` subcommand in remote mode to test if an `SSH` node is reachable.

*Before You Begin*

Ensure that SSH is configured on the host where the DAS is running and on the host that the node represents.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the `ping-node-ssh` subcommand.
+
NOTE: Only the options that are required to complete this task are provided in
this step. For information about all the options for testing the node, see the xref:docs:reference-manual:ping-node-ssh.adoc[`ping-node-ssh`] help page.

[source,shell]
----
asadmin> ping-node-ssh node-name
----
node-name::
  The name of the node to test.

[[example-3-9]]
*_Example 3-9 Testing if an `SSH` Node Is Reachable_*

This example tests if the `SSH` node `sj01` is reachable.

[source,shell]
----
asadmin> ping-node-ssh sj01
Successfully made SSH connection to node sj01 (sj01.example.com)
Command ping-node-ssh executed successfully.
----

*See also*

xref:docs:reference-manual:ping-node-ssh.adoc[`ping-node-ssh`]

You can also view the full syntax and options of the subcommand by typing `asadmin help ping-node-ssh` at the command line.

[[to-delete-an-ssh-node]]
=== To Delete an `SSH` Node

Use the `delete-node-ssh` subcommand in remote mode to delete an `SSH` node.

Deleting a node removes the node from the configuration of the DAS. The node's directories and files are deleted when the last Payara Server instance that resides on the node is deleted.

*Before You Begin*

Ensure that no Payara Server instances reside on the node that you are deleting. For information about how to delete an instance, see the following sections.

* xref:instances.adoc#to-delete-an-instance-centrally[To Delete an Instance Centrally]
* xref:instances.adoc#to-delete-an-instance-locally[To Delete an Instance Locally]

. Ensure that the DAS is running. Remote subcommands require a running server.
. Confirm that no instances reside on the node that you are deleting.
+
[source,shell]
----
asadmin> list-nodes-ssh --long=true
----
. Run the xref:reference-manual:delete-node-ssh.adoc[`delete-node-ssh`] subcommand.
+
[source,shell]
----
asadmin> delete-node-ssh node-name
----
node-name::
  The name of the node that you are deleting.

[[example-3-10]]
*_Example 3-10 Deleting an `SSH` Node_*

This example confirms that no instances reside on the `SSH` node `sj01` and deletes the node `sj01`.

[source,shell]
----
asadmin> list-nodes-ssh --long=true
NODE NAME   TYPE   NODE HOST          INSTALL DIRECTORY    REFERENCED BY
sj01        SSH    sj01.example.com   /export/payara
sj02        SSH    sj02.example.com   /export/payara   pmd-i2
Command list-nodes-ssh executed successfully.
asadmin> delete-node-ssh sj01
Command delete-node-ssh executed successfully.
----

*See also*

* xref:instances.adoc#to-delete-an-instance-centrally[To Delete an Instance Centrally]
* xref:instances.adoc#to-delete-an-instance-locally[To Delete an Instance Locally]
* xref:docs:reference-manual:delete-node-ssh.adoc[`delete-node-ssh`]
* xref:docs:reference-manual:list-nodes-ssh.adoc[`list-nodes-ssh`]

You can also view the full syntax and options of the subcommands by typing the following commands at the command line:

* `asadmin help delete-node-ssh`
* `asadmin help list-nodes-ssh`

[[creating-listing-and-deleting-config-nodes]]
== Creating, Listing, and Deleting `CONFIG` Nodes

A `CONFIG` node does not support remote communication. If SSH is set up and you plan to administer your instances locally, the
instances can reside on `CONFIG` nodes. You cannot use `CONFIG` nodes for instances that you plan to administer centrally.

Payara Server enables you to create `CONFIG` nodes for use by instances, obtain information about `CONFIG` nodes, and delete `CONFIG`
nodes that are no longer required.

The following topics are addressed here:

* xref:to-create-a-config-node[To Create a CONFIG Node]
* xref:to-list-config-nodes-in-a-domain[To List CONFIG Nodes in a Domain]
* xref:to-delete-a-config-node[To Delete a CONFIG Node]

[[to-create-a-config-node]]
=== To Create a `CONFIG` Node

Use the `create-node-config` command in remote mode to create a `CONFIG` node.

NOTE: If you create an instance locally on a host for which no nodes are defined, you can create the instance without creating a node beforehand.
In this situation, Payara Server creates a `CONFIG` node for you. The name of the node is the unqualified name of the host.
For more information, see xref:instances.adoc#to-create-an-instance-locally[To Create an Instance Locally].

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the `create-node-config` subcommand.

NOTE: Only the options that are required to complete this task are provided in this step. For information about all the options for configuring the node, see the xref:docs:reference-manual:create-node-config.adoc[`create-node-config`] help page.

[source,shell]
----
asadmin> create-node-config [--nodehost node-host] [--installdir install-dir ]
node-name
----
node-host::
  The name of the host that the node represents. You may omit this option. The name of the host can be determined when instances that reside on the node are created.
install-dir::
  The full path to the parent of the base installation directory of the Payara Server software on the host, for example, `/export/payara/`. You may omit this option.
  The installation directory can be determined when instances that reside on the node are created.
node-name::
  Your choice of name for the node that you are creating.

[[example-3-11]]
*_Example 3-11 Creating a `CONFIG` Node_*

This example creates the `CONFIG` node `cfg01`. The host that the node represents and the installation directory of the Payara Server
software on the host are to be determined when instances are added to the node.

[source,shell]
----
asadmin> create-node-config cfg01
Command create-node-config executed successfully.
----

*See also*

xref:docs:reference-manual:create-node-config.adoc[`create-node-config`]

You can also view the full syntax and options of the subcommand by typing `asadmin help create-node-config` at the command line.

*Next Steps*

After creating a node, you can create instances on the node as explained in xref:instances.adoc#to-create-an-instance-locally[To Create an Instance Locally].

[[to-list-config-nodes-in-a-domain]]
=== To List `CONFIG` Nodes in a Domain

Use the `list-nodes-config` subcommand in remote mode to obtain information about existing `CONFIG` nodes in a domain.

NOTE: To obtain information about all existing nodes in a domain, use the xref:docs:reference-manual:list-nodes.adoc[`list-nodes`] subcommand.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the xref:docs:reference-manual:list-nodes-config.adoc[`list-nodes-config`] subcommand.
+
[source,shell]
----
asadmin> list-nodes-config
----

[[example-3-12]]
*_Example 3-12 Listing Basic Information About All `CONFIG` Nodes in a Domain_*

This example lists the name, type, and host of all `CONFIG` nodes in the current domain.

[source,shell]
----
asadmin> list-nodes-config
localhost-domain1  CONFIG  localhost
cfg01  CONFIG  cfg01.example.com
cfg02  CONFIG  cfg02.example.com
Command list-nodes-config executed successfully.
----

[[example-3-13]]
*_Example 3-13 Listing Detailed Information About All `CONFIG` Nodes in a Domain_*

This example lists detailed information about all `CONFIG` nodes in the current domain.

[source,shell]
----
asadmin> list-nodes-config --long=true
NODE NAME           TYPE     NODE HOST            INSTALL DIRECTORY    REFERENCED BY
localhost-domain1   CONFIG   localhost            /export/payara
cfg01               CONFIG   cfg01.example.com    /export/payara   yml-i1
cfg02               CONFIG   cfg02.example.com    /export/payara   yml-i2
Command list-nodes-config executed successfully.
----

*See also*

* xref:docs:reference-manual:list-nodes.adoc[`list-nodes`]
* xref:docs:reference-manual:list-nodes-config.adoc[`list-nodes-config`]

You can also view the full syntax and options of the subcommands by typing the following commands at the command line:

* `asadmin help list-nodes`
* `asadmin help list-nodes-config`

[[to-delete-a-config-node]]
=== To Delete a `CONFIG` Node

Use the `delete-node-config` subcommand in remote mode to delete a `CONFIG` node.

Deleting a node removes the node from the configuration of the DAS. The node's directories and files are deleted when the last Payara Server instance that resides on the node is deleted.

*Before You Begin*

Ensure that no Payara Server instances reside on the node that you are deleting. For information about how to delete an instance that resides on a `CONFIG` node, see xref:instances.adoc#to-delete-an-instance-locally[To Delete an Instance Locally].

. Ensure that the DAS is running. Remote subcommands require a running server.
. Confirm that no instances reside on the node that you are deleting.
+
[source,shell]
----
asadmin> list-nodes-config --long=true
----
. Run the xref:reference-manual:delete-node-config.adoc[`delete-node-config`] subcommand.
+
[source,shell]
----
asadmin> delete-node-config node-name
----
node-name::
  The name of the node that you are deleting.

[[example-3-14]]
*_Example 3-14 Deleting a `CONFIG` Node_*

This example confirms that no instances reside on the `CONFIG` node `cfg01` and deletes the node `cfg01`.

[source,shell]
----
asadmin> list-nodes-config --long=true
NODE NAME           TYPE     NODE HOST           INSTALL DIRECTORY    REFERENCED BY
localhost-domain1   CONFIG   localhost           /export/payara
cfg01               CONFIG   cfg01.example.com   /export/payara
cfg02               CONFIG   cfg02.example.com   /export/payara   yml-i2
Command list-nodes-config executed successfully.
asadmin> delete-node-config cfg01
Command delete-node-config executed successfully.
----

*See also*

* xref:instances.adoc#to-delete-an-instance-locally[To Delete an Instance Locally]
* xref:docs:reference-manual:delete-node-config.adoc[`delete-node-config`]
* xref:docs:reference-manual:list-nodes-config.adoc[`list-nodes-config`]

You can also view the full syntax and options of the subcommands by typing the following commands at the command line:

* `asadmin help delete-node-config`
* `asadmin help list-nodes-config`

[[updating-and-changing-the-type-of-a-node]]
== Updating and Changing the Type of a Node

Payara Server enables you to update the configuration data of any node and to change the type of a node.

The following topics are addressed here:

* xref:to-update-an-ssh-node[To Update an SSH Node]
* xref:to-update-a-config-node[To Update a CONFIG Node]
* xref:to-change-the-type-of-a-node[To Change the Type of a Node]

[[to-update-an-ssh-node]]
=== To Update an `SSH` Node

Use the `update-node-ssh` subcommand in remote mode to update an `SSH` node.

Options of this subcommand specify the new values of the node's configuration data. If you omit an option, the existing value is unchanged.

*Before You Begin*

Ensure that the following prerequisites are met:

* SSH is configured on the host where the DAS is running and on the host that the node represents.
* The node that you are updating exists.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the `update-node-ssh` subcommand.
+
[source,shell]
----
asadmin> update-node-ssh options node-name
----
options::
  Options of the `update-node-ssh` subcommand for changing the node's configuration data. For information about these options, see the
xref:docs:reference-manual:update-node-ssh.adoc[`update-node-ssh`] help page.
node-name::
  The name of the `SSH` node to update.

[[example-3-16]]
*_Example 3-16 Updating an `SSH` Node_*

This example updates the host that the node `sj01` represents to `adc01.example.com`.

[source,shell]
----
asadmin> update-node-ssh --nodehost adc01.example.com sj01
Command update-node-ssh executed successfully.
----

*See also*

xref:docs:reference-manual:update-node-ssh.adoc[`update-node-ssh`]

You can also view the full syntax and options of the subcommand by typing `asadmin help update-node-ssh` at the command line.

[[to-update-a-config-node]]
=== To Update a `CONFIG` Node

Use the `update-node-config` subcommand in remote mode to update a `CONFIG` node.

Options of this subcommand specify the new values of the node's configuration data. If you omit an option, the existing value is unchanged.

*Before You Begin*

Ensure that the node that you are updating exists.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the `update-node-config` subcommand.
+
[source,shell]
----
asadmin> uupdate-node-config options node-name
----
options::
  Options of the `update-node-config` subcommand for changing the node's configuration data. For information about these options, see the
xref:docs:reference-manual:update-node-config.adoc[`update-node-config`] help page.
node-name::
  The name of the `CONFIG` node to update.

[[example-3-17]]
*_Example 3-17 Updating a `CONFIG` Node_*

This example updates the host that the node `cfg02` represents to `adc02.example.com`.

[source,shell]
----
asadmin> update-node-config --nodehost adc02.example.com cfg02
Command update-node-config executed successfully.
----

*See also*

xref:docs:reference-manual:update-node-config.adoc[`update-node-config`]

You can also view the full syntax and options of the subcommand by typing `asadmin help update-node-config` at the command line.

[[to-change-the-type-of-a-node]]
=== To Change the Type of a Node

The subcommands for updating a node can also be used to change the type of a node.

Changing the type of a `CONFIG` node enables remote communication for the node. The type of the node after the change determines the protocol over which the node is enabled for remote communication:

* An `SSH` node is enabled for communication over SSH.

As part of the process of changing the type of a node, you can also change other configuration data for the node.

Options of the subcommands for updating a node specify the new values of the node's configuration data. For most options, if you omit the option,
the existing value is unchanged. However, default values are applied in the following situations:

* Any of the following options of the `update-node-ssh` subcommand is omitted:

** `--sshport`

** `--sshuser`

** `--sshkeyfile`

CAUTION: Changing an `SSH` node to a `CONFIG` node disables remote communication for the node.

*Before You Begin*

Ensure that the following prerequisites are met:

* SSH is configured on the host where the DAS is running and on the host that the node represents.
* The node the type of which you are changing exists.

. Ensure that the DAS is running. Remote subcommands require a running server.
. Run the appropriate subcommand for updating a node, depending on the type of the node after the change.

config-or-ssh-node-name::
  The name of the `CONFIG` node or the `SSH` node to change.
* To change the type of a node to `SSH`, run the `update-node-ssh` subcommand on the node.
+
options::
  Options of the `update-node-ssh` subcommand for changing the node's configuration data. For information about these options, see the xref:docs:reference-manual:update-node-ssh001.adoc[`update-node-ssh`] help page.

* To change the type of a node to `CONFIG`, run the `update-node-config` subcommand on the node.
+
[source,shell]
----
asadmin> update-node-config [options] ssh-node-name
----
options::
  Options of the `update-node-config` subcommand for changing the node's configuration data. For information about these options, see the
xref:docs:reference-manual:update-node-config.adoc[`update-node-config`] help page.
ssh-node-name::
  The name of the `SSH` node to change.

[[example-3-18]]
*_Example 3-18 Changing a `CONFIG` Node to an `SSH` Node_*

This example changes the `CONFIG` node `cfg02` to an `SSH` node.

[source,shell]
----
asadmin> update-node-ssh cfg02
Command update-node-ssh executed successfully.
----

*See also*

* xref:docs:reference-manual:update-node-config.adoc[`update-node-config`]
* xref:docs:reference-manual:update-node-ssh001.adoc[`update-node-ssh`]

You can also view the full syntax and options of the subcommand by
typing the following commands at the command line.

* `asadmin help update-node-config`
* `asadmin help update-node-ssh`
