[[preface]]
= Preface

[NOTE]
====

This documentation is part of the Java Enterprise Edition contribution  to the Eclipse Foundation and is not intended for use in relation to Java Enterprise Edition or Payara. The documentation is in the process of being revised to reflect the new Jakarta EE branding. Additional changes will be made as requirements and procedures evolve for Jakarta EE. Where applicable, references to Java EE or Java  Enterprise Edition should be considered references to Jakarta EE.

Please see the Title page for additional license information.
====

This document explains how to run applications in embedded Payara Server and to develop applications in which Payara Server is embedded. This document is for software developers who are developing applications to run in embedded Payara Server. The ability to program in the Java language is assumed.


[NOTE]
====

The main thrust of the Payara Server 4.0 release is to provide an application server for developers to explore and begin exploiting the new and updated technologies in the Java EE 7 platform. Thus, the embedded server feature of Payara Server was not a focus of this release. This feature is included in the release, but it may not function properly with some of the new features added in support of the Java EE 7 platform.
====


This preface contains information about and conventions for the entire Payara Server documentation set.

Payara Server is developed through the GlassFish project open-source community at `http://glassfish.java.net/`. The GlassFish project provides a structured process for developing the GlassFish Server platform that makes the new features of the Java EE platform available faster, while maintaining the most important feature of Java EE: compatibility. It enables Java developers to access the GlassFish Server source code and to contribute to the development of the GlassFish Server. The GlassFish project is designed to encourage communication between Oracle engineers and the community.

[[glassfish-server-documentation-set]]
== Payara Server Documentation Set

The Payara Server documentation set describes deployment planning and system installation. For an introduction to Payara Server, refer to the books in the order in which they are listed in the following table.

[width="100%",cols="<30%,<70%",options="header",]
|===
|Book Title |Description
|xref:reference-manual:title.adoc[Release Notes]
|Provides late-breaking information about the software and the documentation and includes a comprehensive, table-based summary of the supported hardware, operating system, Java Development Kit (JDK), and database drivers.

|link:../quick-start-guide/toc.html#GSQSG[Quick Start Guide]
|Explains how to get started with the Payara Server product.


|xref:docs:application-deployment-guide:overview.adoc[Deployment Planning Guide]
|Explains how to build a production deployment of Payara Server that meets the requirements of your system and enterprise.

|xref:docs:administration-guide:overview.adoc[Administration Guide]
|Explains how to configure, monitor, and manage Payara Server subsystems and components from the command line by using the xref:docs:reference-manual:asadmin.adoc#asadmin[`asadmin`] utility. Instructions for performing these tasks from the Administration Console are provided in the Administration Console online help.

|xref:security-guide:title.adoc[Security Guide]
|Provides instructions for configuring and administering Payara Server security.

|xref:docs:application-deployment-guide:deploying-applications.adoc[Application Deployment Guide]
|Explains how to assemble and deploy applications to the Payara Server and provides information about deployment descriptors.

|xref:docs:application-development-guide:title.adoc[Application Development Guide]
|Explains how to create and implement Java Platform, Enterprise Edition (Java EE platform) applications that are intended to run on the Payara Server. These applications follow the open Java standards model for Java EE components and application programmer interfaces (APIs). This guide provides information about developer tools, security, and debugging.

|xref:docs:embedded-server-guide:embedded-server-guide.adoc[Embedded Server Guide]
|Explains how to run applications in embedded Payara Server and to develop applications in which Payara Server is embedded.

|xref:docs:ha-administration-guide:overview.adoc[High Availability Administration Guide] |Explains how to configure Payara Server to provide higher availability and scalability  through fail-over and load balancing.

|xref:docs:performance-tuning-guide:title.adoc[Performance Tuning Guide]
|Explains how to optimize the performance of Payara Server.

xref:docs:reference-manual:title.adoc[Reference Manual]
|Provides reference information in man page format for Payara Server administration commands, utility commands, and related concepts.
|===

[[related-documentation]]
== Related Documentation


The following tutorials explain how to develop Java EE applications:

* http://docs.oracle.com/javaee/7/firstcup/doc/home.html[Your First Cup: An Introduction to the Java EE Platform] (`http://docs.oracle.com/javaee/7/firstcup/doc/home.html`). For beginning Java EE programmers, this short tutorial explains the entire process for developing a simple enterprise application. The sample application is a web application that consists of a component that is based on the Enterprise JavaBeans specification, a JAX-RS web service, and a JavaServer Faces component for the web front end.
* http://docs.oracle.com/javaee/7/tutorial/doc/home.html[The Java EE 7 Tutorial] (`http://docs.oracle.com/javaee/7/tutorial/doc/home.html`). This comprehensive tutorial explains how to use Java EE 7 platform technologies and APIs to develop Java EE applications.

Javadoc tool reference documentation for packages that are provided with Payara Server is available as follows.

* The API specification for version 7 of Java EE is located at `http://docs.oracle.com/javaee/7/api/`.
* The API specification for Payara Server, including Java EE 7 platform packages and non-platform packages that are specific to the Payara Server product, is located at `http://glassfish.java.net/nonav/docs/v3/api/`.

Additionally, the http://www.oracle.com/technetwork/java/javaee/tech/index.html[Java EE Specifications] (`http://www.oracle.com/technetwork/java/javaee/tech/index.html`) might be useful.

For information about creating enterprise applications in the NetBeans Integrated Development Environment (IDE), see the http://www.netbeans.org/kb/[NetBeans Documentation, Training & Support page] (`http://www.netbeans.org/kb/`).

For information about the Java DB database for use with the Payara Server, see the http://www.oracle.com/technetwork/java/javadb/overview/index.html[Java DB product page] (`http://www.oracle.com/technetwork/java/javadb/overview/index.html`).

The Java EE Samples project is a collection of sample applications that demonstrate a broad range of Java EE technologies. The Java EE Samples are bundled with the Java EE Software Development Kit (SDK) and are also available from the http://glassfish-samples.java.net/[Java EE Samples project page] (`http://glassfish-samples.java.net/`).


[[typographic-conventions]]
== Typographic Conventions

The following table describes the typographic changes that are used in this book.

[width="100%",cols="<14%,<37%,<49%",options="header",]
|===
|Typeface |Meaning |Example
|`AaBbCc123`
|The names of commands, files, and directories, and onscreen computer output
a|
Edit your `.login` file.

Use `ls` `a` to list all files.

`machine_name% you have mail.`

|`AaBbCc123`
|What you type, contrasted with onscreen computer output
a|
`machine_name%` `su`

`Password:`

|AaBbCc123
|A placeholder to be replaced with a real name or value
|The command to remove a file is `rm` filename.

|AaBbCc123
|Book titles, new terms, and terms to be emphasized (note that some emphasized items appear bold online)
a|
Read Chapter 6 in the User's Guide.

A cache is a copy that is stored locally.

Do not save the file.
|===

[[symbol-conventions]]
== Symbol Conventions

The following table explains symbols that might be used in this book.

[width="100%",cols="<10%,<26%,<28%,<36%",options="header",]
|===
|Symbol |Description |Example |Meaning
|`[ ]`
|Contains optional arguments and command options.
|`ls [-l]`
|The `-l` option is not required.

|`{ \| }`
|Contains a set of choices for a required command option.
|`-d {y\|n}`
|The `-d` option requires that you use either the `y` argument or the `n` argument.

|`${ }`
|Indicates a variable reference.
|`${com.sun.javaRoot}`
|References the value of the `com.sun.javaRoot` variable.

|-
|Joins simultaneous multiple keystrokes.
|Control-A
|Press the Control key while you press the A key.

|+ +
|Joins consecutive multiple keystrokes.
|Ctrl+A+N
|Press the Control key, release it, and then press the subsequent keys.

|>
|Indicates menu item selection in a graphical user interface.
|File > New > Templates
|From the File menu, choose New. From the New submenu, choose Templates.

|===

[[default-paths-and-file-names]]
== Default Paths and File Names

The following table describes the default paths and file names that are used in this book.

[width="100%",cols="<14%,<34%,<52%",options="header",]
|===
|Placeholder
|Description
|Default Value
|as-install +
a|
Represents the base installation directory for GlassFish Server.

In configuration files, as-install is represented as follows:

`${com.sun.aas.installRoot}`

a|
Installations on the Oracle Solaris operating system, Linux operating
system, and macOS operating system:

user's-home-directory`/glassfish3/glassfish`

Installations on the Windows operating system:

SystemDrive`:\glassfish3\glassfish`

|as-install-parent +
|Represents the parent of the base installation directory for GlassFish Server.
a|
Installations on the Oracle Solaris operating system, Linux operating
system, and Mac operating system:

user's-home-directory`/glassfish3`

Installations on the Windows operating system:

SystemDrive`:\glassfish3`

|domain-root-dir +
|Represents the directory in which a domain is created by default.
|as-install`/domains/`

|domain-dir +
a|
Represents the directory in which a domain's configuration is stored.

In configuration files, domain-dir is represented as follows:

`${com.sun.aas.instanceRoot}`

|domain-root-dir`/`domain-name

|instance-dir +
|Represents the directory for a server instance.
|domain-dir`/`instance-name
|===
