[[preface]]
= Preface

This documentation describes the high-availability features in Payara Server, including converged load balancing, HTTP load balancing, clusters, session persistence and failover.

[NOTE]
====
The main thrust of the Payara Server release is to provide an application server for developers to explore and begin exploiting the new and updated technologies in the Jakarta EE platform. Thus, the clustering, standalone instance and high availability features of Payara Server were not a focus of this release. These features are included in the release, but they may not function properly with some of the new features added in support of the Jakarta EE platform.
====

This preface contains information about and conventions for the entire Payara Server documentation set.

Payara Server is developed through the Payara Foundation at `https://www.payara.org/`. The Payara Foundation provides a structured process for developing the Payara Server platform that makes the new features of the Jakarta EE platform available faster, while maintaining the most important feature of Jakarta EE: compatibility. It enables Jakarta developers to access the Payara Server source code and to contribute to the development of the Payara Server. The Payara Foundation is designed to encourage communication between Payara engineers and the community.

[[default-paths-and-file-names]]
== Default Paths and File Names

The following table describes the default paths and file names that are used in this book.

[width="100%",cols="<14%,<34%,<52%",options="header",]
|===
|Placeholder
|Description
|Default Value
|as-install +
a|
Represents the base installation directory for Payara Server.

In configuration files, as-install is represented as follows:

`${com.sun.aas.installRoot}`

a|
Installations on the Oracle Solaris operating system, Linux operating
system, and macOS operating system:

user's-home-directory`/payara6/glassfish`

Installations on the Windows operating system:

SystemDrive`:\payara6\glassfish`

|as-install-parent +
|Represents the parent of the base installation directory for Payara Server.
a|
Installations on the Oracle Solaris operating system, Linux operating
system, and Mac operating system:

user's-home-directory`/payara6`

Installations on the Windows operating system:

SystemDrive`:\payara6`

|domain-root-dir +
|Represents the directory in which a domain is created by default.
|as-install`/domains/`

|domain-dir +
a|
Represents the directory in which a domain's configuration is stored.

In configuration files, domain-dir is represented as follows:

`${com.sun.aas.instanceRoot}`

|domain-root-dir`/`domain-name

|instance-dir +
|Represents the directory for a server instance.
|domain-dir`/`instance-name
|===