= Server Extensions

Payara Server Community Edition allows plugin extensions to expand the features of the server's runtime. This is a way of keeping the Community Edition more compact, and allowing these extensions to be developed and released quickly without being forced into the Community release cycle. This also makes it much easier to extend the server functionality and provide additional features.

Currently, the following extensions are provided:

xref:Technical Documentation/Payara Server Documentation/Extensions/Notifiers/Overview.adoc[Notifier Extensions]::
The notifier extensions allow notifications from the Notification Service to propagate to various channels on top of the notifiers provided by default.

xref:/Technical Documentation/Payara Server Documentation/Extensions/AutoScale Groups/Overview.adoc[AutoScale Extensions]::
The AutoScale extensions provide the means for users to scale Payara Server instances up and down across different environments.

[[see-also]]
== See Also

* xref:Technical Documentation/Payara Server Documentation/Logging and Monitoring/Notification Service/Overview.adoc[Notification Service Overview]