= Payara Deployment Transformer

The Deployment Transformer extension integrates the Eclipse Jakarta EE namespace transformer into Payara Server, allowing a user to have their Jakarta EE 8 applications transformed on the fly into the Jakarta EE 10 namespace.

You can find the code for the transformer here: https://github.com/payara/transformer.

== Installing the Extension

To install the transformer extension: download the implementation artifact and drop it into the `${PAYARA_HOME}/glassfish/modules` directory of your Payara Server installation. Alternatively, you can build the `deployment-transformer/deployment-transformer-impl` module straight from the GitHub repository and drop all JARs from the `target/` directory of the extension into the same installation directory.

You can then restart the server instances to see your extension activated.

TIP: The 'deployment-transformer-api' artifact is already included within Payara Server and so you only need to provide its implementation

== Activating the Transformer Extension

The transformer, once installed, is activated in one of two ways:

* Setting the `fish.payara.deployment.transform.namespace` system property on a server config or instance to `true`
* Having `fish.payara.deployment.transform.namespace` unconfigured, and deploying an application which doesn't contain any `jakarta.*` classes.

== IDE Integration

Using Payara plugins/extensions, you can transform whole projects or single files from Java EE 8 to Jakarta EE 10. They are available for the following IDEs:

* xref:Technical Documentation/Ecosystem/IDE Integration/Eclipse Plugin/Transform to Jakarta-EE10.adoc[Eclipse]
* xref:Technical Documentation/Ecosystem/IDE Integration/IntelliJ Plugin/Transform to Jakarta-EE10.adoc[IntelliJ]
* xref:Technical Documentation/Ecosystem/IDE Integration/Apache NetBeans IDE/Transform to Jakarta-EE10.adoc[NetBeans]
* xref:Technical Documentation/Ecosystem/IDE Integration/VSCode Extension/Transform to Jakarta-EE10.adoc[VSCode]
