[[administering-the-javamail-service]]
= Administering the JavaMail Service

Payara Server includes the JavaMail API along with JavaMail service providers that allow an application component to send email notifications over
the Internet and to read email from IMAP and POP3 mail servers.

Instructions for accomplishing the tasks in this chapter by using the Administration Console are contained in the Administration Console online help.

[[about-javamail]]
== About JavaMail

The JavaMail API is a set of abstract APIs that model a mail system. The JavaMail API provides a platform-independent and protocol-independent framework to
build mail and messaging applications and provide facilities for reading and sending electronic messages. Service providers implement particular protocols.
Using the API you can add email capabilities to your applications. JavaMail provides access from Java applications to Internet Message Access Protocol (IMAP) and
Simple Mail Transfer Protocol (SMTP) capable mail servers on your network or the Internet. The API does not provide mail server functionality;
you must have access to a mail server to use JavaMail.

The JavaMail API is implemented as an optional package in the Jakarta platform and is also available as part of the Jakarta EE platform.

To learn more about the JavaMail API, consult the https://jakarta.ee/specifications/mail/2.0/jakarta-mail-spec-2.0.html[Jakarta Mail web site] .

[[administering-javamail-resources]]
== Administering JavaMail Resources

When you create a mail session, the server-side components and applications are enabled to access JavaMail services with JNDI, using the session
properties you assign for them. When creating a mail session, you can designate the mail hosts, the transport and store protocols, and
the default mail user so that components that use JavaMail do not have to set these properties. Applications that are heavy email users benefit because
Payara Server creates a single session object and makes the session available to any component that needs it.

.JavaMail settings such as the following can be specified:
[header, cols="2,8"]
|===
| JavaMail settings  | Description

| JNDI Name
| The unique name for the mail session. Use the naming sub-context prefix mail/ for JavaMail resources. For example: `mail/MySession`

| Mail Host
| The host name of the default mail server. The connect methods of the store and transport objects use this value if a protocol-specific host property is not supplied.
The name must be resolvable to an actual host name.

| Default User
| The default user name to provide when connecting to a mail server. The connect methods of the store and transport objects use this value if a protocol-specific username property is not supplied.

| Default Return Address
| The email address of the default user, in the form: username@host.domain.

| Description
| A descriptive statement for the component.

| Session
| Indicates whether or not mail session is enabled or disabled at this time

|===

[[to-create-a-javamail-resource]]
=== To Create a JavaMail Resource

Use the `create-javamail-resource` subcommand in remote mode to create a JavaMail session resource. The JNDI name for a JavaMail session
resource customarily includes the mail/ naming subcontext, For example: `mail/MyMailSession.`

. Ensure that the server is running. Remote subcommands require a running server.
. Create a JavaMail resource by using the xref:docs:reference-manual:create-javamail-resource.adoc[`create-javamail-resource`] subcommand.
Information about the properties for the subcommand is included in this help page.
. To apply your changes, restart Payara Server. See xref:docs:administration-guide:domains.adoc#to-restart-a-domain[To Restart a Domain].

.Example 16-1 Creating a JavaMail Resource
[source,shell]
----
asadmin> create-javamail-resource --mailhost localhost
--mailuser sample --fromaddress sample\@sun\.com mail/MyMailSession
Command create-javamail-resource executed successfully.
----
This example creates a JavaMail resource named `mail/MyMailSession`. The escape character (\) is used in the `--fromaddress` option to distinguish the dot (.) and at sign (@).

[[to-list-javamail-resources]]
=== To List JavaMail Resources

Use the `list-javamail-resources` subcommand in remote mode to list the existing JavaMail session resources.

. Ensure that the server is running. Remote subcommands require a running server.
. List the JavaMail resources by using the xref:docs:reference-manual:list-javamail-resources.adoc[`list-javamail-resources`] subcommand.

.Example 16-2 Listing JavaMail Resources
[source,shell]
----
asadmin> list-javamail-resources
mail/MyMailSession
Command list-javamail-resources executed successfuly.
----
This example lists the JavaMail resources on `localhost`.

[[to-update-a-javamail-resource]]
=== To Update a JavaMail Resource

. List the JavaMail resources by using the xref:docs:reference-manual:list-javamail-resources.adoc[`list-javamail-resources`] subcommand.
. Modify the values for the specified JavaMail source by using the xref:docs:reference-manual:set.adoc[`set`] subcommand. The resource is identified by its dotted name.

.Example 16-3 Updating a JavaMail Resource
[source,shell]
----
asadmin> set server.resources.mail-resource.mail/
MyMailSession.user=joeserver.resources.mail-resource.mail/
MyMailSession.user=joe
Command set executed successfully.
----
This example changes `joeserver` to `joe`.

[[to-delete-a-javamail-resource]]
=== To Delete a JavaMail Resource

Use the `delete-javamail-resource` subcommands in remote mode to delete a JavaMail session resource.

References to the specified resource must be removed before running the `delete-javamail-resource` subcommands.

. Ensure that the server is running. Remote subcommands require a running server.
. List the JavaMail resources by using the xref:docs:reference-manual:list-javamail-resources.adoc[`list-javamail-resources`] subcommands.
. Delete a JavaMail resource by using thexref:docs:reference-manual:delete-javamail-resource.adoc[`delete-javamail-resource`] subcommands.
. To apply your changes, restart Payara Server. xref:docs:administration-guide:domains.adoc#to-restart-a-domain[To Restart a Domain].

.Example 16-4 Deleting a JavaMail Resource
[source,shell]
----
asadmin> delete-javamail-resource mail/MyMailSession
Command delete-javamail-resource executed successfully.
----

This example deletes the JavaMail session resource named `mail/MyMailSession`.


