[[release-highlights]]
Release Highlights
------------------

The 163 release of Payara will feature a couple of new tech previews. These are new features added to Payara which we do not recommend are used on production systems. Request Tracing is a new service that will allow Payara to track and log information about the requests it handles. Payara now offers a JMX Monitoring Service. Once configured, Payara Server will monitor and log the values of attributes that have been listed for monitoring.

[[updated-modules]]
Updated Modules
---------------

* ibm.jbatch.container.version 1.0.1.payara-p2
* Hazelcast 3.6.4
* Grizzly 2.3.25
* mimepull 1.9.6
* javax.batch-api.version 1.0.1
* jbatch.container.version 1.0.1
* jbatch.spi.version 1.0.1
* Weld 2.3.5.Final
* Tyrus 1.13

[[new-features]]
New Features
------------

This section details the newly developed additions to Payara Server.

* https://github.com/payara/Payara/pull/754/commits/dee00e0a78dbf5a3a00c5f91a800ab63a7b0b98d[PAYARA-168 - Integrate HealthCheck notifications with the Notification Service]
* https://github.com/payara/Payara/pull/754/commits/dee00e0a78dbf5a3a00c5f91a800ab63a7b0b98d[PAYARA-612 - Create a general notification service]
* https://github.com/payara/Payara/pull/856[856/PAYARA-186 - Hazelcast Based EJB Persistent Timer Store for Payara Micro]
* https://github.com/payara/Payara/pull/857[857/PAYARA-592 - Monitoring for Concurrent Resources]
* https://github.com/payara/Payara/pull/939[939/PAYARA_174 - Initial Tech Preview implementation of Request Tracing]
* https://github.com/payara/Payara/pull/975[975/PAYARA-811 - Monitor agent to write JMX metrics to file periodically]
* https://github.com/payara/Payara/pull/977[977/PAYARA-180 - CDI Interceptor api that can be used to wrap any CDI call to be traced by Request Tracing] 

[[enhancements]]
Enhancements
------------

This section details the issues marked as enhancements that have been implemented for this release.

* https://github.com/payara/Payara/pull/754/commits/3185e7f0ce644233b7abbc8c6bace0e4fd7315ab[PAYARA-177 - Trace EJB Method Calls]
* https://github.com/payara/Payara/pull/754/commits/5d7b28a94b8390cbb933adeda5eaeb474586619e[PAYARA-183 - asadmin commands to configure and control request tracing]
* https://github.com/payara/Payara/pull/754/commits/dee00e0a78dbf5a3a00c5f91a800ab63a7b0b98d[PAYARA-697 - Create Notification Service Log Notifier]
* https://github.com/payara/Payara/commit/3185e7f0ce644233b7abbc8c6bace0e4fd7315ab[PAYARA-757 - Request tracing of outbound WebService calls]
* https://github.com/payara/Payara/pull/754/commits/291ec6c74bc36acf5c37cde0310099098b42cd00[PAYARA-758 - Request tracing of outbound REST calls]
* https://github.com/payara/Payara/pull/754[754/PAYARA-755 - Request tracing support for WebSockets]
* https://github.com/payara/Payara/pull/787[787/PAYARA-729 - Send Payara access logs to stdout/stderr]
* https://github.com/payara/Payara/pull/820[820/PAYARA-740 - Add a --version option to Payara Micro]
* https://github.com/payara/Payara/pull/836[836/PAYARA-746 - Add validation to prevent you entering a negative value for fish.payara.jts.RecoveryResynchTimeout property]
* https://github.com/payara/Payara/pull/851[851/PAYARA-754 - Add extra output location validation for the Asadmin Recorder service]
* https://github.com/payara/Payara/pull/855[855/PAYARA-827 - JTA Transaction Timer Thread should be named]
* https://github.com/payara/Payara/pull/859[859/PAYARA-791 - server.log file empty for Payara micro]
* https://github.com/payara/Payara/pull/862[862/PAYARA-823 - DataSource is silently defaulted to jdbc/__default on any lookup failure]
* https://github.com/payara/Payara/pull/865[865/PAYARA-683 - When EAR is deployed, it is not possible to see details of EJB modules in admin console]
* https://github.com/payara/Payara/pull/891[891/PAYARA-184 - Admin Console Integration for configuration of request tracing]
* https://github.com/payara/Payara/pull/894[894/PAYARA-848 - Admin Console Integration for configuration of Notification Service]
* https://github.com/payara/Payara/pull/897[897/PAYARA-169 - Admin Console integration to display Notifications on server tab]
* https://github.com/payara/Payara/pull/903[903/PAYARA-628 - Move Hazelcast and JBatch configuration into the tree view rather than its current location on the tab view. Only members should be on the tab view.]
* https://github.com/payara/Payara/pull/905[905/PAYARA-796 - Add license key field for Payara Scales]
* https://github.com/payara/Payara/pull/913[913/PAYARA-845 - Add option to disable the Server Header]
* https://github.com/payara/Payara/pull/915[915/PAYARA-832 - Create new version identifier for Payara Blue]
* https://github.com/payara/Payara/pull/916[916/PAYARA-847 - Change the thread-pool for the Admin HTTP listener in a cluster environment]
* https://github.com/payara/Payara/pull/924[924/PAYARA-859 - Request for finer-grained slow sql logger with miliseconds]
* https://github.com/payara/Payara/pull/934[934/PAYARA-839 - Disabled apps have no contextRoot param after restart]
* https://github.com/payara/Payara/pull/943[943/PAYARA-909 - healthcheck commands do not accept configurations as a target]
* https://github.com/payara/Payara/pull/947[947/PAYARA-927 - Merge two Request Tracing Service configuration page into one]
* https://github.com/payara/Payara/pull/950[950/PAYARA-928 - Merge two Notification Service configuration page into one]
* https://github.com/payara/Payara/pull/957[957/PAYARA-926 - Request Tracing for EJB Timers]
* https://github.com/payara/Payara/pull/968[968/PAYARA-851 - Access logging command line option for Payara Micro]
* https://github.com/payara/Payara/pull/970[970/PAYARA-731 - Shrink the Payara Micro Jar]
* https://github.com/payara/Payara/pull/974[974/PAYARA-836 - Allow user to use their own logging.properties file for Payara Micro]
* https://github.com/payara/Payara/pull/975[975/PAYARA-771 - Create asadmin commands for the monitoring logger]
* https://github.com/payara/Payara/pull/943[943/PAYARA-909 - healthcheck commands do not accept configurations as a target]

[[fixed-issues]]
Fixed Issues
------------

This section details the issues marked as bugs that have been fixed for this release. ### Payara Fixes This section details the fixes implemented by the Payara team or community.

* https://github.com/payara/Payara/issues/244[244/PAYARA-470 - JTS recovery hangs for the full length of the recovery timeout and then succeeds]
* https://github.com/payara/Payara/pull/842[PAYARA-580 -Investigate Closed Entity Factory possible bug]
* https://github.com/payara/Payara/pull/810[PAYARA-682 - Properties substitustion does not work when EJB module with application-scoped datasource is deployed]
* https://github.com/payara/Payara/pull/794[794/PAYARA-776 - Windows service is named "domain1 GlassFish Server"]
* https://github.com/payara/Payara/pull/798[798/PAYARA-775 - Unwrapping principal interferes with JASPIC's register session]
* https://github.com/payara/Payara/pull/799[799/PAYARA-710 - Fix CVE-2012-2098]
* https://github.com/payara/Payara/pull/807[807/PAYARA-643 - The JMS Availability tab contains a deep link to Oracle docs]
* https://github.com/payara/Payara/pull/808[808/PAYARA-594 - Spurious AllPermission warning]
* https://github.com/payara/Payara/pull/812[812/PAYARA-382 - Fix GitHub issue 384 spurious SEVERE log message when deploying WebService]
* https://github.com/payara/Payara/pull/816[816/PAYARA-742 - Eclipselink generates broken SQL for Informix]
* https://github.com/payara/Payara/pull/822[822/PAYARA-355 - thousands of ClassNotFound warnings while deploying an EAR with many WAR's]
* https://github.com/payara/Payara/pull/825[825/PAYARA-800 - Payara Micro Maven Deployer gives a FileNotFoundException]
* https://github.com/payara/Payara/pull/828[828/PAYARA-794 - NPE in LazyBootPersistenceManager if configured JNDI name does not point to a valid datasource]
* https://github.com/payara/Payara/pull/829[829/PAYARA-803 - No LoginModules configured for jdcbRealm on Payara Micro]
* https://github.com/payara/Payara/pull/831[831/PAYARA-802 - Payara Domain is missing -Djavax.xml.accessExternalSchema=all]
* https://github.com/payara/Payara/pull/834[834/PAYARA-799 - The exception: "java.lang.IllegalArgumentException: PWC2788: setAttribute: Non-serializable attribute" will occur when a web-fragment.xml with is found]
* https://github.com/payara/Payara/pull/835[835/PAYARA-724 - The admin console does not render escape characters on the log levels page]
* https://github.com/payara/Payara/pull/837[837/PAYARA-639 - Weld NPE when invalidating sessions]
* https://github.com/payara/Payara/pull/845[845/PAYARA-664 - NullPointerException during WebDirContext.lookupFromJars probably caused by race conditions]
* https://github.com/payara/Payara/pull/847[847/PAYARA-734 - Admin console should spit out a warning if JMS destination name contains a forward slash]
* https://github.com/payara/Payara/pull/852[852/PAYARA-795 - Payara Blue on IBM JDK invalid JVM options]
* https://github.com/payara/Payara/pull/854[854/PAYARA-826 - ClassNotFoundException with JSR107 annotations on stateless session bean]
* https://github.com/payara/Payara/pull/867[867/PAYARA-821 - JoinFetch annotation in EclipseLink ignores default]
* https://github.com/payara/Payara/pull/889[889/PAYARA-808 - j-interop-repackaged.jar is missing in Payara Server 162]
* https://github.com/payara/Payara/pull/893[893/PAYARA-853 - thread pool statistics counters not correct]
* https://github.com/payara/Payara/pull/899[899/PAYARA-852 - New admin console design doesn't display on Chinese, Japanese and korean]
* https://github.com/payara/Payara/pull/908[908/PAYARA-863 - Payara no longer starts in windows]
* https://github.com/payara/Payara/pull/920[920/PAYARA-900 - NPE in Payara Micro when --noCluster]
* https://github.com/payara/Payara/pull/922[922/PAYARA-889 - Hazelcast not booting when started from the Configurations.]
* https://github.com/payara/Payara/pull/925[925/PAYARA-903 - Error message for config validator gives incorrect property]
* https://github.com/payara/Payara/pull/926[926/PAYARA-810 - Group principal not evaluated in WS-Security context]
* https://github.com/payara/Payara/pull/933[933/PAYARA-911 - asadmin requesttracing-configure command not working when threshold values not explicitly specified]
* https://github.com/payara/Payara/pull/935[935/PAYARA-904 - asadmin fails on add-resources when creating a jdbc pool with connection validation]
* https://github.com/payara/Payara/pull/948[948/PAYARA-908 - asadmin healthcheck-configure-service failing on remote standalone instance without optional parameters]
* https://github.com/payara/Payara/pull/952[952/PAYARA-869 - Batch job xml file in META-INF/batch-jobs folder is not closed after executing batchlet]
* https://github.com/payara/Payara/pull/953[953/PAYARA-901 - Fix CVE-2016-3092]
* https://github.com/payara/Payara/pull/958[958/PAYARA-893 - Payara Micro and embedded contains different classes for jboss logging than Payara Server]
* https://github.com/payara/Payara/pull/964[964/PAYARA-870 - Notification Service isn't dynamic]
* https://github.com/payara/Payara/issues/967[967/PAYARA-945 - Race condition on restart command]
* https://github.com/payara/Payara/pull/973[973/PAYARA-841 - Malformed SQL Query caused by EclipseLink @JoinFetch with Table per class inheritance and secondary tables]
* https://github.com/payara/Payara/pull/988[988/PAYARA-960 - RequestTraceTest fails on Windows]
* https://github.com/payara/Payara/pull/990[990/PAYARA-961 - Set-monitoring-configuration delete property not working if property is last item in list]
* https://github.com/payara/Payara/pull/991[991/PAYARA-962 - Get-monitoring-configuration using --pretty output by default]
* https://github.com/payara/Payara/pull/993[993/PAYARA-965 - Notification or RequestTracing Service does not seem to be dynamic]
* https://github.com/payara/Payara/pull/997[997/PAYARA-951 - Admin Console does not prevent you setting the Request Tracing Threshold to less than 0]
* https://github.com/payara/Payara/pull/1002[1002/PAYARA-968 - Notification starting incorrectly from the Configurations.]
* https://github.com/payara/Payara/pull/1003[1003/PAYARA-967 - Request tracing starting incorrectly from the Configurations.]
* https://github.com/payara/Payara/pull/1007[1007/PAYARA -970 - Validation on Request Tracing service "thresholdUnit" value.]
* https://github.com/payara/Payara/pull/1008[1008/PAYARA-816 - Fix JAXWS Tests in Payara Blue]
* https://github.com/payara/Payara/pull/1011[1011/PAYARA-953 - Fix CVE-2016-3607]
* https://github.com/payara/Payara/pull/1012[1012/PAYARA-986 - Add -configuration suffix to the set commands of both request tracing and notification service.]

[[upstream-fixes]]
Upstream Fixes
--------------

There have been no upstream fixes brought in for this release.

[[known-issues]]
Known Issues
------------

Known issues can be seen on our GitHub issues page here:
https://github.com/payara/Payara/issues
