[[jdk17-support]]
= JDK 17+ Support Considerations

The following considerations must be taken into account when using EJB Features on JDK 17+:

* If using a Java SE client for remote EJB lookups, add the `--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.management/javax.management.openmbean=ALL-UNNAMED` JVM arguments to the list of startup arguments of the client.
* If using the `appclient` script, add the following options to the `VMARGS` environment variable: `--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.management/javax.management.openmbean=ALL-UNNAMED`
  * Note: these options are the minimal set for a rudimentary client on Java 17 or 21, more advanced clients may require additional options.