[[configuring-managed-scheduled-executor-services]]
= Configuring Managed Scheduled Executor Services

Managed scheduled executor services are used by applications to execute submitted tasks asynchronously at specific times. Tasks are executed on threads that are started and managed by the container. The context of the container is propagated to the thread executing the task.

The following tasks are used to administer managed scheduled executor service resources:

* xref:#to-create-managed-scheduled-executor-service[To Create a Managed Scheduled Executor Service]
* xref:#to-list-managed-scheduled-executor-services[To List Managed Scheduled Executor Services]
* xref:#to-update-managed-scheduled-executor-services[To Update a Managed Scheduled Executor Service]
* xref:#to-delete-managed-scheduled-executor-services[To Delete a Managed Scheduled Executor Service]

[[to-create-managed-scheduled-executor-service]]
== To Create a Managed Scheduled Executor Service

Use the `create-managed-scheduled-executor-service` subcommand in remote mode to create a managed scheduled executor service resource.

Because all JNDI names are in the `java:comp/env` subcontext, when specifying the JNDI name of a managed scheduled executor service, use only the `concurrent/name` format. For example, `concurrent/ScheduledExecutor1`.

For more information about the default managed scheduled executor service resource included with Payara Server, see xref:/Technical Documentation/Payara Server Documentation/Server Configuration And Management/Concurrency Enhancements/Default Concurrent Resources.adoc[Default Concurrent Resources].

IMPORTANT: Creating a managed scheduled executor service resource is a dynamic event and typically does not require server restart. Applications can use a resource as soon as it is created. However, if an application tried to use a resource before it was created, and that resource is created later, the application or the server must be restarted. Otherwise, the application will not be able to locate the resource.

. Ensure that the server is running. +
Remote subcommands require a running server.
. Create a managed scheduled executor service by using the `create-managed-scheduled-executor-service` subcommand. 
. If necessary, notify users that the new resource has been created.

=== Creating a Managed Scheduled Executor Service
This example creates a managed scheduled executor service resource named `concurrent/ScheduledExecutor1`.
[source, shell, subs="quotes"]
----
asadmin> *create-managed-scheduled-executor-service concurrent/ScheduledExecutor1*
Managed scheduled executor service concurrent/ScheduledExecutor1 created successfully.
Command create-managed-scheduled-executor-service executed successfully.
----

=== See Also

You can also view the full syntax and options of the subcommand by typing `asadmin help create-managed-scheduled-executor-service` at the command line.

[[to-list-managed-scheduled-executor-services]]
== To List Managed Scheduled Executor Services

Use the `list-managed-scheduled-executor-services` subcommand in remote mode to list the existing managed scheduled executor service resources. 

. Ensure that the server is running. +
Remote subcommands require a running server. 

. List managed scheduled executor service resources by using the `list-managed-scheduled-executor-services` subcommand.

=== Listing Managed Scheduled Executor Services
This example lists managed scheduled executor service resources on the default server instance, `server`.
[source, shell, subs="quotes"]
----
asadmin> *list-managed-scheduled-executor-services*
concurrent/__defaultManagedExecutorService 
concurrent/ScheduledExecutor1 
concurrent/ScheduledExecutor2 
Command list-managed-scheduled-executor-services executed successfully.
----

=== See Also

You can also view the full syntax and options of the subcommand by typing `asadmin help list-managed-scheduled-executor-services` at the command line.

[[to-update-managed-scheduled-executor-services]]
== To Update a Managed Scheduled Executor Service

You can change all of the settings for an existing managed scheduled executor service resource except its JNDI name. Use the `get` and `set` subcommands to view and change the values of the managed scheduled executor service attributes.

IMPORTANT: When a resource is updated, the existing resource is shut down and recreated. If an application used the resource prior to the update, the application or the server must be restarted.

. Ensure that the server is running. +
Remote subcommands require a running server.
. List the context service resources by using the `list-managed-scheduled-executor-services`
subcommand.
. View the attributes of a managed scheduled executor service by using the `get` subcommand. +
For example: +
`asadmin> *get resources.managed-scheduled-executor-service.concurrent/ScheduledExecutor1.**`
. Set an attribute of the managed scheduled executor service by using the set subcommand. +
For example: +
`asadmin> *set resources.managed-scheduled-executor-service.concurrent/ScheduledExecutor1.deployment-order=120*`

[[to-delete-managed-scheduled-executor-services]]
== To Delete a Managed Scheduled Executor Service

Use the `delete-managed-scheduled-executor-service` subcommand in remote mode to delete an existing managed scheduled executor service. Deleting a managed scheduled executor service is a dynamic event and does not require server restart.

Before deleting a managed scheduled executor service resource, all associations to the resource must be removed.

. Ensure that the server is running. +
Remote subcommands require a running server.
. List the managed scheduled executor service resources by using the `list-managed-scheduled-executor-services`
subcommand.
. If necessary, notify users that the managed scheduled executor service is being deleted.
. Delete the managed scheduled executor service by using the `delete-managed-scheduled-executor-service` subcommand.

=== Deleting a Managed scheduled Executor Service
This example deletes the managed scheduled executor service resource named `concurrent/ScheduledExecutor1`.

[source, shell, subs="quotes"]
----
asadmin> *delete-managed-scheduled-executor-service concurrent/ScheduledExecutor1*
Managed scheduled executor service concurrent/ScheduledExecutor1 deleted successfully.
Command delete-managed-scheduled-executor-service executed successfully.
----

=== See Also

You can also view the full syntax and options of the subcommand by typing `asadmin help delete-managed-scheduled-executor-service` at the command line.