[[default-concurrent-resources]]
= Default Concurrent Resources

When you create a concurrent resource, you specify a unique JNDI name for the resource. Applications use this name to access the resource.

The Java EE standard specifies that certain default resources be made available to applications, and defines specific JNDI names for these default resources. GlassFish Server makes these names available through the use of logical JNDI names, which map Java EE standard JNDI names to specific Payara Server resources. For concurrent resources, the mappings are as follows:

*java:comp/DefaultContextService* +
This Java EE standard name is mapped to the concurrent/__defaultContextService resource. 

*java:comp/DefaultManagedThreadFactory* +
This Java EE standard name is mapped to the concurrent/__defaultManagedThreadFactory resource. 

*java:comp/DefaultManagedExecutorService* +
This Java EE standard name is mapped to the concurrent/__defaultManagedExecutorService resource. 

*java:comp/DefaultManagedScheduledExecutorService* +
This Java EE standard name is mapped to the concurrent/__defaultManagedScheduledExecutorService resource.