
[[payara-server-documentation]]
= Payara Server Documentation

Comprehensive documentation of how to operate and manage a Payara Server installation composed of the following subsections:

General Administration:: Details the basics of how to manage the configuration and runtime settings of Payara Server.
Deployment Planning:: Contains instructions and recommendations on how to plan an application deployment in Payara Server.
Application Deployment:: Details how application deployments work in Payara Server.
High Availability:: Details how to configure and use the high-availability features of Payara Server on distributed environments.
Security Guide:: A comprehensive guide that offers basic recommendations and advice on how to secure a Payara Server installation.
Command Reference:: A complete reference manual of alf available Asadmin CLI commands.
Extensions:: Documents the features of all available extensions for Payara Server and how to use them.
Upgrade Guide:: A guide with recommendations and strategies for upgrading Payara Server across versions.

[[conventions]]
== Documentation Conventions

The following conventions are applied through the pages in this section to improve readability and familiarity with how Payara Server operates.

[[symbol-conventions]]
=== Symbol Conventions

The following table explains symbols that might be used in this section.

[width="100%", cols="10%,25%,25%,40% a",options="header",]
|=======================================================================
|Symbol |Description |Example |Meaning
|`[ ]` |Contains optional arguments and command options. |`ls [-l]` |The `-l` option is not required.

|`{ \| }` |Contains a set of choices for a required command option.
|`-d {y\|n}` |The `-d` option requires that you use either the `y` argument or the `n` argument.

|`${ }` |Indicates a variable reference or a placeholder reference for a default path.
|`${com.sun.javaRoot}`
|References the value of the `com.sun.javaRoot` variable.

|- |Joins simultaneous multiple keystrokes. |`Control-A` |Press the `Control key while you press the A key.

|+ + |Joins consecutive multiple keystrokes. |`Ctrl+A+N` |Press the Control key, release it, and then press the subsequent keys.

| -> |Indicates menu item selection in a graphical user interface. |File ->
New -> Templates |From the _File_ menu, choose New. From the _New_ submenu,
choose _Templates_.
|=======================================================================

[[default-paths-and-file-names]]
=== Default Paths and File Names

The following table describes the default paths and file names that are used in this book.

[width="100%",cols="<14%,<34%,<52%",options="header",]
|===
|Placeholder |Description |Default Value

|`as-install`
a| Represents the base installation directory for Payara Server.

In configuration files, as-install is represented as follows:

`${com.sun.aas.installRoot}`

a| Installations on a Linux operating system, and macOS operating system:

`+{USER_HOME}+/payara6/glassfish`

Installations on a Windows operating system:

`+{SystemDrive}+:\payara6\glassfish`

|`as-install-parent`
|Represents the parent of the base installation directory for Payara Server.

a| Installations on a Linux operating system, and Mac operating system:

`+{USER_HOME}+/payara6`

Installations on a Windows operating system:

`+{SystemDrive}+\payara6`

|`domain-root-dir`
|Represents the directory in which a domain is created by default.
|`as-install/domains/`

|`domain-dir`
a| Represents the directory in which a domain's configuration is stored.

In configuration files, `domain-dir` is represented as follows:
`${com.sun.aas.instanceRoot}`

|`domain-root-dir/<domain-name>`

|`node-dir`
|Represents the directory for a configured node.
|`as-install/glassfish/nodes/<node-name>`

|`instance-dir`
|Represents the directory for a server instance.
|`node-dir/<instance-name>`

|===

[[docker-images]]
== Docker Images

Payara Services Limited provides official Payara Server Docker Images which are updated every release.

These images are hosted on Docker hub in the following locations:

* https://hub.docker.com/r/payara/server-full/[Payara Server Full Profile Docker Image]
* https://hub.docker.com/r/payara/server-web/[Payara Server Web Profile Docker Image]

TIP: Payara Enterprise customers have access to a private Docker repository containing Payara Enterprise Edition equivalent images, which are also released and updated every month.
