:ordinal: 900
[[payara-server-documentation]]
= Payara Server Documentation

Documentation of Payara Server Community features. Includes full documentation of the features added on top of _GlassFish Server {glassfishVersion} Open Source Edition_ as well as features shared with GlassFish Server or their improvements specific to Payara Server.

All documentation for _GlassFish Server {glassfishVersion}_ is also valid for Payara Server Community {currentVersion} unless stated otherwise in Payara Server Community documentation.

[[docker-images]]
== Docker Images

Payara Services Limited provides official Payara Server Docker Images which are updated every release.

These images are hosted on Docker hub in the following locations:

* https://hub.docker.com/r/payara/server-full/[Payara Server Full Profile Docker Image]
* https://hub.docker.com/r/payara/server-web/[Payara Server Web Profile Docker Image]

TIP: Payara Enterprise customers have access to a private Docker repository containing Payara Enterprise Edition equivalent images, which are also released and updated every month.

[[references]]
== References

* https://javaee.github.io/glassfish/documentation[GlassFish Server {glassfishVersion} Open Source Edition Documentation]
