:ordinal: 900
[[Public API]]
= Public API

This page contains information on using the Public API integrated within Payara Server and Payara Micro.

TIP: See the http://javadoc.io/doc/fish.payara.api/payara-api[Payara API Javadoc] for the complete public Payara API reference. 

[[use-cases]]
== Use Cases

The Public API should be used in the following scenarios:

. Java EE Developers and end users that develop web and enterprise applications that require Payara specific features outside the specifications (and *JCache*).
. Contributors that want to develop extensions for Payara Server or Payara Micro.

[[maven-coordinates]]
== Maven Coordinates

The Public API is released as a Maven artifact in *Maven Central*. To use it in a Maven project, set the following dependency in your project's POM:

[source, xml]
----
<dependency>
    <groupId>fish.payara.api</groupId>
    <artifactId>payara-api</artifactId>
    <version>${payara.version}</version>
    <scope>provided</scope>
</dependency>
----

Where `${payara.version}` of the artifact corresponds with the oldest version of Payara Server your application should support.