[[public-api]]
= Public API

This page contains information on using the Public API integrated within Payara Server and Payara Micro.

TIP: See the http://javadoc.io/doc/fish.payara.api/payara-api[Payara API Javadoc] for the complete public Payara API reference. 

[[use-cases]]
== Use Cases

The Public API should be used in the following scenarios:

. Java EE Developers and end users that develop web and enterprise applications that require Payara specific features outside the specifications (and *JCache*).
. Contributors that want to develop extensions for Payara Server or Payara Micro.

[[maven-coordinates]]
== Maven Coordinates

The Public API is released as a Maven artifact in *Payara Nexus*, in the `payara-artifacts` repository. To use it in a Maven project, set the following dependencies in your project's POM:

[source, xml, subs=attributes+]
----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>fish.payara.api</groupId>
            <artifactId>payara-bom</artifactId>
            <version>{page-version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
</dependencyManagement>

<dependencies>
    <dependency>
        <groupId>fish.payara.api</groupId>
        <artifactId>payara-api</artifactId>
        <scope>provided</scope>
    </dependency>
</dependencies>
----

For information on the Payara BOM, please see xref:Technical Documentation/Ecosystem/Project Management Tools/Maven Bom.adoc[Maven Bom].
