= Security Connectors

Security Connectors are a collection of Jakarta EE Security adapters that implements
industry-standard security protocols, specifications and integrates with third-party
security artifacts & components.

The available connectors on Maven central are:

== xref:/Technical Documentation/Public API/OpenID Connect Support.adoc[OpenId Connect Client]

Implements https://openid.net/connect/[OpenId Connect] standard protocol by implementing Jakarta EE Security
https://jakarta.ee/specifications/security/1.0/apidocs/javax/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanism.html[HTTP Authentication Mechanism]
and https://jakarta.ee/specifications/security/1.0/apidocs/javax/security/enterprise/identitystore/IdentityStore.html[Identity Store]
for authentication & authorization using `@OpenIdAuthenticationDefinition` annotation
and also provides access to the user's profile info, Identity token, Access token,
& Refresh token using CDI based injection.

Maven Coordinates: https://mvnrepository.com/artifact/fish.payara.security.connectors/security-connector-oidc-client[`fish.payara.security.connectors:security-connector-oidc-client`]

== xref:/Technical Documentation/Public API/OAuth Support.adoc[OAuth 2.0 Client:]

Implements https://oauth.net/2/[OAuth 2.0] standard protocol by implementing Jakarta EE Security
https://jakarta.ee/specifications/security/1.0/apidocs/javax/security/enterprise/authentication/mechanism/http/HttpAuthenticationMechanism.html[HTTP Authentication Mechanism]
and https://jakarta.ee/specifications/security/1.0/apidocs/javax/security/enterprise/identitystore/IdentityStore.html[Identity Store]
for authorization using `@OAuth2AuthenticationDefinition` annotation and provides
access to the Identity token and Access token using CDI based injection.

Maven Coordinates: https://mvnrepository.com/artifact/fish.payara.security.connectors/security-connector-oauth2-client[`fish.payara.security.connectors:security-connector-oauth2-client`]

TIP: Payara Platform Enterprise also provides the built-in link:{enterpriseDocsPageRootUrl}/Technical Documentation/Payara Server Documentation/Public API/yubikey.html[Yubikey Authentication Mechanism]. This allows authentication through a hardware device. This type of authentication removes some need of using credentials and requires authenticating using a physical token in a very secure way.
