[[upgrade-payara-server]]
= Upgrading Payara Server

There are two valid methods of fully upgrading to a new release of Payara Server. Either of the following two methods would work in most circumstances:

IMPORTANT: These methods should not be used for upgrading from Payara Server 5 to Payara Server 6 and will not update your installation correctly. You should instead use a clean installation of Payara Server 6

. Backing up and restoring the existing configuration to a new installation. xref:Technical Documentation/Payara Server Documentation/Upgrade Guide/Backup and Restore Method.adoc[Read Backup and Restore Method]

. Maintaining completely separate domain and node directories and pointing the new version to the existing directories. xref:Technical Documentation/Payara Server Documentation/Upgrade Guide/Domain and Node Directories Method.adoc[Read Domain and Node Directories Method]

[[migration-5-to-6-considerations]]
== Payara Server 5 to Payara Server 6 Migration Considerations
Package names for Corba classes have changed from `com.sun` to `org.glassfish`, therefore if you use the `java.naming.factory.initial` system property you should set it to `org.glassfish.jndi.cosnaming.CNCtxFactory` for Payara Server 6.
