= Root Configuration Directory
:ordinal: 3

Payara Micro is distributed as a single JAR file. However, at runtime, it creates and depends on a folder structure that is referred to as Root Configuration Directory or `rootdir`.

This directory stores all of the instance configuration, deployed applications, as well as implementation JAR files needed for running the instance.

[[temp-rootdir]]
== Temporary Root Configuration Directory

By default, Payara Micro will create a folder in the system's temporary directory and prepares a root configuration directory there.
This makes instances' configuration stateless, but also has two potentially undesirable effects:

* Temporary directory may be deleted by system cleanup procedure. 
  If files are removed by a third party process, the application will not behave correctly anymore.
* Preparing the directory has an impact on startup time

IMPORTANT: For the reasons mentioned above, do not to use a temporary directory in production scenarios.

[[persistent-rootdir]]
== Persistent Root Configuration Directory

Root configuration directory can be explicitly specified with the command line parameter `--rootDir <directory>`.
In such case, the directory is created only once, and instance configuration is preserved across restarts of the instance.

Following configuration is preserved:

* Deployed applications
* Effects of preboot, postboot and post-deploy commands
* Logging configuration