= Supported Platforms

Though it is always possible for new versions to be supported, this page
details the JVMs currently supported by the Payara Platform Community (both Payara Server Community and Payara Micro Community).


== Supported Java Virtual Machines

The Payara Platform currently runs the following Java Virtual Machines:

* Azul Zulu JDK: 8 (u162+), 11 (11.0.5u10+)
* Oracle JDK: 8 (u162+), 11 (11.0.5+)
* Amazon Corretto: 8, 11 (11.0.5+)
* Adopt Open JDK: 8, 11 (11.0.5+)
* Adopt Open JDK with Eclipse Open J9: 8, 11 (11.0.5+)
* Any other JVM based on OpenJDK 8u162+ or 11.0.5+

The Payara Platform runs on the `x64` and `arm64` variants of the above JVMs.

TLS 1.3 is supported on JDK 8 with Azul Zulu 1.8.222+, Open JDK 8u262+ based builds, and all version 11 of all above JDKs.

== Supported Operating Systems

The Payara Platform currently runs on the following Operating Systems in all the versions listed below and all their newer versions:

* Windows
** Windows 7+
** Windows Server 2008+
* Linux
** Ubuntu 14.04 (Trusty Tahr) LTS+
** Debian 7 (Wheezy)+
** CentOS 6+
** RHEL 5+
** OpenSUSE 42.2+
** SUSE 11.4, 12.2+, 15.0+
** Amazon Linux (all versions)
* Other
** MacOS(OSX) 10.10.5 (Yosemite)+
** IBM AIX 7.1+ 

In general, Payara Server runs on any system supported by at least one of the JVMs it runs on.