[[maven-support]]
= Maven Support

This section describes Apache Maven support for Payara Micro.

[[artifacts-in-maven-central]]
== Maven Central Artifacts

Payara Micro is available in Maven Central, allowing you to include it as a dependency in your project's POM. This allows you to easily add the required Payara Micro classes and methods to your application to use Payara Micro programmatically.

To do this, use the following GAV coordinates:

[source, xml, subs=attributes+]
----
<dependency>
    <groupId>fish.payara.extras</groupId>
    <artifactId>payara-micro</artifactId>
    <version>{currentVersion}</version>
</dependency>
----

IMPORTANT: The xref:/documentation/payara-server/public-api/Overview.adoc[Public API] dependency must be also added to the project's POM when developing applications that use proprietary features (`@Clustered` or `@NamedCache` for example).

[[run-payara-micro-using-the-maven-plugin]]
== Run Payara Micro using the Maven Plugin

There is a maven plugin built specifically for use with Payara Micro. It has goals to `bundle` the application into an Uber JAR, `start` and `stop` Payara Micro. This plugin is xref:/documentation/ecosystem/maven-plugin.adoc[fully documented in its own section].

[[run-payara-micro-using-the-netbeans-ide]]
== Run Payara Micro using the NetBeans IDE

There is a https://github.com/payara/ecosystem-netbeans-plugin/tree/master/payara.micro[NetBeans IDE plugin - payara.micro module] built specifically for Payara Micro to create and manage the application actions (e.g run, reload & debug). This plugin is xref:/documentation/ecosystem/netbeans-plugin/payara-micro.adoc[fully documented in its own section].